<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="javascript:window.history.go(-1);" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
    <div class="col m6 s6 text-right">
        <a class="btn" href="/prestamo/pdfprestamo/id/<?php echo $this->id_solicitud; ?>"><i class="material-icons right">insert_drive_file</i>Archivo</a>
    </div>
</div>

<style type="text/css">
	.table_wrapper{
        overflow-x: auto;
    }
</style>

<div class="row"> 
    <div class="col m12 s12 text-center" style="margin-top: 30px;">
        <span style="font-size:28px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalle del Descuento</span>
    </div>
</div>


<?php foreach ($this->personal as $key) {
	$id_user = $key['id'];
	$nombre = $key['nombre'];
	$ap = $key['apellido_pa'];
	$ma = $key['apellido_ma'];
	$imagen = $key['imagen'];
	$telefono = $key['telefono'];
	$email = $key['email_personal'];
} ?>

<?php foreach ($this->puestos as $key) {
	$puesto = $key['nombre'];
} ?>

<?php foreach ($this->solicitud as $value) {
	$id = $value['id'];
	$fecha_prestamo = $value['fecha_prestamo'];
	$monto = $value['monto'];
	$cantidad_pagos = $value['cantidad_pagos'];
	$motivo = $value['motivo'];
	$evidencia = $value['evidencia'];
	$cantidad_saldada = $value['cantidad_saldada'];
	$user_prestamo = $value['user_prestamo'];
	$user_fecha = $value['user_fecha'];
} ?>

<div class="row">
    <div class="col s12 m6">
      	<div class="card">
        	<div class="card-content">
          		<span style="font-size:21px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información del Personal</span>
          		
          		<div class="row" style="margin-top: 20px;">
          			<div class="col m12 s12">
	          			<span style="font-size:14px;">Nombre: </span>
	          			<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $nombre; ?> <?php echo $ap; ?> <?php echo $ma; ?></span> <br>
	          			<span style="font-size:14px;">Puesto: </span>
	          			<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $puesto; ?></span> <br>
	          			<span style="font-size:14px;">Telefono: </span>
	          			<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $telefono; ?></span> <br>
	          			<span style="font-size:14px;">Correo: </span>
	          			<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $email; ?></span> <br>

          			</div>
          		</div>
        	</div>
      	</div>
    </div>

    <div class="col s12 m6">
      	<div class="card">
        	<div class="card-content">
          		<span style="font-size:21px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información del Descuento</span>
          		
          		<div class="row" style="margin-top: 20px;">
          			<div class="col m12 s12">
	          			<span style="font-size:14px;">No: </span>
	          			<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $id; ?> </span> <br>
	          			<span style="font-size:14px;">Monto: </span>
	          			<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($monto, 2, '.', ','); ?></span> <br>
	          			<span style="font-size:14px;">Cantidad pagos: </span>
	          			<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $cantidad_pagos; ?></span> <br>
	          			<span style="font-size:14px;">Cantidad pagos saldados: </span>
	          			<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $cantidad_saldada; ?></span> <br>
          			</div>
          		</div>
        	</div>
      	</div>
    </div>
</div>


<div class="row">
    <div class="col s12 m12">
      	<div class="card">
        	<div class="card-content">
          		
          		<div class="row" style="margin-top: 20px;">
          			<div class="col m12 s12 table_wrapper">
      					<table>
        					<thead>
          						<tr style="background-color: #EDEDED;">
              						<th>Motivo</th>
              						<th>Evidencia</th>
          						</tr>
        					</thead>

        					<tbody>
          						<tr>
            						<td><?php echo $motivo; ?></td>
            						<td><a href="/<?php echo $evidencia; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a></td>
          						</tr>
        					</tbody>
      					</table>
          			</div>
          		</div>
        	</div>
      	</div>
    </div>
</div>

<div class="row">
    <div class="col s12 m12">
      	<div class="card">
        	<div class="card-content">
          		<span style="font-size:21px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Pagos realizados</span>
          		<div class="row" style="margin-top: 20px;">
          			<div class="col m12 s12 table_wrapper">
					    <table class="table text-left table-hover">
					      <thead>
					        <tr style="background-color: #EDEDED;">
					          <th>Sitio</th>
					          <th>Día</th>
					          <th>Monto descuento</th>
					          <th>Nomina</th>
					        </tr> 
					      </thead>
					      <?php
					      if ($this->pagos_realizados) { 
					      foreach ($this->pagos_realizados as $usr) { ?>
					      <tbody>
			                <tr>
			                    <td>
			                    	<?php echo $usr['nombre'] ?>
			                    </td>
			                    <td>
			                    	<?php echo $usr['dia'] ?>
			                    </td>
			                    <td>
			                    	<?php $monto_pay = substr($usr['monto_pago'], 1);  ?>
			                    	<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($monto_pay, 2, '.', ','); ?></span>
			                    </td>

			                    <td>
			                    	
			                    	<a href="/nomina/detallenomina/id/<?php echo $usr['solicitud_nomina'] ?>/user/<?php echo $id_user; ?>">
			                    		No. <?php echo $usr['solicitud_nomina'] ?>
			                    	</a>
			                    </td>

			                </tr>
					        <?php } }else{ ?>
					        </tbody> 
					        <tbody>
					            <tr>
					                <td class="text-center" colspan="6"><h4>No hay pagos realizados.</h4></td>
					            </tr>
					        </tbody>
					                    
					        <?php } ?>
					    </table>
          			</div>
          		</div>
        	</div>
      	</div>
    </div>
</div>