
<?php 
  function isActhref($nameBtn,$urlname){
      if($nameBtn==1 && $urlname==null){
        return "active"; 
      }
      return ($nameBtn == $urlname)?"active":"";
  }

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>


<style type="text/css">
  .oculto{display: none;}
  .active_menu{
    -webkit-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
    -moz-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
    box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
  }
</style>

<?php 
	$status =  $this->status_documento;
?>
<div class="row" style="margin-top: 20px;">
	<div class="col m12 s12">
  		<ul >
  			<?php if($status == 0){ ?>
	    		<li class="tab col s3 active_menu">
	    			<a class="" href="/prestamo/solicitudprestamo/status/0">
	    			<h4>En Proceso
	  					<div class="chip">
	    					<?php echo $this->enproceso; ?>
	  					</div>
	    			</h4>
	    			</a>
	    		</li>
  			<?php }else{ ?>
	    		<li class="tab col s3">
	    			<a class="" href="/prestamo/solicitudprestamo/status/0">
	    			<h4>En Proceso
	  					<div class="chip">
	    					<?php echo $this->enproceso; ?>
	  					</div>
	    			</h4>
	    			</a>
	    		</li>
  			<?php } ?>

  			<?php if($status == 1){ ?>
  				<li class="tab col s3 active_menu">
  					<a href="/prestamo/solicitudprestamo/1"><h4>Liquidadas</h4></a>
  					<div></div>
  				</li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/prestamo/solicitudprestamo/status/1"><h4>Liquidadas</h4></a></li>
  			<?php } ?>

  		</ul>
	</div>
</div>


<div class="row">
  <div class="col m1 s12"></div>
  <div class="col m10 s12">
    <div class="row">
      <div class="col m5 s6">
        <div class="input-field col s12">
          <select>
            <option value="1" selected>Personal</option>
          </select>
          <label>Buscar por:</label>
        </div>
      </div>
      <div class="col m5 s6">
        <div class="input-field col m12 s12">
          <select id="user_prestamo" name="usuario">
            <option value="0" disabled selected>* Selecciona una opcion:</option>
            <?php foreach ($this->prestamo_user as $rl) { ?>
            <option value="<?php echo $rl["id"]; ?>"><?php echo $rl["nombre"]; ?> <?php echo $rl["apellido_pa"]; ?> <?php echo $rl["apellido_ma"]; ?></option>
            <?php } ?>
          </select>
          <label>Personal</label>
        </div>
      </div>
      <div class="col m2 s12 text-center">
        <a class="btn"><i class="material-icons right">search</i>Buscar</a>
      </div>
    </div>
  </div>
  <div class="col m1 s12"></div>
</div>



<div class="row">
    <div class="col m12 s12">
      <div class="row">
          <div class="col m8 s8">
            <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista Descuento</span>
          </div>
          <div class="col m4 s4 text-right">
            <a class="btn modal-trigger green" href="#modal1">+ Agregar Descuento</a>
          </div>
      </div>
      <table class="table text-left table-hover">
          <thead>
            <tr>
                <th>NO.</th>
                <th>Personal</th>
                <th>Fecha prestamo</th>
                <th>Monto</th> 
                <th>Cantidad</th>
                <th>Pagos</th>
                <th></th>
            </tr> 
          </thead>
          <?php
          if ($this->paginator) { 
          foreach ($this->paginator as $usr) { ?>
          <tbody>
            <tr>
              <td><?php echo $usr['id']; ?></td>
              <td><?php echo $usr['nombre_personal']; ?></td>
              <td><?php echo $usr['fecha_prestamo']; ?></td>
              <td>
                <span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($usr['monto'], 2, '.', ','); ?></span>
              </td>
              <td>
                <?php echo $usr['cantidad_pagos']; ?>
              </td>
              <td>
                <?php echo $usr['cantidad_saldada']; ?>
              </td>
              <td class="text-center">
                <a href="/prestamo/detalleprestamo/id/<?php echo $usr["id"] ?>"><i class="fa fa-2x fa-id-card-o"></i></a>
              </td>
            </tr>
          <?php } }else{ ?>
          </tbody> 
        <tbody>
            <tr>
                <td class="text-center" colspan="6"><h4>No hay solicitudes de Prestamos.</h4></td>
            </tr>
        </tbody>
                    
        <?php } ?>
    </table>
  </div>
</div>


<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
                  <?php if($pagina - 1 == 0){ ?>
                      <li class="page-item disabled">
                          <span class="page-link">Anterior</span>
                      </li>
                  <?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
                  <?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
                  <?php if($pagina >= $this->total): ?>
                        <li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                        </li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>


  <!-- Modal Structure -->
<div id="modal1" class="modal modal-fixed-footer">
  <div class="modal-content">
    <span style="font-size:23px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar Descuento</span>
    <div class="row" style="margin-top: 25px;">
      <form action="/prestamo/requestaddprestamo" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_addprestamo">
      <div class="col m12 s12">
        <div class="input-field col m6 s12">
          <select id="user_pre" name="usuario" required>
            <option value="0" disabled selected>* Selecciona una opcion:</option>
            <?php foreach ($this->prestamo_user as $rl) { ?>
            <option value="<?php echo $rl["id"]; ?>"><?php echo $rl["nombre"]; ?> <?php echo $rl["apellido_pa"]; ?> <?php echo $rl["apellido_ma"]; ?></option>
            <?php } ?>
          </select>
          <label>Personal</label>
        </div>

        <div class="input-field col m6 s12">
          <input id="fecha_prestamo" name="fecha" type="date" class="validate">
          <label for="fecha_prestamo">Fecha Prestamo</label>
        </div>

        <div class="input-field col m6 s12">
          <input id="monto_prestamo" name="monto" type="number" class="validate">
          <label for="monto_prestamo">Monto</label>
        </div>

        <div class="input-field col m6 s12">
          <input id="cantidad_prestamo" name="cantidad" type="number" class="validate">
          <label for="cantidad_prestamo">Cantidad Pagos</label>
        </div>

        <div class="file-field input-field col m s12">
          <div class="btn">
            <span>Evidencia</span>
            <input type="file" name="url">
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" id="validate_url" type="text">
          </div>
        </div>

        <div class="input-field col m12 s12">
          <input id="motivo_prestamo" name="motivo" type="text" class="validate">
          <label for="motivo_prestamo">Motivo</label>
        </div>
      </div>
     </form> 
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" id="add_generarprestamo" class="btn">Generar</button>
    <button  class="modal-close red btn">Cerrar</button>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function(){
    $('.modal').modal();
  });

    $("#add_generarprestamo").click(function(){
      var user_prestamo = document.getElementById("user_pre").value;
      var monto_prestamo = document.getElementById("monto_prestamo").value;
      var cantidad_prestamo = document.getElementById("cantidad_prestamo").value;
      var motivo_prestamo = document.getElementById("motivo_prestamo").value;
      var fecha_prestamo = document.getElementById("fecha_prestamo").value;

        if(user_prestamo == 0 ||  monto_prestamo== 0 || cantidad_prestamo == 0 ||  motivo_prestamo == "" || fecha_prestamo == ""){
            swal({
                title: "Para continuar es neceario agregar la información solicitada",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submitprestamo, 1500);     
        }
    });
    function submitprestamo() { document.getElementById("submit_addprestamo").submit() }

</script>