<style type="text/css">
	.oculto{
		display: none;
	}
</style>

<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="javascript:window.history.go(-1);" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
    <div class="col m6 s6 text-right">
     	<a class="btn" href="/nomina/pdfnomina/id/<?php echo $this->solicitudid_nomina; ?>/user/<?php echo $this->user_solicitud; ?>"><i class="material-icons right">insert_drive_file</i>Documento</a>
    </div>
</div>

<div class="row"> 
    <div class="col m12 s12 text-center" style="margin-top: 30px;">
        <span style="font-size:28px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalle Nomina</span>
    </div>
</div>

<?php foreach ($this->personal_nomina as $key) {
	$id_user = $key['id'];
	$name_user = $key['nombre'];
	$app_user = $key['apellido_pa'];
	$apm_user = $key['apellido_ma'];
	$imagen = $key['imagen'];
	$puesto = $key['puesto'];
} ?>

<?php foreach ($this->solicitud_nomina as $key) {
	$sitio_solicitud = $key['sitio'];
	$monto_solicitud = $key['monto_nomina'];
	$fecha_soliciutd = $key['solicitud_fecha'];
	$user_solicitud = $key['solicitud_user'];
} ?>

<div class="row">
    <div class="col s12 m6">
      	<div class="card" style="height: 350px;">
	        <div class="card-content">
	          	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información del Personal</span>

	          	<div class="row">
	          		<div class="col m12 s12" style="margin-top: 20px;">
	          			<span style="font-size:16px;">Personal: </span>
	          			<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $name_user; ?> <?php echo $app_user; ?> <?php echo $apm_user; ?></span> <br>
	          			<span style="font-size:16px;">Puesto: </span>
	          			<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $puesto; ?></span>
	          		</div>	
	          	</div>
	          	<div class="row">
	          		<div class="col m12 s12 text-center">
	          			<a class="example-image-link" href="/<?php echo $imagen; ?>" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $imagen; ?>"  alt="image-1" style="width: 150px; height: 150px;"/></a>
	          		</div>
	          	</div>
	        </div>
      	</div>
    </div>


    <div class="col s12 m6">
      	<div class="card" style="height: 350px;">
	        <div class="card-content">
	          	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información de la Solicitud</span>

	          	<div class="row">
	          		<div class="col m12 s12" style="margin-top: 20px;">
	          			<span style="font-size:16px;">Sitio: </span>
	          			<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $sitio_solicitud; ?> </span> <br>
	          			<span style="font-size:16px;">Fecha Solicitud: </span>
	          			<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $fecha_soliciutd; ?> </span> <br>
	          			<span style="font-size:16px;">Usuario: </span>
	          			<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $user_solicitud; ?></span> <br>
	          			<span style="font-size:16px;">Monto: </span>
	          			<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($monto_solicitud, 2, '.', ','); ?></span>
	          		</div>	
	          	</div>
	        </div>
      	</div>
    </div>
</div>

<?php foreach ($this->solicitud_nomina as $key){ 
	$monto_nomina = $key['monto_nomina'];
}?>


<div class="row">
    <div class="col s12 m12">
      	<div class="card">
	        <div class="card-content">
	        	<div class="row">
	        		<div class="col m6 s6">
	        			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalle de la Nomina</span>
	        		</div>
	        		<div class="col m6 s6 text-right">
	        			
	        		</div>
	        	</div>
	          	

	          	<div class="row">
	          		<div class="col m12 s12">
				        <table class="table text-left table-hover">
				            <thead>
				                <tr>
				                	<th>Id</th>
									<th>Sitio</th>
									<th>Asistencia</th>
									<th>Entrada</th>
									<th>Salida</th>
									<th>Información dia</th>
									<th>Pago</th>
				                </tr> 
				            </thead>

				            <?php 
				            $montos = 0;
				            if ($this->detalle_nomina) { 
				                foreach ($this->detalle_nomina as $usr) { ?>
				            <tbody>
				                <tr>
				                	<td><?php echo $usr['id']; ?></td>
				                	<td>
				                		<?php echo $usr['nombre']; ?>
				                	</td>
				                	<td>
				                		<?php echo $usr['dia']; ?>
				                	</td>

				                	<?php if($usr['status_asistencia'] == 0){ ?>
				                	<td>
				                		<?php if($usr['status_tipos'] == 0){ ?>
				                			<?php echo $usr['hora_entrada']; ?>
				                		<?php }?>

				                		<?php if($usr['status_tipos'] == 1){ ?>
				                			Descuento
				                		<?php }?>

				                		<?php if($usr['status_tipos'] == 2){ ?>
				                			Herramientas
				                		<?php }?>

				                		<?php if($usr['status_tipos'] == 3){ ?>
				                			EPP
				                		<?php }?>
				                	</td>
				                	<td>
				                		<?php if($usr['solicitud_prestamo'] == 0){ ?>
				                			<?php echo $usr['hora_salida']; ?>
				                		<?php }?>

				                		<?php if($usr['status_tipos'] == 1){ ?>
				                			Descuento
				                		<?php }?>

				                		<?php if($usr['status_tipos'] == 2){ ?>
				                			Herramientas
				                		<?php }?>

				                		<?php if($usr['status_tipos'] == 3){ ?>
				                			EPP
				                		<?php }?>
				                	</td>
                                        <?php 
                                            $datetime1 = new DateTime($usr['hora_entrada']);
                                            $datetime2 = new DateTime($usr['hora_salida']);
                                            $interval = $datetime1->diff($datetime2);
                                            $diferencia = $interval->format("%H:%I");
                                            $rest = substr($diferencia, 0, -3);
                                            $day_num = $usr['day_num']; 

                                                if($day_num == 6 || $day_num == 7){
                                                    if($rest == 5){
                                                        $op_day = "1 Día";
                                                    } 
                                                if($rest <= 9){
                                                    $total = $rest - 5;
                                                    $op_day = "1 dia ".$total."Hrs";
                                                    // echo "menor";
                                                }

                                                }else{
                                                    if($rest < 10){
                                                        $total = $rest - 2;
                                                        // echo "menor";
                                                        $op_day = $total."Hrs";
                                                    }

                                                    if($rest > 10){
                                                        $total = $rest - 10;
                                                        // echo "mayor";
                                                        $op_day = "1 día"." ".$total."Hrs";
                                                    }

                                                    if($rest == 10){
                                                        $monto = $dia_pago;
                                                        // echo "igual";
                                                        $op_day = "1 día";
                                                    }
                                                }
                                         ?>
				                  	<td>
                                        <?php if($usr['solicitud_prestamo']==0){ ?>
                                            <?php echo $op_day; ?>
                                        <?php } ?> 
				                  	</td>

				                  	<td>
				                  		<?php $monto = $usr['monto_pago']; ?>

				                  		<?php if($usr['solicitud_prestamo']==0){ ?>
					                  		<?php if($usr['status_extra'] == 0){ ?>
					                  			<span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo $usr['monto_pago']; ?></span>
					                  		<?php }else{ ?>
					                  			<span  style="font-size:15px; color: green; letter-spacing: 0.1em; font-weight: bold;">$<?php echo $usr['monto_pago']; ?></span>
					                  		<?php } ?>
				                  		<?php }else{ ?>
				                  			<span  style="font-size:15px; color: red; letter-spacing: 0.1em; font-weight: bold;">$<?php echo $usr['monto_pago']; ?></span>
				                  		<?php } ?>
				                  	</td>
				                  <?php }else{ ?>
				                  	<td>00:00</td>
				                  	<td>00:00</td>
				                  	<td>Inasistencia</td>
				                  	<td>
				                  		<?php $monto = 0; ?>
				                  		<span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($monto, 2, '.', ','); ?></span>
				                  	</td>
				                  <?php } ?>
				                  	<td>

					                  	<?php if($usr['solicitud_prestamo'] == 0 ){ ?>

					                  		<a class="delete modal-trigger" data-id="<?php echo $usr["id_pa"]; ?>" data-name="<?php echo $usr['name_personal']; ?> <?php echo $usr['apellido_pa']; ?> <?php echo $usr['apellido_ma']; ?>" data-sitio="<?php echo $usr['nombre']; ?>" data-diapago="<?php echo $usr['dia_pago']; ?>" data-horapago="<?php echo $usr['hora_pago']; ?>" data-dia="<?php echo $usr['day_num']; ?>" data-today="<?php echo $usr['dia']; ?>" data-eventrada="/<?php echo $usr['ev_entrada']; ?>" data-hentrada="<?php echo $usr['hora_entrada']; ?>" data-evsalida="/<?php echo $usr['ev_salida']; ?>" data-hsalida="<?php echo $usr['hora_salida']; ?>" data-extra="<?php echo $usr['status_extra']; ?>" href="#modaldelete"><span class="warning"><i class="fa fa-2x fa-address-card-o" ></i></span></a>
					                  	<?php } ?>

	                                    <?php if($usr['solicitud_prestamo'] != 0 ){ ?>
					                		<?php if($usr['status_tipos'] == 1){ ?>
	                                            <a style="font-size:15px; font-weight: bold;" href="/prestamo/detalleprestamo/id/<?php echo $usr['solicitud_prestamo']; ?>">
	                                            	No. <?php echo $usr['solicitud_prestamo']; ?>
	                                            </a>
					                		<?php }?>

					                		<?php if($usr['status_tipos'] == 2){ ?>
	                                            <a style="font-size:15px; font-weight: bold;" href="/herramienta/costodetail/id/<?php echo $usr['solicitud_prestamo']; ?>">
	                                            	No. <?php echo $usr['solicitud_prestamo']; ?>
	                                            </a>
					                		<?php }?>

					                		<?php if($usr['status_tipos'] == 3){ ?>
	                                            <a style="font-size:15px; font-weight: bold;" href="/epp/eppdetailcosto/id/<?php echo $usr['solicitud_prestamo']; ?>">
	                                            	No. <?php echo $usr['solicitud_prestamo']; ?>
	                                            </a>
					                		<?php }?>
	                                    <?php }?>
				                  	</td>

<!-- 				                  	<td>
				                  		<a href="/asistencia/editregistroasistencia/user/<?php echo $this->personal_id; ?>/sitio/<?php echo $this->sitio_name; ?>/id/<?php echo $usr['id_pa'] ?>/proyecto/<?php echo $this->proyecto ?>"><i class="fa fa-2x fa-pencil-square-o" ></i></a>
				                  	</td> -->
				                  	<?php $montos = $montos + $monto; ?>
				                </tr>
				            </tbody>
				            <?php } }else{ ?>
				            <tbody>
				                <tr>
				                    <td>No hay registros de la asistencia </td>
				                    <td></td>
				                    <td></td>
				                    <td></td>
				                    <td></td>
				                </tr>
				            </tbody>
				            <?php } ?>
				        </table>
	          		</div>	
	          	</div>

	          	<div class="row">
	          		<div class="col m12 s12 text-right">
	          			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($montos, 2, '.', ','); ?></span>
	          		</div>
	          	</div>

	        </div>
      	</div>
    </div>
</div>

<!-- Modal Structure -->
<div id="modaldelete" class="modal modal-fixed-footer">
    <div class="modal-content">
        <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalle de la Asistencia</span>
        <div class="row div_info">
        	<div class="col m8 s12" style="margin-top: 20px;">
<!-- 				<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Sitio Actual:</span> <span id="sitio_modal"></span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nombre:</span> <span id="name_modal"></span> <br> -->

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Día Pago:</span> $<span id="diapago_modal"></span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Hora Pago:</span> $<span id="horapago_modal"></span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Día Asistencia:</span> <span id="dia_modal"></span> <span id="today_modal"></span><br>
        		<span style="font-size:16px; color:green; letter-spacing: 0.1em; font-weight: bold;" id="extra_modal" class="oculto">Horas Extra</span>
        	</div>

        	<div class="col m4 s12 text-center">
        		
        	</div>
        </div>

        <div class="row div_info">
        	<div class="col m6 s12 text-center">
        		<div>
        			<span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Entrada:</span> 
        		</div>
        		<div>
        			<span id="hentrada_modal"></span>
        		</div>
        		<a class="example-image-link" id="href_entrada" data-lightbox="example-1"><img class="example-image" id="img_entrada" alt="image-1" style="width: 250px; height: 150px;"/></a>	  
        	</div>
        	<div class="col m6 s12 text-center">
        		<div>
        			<span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Salida:</span> 
        		</div>
        		<div>
        			<span id="hsalida_modal"></span>
        		</div>
        		<a class="example-image-link" id="href_salida" data-lightbox="example-1"><img class="example-image" id="img_salida" alt="image-1" style="width: 250px; height: 150px;"/></a>	  
        	</div>
        </div>


        <div class="row div_editinfo oculto">
        	<div class="col m12 s12" style="margin-top: 20px;">
		        <div class="input-field col s6">
		        	<input placeholder="" id="edit_day" type="hidden" class="validate">
		        </div>
        	</div>
        </div>

    </div>
    <div class="modal-footer">
        <!-- <button type="button" id="add_inasistencia" class="btn">Guardar</button> -->
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>

<script src="/js/lightbox.js"></script>

<script type="text/javascript">
  	$(document).ready(function(){
  		$('.timepicker').timepicker();
    	$('.modal').modal();
    	$('.datepicker').datepicker( {"format":'dd-mm-yyyy'});
    	var currentDate = document.getElementById("today_picker").value; 
    	$('.datepicker').datepicker( {"format":'dd-mm-yyyy'} ).datepicker("setDate",currentDate);

    	$('select').formSelect();
    	$('.collapsible').collapsible();
    	$('.dropdown-trigger').dropdown();
  	});

    $(".delete").click(function(){
    	var id = $(this).data('id');

    	var diapago = $(this).data('diapago');
    	document.getElementById("diapago_modal").innerHTML=diapago;

    	var horapago = $(this).data('horapago');
    	document.getElementById("horapago_modal").innerHTML=horapago;

    	var dia = $(this).data('dia');
    	if(dia == 1){ day = "Lunes";} if(dia == 2){ day = "Martes";} if(dia == 3){ day = "Miercoles";}
    	if(dia == 4){ day = "Jueves";} if(dia == 5){ day = "Viernes";} if(dia == 6){ day = "Sabado";}
    	if(dia == 7){ day = "Domingo";}
    	document.getElementById("dia_modal").innerHTML=day;

    	var today = $(this).data('today');
    	document.getElementById("today_modal").innerHTML= "("+today+")";
    	document.getElementById("edit_day").value = today;

    	var img = document.getElementById("img_entrada");
    	var entrada = $(this).data('eventrada');
    	img.src=entrada;

    	var element =document.getElementById("href_entrada");
    	element.href =entrada;

    	var hentrada = $(this).data('hentrada');
    	document.getElementById("hentrada_modal").innerHTML=hentrada;

    	var imgs = document.getElementById("img_salida");
    	var salida = $(this).data('evsalida');
    	imgs.src=salida;

    	var elements =document.getElementById("href_salida");
    	elements.href =salida;

    	var hsalida = $(this).data('hsalida');
    	document.getElementById("hsalida_modal").innerHTML=hsalida;

    	var extra = $(this).data('extra');
    	if(extra == 1){
 			$("#extra_modal").show();
    	}else{
    		$("#extra_modal").hide();
    	}
    });

</script>