<style type="text/css">
	.oculto{
		display: none;
	}

	.table_wrapper{
        overflow-x: auto;
    }
</style>

<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="javascript:window.history.go(-1);" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
    <div class="col m6 s6 text-right">
     	<a class="btn" href="/nomina/pdfnomina/id/<?php echo $this->solicitudid_nomina; ?>/user/<?php echo $this->user_solicitud; ?>"><i class="material-icons right">insert_drive_file</i>Documento</a>
    </div>
</div>

<div class="row"> 
    <div class="col m12 s12 text-center" style="margin-top: 30px;">
        <span style="font-size:28px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalle Nomina</span>
    </div>
</div>

<?php foreach ($this->personal_nomina as $key) {
	$id_user = $key['id'];
	$name_user = $key['nombre'];
	$app_user = $key['apellido_pa'];
	$apm_user = $key['apellido_ma'];
	$imagen = $key['imagen'];
	$puesto = $key['puesto'];
} ?>

<?php foreach ($this->solicitud_nomina as $key) {
	$sitio_solicitud = $key['sitio'];
	$monto_solicitud = $key['monto_nomina'];
	$fecha_soliciutd = $key['solicitud_fecha'];
	$user_solicitud = $key['solicitud_user'];
	$status_aud = $key['status_auditoria'];
	$user_auditoria = $key['user_auditoria'];
	$fecha_auditoria = $key['fecha_auditoria'];
	$comentario_rechazo = $key['comentario_auditoria'];
	$status_pago = $key['status_pago'];
} ?>


<div class="row">
	<div class="col m6 s12"></div>
	<div class="col m6 s12 text-center">
		<div class="row">
			<?php if($status_aud == 0){ ?>
				<?php if($this->rol_user == 1 || $this->rol_user == 8) ?>
				<div class="col m6 s6">
					<div class="chip" id="activo_personal">
						<img src="/img/gris.jpg">
						Autorizar
					</div>
				</div>
				<div class="col m6 s6">
					<div class="chip modal-trigger" href="#rechazo_personal">
						<img src="/img/gris.jpg">
						Rechazar
					</div>
				</div>
			<?php } ?>

			<?php if($status_aud == 1){ ?>
				<div class="col m12 s12 text-center">
					<div class="chip">
						<img src="/img/correct.png">
						Autorizada
					</div>					
				</div>

				<div class="row">
					<div class="col m6 s12">
	          			<span style="font-size:16px;">Auditoria: </span> <br>
	          			<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
	          				<?php echo $user_auditoria; ?>		
	          			</span> 
					</div>
					<div class="col m6 s12">
	          			<span style="font-size:16px;">Fecha: </span> <br>
	          			<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
	          				<?php echo $fecha_auditoria; ?>		
	          			</span> 
					</div>
				</div>
			<?php } ?>

			<?php if($status_aud == 2){ ?>
				<div class="col m12 s12 text-center">
					<div class="chip">
						<img src="/img/rojo.png">
						Rechazada
					</div>					
				</div>

				<div class="row">
					<div class="col m6 s12">
	          			<span style="font-size:16px;">Auditoria: </span> <br>
	          			<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
	          				<?php echo $user_auditoria; ?>		
	          			</span> 
					</div>
					<div class="col m6 s12">
	          			<span style="font-size:16px;">Fecha: </span> <br>
	          			<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
	          				<?php echo $fecha_auditoria; ?>		
	          			</span> 
					</div>
				</div>
			<?php } ?>

		</div>
	</div>
</div>

<div id="rechazo_personal" class="modal modal-fixed-footer">
    <div class="modal-content">
	    <span style="font-size:24px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Rechazar Solicitud</span> 
	    <form action="/nomina/requestchangecambiostatusnominapost" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_comprobante">
		<input type="hidden" name="id" value="<?php echo $this->solicitudid_nomina; ?>">
		<input type="hidden" name="comentario" value="">
		<input type="hidden" name="status" value="2">
		<input type="hidden" name="user" value="<?php echo $this->user_solicitud; ?>">

	    <div class="row">
	        <div class="input-field col s12">
	        	<input id="motivo_rechazo" name="comentario" type="text" class="validate">
	        	<label for="motivo_rechazo">Motivo del Rechazo</label>
	        </div>	    	
	    </div>
		</form>
    </div>
    <div class="modal-footer">
		<button type="button" id="rechazada_form" class="btn">Guardar</button>
		<button  class="modal-close red btn">Cerrar</button>
    </div>
</div>


<div class="row">
    <div class="col s12 m6">
      	<div class="card" style="height: 350px;">
	        <div class="card-content">
	          	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información del Personal</span>

	          	<div class="row">
	          		<div class="col m12 s12" style="margin-top: 20px;">
	          			<span style="font-size:16px;">Personal: </span>
	          			<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $name_user; ?> <?php echo $app_user; ?> <?php echo $apm_user; ?></span> <br>
	          			<span style="font-size:16px;">Puesto: </span>
	          			<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $puesto; ?></span>
	          		</div>	
	          	</div>
	          	<div class="row">
	          		<div class="col m12 s12 text-center">
	          			<a class="example-image-link" href="/<?php echo $imagen; ?>" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $imagen; ?>"  alt="image-1" style="width: 150px; height: 150px;"/></a>
	          		</div>
	          	</div>
	        </div>
      	</div>
    </div>


    <div class="col s12 m6">
      	<div class="card" style="height: 350px;">
	        <div class="card-content">
	          	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información de la Solicitud</span>

	          	<div class="row">
	          		<div class="col m12 s12" style="margin-top: 20px;">
	          			<span style="font-size:16px;">Sitio: </span>
	          			<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $sitio_solicitud; ?> </span> <br>
	          			<span style="font-size:16px;">Fecha Solicitud: </span>
	          			<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $fecha_soliciutd; ?> </span> <br>
	          			<span style="font-size:16px;">Usuario: </span>
	          			<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $user_solicitud; ?></span> <br>
	          			<span style="font-size:16px;">Monto: </span>
	          			<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($monto_solicitud, 2, '.', ','); ?></span>
	          		</div>	
	          	</div>
	        </div>
      	</div>
    </div>
</div>

<?php foreach ($this->solicitud_nomina as $key){ 
	$monto_nomina = $key['monto_nomina'];
}?>


<?php if($status_aud == 2){ ?>
<div class="row">
    <div class="col s12 m12">
      	<div class="card">
	        <div class="card-content">
	        	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Motivo del Rechazo</span>

	        	<div class="row" style="margin-top: 20px;">
	        		<div class="col m12 s12">
			      		<table>
			        		<thead>
			          			<tr>
			              			<th><?php echo $comentario_rechazo; ?></th>
			          			</tr>
			        		</thead>
			      		</table>
	        		</div>
	        	</div>
	        </div>
      	</div>
    </div>
</div>
<?php } ?>


<div class="row">
    <div class="col s12 m12">
      	<div class="card">
	        <div class="card-content">
	        	<div class="row">
	        		<div class="col m6 s6">
	        			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalle de la Nomina</span>
	        		</div>
	        		<div class="col m6 s6 text-right">
	        			
	        		</div>
	        	</div>
	          	

	          	<div class="row">
	          		<div class="col m12 s12 table_wrapper">
				        <table class="table text-left table-hover">
				            <thead>
				                <tr>
				                	<th>Id</th>
									<th>Sitio</th>
									<th>Asistencia</th>
									<th>Entrada</th>
									<th>Salida</th>
									<th>Información dia</th>
									<th>Pago</th>
									<th></th>
				                </tr> 
				            </thead>

				            <?php 
				            $montos = 0;
				            if ($this->detalle_nomina) { 
				                foreach ($this->detalle_nomina as $usr) { ?>
				            <tbody>
				                <tr>
				                	<td><?php echo $usr['id']; ?></td>
				                	<td>
				                		<?php echo $usr['nombre']; ?>
				                	</td>
				                	<td>
				                		<?php echo $usr['dia']; ?>
				                	</td>

				                	<?php if($usr['status_asistencia'] == 0){ ?>
				                	<td>
				                		<?php if($usr['status_tipos'] == 0){ ?>
				                			<?php echo $usr['hora_entrada']; ?>
				                		<?php }?>

				                		<?php if($usr['status_tipos'] == 1){ ?>
				                			Descuento
				                		<?php }?>

				                		<?php if($usr['status_tipos'] == 2){ ?>
				                			Herramientas
				                		<?php }?>

				                		<?php if($usr['status_tipos'] == 3){ ?>
				                			EPP
				                		<?php }?>
				                	</td>
				                	<td>
				                		<?php if($usr['solicitud_prestamo'] == 0){ ?>
				                			<?php echo $usr['hora_salida']; ?>
				                		<?php }?>

				                		<?php if($usr['status_tipos'] == 1){ ?>
				                			Descuento
				                		<?php }?>

				                		<?php if($usr['status_tipos'] == 2){ ?>
				                			Herramientas
				                		<?php }?>

				                		<?php if($usr['status_tipos'] == 3){ ?>
				                			EPP
				                		<?php }?>
				                	</td>
                                        <?php 
                                        $dia_pago = $usr['dia_pago'];
                                            $datetime1 = new DateTime($usr['hora_entrada']);
                                            $datetime2 = new DateTime($usr['hora_salida']);
                                            $interval = $datetime1->diff($datetime2);
                                            $diferencia = $interval->format("%H:%I");
                                            $rest = substr($diferencia, 0, -3);
                                            $day_num = $usr['day_num']; 

                                                if($day_num == 6 || $day_num == 7){
                                                    if($rest == 5){
                                                        $op_day = "1 Día";
                                                    } 
                                                if($rest <= 9){
                                                    $total = $rest - 5;
                                                    $op_day = "1 dia ".$total."Hrs";
                                                    // echo "menor";
                                                }

                                                    if($rest == 10){
                                                        $op_day = "5 Hrs";
                                                    }

                                                }else{
                                                    if($rest <= 9){
                                                        $total = $rest - 2;
                                                        // echo "menor";
                                                        $op_day = $total."Hrs";
                                                    }

                                                    if($rest > 10){
                                                        $total = $rest - 10;
                                                        // echo "mayor";
                                                        $op_day = "1 día"." ".$total."Hrs";
                                                    }

                                                    if($rest == 10){
                                                        $op_day = $rest."Hrs";
                                                    }
                                                }
                                         ?>
				                  	<td>
                                        <?php if($usr['solicitud_prestamo']==0){ ?>
                                            <?php echo $op_day; ?>
                                        <?php } ?> 
				                  	</td>

				                  	<td>
				                  		<?php $monto = $usr['monto_pago']; ?>

				                  		<?php if($usr['solicitud_prestamo']==0){ ?>
					                  		<?php if($usr['status_extra'] == 0){ ?>
					                  			<span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo $usr['monto_pago']; ?></span>
					                  		<?php }else{ ?>
					                  			<span  style="font-size:15px; color: green; letter-spacing: 0.1em; font-weight: bold;">$<?php echo $usr['monto_pago']; ?></span>
					                  		<?php } ?>
				                  		<?php }else{ ?>
				                  			<span  style="font-size:15px; color: red; letter-spacing: 0.1em; font-weight: bold;">$<?php echo $usr['monto_pago']; ?></span>
				                  		<?php } ?>
				                  	</td>
				                  <?php }?>

				                  <?php if($usr['status_asistencia'] == 1){ ?>
				                  	<td>00:00</td>
				                  	<td>00:00</td>
				                  	<td>Inasistencia</td>
				                  	<td>
				                  		<?php $monto = 0; ?>
				                  		<span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($monto, 2, '.', ','); ?></span>
				                  	</td>
				                  <?php } ?>

				                  	<?php if($usr['status_asistencia'] == 2){ ?>

					                  	<td>00:00</td>
					                  	<td>00:00</td>
					                  	<td>Otros..</td>
					                  	<td>
					                  		<?php $monto = $usr['monto_pago']; ?>
					                  		<span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($monto, 2, '.', ','); ?></span>
					                  	</td>
				                  	<?php } ?>

				                  	<td>

					                  	<?php if($usr['solicitud_prestamo'] == 0 ){ ?>
					                  		<?php if($usr['status_asistencia'] == 0){ ?>
					                  			<a class="delete modal-trigger" data-id="<?php echo $usr["id_pa"]; ?>" data-name="<?php echo $usr['name_personal']; ?> <?php echo $usr['apellido_pa']; ?> <?php echo $usr['apellido_ma']; ?>" data-sitio="<?php echo $usr['nombre']; ?>" data-diapago="<?php echo $usr['dia_pago']; ?>" data-horapago="<?php echo $usr['hora_pago']; ?>" data-dia="<?php echo $usr['day_num']; ?>" data-today="<?php echo $usr['dia']; ?>" data-eventrada="/<?php echo $usr['ev_entrada']; ?>" data-hentrada="<?php echo $usr['hora_entrada']; ?>" data-evsalida="/<?php echo $usr['ev_salida']; ?>" data-hsalida="<?php echo $usr['hora_salida']; ?>" data-extra="<?php echo $usr['status_extra']; ?>" href="#modaldelete"><span class="warning"><i class="fa fa-2x fa-address-card-o" ></i></span></a>
					                  		<?php } ?>

					                  		<?php if($usr['status_asistencia'] == 1){ ?>
					                  			<a class="inaistencia modal-trigger" data-id="<?php echo $usr["id_pa"]; ?>" data-name="<?php echo $usr['name_personal']; ?> <?php echo $usr['apellido_pa']; ?> <?php echo $usr['apellido_ma']; ?>" data-sitio="<?php echo $usr['nombre']; ?>" data-diapago="<?php echo $usr['dia_pago']; ?>" data-horapago="<?php echo $usr['hora_pago']; ?>" data-dia="<?php echo $usr['day_num']; ?>" data-today="<?php echo $usr['dia']; ?>" data-eventrada="/<?php echo $usr['ev_entrada']; ?>" data-hentrada="<?php echo $usr['hora_entrada']; ?>" data-evsalida="/<?php echo $usr['ev_salida']; ?>" data-hsalida="<?php echo $usr['hora_salida']; ?>" data-extra="<?php echo $usr['status_extra']; ?>"
					                  			data-motivo="<?php echo $usr['motivo_inasistencia']; ?>" href="#modalinaistencia"><span class="warning"><i class="fa fa-2x fa-address-card-o" ></i></span></a>
					                  		<?php } ?>


					                  		<?php if($usr['status_asistencia'] == 2){ ?>
					                  			<a class="otros modal-trigger" data-id="<?php echo $usr["id_pa"]; ?>" data-name="<?php echo $usr['name_personal']; ?> <?php echo $usr['apellido_pa']; ?> <?php echo $usr['apellido_ma']; ?>" data-sitio="<?php echo $usr['nombre']; ?>" data-diapago="<?php echo $usr['dia_pago']; ?>" data-horapago="<?php echo $usr['hora_pago']; ?>" data-dia="<?php echo $usr['day_num']; ?>" data-today="<?php echo $usr['dia']; ?>" data-eventrada="/<?php echo $usr['ev_entrada']; ?>" data-hentrada="<?php echo $usr['hora_entrada']; ?>" data-evsalida="/<?php echo $usr['ev_salida']; ?>" data-hsalida="<?php echo $usr['hora_salida']; ?>" data-extra="<?php echo $usr['status_extra']; ?>"
					                  			data-motivo="<?php echo $usr['motivo_inasistencia']; ?>" href="#modalotros"><span class="warning"><i class="fa fa-2x fa-address-card-o" ></i></span></a>
					                  		<?php } ?>

					                  	<?php } ?>

	                                    <?php if($usr['solicitud_prestamo'] != 0 ){ ?>
					                		<?php if($usr['status_tipos'] == 1){ ?>
	                                            <a style="font-size:15px; font-weight: bold;" href="/prestamo/detalleprestamo/id/<?php echo $usr['solicitud_prestamo']; ?>">
	                                            	No. <?php echo $usr['solicitud_prestamo']; ?>
	                                            </a>
					                		<?php }?>

					                		<?php if($usr['status_tipos'] == 2){ ?>
	                                            <a style="font-size:15px; font-weight: bold;" href="/herramienta/costodetail/id/<?php echo $usr['solicitud_prestamo']; ?>">
	                                            	No. <?php echo $usr['solicitud_prestamo']; ?>
	                                            </a>
					                		<?php }?>

					                		<?php if($usr['status_tipos'] == 3){ ?>
	                                            <a style="font-size:15px; font-weight: bold;" href="/epp/eppdetailcosto/id/<?php echo $usr['solicitud_prestamo']; ?>">
	                                            	No. <?php echo $usr['solicitud_prestamo']; ?>
	                                            </a>
					                		<?php }?>
	                                    <?php }?>
				                  	</td>

<!-- 				                  	<td>
				                  		<a href="/asistencia/editregistroasistencia/user/<?php echo $this->personal_id; ?>/sitio/<?php echo $this->sitio_name; ?>/id/<?php echo $usr['id_pa'] ?>/proyecto/<?php echo $this->proyecto ?>"><i class="fa fa-2x fa-pencil-square-o" ></i></a>
				                  	</td> -->
				                  	<?php $montos = $montos + $monto; ?>
				                </tr>
				            </tbody>
				            <?php } }else{ ?>
				            <tbody>
				                <tr>
				                    <td>No hay registros de la asistencia </td>
				                    <td></td>
				                    <td></td>
				                    <td></td>
				                    <td></td>
				                </tr>
				            </tbody>
				            <?php } ?>
				        </table>
	          		</div>	
	          	</div>

	          	<div class="row">
	          		<div class="col m6 s6 text-right">
	          			<span style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Monto Real: $<?php echo number_format($montos, 2, '.', ','); ?></span>
	          		</div>

	          		<div class="col m6 s6 text-right">
						<?php 
							$num = $montos;
							$multi = 5;
 
							if (fmod($num, $multi) <> 0) {
    							$valor_suma = $num-fmod($num, $multi)+$multi;
							} else {
    							$valor_suma = $num;
							}
						?>

						<span style="font-size:20px; color: green; letter-spacing: 0.1em; font-weight: bold;">Monto a pagar: $<?php echo number_format($valor_suma); ?></span>          			

	          		</div>
	          	</div>
	        </div>
      	</div>
    </div>
</div>



<?php if($status_aud == 1){ ?>
<div class="row">
    <div class="col s12 m12">
      	<div class="card">
	        <div class="card-content">
	        	<div class="row">
	        		<div class="col m6 s6">
	        			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Pago de la Nomina</span>
	        		</div>
	        		<div class="col m6 s6 text-right">
	        			<?php if($status_pago != 0){?>
	        				<?php if($this->rol_user == 1 || $this->rol_user == 4){ ?>
	        					<a class="btn red" id="delete_pago"><i class="material-icons right">clear</i>Eliminar Pago</a>
	        				<?php } ?>
	        			<?php } ?>
	        		</div>
	        	</div>

	        	<?php if($status_pago == 0){?>
		        	<div class="row">
		        		<form action="/nomina/requestaddstatuspagonomina" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_pago">
		        		<div class="col m12 s12">
					        <div class="input-field col m6 s12">
					          	<input id="pagonomina" name="monto" value="<?php echo $valor_suma ?>" type="number" class="validate">
					          	<label for="pagonomina">Monto Autorizado</label>
					        </div>
							<input type="hidden" name="id_solicitud" value="<?php echo $this->solicitudid_nomina; ?>">
							<input type="hidden" name="user" value="<?php echo $this->user_solicitud; ?>">
						    <div class="file-field input-field col m6 s12">
						    	<div class="btn">
						        	<span>Evidencia</span>
						        	<input type="file" name="url">
						    	</div>
						    	<div class="file-path-wrapper">
						        	<input class="file-path validate" id="valdiation_file" type="text">
						    	</div>
						    </div>
		        		</div>
		        		</form>
		        	</div>

		        	<div class="row">
		        		<div class="col m12 s12 text-center">
		        			<a class="btn" id="add_pagonomina"><i class="material-icons right">send</i>Guardar Pago</a>
		        		</div>
		        	</div>
	        	<?php } ?>


	        	<div class="row" style="margin-top: 20px;">
	        		<div class="col m12 s12 table_wrapper">
			      		<table>
			        		<thead>
					        	<tr>
					            	<th>Id</th>
					            	<th>Evidencia</th>
					            	<th>Fecha pago</th>
					            	<th>Usuario pago</th>
					            	<th>Pago</th>
					          	</tr>
			        		</thead>

							<?php
							if ($this->pago_nomina) { 
							foreach ($this->pago_nomina as $usr) { ?>
							<tbody>
								<tr>
									<td>
										<h5><?php echo $usr['id']; ?></h5>
									</td>
									<td>
										<?php echo $usr['evidencia_pago']; ?>
									</td>
									<td>
										<?php echo $usr['fecha_pago']; ?>
									</td>
									<td>
										<?php echo $usr['user_pago']; ?>
									</td>
									<td>
										<h4 style="font-weight: bold;">
											$<?php echo number_format($usr['pago_nomina'], 2, '.', ','); ?>
										</h4>
									</td>
								</tr>
						    <?php } }else{ ?>
						    </tbody> 
						    <tbody>
						        <tr>
						            <td class="text-center" colspan="6"><h4>No hay Pagos realizados.</h4></td>
						        </tr>
						    </tbody>
						                
						    <?php } ?>
			      		</table>
	        		</div>
	        	</div>
	        </div>
      	</div>
    </div>
</div>
<?php } ?>


<!-- Modal Structure -->
<div id="modaldelete" class="modal modal-fixed-footer">
    <div class="modal-content">
        <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalle de la Asistencia</span>
        <div class="row div_info">
        	<div class="col m8 s12" style="margin-top: 20px;">
<!-- 				<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Sitio Actual:</span> <span id="sitio_modal"></span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nombre:</span> <span id="name_modal"></span> <br> -->

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Día Pago:</span> $<span id="diapago_modal"></span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Hora Pago:</span> $<span id="horapago_modal"></span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Día Asistencia:</span> <span id="dia_modal"></span> <span id="today_modal"></span><br>
        		<span style="font-size:16px; color:green; letter-spacing: 0.1em; font-weight: bold;" id="extra_modal" class="oculto">Horas Extra</span>
        	</div>

        	<div class="col m4 s12 text-center">
        		
        	</div>
        </div>

        <div class="row div_info">
        	<div class="col m6 s12 text-center">
        		<div>
        			<span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Entrada:</span> 
        		</div>
        		<div>
        			<span id="hentrada_modal"></span>
        		</div>
        		<a class="example-image-link" id="href_entrada" data-lightbox="example-1"><img class="example-image" id="img_entrada" alt="image-1" style="width: 250px; height: 150px;"/></a>	  
        	</div>
        	<div class="col m6 s12 text-center">
        		<div>
        			<span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Salida:</span> 
        		</div>
        		<div>
        			<span id="hsalida_modal"></span>
        		</div>
        		<a class="example-image-link" id="href_salida" data-lightbox="example-1"><img class="example-image" id="img_salida" alt="image-1" style="width: 250px; height: 150px;"/></a>	  
        	</div>
        </div>

        <div class="row div_editinfo oculto">
        	<div class="col m12 s12" style="margin-top: 20px;">
		        <div class="input-field col s6">
		        	<input placeholder="" id="edit_day" type="hidden" class="validate">
		        </div>
        	</div>
        </div>

    </div>
    <div class="modal-footer">
        <!-- <button type="button" id="add_inasistencia" class="btn">Guardar</button> -->
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>




<!-- Modal Structure -->
<div id="modalinaistencia" class="modal modal-fixed-footer">
    <div class="modal-content">
        <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalle de la Inasistencia</span>
        <div class="row div_info">
        	<div class="col m8 s12" style="margin-top: 20px;">

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Día Pago:</span> $<span id="diapago_modal_in"></span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Hora Pago:</span> $<span id="horapago_modal_in"></span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Día Asistencia:</span> <span id="dia_modal_in"></span> <span id="today_modal_in"></span><br>
        		<span style="font-size:16px; color:green; letter-spacing: 0.1em; font-weight: bold;" id="extra_modal_in" class="oculto">Horas Extra</span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Motivo Inasistencia:</span> <span id="motivo_modal_in"></span> 
        	</div>

        	<div class="col m4 s12 text-center">
        		
        	</div>
        </div>

        <div class="row div_editinfo oculto">
        	<div class="col m12 s12" style="margin-top: 20px;">
		        <div class="input-field col s6">
		        	<input placeholder="" id="edit_day" type="hidden" class="validate">
		        </div>
        	</div>
        </div>

    </div>
    <div class="modal-footer">
        <!-- <button type="button" id="add_inasistencia" class="btn">Guardar</button> -->
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>


<!-- Modal Structure -->
<div id="modalotros" class="modal modal-fixed-footer">
    <div class="modal-content">
        <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Otro Concepto de pago</span>
        <div class="row div_info">
        	<div class="col m8 s12" style="margin-top: 20px;">

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Día Pago:</span> $<span id="diapago_modal_ot"></span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Hora Pago:</span> $<span id="horapago_modal_ot"></span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Día Asistencia:</span> <span id="dia_modal_ot"></span> <span id="today_modal_ot"></span><br>
        		<span style="font-size:16px; color:green; letter-spacing: 0.1em; font-weight: bold;" id="extra_modal_ot" class="oculto">Horas Extra</span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Motivo:</span> <span id="motivo_modal_ot"></span> 
        	</div>

        	<div class="col m4 s12 text-center">
        		
        	</div>
        </div>

        <div class="row div_editinfo oculto">
        	<div class="col m12 s12" style="margin-top: 20px;">
		        <div class="input-field col s6">
		        	<input placeholder="" id="edit_day" type="hidden" class="validate">
		        </div>
        	</div>
        </div>

    </div>
    <div class="modal-footer">
        <!-- <button type="button" id="add_inasistencia" class="btn">Guardar</button> -->
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>


<form>

	<input type="hidden" id="sol_nomina" value="<?php echo $this->solicitudid_nomina; ?>">
	<input type="hidden" id="comentario_nomina" value="">
	<input type="hidden" id="status_nomina" value="1">


<script src="/js/lightbox.js"></script>
<script type="text/javascript">
  	$(document).ready(function(){
  		$('.timepicker').timepicker();
    	$('.modal').modal();
    	$('.datepicker').datepicker( {"format":'dd-mm-yyyy'});
    	var currentDate = document.getElementById("today_picker").value; 
    	$('.datepicker').datepicker( {"format":'dd-mm-yyyy'} ).datepicker("setDate",currentDate);

    	$('select').formSelect();
    	$('.collapsible').collapsible();
    	$('.dropdown-trigger').dropdown();
  	});

    $(".delete").click(function(){
    	var id = $(this).data('id');

    	var diapago = $(this).data('diapago');
    	document.getElementById("diapago_modal").innerHTML=diapago;

    	var horapago = $(this).data('horapago');
    	document.getElementById("horapago_modal").innerHTML=horapago;

    	var dia = $(this).data('dia');
    	if(dia == 1){ day = "Lunes";} if(dia == 2){ day = "Martes";} if(dia == 3){ day = "Miercoles";}
    	if(dia == 4){ day = "Jueves";} if(dia == 5){ day = "Viernes";} if(dia == 6){ day = "Sabado";}
    	if(dia == 7){ day = "Domingo";}
    	document.getElementById("dia_modal").innerHTML=day;

    	var today = $(this).data('today');
    	document.getElementById("today_modal").innerHTML= "("+today+")";
    	document.getElementById("edit_day").value = today;

    	var img = document.getElementById("img_entrada");
    	var entrada = $(this).data('eventrada');
    	img.src=entrada;

    	var element =document.getElementById("href_entrada");
    	element.href =entrada;

    	var hentrada = $(this).data('hentrada');
    	document.getElementById("hentrada_modal").innerHTML=hentrada;

    	var imgs = document.getElementById("img_salida");
    	var salida = $(this).data('evsalida');
    	imgs.src=salida;

    	var elements =document.getElementById("href_salida");
    	elements.href =salida;

    	var hsalida = $(this).data('hsalida');
    	document.getElementById("hsalida_modal").innerHTML=hsalida;

    	var extra = $(this).data('extra');
    	if(extra == 1){
 			$("#extra_modal").show();
    	}else{
    		$("#extra_modal").hide();
    	}
    });

    $(".inaistencia").click(function(){
    	var id = $(this).data('id');

    	var diapago = $(this).data('diapago');
    	document.getElementById("diapago_modal_in").innerHTML=diapago;

    	var motivo = $(this).data('motivo');
    	document.getElementById("motivo_modal_in").innerHTML=motivo;

    	var horapago = $(this).data('horapago');
    	document.getElementById("horapago_modal_in").innerHTML=horapago;

    	var dia = $(this).data('dia');
    	if(dia == 1){ day = "Lunes";} if(dia == 2){ day = "Martes";} if(dia == 3){ day = "Miercoles";}
    	if(dia == 4){ day = "Jueves";} if(dia == 5){ day = "Viernes";} if(dia == 6){ day = "Sabado";}
    	if(dia == 7){ day = "Domingo";}
    	document.getElementById("dia_modal_in").innerHTML=day;

    	var today = $(this).data('today');
    	document.getElementById("today_modal_in").innerHTML= "("+today+")";
    	document.getElementById("edit_day_in").value = today;

    	var element =document.getElementById("href_entrada_in");
    	element.href =entrada;

    	var hentrada = $(this).data('hentrada');
    	document.getElementById("hentrada_modal_in").innerHTML=hentrada;

    	var elements =document.getElementById("href_salida_in");
    	elements.href =salida;

    	var hsalida = $(this).data('hsalida');
    	document.getElementById("hsalida_modal_in").innerHTML=hsalida;

    	var extra = $(this).data('extra');
    	if(extra == 1){
 			$("#extra_modal").show();
    	}else{
    		$("#extra_modal").hide();
    	}
    });


    $(".otros").click(function(){
    	var id = $(this).data('id');

    	var diapago = $(this).data('diapago');
    	document.getElementById("diapago_modal_ot").innerHTML=diapago;

    	var motivo = $(this).data('motivo');
    	document.getElementById("motivo_modal_ot").innerHTML=motivo;

    	var horapago = $(this).data('horapago');
    	document.getElementById("horapago_modal_ot").innerHTML=horapago;

    	var dia = $(this).data('dia');
    	if(dia == 1){ day = "Lunes";} if(dia == 2){ day = "Martes";} if(dia == 3){ day = "Miercoles";}
    	if(dia == 4){ day = "Jueves";} if(dia == 5){ day = "Viernes";} if(dia == 6){ day = "Sabado";}
    	if(dia == 7){ day = "Domingo";}
    	document.getElementById("dia_modal_ot").innerHTML=day;

    	var today = $(this).data('today');
    	document.getElementById("today_modal_ot").innerHTML= "("+today+")";
    	document.getElementById("edit_day_ot").value = today;

    	var element =document.getElementById("href_entrada_ot");
    	element.href =entrada;

    	var hentrada = $(this).data('hentrada');
    	document.getElementById("hentrada_modal_ot").innerHTML=hentrada;

    	var elements =document.getElementById("href_salida_ot");
    	elements.href =salida;

    	var hsalida = $(this).data('hsalida');
    	document.getElementById("hsalida_modal_ot").innerHTML=hsalida;

    	var extra = $(this).data('extra');
    	if(extra == 1){
 			$("#extra_modal").show();
    	}else{
    		$("#extra_modal").hide();
    	}
    });


    $("#activo_personal").click(function(){
    	var id = document.getElementById("sol_nomina").value;
    	var status = document.getElementById("status_nomina").value;
    	var comentario = document.getElementById("comentario_nomina").value;
		swal({
			title: "Estas seguro de cambiar el status de la solicitud?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
		        swal("Espere un momento, la información esta siendo procesada", {
		          icon: "success",
		          buttons: false,
		        });  

	    		var dato = "1";
	            var request = $.ajax({
	                url:"/nomina/requestchangecambiostatusnomina",
	                method:"POST",
	                data: {id:id, status:status, comentario:comentario },
	                processData: true,
	            });
	//-------------------end de ajax---------------------------
	//-------------peticion de respuesta de ajax------------------
	            request.done(function(response) {
	                console.log(response);//imprime lo que responde el ajax
	                // alert
	                window.location.reload(true);
	            });
	//-------------------end de respuesta ajax---------------------
	            return false;


		  	} else {
		    	swal("Accion cancelada!");
		  	}
		});
    });

    $("#rechazada_form").click(function(){
    	var motivo_rechazo = document.getElementById("motivo_rechazo").value;

    	if(motivo_rechazo == ""){
            swal({
            	title: "Para continuar debes agregar el motivo por el cual se rechazara la solicitud",
            });
    	}else{
	        swal("Espere un momento, la información esta siendo procesada", {
	        	icon: "success",
	        	buttons: false,
	        });  
	        setTimeout(submitrechzar, 1500);
    	}
    });

    function submitrechzar() { document.getElementById("submit_comprobante").submit() }

    $("#add_pagonomina").click(function(){
    	var file = document.getElementById("valdiation_file").value;
    	var pagonomina = document.getElementById("pagonomina").value;

    	if(motivo_rechazo == ""){
            swal({
            	title: "Para continuar debes agregar el motivo por el cual se rechazara la solicitud",
            });
    	}else{
	        swal("Espere un momento, la información esta siendo procesada", {
	        	icon: "success",
	          	buttons: false,
	        });  
	        setTimeout(submitpagonomina, 1500);
    	}
    });
    function submitpagonomina() { document.getElementById("submit_pago").submit() }


    $("#delete_pago").click(function(){
    	var id = document.getElementById("sol_nomina").value;
		swal({
			title: "Estas seguro de eliminar el pago?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
		        swal("Espere un momento, la información esta siendo procesada", {
		        	icon: "success",
		        	buttons: false,
		        });  

	    		var dato = "1";
	            var request = $.ajax({
	                url:"/nomina/requestdeletepagonomina",
	                method:"POST",
	                data: {id:id},
	                processData: true,
	            });
	//-------------------end de ajax---------------------------
	//-------------peticion de respuesta de ajax------------------
	            request.done(function(response) {
	                console.log(response);//imprime lo que responde el ajax
	                // alert
	                window.location.reload(true);
	            });
	//-------------------end de respuesta ajax---------------------
	            return false;
		  	} else {
		    	swal("Accion cancelada!");
		  	}
		});
    });

</script>