
<?php 
    function isActhref($nameBtn,$urlname){
        if($nameBtn==1 && $urlname==null){
            return "active"; 
        }
        return ($nameBtn == $urlname)?"active":"";
    }

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

    if($this->total== 1){
        $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
    }else{

        if ($this->total >= 1 && $pagina <= $this->total) {
            
            if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
            }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
            }

            $i = max(2, $pagina - 3);

            if ($i > 2)
                $links .= " <li><a>...</a></li> ";
            for (; $i < min($pagina + 3, $this->total); $i++) {
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                }
            }

            if ($i != $this->total)
                $links .= " <li><a>...</a></li> ";
            if($i ==$this->actpage){
                $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
            }else{
                $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
            }
        }           
    }
?>

<style type="text/css">
    .oculto{display: none;}
    .active_menu{
        -webkit-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
        -moz-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
        box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
    }
    .table_wrapper{
        overflow-x: auto;
    }
</style>

<?php 
    $status =  $this->status_documento;
?>

<div class="row" style="margin-top: 20px;">
  	<div class="col m12 s12">
    		<ul>
      			<?php if($status == 1){ ?>
      	    		<li class="tab col s3 active_menu">
        	    			<a class="" href="/nomina/listanominamgr/status/1">
            	    			<h4>Finalizadas
            	  					  <div class="chip">
            	    					    <?php echo $this->enproceso; ?>
            	  					  </div>
            	    			</h4>
        	    			</a>
      	    		</li>
      			<?php }else{ ?>
      	    		<li class="tab col s3">
        	    			<a class="" href="/nomina/listanominamgr/status/1">
            	    			<h4>Finalizadas
              	  					<div class="chip">
              	    					  <?php echo $this->enproceso; ?>
              	  					</div>
            	    			</h4>
        	    			</a>
      	    		</li>
      			<?php } ?>

      			<?php if($status == 2){ ?>
        				<li class="tab col s3 active_menu">
          					<a href="/nomina/listanominamgr/status/2"><h4>Rechazadas</h4></a>
          					<div></div>
        				</li>
      			<?php }else{ ?>
      				  <li class="tab col s3"><a href="/nomina/listanominamgr/status/2"><h4>Rechazadas</h4></a></li>
      			<?php } ?>	
    		</ul>
  	</div>
</div>


<div class="row">
  	<div class="col m1 s12"></div>
  	<div class="col m10 s12">
    		<div class="row">
      			<div class="col m5 s6">
      				  <div class="input-field col s12">
        			    	<select id="search_op">
        			      		<option value="1" selected>Sitio</option>
        			      		<option value="2">Id solicitud</option>
        			    	</select>
      			    	  <label>Buscar por:</label>
      			  	</div>
      			</div>
      			<div class="col m5 s6">
      		      <div class="input-field col s12 op_sitio">
      		          <input placeholder="Ingresa el nombre del sitio" id="sitio_search" type="text" class="validate">
      		          <label for="sitio_search">Sitio</label>
      		      </div>

      		      <div class="input-field col s12 oculto op_id">
      		          <input  id="id_search" type="number" class="validate">
      		          <label for="id_search">Id solicitud</label>
      		      </div>
      			</div>

      			<div class="col m2 s12 text-center op_sitio">
      				  <a class="btn" id="btn_sitio"><i class="material-icons right">search</i></a>
      			</div>

      			<div class="col m2 s12 text-center oculto op_id">
      				  <a class="btn" id="btn_id"><i class="material-icons right">search</i></a>
      			</div>
    		</div>
  	</div>
  	<div class="col m1 s12"></div>
</div>


<div class="row">
  	<div class="col m12 s12">
        <div class="row">
            <div class="col m8 s8">
                <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de solicitudes de Nomina</span>
	      	  </div>
	      	  <div class="col m4 s4 text-right">
            </div>
	      </div>

        <div class="row">
            <div class="col m12 s12 table_wrapper">
                <table class="table text-left table-hover">
                    <thead>
                    		<tr style="background-color: #EDEDED;">
                      			<th class="text-center">NO.</th>
                      			<th class="text-center">Sitio</th> 
                      			<th class="text-center">Fecha Auditada</th>
                      			<th class="text-center">Monto</th>  
                      			<th class="text-center">Status</th>
                      			<th class="text-center"></th>
                    		</tr> 
      		          </thead>
                    <?php if ($this->paginator) { 
                        foreach ($this->paginator as $usr) { ?>
                            <tbody>
                                <tr>
                              			<td class="text-center">
                                        <h5><?php echo $usr['id']; ?></h5>
                              			</td>
                              			<td class="text-center">
                                        <h5><?php echo $usr['sitio']; ?></h5>
                              			</td>
                              			<td class="text-center">
                                  			<h5>
                                    				<?php echo $usr['fecha_auditoria']; ?>
                                  			</h5>
                              			</td>
 
                                    <td class="text-center">
                                        <?php 
                                            $num = $usr['monto'];
                                            $multi = 5;

                                            if (fmod($num, $multi) <> 0) {
                                                $valor_suma = $num-fmod($num, $multi)+$multi;
                                            } else {
                                                $valor_suma = $num;
                                            }
                                        ?>
                                        <span style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($valor_suma); ?></span>  
                                    </td>

                                    <td class="text-center">
                                        <?php if($usr['status'] == 1){ ?>
                                    				<div class="chip" id="activo_personal">
                                        				<img src="/img/correct.png" >
                                        				Finalizada
                                      			</div>
            			                      <?php } ?>

                                        <?php if($usr['status'] == 2){ ?>
                                            <div class="chip" id="activo_personal">
                                                <img src="/img/rojo.png" >
                                                Rechazado
                                            </div>
                                        <?php } ?>
          			                    </td>
                              			<td class="text-center">
                                        <a href="/nomina/detallemgrnom/id/<?php echo $usr["id"] ?>"><i class="fa fa-2x fa-id-card-o"></i></a>
                              			</td> 
                                </tr>
                    <?php } }else{ ?>
                          </tbody> 
                          <tbody>
                              <tr>
                                  <td class="text-center" colspan="6"><h4>No hay solicitudes de Nominas.</h4></td>
                              </tr>
                          </tbody>
                    <?php } ?>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
                  <?php if($pagina - 1 == 0){ ?>
                      <li class="page-item disabled">
                          <span class="page-link">Anterior</span>
                      </li>
                  <?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
                  <?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
                  <?php if($pagina >= $this->total): ?>
                        <li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                        </li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>

<input type="hidden" id="status_op" value="<?php echo $this->status_documento; ?>">
<input type="hidden" id="buscador" value="1">
<script type="text/javascript">
  	$("#search_op").on('change', function() {
    		var value = this.value;
    		document.getElementById("buscador").value= value;

    		if(value == 1){
    			$(".op_sitio").show();
    			$(".op_id").hide();
    		}
    		if(value == 2){
    			$(".op_id").show();
    			$(".op_sitio").hide();
    		}
  	});

	$("#btn_sitio").click(function(){
		  var sitio = document.getElementById("sitio_search").value;
		  var status = document.getElementById("status_op").value;
		  swal({
          title: "La busqueda sera por el sitio, Desea continuar?",
			    icon: "warning",
			    buttons: true,
			    dangerMode: true,
      })

      .then((willDelete) => {
          if (willDelete) {
              swal("Espere un momento, la información esta siendo procesada", {
                  icon: "success",
					        buttons: false,
				      }); 
			        window.location.href = "/nomina/searchsolnominamgr/status/"+status+"/sitio/"+sitio+"/op/1";
		      } else {
		          swal("La asignacion fue cancelada!");
		      }
      });
  });

	$("#btn_id").click(function(){
		  var id = document.getElementById("id_search").value;
		  var status = document.getElementById("status_op").value;

      swal({
          title: "La busqueda sera por el sitio, Desea continuar?",
			    icon: "warning",
			    buttons: true,
			    dangerMode: true,
      })
      .then((willDelete) => {
          if (willDelete) {
              swal("Espere un momento, la información esta siendo procesada", {
                  icon: "success",
					        buttons: false,
				      }); 
			        window.location.href = "/nomina/searchsolnominamgr/status/"+status+"/id/"+id+"/op/2";
		      } else {
              swal("La asignacion fue cancelada!");
		      }
      });
  });
</script>