
<?php foreach ($this->Personal as $pc) { 
	$imagen = $pc['imagen'];   
	$nombre =$pc['nombre']; 
	$apellidopa =$pc['apellido_pa']; 
	$apellidoma =$pc['apellido_ma']; 
	$idps = $pc['id']; 
} ?>

<?php foreach ($this->herramienta as $hc) { 
	$herpersonal = $hc['id_responsable'];  
} ?>


<style type="text/css">
	.table_wrapper{
		overflow-x: auto;
	}
</style>

<!-- INICIO DETAIL-->
<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/herramienta/regresarh" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
    </div>
</div>
<!-- END INICIO DETAIL-->

<!-- INICIO Nombre Personal-->
<?php foreach ($this->Personal as $per) { ?>
<div class="row mt-4">
	<div class="col m12 s12 text-center">
		<div class="col m12 s12 " style="margin-top: 10px;">
			<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Herramientas asignadas a:
		</div>
		<h2> <?php echo $per["nombre"]; ?> <?php echo $per["apellido_pa"]; ?> <?php echo $per["apellido_ma"]; ?></h2>
	</div>
</div>
<?php } ?>
<!-- END Nombre Personal-->
 
<!--Inicio Botones Responsivas-->
<div class="col m12 s12">
	<div class="col m4 s12 text-center"></div>
	<div class="col m8 s12 text-center">
		<?php if ($this->herramienta) {  ?>
			<div class="col m12 s12">
				<div class="input-field col m4 s4">
					<a class="waves-effect darken-1 waves-light lighten-4 btn modal-trigger" href="/herramienta/responsivah/id/<?php echo $herpersonal; ?>">Responsiva</a>
				</div>
				<div class="input-field col m4 s4">
					<a class="waves-effect darken-1 waves-light lighten-4 btn modal-trigger" href="/herramienta/historialh/id/<?php echo $herpersonal; ?>">Historial</a>
				</div>
				<?php if ($this->cobros) {  ?>
					<div class="input-field col m4 s4">
						<a class="waves-effect darken-1 waves-light lighten-4 btn modal-trigger" href="/herramienta/cobroh/id/<?php echo $herpersonal; ?>">Ficha Cobro</a>
					</div>	
				<?php } else {}?>
			</div>
		<?php } else {?>
			<div class="col m12 s12">
				<div class="input-field col m6 s6">
					<a class="waves-effect darken-1 waves-light lighten-4 btn modal-trigger" href="/herramienta/historialh/id/<?php echo $idps; ?>">Historial</a>
				</div>
				<?php if ($this->cobros) {  ?>
					<div class="input-field col m6 s6">
						<a class="waves-effect darken-1 waves-light lighten-4 btn modal-trigger" href="/herramienta/cobroh/id/<?php echo $idps; ?>">Ficha Cobro</a>
					</div>	
				<?php } else {}?>
			</div>
		<?php } ?>
	</div>
</div>
<!--End Botones -->

<!-- Inicio Panel Inicial-->
<div class="row">
	<div class="col m4 s12 text-center">
		<?php if($imagen== null){ ?>
			<img src="/img/no_disponible1.png" class="responsive-img" style="width: 200px; margin-top: 5px;">
		<?php }else{ ?>
			<a class="example-image-link" href="/<?php echo $imagen; ?>" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $imagen; ?>" id="camara_div" alt="<?php echo $nombre; ?>" style="width: 200px;  margin-top: 5px;"/></a>
		<?php } ?>
	</div>

	<div class="col m8 s12 text-center">
		<div class="card darken-1">
			<div class="card-content">
				
				<div class="row">
					<div class="col m12 s12">
						<h3 class="card-title">Detalles Generales:</h3>
		  				<hr>
		          	</div>
		        </div>

		        <div class="row">
		        	<div class="col m12 s12 text-left">
		        		<?php foreach ($this->per as $per ) { ?>
		        			<h5>
		        				<strong><span class="font_tittle">Nombre del personal: </span></strong>
		        				<?php echo $per['nombre']; ?> <?php echo $per["apellido_pa"]; ?> <?php echo $per["apellido_ma"]; ?>
							</h5>
							<h5>
								<strong><span class="font_tittle">Puesto: </span> </strong>
								<?php echo $per['puestop']; ?>
							</h5>
							<h5>
								<strong><span class="font_tittle">Sitio: </span> </strong>
								<?php echo $per['sitio']; ?>
							</h5>
						<?php } ?>
						<?php foreach ($this->contador as $per ) { ?>
							<h5>
								<strong><span class="font_tittle">Número de herramientas Asignadas: </span> </strong>
								<?php echo $per['Asignadas']; ?>
							</h5>
						<?php } ?>
					</div>
		        </div>
		    </div>
	    </div>
	</div>
</div>
<!-- End Panel Inicial-->

<!-- Inicio Regresar Herramientas-->
<div class="col m12 s12 text-center">
	<div class="row">
		<div class="col s12 m12">
			<div class="card darken-1">
				<div class="card-content">
					
					<div class="row">
						<div class="col m12 s12">
							<h3 class="card-title">Herramientas Asignadas</h3>
							<hr>
						</div>
					</div>

					<div class="row table_wrapper">
						<form action="" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="actualizasel">
							<table class="table text-center table-hover ">
								<thead>
									<tr>
										<th>Selección</th>
										<th>ID</th>
										<th class="text-center">Imagen</th>
										<th>Codigo</th>
										<th>Nombre</th>
										<th></th>
									</tr>
								</thead>
								
								<?php if ($this->herramienta) { 
									foreach ($this->herramienta as $her) { ?> 
										<input type="hidden" name="id_h" value="<?php echo $her['id_herramienta']; ?>">
										<input type="hidden" name="idp" value="<?php echo $her['id_responsable']; ?>">
										<tbody>
											<tr>
												<td class="text-center">
													<label>
														<input type="checkbox" name="idh[]" value="<?php echo $her['id_herramienta']; ?>">
														<span></span>
													</label>
												</td>
												<td>
													<?php echo $her['id_herramienta']; ?>
												</td>
												<td>
													<?php if($her['imagen'] == null){ ?>
														<img src="/img/no_disponible.png" style="width: 80px;">
													<?php } else { ?>
														<img src="/<?php echo $her["imagen"]; ?>" style="width: 80px;">
													<?php } ?>
												</td>
												<td>
													<?php echo $her['codigo']; ?>
												</td>
												<td>
													<?php echo $her['nombre']; ?>
												</td>	
												<td>
													<a class="liberar waves-effect green darken-1 waves-light lighten-4 btn" data-id="<?php echo $her["id_herramienta"]; ?>" data-nombre="<?php echo $her["nombre"]; ?>">Liberar</a>
												</td>
											</tr>
										</tbody>
									<?php } }else{ ?>
										<tbody>
											<tr>
												<td></td>
												<td></td>
												<td>No tiene herramientas a su cargo</td>
												<td></td>
												<td></td>
											</tr>
										</tbody>
									<?php } ?>
							</table>
							<?php if ($this->herramienta) { ?> 
							<div class="col s12 m12">
								<div class="col s4 m4">
									<input type="submit" class="btn" name="liberas" value="Liberar Selección"   dir="/herramienta/requestactualizaseleccion" />
								</div>

								<div class="col s4 m4"></div>
								
								<div class="col s4 m4">
									<input type="submit" class=" btn" name="cobrars" value="Baja con Cobro"  dir="/herramienta/requestcobrar" />
								</div>
							</div>	
							<?php  }else{ }?>
						</form>
						<!-- <form action="/herramienta/requestcobrar" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="sub_cobrar">
							<?php if ($this->herramienta) { 
								foreach ($this->herramienta as $her) { ?> 
									<input type="hidden" name="idp" value="<?php echo $her['id_responsable']; ?>">
							<?php } }else{ }?>
						</form> -->
						<form action="/herramienta/requestactualizatodo" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="actualizat">
							<?php if ($this->herramienta) { 
								foreach ($this->herramienta as $her) { ?> 
									<input type="hidden" name="idp" value="<?php echo $her['id_responsable']; ?>">
							<?php } }else{ }?>
						</form>
						

						<?php if ($this->herramienta) { ?> 
							<div class="col s12 m12">
								<div class="col s4 m4"></div>
								<!-- <div class="col s4 m4">
									<button class="btn" name="sel"  id="liberas">Liberar Selección</button>
								</div> -->
								<div class="col s4 m4">
									<button class=" btn"  id="liberato">Liberar Todo</button>
								</div>
								<!-- <div class="col s4 m4">
									<button class=" btn" name="selc" id="cobrars">Baja con Cobro</button>
								</div> -->
								<div class="col s4 m4"></div>
							</div>
						<?php  }else{ }?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Regresar Herramientas-->

<script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script type="text/javascript">

	$(document).ready(function(){
		$("input[type=submit]").click(function() {
			var accion = $(this).attr('dir');
			$('form').attr('action', accion);
			$('form').submit();
		});
	});

	//Inicio liberar1 Ajax
	$(".liberar").click(function(){
		id=$(this).data('id');
		nombre=$(this).data('nombre');
		swal({
			title: "Estas seguro de que regresaron la herramienta "+nombre+"?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})

		.then((willDelete) => {
			if (willDelete) {
				swal("Espera un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				});

				var request = $.ajax({
					url:"/herramienta/requeststatush",
					method:"POST",
					data: { id : id },
					processData: true,
				});
		//-------------------end de ajax---------------------------

		//-------------peticion de respuesta de ajax------------------
				request.done(function(response) {
	                console.log(response);//imprime lo que responde el ajax
	                // alert
	                window.location.reload(true);
	            });
		//-------------------end de respuesta ajax---------------------
				return false;
			} else {
				swal("La accion fue cancelada!");
			}
		});
	});// End liberar 1 Ajax
	

	$("#liberas").click(function(){
		swal({
			title: "¿Estas seguro de deseas habilitar la selección?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})

		.then((willDelete) => {
			if (willDelete) {
				swal("Espera un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				});
				setTimeout(submitForm, 500); 
			} else {
				swal("La accion fue cancelada!");
			}
		});
	});


	function submitForm() {
		document.getElementById("actualizasel").submit()
	}// End Liberar seleccion Ajax


	$("#liberato").click(function(){
		swal({
			title: "¿Estas seguro de que regresaron todas las herramientas?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})

		.then((willDelete) => {
			if (willDelete) {
				swal("Espera un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				});
				setTimeout(submitForm1, 500); 
			} else {
				swal("La accion fue cancelada!");
			}
		});
	});


	function submitForm1() {
		document.getElementById("actualizat").submit()
	}// End Liberar todo Ajax


	$("#cobrars").click(function(){
		swal({
			title: "¿Estas seguro de deseas cobrar la selección?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})

		.then((willDelete) => {
			if (willDelete) {
				swal("Espera un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				});
				// setTimeout(submitForm2, 500); 
			} else {
				swal("La accion fue cancelada!");
			}
		});
	});

	function submitForm2() {
		document.getElementById("actualizat").submit()
	}	// End Liberar todo Ajax
</script>



  