<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/herramienta/categoria" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
    </div>
</div>

<div class="row">
	<div class="col m12 s12 text-center" style="margin-top: 10px;">
		<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Categorías
	</div>
</div>


		<div class="col m12 s12">
			<form action="/herramienta/requestupdatecat" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cat">
			<?php foreach ($this->cat_herramientas as $cat) { ?>
			<input type="hidden" name="ids" value="<?php echo $cat["id_cat"]; ?>">
				<div class="row">
			        <div class="input-field col m12 s12">
			          	<i class="material-icons prefix">account_circle</i>
			          	<input id="name" type="text" name="name" value="<?php echo $cat["nombre"]; ?>" class="validate" required>
			          	<label for="name">* Nombre:</label>
			        </div> 
		      	</div>

		      	 <div class="file-field input-field col m12 s12">
					    <div class="btn">
					        <span>Imagen</span>
					        <input type="file" name="url">
					        <input type="hidden" name="imahidden" value="<?php echo $cat["imagen"]; ?>">   
					    </div>
					    <div class="file-path-wrapper">
					        <input class="file-path validate" type="text">
					    </div>
				
				  </div>
		     <?php } ?>
		    </form>
		</div>

		<div class="input-field col m12 s12 text-right">
			<div class="row">
				<a href="/herramienta/categoria" class="waves-effect red waves-light btn">Cancelar</a>
				<button  id="addcat" class="waves-effect waves-light btn">Actualizar</button>
			</div>	
		</div>


<script type="text/javascript">
    $("#addcat").click(function(){
        var name = document.getElementById("name").value;

        if(name == ""){
            swal({
                title: "Para editar una categoría debes agregarle un nombre",
            });
        }else{
             swal("Espera un momento, la información esta siendo procesada", {
				icon: "success",
			 	buttons: false,
			});
            setTimeout(submitForm, 500);     
        }

    });


    function submitForm() {
        document.getElementById("submit_cat").submit()
    }
</script>