
<?php

require_once'../vendor/autoload.php';

$qrcode = new Zxing\QrReader($_FILES['qrimage']['tmp_name']);;
$text = $qrcode->text();
if ($text != null) {
    $vacio ="Trae datos";
}else {
    $vacio="No trae nada";
}
?>


<head>
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</head>
    <div class="col m12 s12"><br>
        <div class="row ">
            
                <h2>Detalles Herramienta</h2>

                <?php if ($text != null||false) { ?>
                    <p><strong>Datos del código QR:</strong></p>
                    <p><?php echo $text ?></p>  
                <?php } else{ ?>

                    <div class="input-field col m12 s12 ">
                        <div class="col m6 s6  text-center">    
                            <h3><strong style="color: red">No fue posible leer el código.</strong></h3>
                        </div>

                        <div class="input-field col m6 s6  text-center">
                            <a href="/herramienta/escaneaqr" class="waves-effect red waves-light btn">Intenta de nuevo <i class="material-icons left">loop</i></a>
                        </div>
                    </div>
                    <div class="input-field col m12 s12 text-center">
                        <img src="/img/QR/ErrorQR.jpg" style="height: 250px;">
                    </div>

                    
                <?php }  ?>
         
        </div>
    </div>

