<?php 
	function eliminar_acentos($cadena){
		$cadena = str_replace(
		array('Á', 'À', 'Â', 'Ä', 'á', 'à', 'ä', 'â', 'ª'),
		array('A', 'A', 'A', 'A', 'a', 'a', 'a', 'a', 'a'),
		$cadena
		);

		$cadena = str_replace(
		array('É', 'È', 'Ê', 'Ë', 'é', 'è', 'ë', 'ê'),
		array('E', 'E', 'E', 'E', 'e', 'e', 'e', 'e'),
		$cadena );

		$cadena = str_replace(
		array('Í', 'Ì', 'Ï', 'Î', 'í', 'ì', 'ï', 'î'),
		array('I', 'I', 'I', 'I', 'i', 'i', 'i', 'i'),
		$cadena );

		$cadena = str_replace(
		array('Ó', 'Ò', 'Ö', 'Ô', 'ó', 'ò', 'ö', 'ô'),
		array('O', 'O', 'O', 'O', 'o', 'o', 'o', 'o'),
		$cadena );

		$cadena = str_replace(
		array('Ú', 'Ù', 'Û', 'Ü', 'ú', 'ù', 'ü', 'û'),
		array('U', 'U', 'U', 'U', 'u', 'u', 'u', 'u'),
		$cadena );

		$cadena = str_replace(
		array('Ñ', 'ñ', 'Ç', 'ç'),
		array('N', 'n', 'C', 'c'),
		$cadena
		);
		
		return $cadena;
	}
?>

<?php foreach ($this->reporte as $rep) { $id_h = $rep['id_herramienta'];  } ?>

<style> 
	.table_wrapper{
		overflow-x: auto;
	}
</style>

<div class="row" style="margin-top: 10px;">
	<div class="col m6 s12 text-left">
	<!-- 	<a href="/herramienta/herramientadetail/id/<?php echo $id_h; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a> -->
	</div>
	
	<div class="col m6 s12 text-right">
		<a class=" btn" onclick="exportTableToCSV(null,'Reporte_Reparacion.csv')"><i class="material-icons right">file_download</i>Descargar</a>
	</div>
</div>

<div class="col m12 s12 text-right table_wrapper">
	<table class="table text-left table-hover ">
		<thead>
			<tr>
				<th>Id Reparacion</th>
				<th>Id Herramienta</th>		
				<th>Nombre</th>
				<th>Motivo Reparacion</th>
				<th>Fecha Inicio</th>
        		<th>Fecha Regreso</th>
        		<th>Costo</th>
        		<th>Categoria</th>
        		<th>Orden de Compra</th>
			</tr>
		</thead>

		<?php foreach ($this->reporte as $rh) { ?>
		<tbody>
			<tr>
				<td><?php echo $rh["id_reporte"]; ?></td>
				<td><?php echo $rh["id_herramienta"]; ?></td>
				<td><?php echo eliminar_acentos( $rh["nombre"]); ?></td>
				<td><?php echo eliminar_acentos( $rh["motivo"]); ?></td>
				<td><?php echo $rh["fecha_inicio"]; ?></td>
				<td><?php echo $rh["fechaa"]; ?></td>
				<td><?php echo $rh["costo"]; ?></td>
				<td><?php echo $rh["nombrecategoria"]; ?></td>
				<td><?php echo $rh["asignado"]; ?></td>
			</tr>
		</tbody>
		<?php } ?>
	</table>
</div>

<script type="text/javascript">
	function exportTableToCSV(html, filename) {
	    var csv = [];
	    var rows = document.querySelectorAll("table tr");
	    for(var i = 0; i < rows.length; i++){
	        var row = [], cols = rows[i].querySelectorAll("td, th");
	        for(var j = 0; j < cols.length; j++){
	            row.push(cols[j].innerText);
	        }
	        csv.push(row.join(","));
	    }
	    downloadCSV(csv.join("\n"), filename);
	}

	function downloadCSV(csv, filename) {
	    var csvFile;
	    var downloadLink;
		if (window.Blob == undefined || window.URL == undefined || window.URL.createObjectURL == undefined) {
			alert("Your browser doesn't support Blobs");
			return;
		}
		
	    csvFile = new Blob([csv], {type:"text/csv"});
	    downloadLink = document.createElement("a");
	    downloadLink.download = filename;
	    downloadLink.href = window.URL.createObjectURL(csvFile);
	    downloadLink.style.display = "none";
	    document.body.appendChild(downloadLink);
	    downloadLink.click();
	}
</script>