<html>
    <head>
        <style>html { font-size: 14px; font-family: Arial, Helvetica, sans-serif; }</style>
        <title>Multipage PDF Export with Chart and Grid</title>
        <script src="http://code.jquery.com/jquery-1.12.3.min.js"></script>
        <script src="http://kendo.cdn.telerik.com/2016.3.1118/js/kendo.all.min.js"></script>
        <link rel="stylesheet" href="http://kendo.cdn.telerik.com/2016.3.1118/styles/kendo.common.min.css">
        <link rel="stylesheet" href="http://kendo.cdn.telerik.com/2016.3.1118/styles/kendo.default.min.css">
    </head>
    <body>


    <div id="example">

      <?php foreach ($this->herramienta as $her){ 

        $id_herramienta = $her['id_herramienta'];
        $codigo = $her['codigo'];
        $nombre = $her['nombre'];
        $unidad = $her['unidad'];
        $descripcion = $her['descripcion'];
        $imagen = $her['imagen'];
        $status_disponible = $her['status_disponible'];
        $fecha_salida = $her['fecha_salida'];
        $fecha_entrega = $her['fecha_entrega'];
        $fecha_entrega = $her['fecha_entrega'];
        $id_cat_herramienta = $her['id_cat_herramienta'];
        $id_sitio = $her['id_sitio'];
        $tiempo_vida = $her['tiempo_vida'];
        $factura_imagen = $her['factura_imagen'];
        $fecha_compra = $her['fecha_compra'];
        $vencimiento_gar = $her['vencimiento_gar'];
        $marca = $her['marca'];
        $modelo = $her['modelo'];
        $no_serie = $her['no_serie'];
        $factura_numero = $her['factura_numero'];
        $comentario_b = $her['comentario_b'];
        $evidencia_b = $her['evidencia_b'];
        $nombrea = $her['nombrea'];
        $apellido_pa = $her['apellido_pa'];
        $apellido_ma = $her['apellido_ma'];
        $pueston = $her['pueston'];
        $name_sitio = $her['name_sitio'];
        $telefono = $her['telefono'];
        $email = $her['email_personal'];
        $idp = $her['id']; 


    } ?>

    <?php foreach ($this->contador as $con){ 
        $Asignadas = $con['Asignadas'];
    } ?>

    <?php 
            date_default_timezone_set('America/Mexico_City');
            $hoy = date("d/m/Y H:i:s");
    ?>


    <div class="row" style="margin-top: 10px;">
        <div class="col m6 s6">
            <a href="/herramienta/bresponsable?responsable=<?php echo $idp ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
        </div>

        <div class="col m6 s6 text-right" id="download" style="display: none;" >
            <button class="export-pdf btn"  onclick="getPDF('.pdf-page')">Descargar Responsiva</button>
        </div>
    </div>
 

    <div class="page-container hidden-on-narrow">
        <div class="pdf-page size-a4">
            <div class="pdf-header">
                <span class="col m6 s6 company-logo">
                    <img src="/img/head.png" style="width: 130px;" />
                </span>

                <span class="col m6 s6 text-right invoice-number">
                    <img src="/img/logo-2.png" style="width: 220px;" />
                </span>

                <div class="row">
                    <div class="company-logo col m12 s12 text-center">
                        Responsiva de Herramientas
                    </div>
                </div>

                <div class="row">
                    <div class="col m6 s6 for ">
                        <h3> Datos del Personal</h3>
                        <p>
                            <span class="title-pdf">Personal: </span> <?php echo $nombrea; ?> <?php echo $apellido_pa; ?> <?php echo $apellido_ma; ?> <br />
                            <span class="title-pdf">Puesto:</span> <?php echo $pueston; ?><br />
                            <span class="title-pdf">Telefono:</span> <?php echo $telefono; ?><br />
                            <span class="title-pdf">Email:</span> <?php echo $email ?><br/>
                        </p>
                    </div>

                    <div class="col m6 s6 text-right from">
                        <!-- <h3> Fecha de Entrega: <?php echo $hoy; ?></h3> -->
                        <h3> No. Herramientas: <b><?php echo $Asignadas; ?></b></h3>
                    </div>
                </div>

                <div class="row">
                    <div class="col m12 s12 text-center">
                      <span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Herramientas Asignadas
                    </span><br>
                </div>
            </div>
            
          

            <div class="pdf-body">
                <div class="grida" id="grid">
                  <input type="hidden" name="datos" id="datos" value="<?php echo $idp; ?>">
                </div>
            </div>
            
            <div class="row">
              <div class="col m12 s12 ">
                <span class="title-pdf">
                    Gps Constructivos      
                </span><br> 
                <span class="title-pdf">
                    Fecha de descarga: <?php echo $hoy; ?>     
                </span>
              </div>
            </div>

            <div class="row signature">
                <div class="col m6 s6 text-center">
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Entregado por:</span><br><br><br>
                    <hr>
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nombre y Firma</span>
                </div>
                <div class="col m6 s6 text-center">
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Recibido por:</span><br><br>
                    <?php echo $nombrea; ?> <?php echo $apellido_pa; ?> <?php echo $apellido_ma; ?>
                    <hr>
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nombre y Firma</span>
                </div>
            </div>


        </div>
    </div>

      <div class="responsive-message"></div>

      <div id="pdfPageCopy"></div>


      <!-- Load Pako ZLIB library to enable PDF compression -->
      <script src="../content/shared/js/pako.min.js"></script>

      <script>
      $(document).ready(function(){
      
      cpAjax();

      });


        function getPDF(selector) {

          kendo.drawing.drawDOM($('.pdf-page'), {
            paperSize: "A4",
            
            scale: 0.7})          
            .then(function(group){
            return kendo.drawing.exportPDF(group, {
              margin: { left: "0.5cm", top: "0.5cm", right: "0.5cm", bottom: "0cm" }
            });
          })
            .done(function(data) {
            kendo.saveAs({
              dataURI: data,
              fileName: "Responsiva <?php echo $nombrea; ?><?php echo $apellido_pa; ?>.pdf"
            });
          });
        }

        function herramientas(datost){

          var data = datost;
          var grid = $("#grid").kendoGrid({
            editable: false,
            sortable: true,
            dataSource: {
              data: data
            }
          });
        
        }


      function cpAjax(){ 
      
      var download = document.getElementById("download");
      
      datos= document.getElementById("datos").value;
      variable = datos;

      $.ajax({

        url: "/herramienta/datos",

        data: {

          variable: variable

        },

        type: "POST",

        success: function( data ) {

          // console.log( data );
        

        download.style.display = "block";



          var aData = JSON.parse( data );

          herramientas(aData);

          //console.log( aData );
          
        }
        ,
        error: function(a, b, c) {

          console.log(a);

          console.log(b);

          console.log(c);

        }

      });

  }

      </script>
       <style>

        .title-pdf {
            font-weight: bold;
            font-size: 13px;
        }

        .invoice-number {
            padding-top: .17in;
            float: right;
        }
        .pdf-footer {
            position: absolute;
            bottom: .5in;
            height: .6in;
            left: .5in;
            right: .5in;
            padding-top: 10px;
            border-top: 1px solid #e5e5e5;
            text-align: left;
            color: #787878;
            font-size: 12px;
        }
        .pdf-body {
            
            top: 3.5in;
            bottom: 13.2in;
            left: .5in;
            right: .5in;
        }

         .grida {
             color: red;
             font-size: 12px;
           
        }


        .grida th{
            font-weight: bold;
            font-size: 16px;
        }

        .grida td{
          padding-top: 1px;
          padding-bottom: 1px;
        }
        

        .size-a5 { width: 8.3in; height: 5.8in; }
        .size-a4 { width: 210mm; height: 310mm; }
        .size-letter { width: 8.5in; height: 11in; }
        .size-executive { width: 7.25in; height: 10.5in; }

        .company-logo {
            font-size: 30px;
            font-weight: bold;
            color: #000080;
        }
        .for {
            width: 3.5in;
        }
        .from {
            width: 3.5in;
        }
        .from p, .for p {
            color: #787878;
        }
        .signature {
            padding-top: .3in;
        }
    </style>
       

    </div>
  </body>
</html>
