<html>
<head>
    <!-- <base href="https://demos.telerik.com/kendo-ui/pdf-export/page-layout">
    <style>html { font-size: 14px; font-family: Arial, Helvetica, sans-serif; } --></style>
    <title></title>
   <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.common.min.css" />
<!--      <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.black.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.black.mobile.min.css" /> -->

    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/kendo.all.min.js"></script>
</head>
<body>

<?php foreach ($this->add_gasolina as $key) {
    $odometro = $key['odometro_file'];
    $bomba = $key['bomba_file'];
    $ticket = $key['ticket_file'];

    $sitio = $key['name_sitio'];
    $responsable = $key['name_responsable'];
    $fecha_requerida = $key['fecha_requerida'];
    $forma_pago = $key['forma_pago'];
    $importe = $key['importe'];
    $odometro_inicial = $key['odometro_inicial'];
    $odometro_final = $key['odometro_final'];
    $estacion = $key['estacion'];
    $forma_pago = $key['forma_pago'];

    $status_gasolina = $key['status_gasolina'];
    $id_solicitud = $key['id'];
    $name_auditoria = $key['name_auditoria'];
    $fecha_auditoria = $key['fecha_auditoria'];
    $comentario = $key['comentario'];

} ?>

<?php foreach ($this->vehiculo as $value) {
    $marca = $value['marca'];
    $submarca = $value['submarca'];
    $modelo = $value['modelo'];
    $placas = $value['placas'];
    $imagen = $value['imagen'];
} ?>

<div id="example">

<div class="row" style="margin-top: 10px;">

    <div class="col m6 s12">
        <a href="/gasolina/auditoriagasolinadetail/id/<?php echo $id_solicitud; ?>/status/<?php echo $this->status; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>

    <div class="col m6 s12 text-right">
        <button class="export-pdf btn" onclick="getPDF('.pdf-page')">Descargar</button>
    </div>
</div>

    <div class="page-container hidden-on-narrow">
        <div class="pdf-page size-a4">
            <div class="pdf-header">
                <span class="company-logo">
                    <img src="/img/head.png" style="width: 120px;" />
                </span>

                <span class="invoice-number">
                    <img src="/img/logo-2.png" style="width: 125px;" /><br/>
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Solicitud No. <?php echo $id_solicitud; ?></span>
                </span>
                <div class="row">
                    <div class="company-logo col m12 s12 text-center">
                        Auditoría Gasolina
                    </div>
                </div>
            </div>

            <div class="for" style="margin-top: 60px;">
                <h3>Fecha de Ticket : <?php echo $fecha_requerida; ?></h3>
                <p><span class="title-pdf">Sitio:</span> <span style="font-size: 14px;"><?php echo $sitio; ?></span><br />
                    <span class="title-pdf">Responsable:</span> <?php echo $responsable; ?><br />
                    <span class="title-pdf">Importe:</span> $<?php echo number_format($importe, 2, '.', ','); ?><br />
                    <span class="title-pdf">Odometro Inicial:</span><?php echo $odometro_inicial; ?><br />
                    <span class="title-pdf">Odometro Final: </span><?php echo $odometro_final; ?><br />
                    <span class="title-pdf">Estación: </span><?php echo $estacion; ?>
                </p>
            </div>

            <div class="from" style="margin-top: 60px;">
                <p>
                    <?php if($forma_pago == 1){ ?>
                        <span class="title-pdf">Forma de Pago:</span>Efecticard<br/>
                        <span class="title-pdf">Tarjeta No:</span><?php echo $this->tarjeta; ?>
                    <?php } ?>    

                    <?php if($forma_pago == 2){ ?>
                        <span class="title-pdf">Forma de Pago:</span>Tarjeta de Debito<br/>
                    <?php } ?> 

                    <?php if($forma_pago == 3){ ?>
                        <span class="title-pdf">Forma de Pago:</span>Otra..<br/>
                    <?php } ?> 
                </p>
                <h3>Vehiculo</h3>
                <p style="padding-bottom: 20px;">
                    <span class="title-pdf">Marca:</span> <?php echo $marca; ?> <br />
                    <span class="title-pdf">Submarca:</span> <?php echo $submarca; ?><br />
                    <span class="title-pdf">Modelo:</span> <?php echo $modelo; ?><br />
                    <span class="title-pdf">Placas:</span> <?php echo $placas; ?> <br />
                </p>

            </div>
            <div class="pdf-body">

                <div class="row" style="margin-top: 20px;">
                	<div class="col m12 s12">
                         <table>
                            <thead>
                              <tr>
                                  <th><span class="title-pdf">Odometro</span></th>
                                  <th><span class="title-pdf">Bomba</span></th>
                              </tr>
                            </thead>

                            <tbody>
                              <tr>
                                <td class="text-center">
                                    <a class="example-image-link" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $odometro ?>"  alt="image-1" style="width: 220px; height: 120px;"/></a>
                                </td>
                                <td class="text-center">
                                    <a class="example-image-link" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $bomba ?>"  alt="image-1" style="width: 220px; height: 120px;"/></a>   
                                </td>   

                              </tr>
                            </tbody>
                          </table>
                	</div>
                </div>

                <div class="row">
                    <div class="col m12 s12">
                         <table>
                            <thead>
                              <tr>
                                  <th><span class="title-pdf">Ticket</span></th>
                              </tr>
                            </thead>

                            <tbody>
                              <tr>
                                <td class="text-center">
                                    <a class="example-image-link" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $ticket ?>"  alt="image-1" style="width: 220px; height: 120px;"/></a>    
                                </td>
                              </tr>
                            </tbody>
                          </table>
                    </div>
                </div>


                <div class="row">
                    <?php if($status_gasolina == 1){ ?>
                        <div class="col m12 s12">
                             <table>
                                <thead>
                                  <tr>
                                      <th><span class="title-pdf">Status</span></th>
                                      <th><span class="title-pdf">Auditada por:</span></th>
                                      <th><span class="title-pdf">Fecha auditoria</span></th>
                                  </tr>
                                </thead>

                                <tbody>
                                  <tr>
                                    <td class="text-center">
                                        Autorizada  
                                    </td>
                                    <td>
                                        <?php echo $name_auditoria; ?>
                                    </td>
                                    <td>
                                        <?php echo $fecha_auditoria; ?>
                                    </td>
                                  </tr>
                                </tbody>
                              </table>
                        </div>
                    <?php } ?>


                    <?php if($status_gasolina == 2){ ?>
                        <div class="col m12 s12">
                             <table>
                                <thead>
                                  <tr>
                                      <th><span class="title-pdf">Status</span></th>
                                      <th><span class="title-pdf">Auditada por:</span></th>
                                      <th><span class="title-pdf">Fecha auditoria</span></th>
                                      <th><span class="title-pdf">Comentario</span></th>
                                  </tr>
                                </thead>

                                <tbody>
                                  <tr>
                                    <td class="text-center">
                                        Rechazada
                                    </td>
                                    <td>
                                        <?php echo $name_auditoria; ?>
                                    </td>
                                    <td>
                                        <?php echo $fecha_auditoria; ?>
                                    </td>
                                    <td>
                                        <?php echo $comentario; ?>
                                    </td>
                                  </tr>
                                </tbody>
                              </table>
                        </div>
                    <?php } ?>

                </div>

            </div>
        </div>
    </div>
    
    <div class="responsive-message"></div>

    <style>
        /*
            Use the DejaVu Sans font for display and embedding in the PDF file.
            The standard PDF fonts have no support for Unicode characters.
        */
        .pdf-page {
            font-family: "DejaVu Sans", "Arial", sans-serif;
        }
    </style>

    <script>
        // Import DejaVu Sans font for embedding

        // NOTE: Only required if the Kendo UI stylesheets are loaded
        // from a different origin, e.g. cdn.kendostatic.com
        kendo.pdf.defineFont({
            "DejaVu Sans"             : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans.ttf",
            "DejaVu Sans|Bold"        : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Bold.ttf",
            "DejaVu Sans|Bold|Italic" : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf",
            "DejaVu Sans|Italic"      : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf"
        });
    </script>

    <!-- Load Pako ZLIB library to enable PDF compression -->
    <script src="../content/shared/js/pako.min.js"></script>

    <script>
      function getPDF(selector) {
        kendo.drawing.drawDOM($(selector)).then(function(group){
          kendo.drawing.pdf.saveAs(group, "Auditoria Gasolina NO <?php echo $id_solicitud; ?> .pdf");
        });
      }

    $(document).ready(function() {
        var data = [
          { productName: "QUESO CABRALES", unitPrice: 21, qty: 5 },
          { productName: "ALICE MUTTON", unitPrice: 39, qty: 7 },
          { productName: "GENEN SHOUYU", unitPrice: 15.50, qty: 3 },
          { productName: "CHARTREUSE VERTE", unitPrice: 18, qty: 1 },
          { productName: "MASCARPONE FABIOLI", unitPrice: 32, qty: 2 },
          { productName: "VALKOINEN SUKLAA", unitPrice: 16.25, qty: 3 }
        ];
        var schema = {
          model: {
            productName: { type: "string" },
            unitPrice: { type: "number", editable: false },
            qty: { type: "number" }
          },
          parse: function (data) {
                $.each(data, function(){
                    this.total = this.qty * this.unitPrice;
                });
                return data;
          }
        };
        var aggregate = [
          { field: "qty", aggregate: "sum" },
          { field: "total", aggregate: "sum" }
        ];
        var columns = [
          { field: "productName", title: "Product", footerTemplate: "Total"},
          { field: "unitPrice", title: "Price", width: 120},
          { field: "qty", title: "Pcs.", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" },
          { field: "total", title: "Total", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" }
        ];
        var grid = $("#grid").kendoGrid({
          editable: false,
          sortable: true,
          dataSource: {
            data: data,
            aggregate: aggregate,
            schema: schema,
          },
          columns: columns
        });

        $("#paper").kendoDropDownList({
          change: function() {
            $(".pdf-page")
              .removeClass("size-a4")
              .removeClass("size-letter")
              .removeClass("size-executive")
              .addClass(this.value());
          }
        });
    });
    </script>
    <style>

        .title-pdf{
            font-weight: bold;
            font-size: 13px;
        }
        .pdf-page {
            margin: 0 auto;
            box-sizing: border-box;
            box-shadow: 0 5px 10px 0 rgba(0,0,0,.3);
            background-color: #fff;
            color: #333;
            position: relative;
        }
        .pdf-header {
            position: absolute;
            top: .5in;
            height: .6in;
            left: .5in;
            right: .5in;
            /*border-bottom: 1px solid #e5e5e5;*/
        }
        .invoice-number {
            padding-top: .17in;
            float: right;
        }
        .pdf-footer {
            position: absolute;
            bottom: .5in;
            height: .6in;
            left: .5in;
            right: .5in;
            padding-top: 10px;
            border-top: 1px solid #e5e5e5;
            text-align: left;
            color: #787878;
            font-size: 12px;
        }
        .pdf-body {
            position: absolute;
            top: 4.3in;
            bottom: 1.2in;
            left: .5in;
            right: .5in;
        }

        .size-a4 { width: 8.3in; height: 11.7in; }
        .size-letter { width: 8.5in; height: 11in; }
        .size-executive { width: 7.25in; height: 10.5in; }

        .company-logo {
            font-size: 34px;
            font-weight: bold;
            color: #f3e354;
        }
        .for {
            position: absolute;
            top: 1.5in;
            left: .5in;
            width: 3.5in;
        }
        .from {
            position: absolute;
            top: 1.5in;
            right: .5in;
            width: 3.5in;
        }
        .from p, .for p {
            color: #787878;
        }
        .signature {
            padding-top: .5in;
        }
    </style>

</div>


</body>
