
<div class="row" style="margin-top: 10px; margin-top:15px;">
  <div class="col m12 s12 text-center">
    <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Control de Gasolina Paso 1</span>
  </div>
</div>


  
  <?php foreach ($this->control as $usr){ ?>


<div class="row">
  <div class="col s12 m1"></div>
    <div class="col s12 m10">
        <div class="card">
          <div class="card-content">
              <div class="row">
                <form action="/gasolina/requestupdatecontrolgasolina" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_gasolina">
                  <input type="hidden" name="ids" value="<?php echo $this->ids; ?>">
                <div class="col m12 s12">
    <div class="input-field col m6 s12">
      <input id="importe" name="importe" type="number" value="<?php echo $usr['importe']; ?>">
      <label for="importe">Importe</label>
    </div>

    <div class="input-field col m6 s12">
      <select id="sitio" name="sitio">
        <option value="0" disabled>* Selecciona un Sitio</option>
          <?php if($usr['id_sitios'] == "0"){?>
            <option value="oficina" selected>Oficina</option>
          <?php }else{ ?>
            <option value="oficina">Oficina</option>
          <?php } ?>

          <?php foreach ($this->sitios as $mar) { 
            if ($mar['id']==$usr['id_sitios']) { ?>
              <option value="<?php echo $mar["id"]; ?>" selected><?php echo $mar['nombre']; ?> - <?php echo $mar['id_cliente']; ?></option>
          <?php } if ($mar['id']!=$usr['id_sitios']) { ?>
              <option value="<?php echo $mar["id"]; ?>" ><?php echo $mar['nombre']; ?> - <?php echo $mar['id_cliente']; ?></option>
          <?php } } ?>  
      </select>
      <label>Sitio:</label>
    </div>

    <div class="input-field col m6 s12">
      <select id="responsable" name="responsable" required>
        <?php foreach ($this->usuarios as $mar) { 
          if ($mar['id']==$usr['id_responsable']) { ?>
            <option value="<?php echo $mar["id"]; ?>" selected><?php echo $mar['nombre']; ?> <?php echo $mar['apellido_pa'] ?> <?php echo $mar['apellido_ma'] ?></option>
        <?php } if ($mar['id']!=$usr['id_responsable']) { ?>
          <option value="<?php echo $mar["id"]; ?>" ><?php echo $mar['nombre']; ?> <?php echo $mar['apellido_pa'] ?> <?php echo $mar['apellido_ma'] ?></option>
        <?php } } ?>  
      </select>
      <label>Responsable</label>
    </div>

    <div class="input-field col m6 s12">
      <input id="fecha_requerida" name="fecha" value="<?php echo $usr['fecha_requerida']; ?>" type="date">
      <label for="fecha_requerida">* Fecha de Ticket</label>
    </div>

    <div class="input-field col m6 s12">
      <select id="vehiculo" name="vehiculo" required>
        <?php foreach ($this->vehiculos as $mar) { 
          if ($mar['id_vehiculos']==$usr['id_vehiculo']) { ?>
            <option value="<?php echo $mar["id_vehiculos"]; ?>" selected><?php echo $mar['marca']; ?> <?php echo $mar['submarca'] ?> <?php echo $mar['modelo'] ?>/ Placas: <?php echo $mar['placas']; ?></option>
        <?php } if ($mar['id_vehiculos']!=$usr['id_vehiculo']) { ?>
          <option value="<?php echo $mar["id_vehiculos"]; ?>" ><?php echo $mar['marca']; ?> <?php echo $mar['submarca'] ?> <?php echo $mar['modelo'] ?>/ Placas: <?php echo $mar['placas']; ?></option>
        <?php } } ?>  
      </select>
      <label>Responsable</label>
    </div>
  <div class="input-field col m6 s12">
    <input id="estacion" name="estacion" value="<?php echo $usr['estacion']; ?>" type="text" class="validate">
    <label for="estacion">Estación</label>
  </div>

  <div class="input-field col m6 s12">
    <select id="forma_pago" name="forma_pago">
      <option value="0" disabled selected>Selecciona la forma de pago</option>
      <?php if($usr['forma_pago'] == 1){ ?>
        <option value="1" selected>Efecticard</option>
        <option value="2">Tarjeta de Debito</option>
        <option value="3">Otra..</option>
      <?php } ?>

      <?php if($usr['forma_pago'] == 2){ ?>
        <option value="1">Efecticard</option>
        <option value="2" selected>Tarjeta de Debito</option>
        <option value="3">Otra..</option>
      <?php } ?>

      <?php if($usr['forma_pago'] == 3){ ?>
        <option value="1">Efecticard</option>
        <option value="2">Tarjeta de Debito</option>
        <option value="3" selected>Otra..</option>
      <?php } ?>

    </select>
    <label>Forma de Pago</label>
  </div>

<?php } ?>
                </div>
                </form>
              </div>
          </div>
          <div class="card-action">
        <div class="row">
          <div class="col m12 s12 text-right">
            <a href="/gasolina/addcontrolgasolinados/id/<?php echo $this->ids; ?>" class="red btn">Paso 2</a>
            <button  id="send_paso" class="btn">Actualizar</button>
          </div>
        </div>
          </div>
        </div>
    </div>
    <div class="col s12 m1"></div>
</div>


<script src="/js/materialize.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      $('.datepicker').datepicker();
    });

    $("#send_paso").click(function(){
        var sitio = document.getElementById("sitio").value;
        var responsable = document.getElementById("responsable").value;
        var vehiculo = document.getElementById("vehiculo").value;
        var fecha = document.getElementById("fecha_requerida").value;
        var importe = document.getElementById("importe").value;

        if(importe == "" || sitio == 0 || responsable == 0 || vehiculo == 0 || fecha == "" ){
            swal({
              title: "Para continuar debes agregar la información marcada con un '*' ",
            });
        }else{
          swal("Espere un momento, la información esta siendo procesada", {
            icon: "success",
            buttons: false,
          }); 
          setTimeout(submitForm, 1500);     
        }
    });


    function submitForm() { document.getElementById("submit_gasolina").submit() }

  </script>
