<?php 
	$status =  $this->status_documento;
?>


<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>

<input type="hidden" id="status_cajachica" value="<?php echo $status; ?>">

<style type="text/css">
	.oculto{display: none;}
	.active_menu{
	-webkit-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	-moz-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	}
</style>

<div class="row" style="margin-top: 20px;">
	<div class="col m12 s12">
  		<ul >
  			<?php if($status == 0){ ?>
	    		<li class="tab col s3 active_menu">
	    			<a class="" href="/comprobacion/cajachicacontabilidad/status/0">
	    			<h4>En Proceso
	  					<div class="chip">
	    					<?php echo $this->enproceso; ?> 
	  					</div>
	    			</h4>
	    			</a>
	    		</li>
  			<?php }else{ ?>
	    		<li class="tab col s3">
	    			<a class="" href="/comprobacion/cajachicacontabilidad/status/0">
	    			<h4>En Proceso
	  					<div class="chip">
	    					<?php echo $this->enproceso; ?> 
	  					</div>
	    			</h4>
	    			</a>
	    		</li>
  			<?php } ?>

<!--   			<?php if($status == 2){ ?>
  				<li class="tab col s3 active_menu"><a href="/comprobacion/cajachicacontabilidad/status/2"><h4>Rechazadas</h4></a></li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/comprobacion/cajachicacontabilidad/status/2"><h4>Rechazadas</h4></a></li>
  			<?php } ?>
 -->
  			<?php if($status == 1){ ?>
  				<li class="tab col s3 active_menu">
  					<a href="/comprobacion/cajachicacontabilidad/status/1"><h4>Pagadas</h4></a>
  					<div></div>
  				</li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/comprobacion/cajachicacontabilidad/status/1"><h4>Pagadas</h4></a></li>
  			<?php } ?>

  			<?php if($status == 3){ ?>
  				<li class="tab col s3 active_menu">
  					<a href="/comprobacion/cajachicacontabilidad/status/3"><h4>Reembolso</h4></a>
  					<div></div>
  				</li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/comprobacion/cajachicacontabilidad/status/3"><h4>Reembolso</h4></a></li>
  			<?php } ?>
  		</ul>
	</div>
</div>

<div class="row" style="margin-top:10px;">
	<div class="col m1 s12"></div>
	<div class="col m10 s12"> 
		<div class="col m12 s12" id="search_nombre">
			<div class="row">
				<div class="col m4 s6">
					<div class="input-field col m12 s12">
	    				<select id="buscador">
	      					<option value="1" selected>Nombre Residente</option>
	      					<option value="2">Nombre Sitio</option>
	    				</select>
    				</div>
				</div>

				<div class="col m4 s6">
			        <div class="input-field col m12 s12" id="name_residente">
					    <select id="residente_search" name="rol" required>
					      	<option value="0" disabled selected>* Selecciona una opcion:</option>
					      	<?php foreach ($this->personal as $rl) { ?>
					      	<option value="<?php echo $rl["id"]; ?>"><?php echo $rl["nombre"]; ?> <?php echo $rl["apellido_pa"]; ?> <?php echo $rl["apellido_ma"]; ?></option>
					      	<?php } ?>
					    </select>
					    <label>Nombre Residente</label>
			        </div>

			        <div class="input-field col m12 s12 oculto" id="name_sitio">
			        	<input id="sitio_searc" type="text" class="validate">
			        	<label for="sitio_searc">Nombre Sitio</label>
			        </div>
				</div>

				<div class="col m4 s12 text-center">
					<div class="input-field col m12 s12">
						<a class="btn" id="search"><i class="material-icons right">search</i>Buscar</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col m1 s12"></div>
</div>


<div class="row"> 
	<div class="col m12 s12">
		<div class="col m6 s6">
			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de Solicitudes de Caja chica</span>
		</div>
		<div class="col m6 s6 text-right">
			<?php $suma = 0;
			if ($this->paginator) { 
			foreach ($this->paginator as $usr) { ?>
				<?php $suma = $suma + $usr['monto']; ?>
			<?php } }else{ ?>

			<?php } ?>
			<span style="font-size: 19px;">Total de la solicitudes <?php echo $this->nombre_sitio; ?>:</span>
			<span style="font-size: 19px; font-weight: bold;">$<?php echo number_format($suma, 2, '.', ','); ?></span>
		</div>
	</div>

	<div class="col m12 s12">
		<table class="table text-left table-hover">
			<thead>
				<tr>
					<th>NO.</th>
					<th>Usuario</th>
					<th>Sitio</th>		
					<th>Residente</th>
					<th>Monto</th>
					<th>Autorización</th>
					<th>Detalle Solicitud</th>
				</tr> 
			</thead>
			<?php
			$total = 0;
			if ($this->paginator) { 
			foreach ($this->paginator as $usr) { ?>
			<tbody>
				<tr>
					<td>
						<?php echo $usr['id']; ?>
					</td>
					<td>
						<?php echo $usr['user_solicitud']; ?>
					</td>
					<td>
						<span style="font-weight: bold;"><?php echo $usr['nombre_sitio']; ?> </span>
					</td>
					<td>
						<?php echo $usr['nombre_residente']; ?>
					</td>
					<td>
						<h5 style="font-weight: bold;">
							$<?php echo number_format($usr['monto'], 2, '.', ','); ?>
							<?php $total = $total + $usr['monto']; ?>
						</h5>
					</td>

					<?php if($this->status_documento != 3 ){ ?>
					<td>
						<?php if($usr['autorizacion_status'] == 0){ ?>
							<a href="#modal1" class="modal-trigger auto-sol" data-id="<?php echo $usr['id']; ?>" data-comentario ="<?php echo $usr['comentario']; ?>">
								<div class="chip" id="inactivo_personal">
							    	<img src="/img/gris.jpg" >
							    	En proceso
							  	</div>
						  	</a>
						<?php } ?>

						<?php if($usr['autorizacion_status'] == 2){ ?>
							<div class="chip" id="activo_personal">
						    	<img src="/img/correct.png" >
						    	Autorizada
						  	</div>
						<?php } ?>

						<?php if($usr['autorizacion_status'] == 1){ ?>
							<div class="chip" id="inactivo_personal">
						    	<img src="/img/rojo.png" >
						    	Rechazada
						  	</div>
						<?php } ?>
						
					</td>
				<?php }else{ ?>

					<td>
						<?php if($usr['status_caja'] == 0){ ?>
							<div class="chip" id="inactivo_personal">
							    <img src="/img/gris.jpg" >
							    En proceso
							</div>
						<?php } ?>

						<?php if($usr['status_caja'] == 1){ ?>
							<div class="chip" id="activo_personal">
						    	<img src="/img/correct.png" >
						    	Caja cerrada
						  	</div>
						<?php } ?>

					</td>

				<?php } ?>

				<?php if($this->status_documento != 3 ){ ?>
					<td class="text-center">
						<a href="/comprobacion/detailcontabilidad/id/<?php echo $usr["id"] ?>/status/<?php echo $status; ?>"><i class="fa fa-2x fa-id-card-o"></i></a>
					</td>

				<?php }else{ ?>
					<td class="text-center">
						<a href="/comprobacion/detailreembolso/id/<?php echo $usr["id"] ?>/status/<?php echo $status; ?>"><i class="fa fa-2x fa-id-card-o"></i></a>
					</td>
				<?php } ?>

				</tr>

		    <?php } }else{ ?>
		    </tbody> 
		    <tbody>
		        <tr>
		        	<td></td>
		        	<td></td>
		        	<td></td>
		            <td class="text-center" colspan=h4><h4>No hay solicitudes de Caja chica.</h4></td>
		            <td></td>
		            <td></td>
		        </tr>
		    </tbody>
		                
		    <?php } ?>
		</table>
	</div>
</div>

<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
               		<?php if($pagina - 1 == 0){ ?>
                    	<li class="page-item disabled">
                        	<span class="page-link">Anterior</span>
                    	</li>
               		<?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
               		<?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
               		<?php if($pagina >= $this->total): ?>
                       	<li class="page-item disabled">
                            <span class="page-link">Siguiente</span>
                       	</li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                   	<?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>


<script type="text/javascript">
  	$('#buscador').change(function(){
    	var buscador = $(this).val();
    	if(buscador == 1){
    		$("#name_residente").show();
    		$("#name_sitio").hide();
    	}else{
    		$("#name_residente").hide();
    		$("#name_sitio").show();
    	}
	});

  	$("#search").click(function(){
  		var buscador = document.getElementById("buscador").value;
  		var status = document.getElementById("status_cajachica").value;
  		if(buscador == 1){
  			var nombre = document.getElementById("residente_search").value;
  			window.location.href = "/comprobacion/buscadorcajachicacontabilidad/status/"+status+"/residente/"+nombre+"/op/1";
  		}else{
  			var nombre = document.getElementById("sitio_searc").value;
  			window.location.href = "/comprobacion/buscadorcajachicacontabilidad/status/"+status+"/sitio/"+nombre+"/op/2";
  		}
  	});
</script>