<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>


<?php 
	$status =  $this->status_documento;
?>

<input type="hidden" id="status_cajachica" value="<?php echo $status; ?>">

<style type="text/css">
	.oculto{display: none;}
	.active_menu{
	-webkit-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	-moz-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	}
</style>

<input type="hidden" name="" id="usuario_id" value="<?php echo $this->user; ?>">

<div class="row" style="margin-top: 20px;">
	<div class="col m12 s12">
  		<ul >
  			<?php if($status == 0){ ?>
	    		<li class="tab col s3 active_menu">
	    			<a class="" href="/comprobacion/solicitudescajachica/status/0">
	    			<h4>En Proceso
	  					<div class="chip">
	    					<?php echo $this->enproceso; ?> 
	  					</div>
	    			</h4>
	    			</a>
	    		</li>
  			<?php }else{ ?>
	    		<li class="tab col s3">
	    			<a class="" href="/comprobacion/solicitudescajachica/status/0">
	    			<h4>En Proceso
	  					<div class="chip">
	    					<?php echo $this->enproceso; ?> 
	  					</div>
	    			</h4>
	    			</a>
	    		</li>
  			<?php } ?>

  			<?php if($status == 2){ ?>
  				<li class="tab col s3 active_menu"><a href="/comprobacion/solicitudescajachica/status/2"><h4>Rechazadas</h4></a></li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/comprobacion/solicitudescajachica/status/2"><h4>Rechazadas</h4></a></li>
  			<?php } ?>

  			<?php if($status == 1){ ?>
  				<li class="tab col s3 active_menu">
  					<a href="/comprobacion/solicitudescajachica/status/1"><h4>Dirección</h4></a>
  					<div></div>
  				</li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/comprobacion/solicitudescajachica/status/1"><h4>Dirección</h4></a></li>
  			<?php } ?>

  			<?php if($status == 3){ ?>
  				<li class="tab col s3 active_menu">
  					<a href="/comprobacion/solicitudescajachica/status/3"><h4>Pagadas</h4></a>
  					<div></div>
  				</li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/comprobacion/solicitudescajachica/status/3"><h4>Pagadas</h4></a></li>
  			<?php } ?>
  		</ul>
	</div>
</div>

<div class="row" style="margin-top:10px;">
	<div class="col m2 s12"></div>
	<div class="col m8 s12"> 
		<div class="col m12 s12" id="search_nombre">
			<div class="row">
				<div class="col m4 s6">
					<div class="input-field col m12 s12">
	    				<select id="buscador">
	      					<option value="1" selected>Nombre Residente</option>
	      					<option value="2">Nombre Sitio</option>
	    				</select>
    				</div>
				</div>

				<div class="col m4 s6">
			        <div class="input-field col m12 s12 oculto" id="name_residente">
			        	<input id="residente_search" type="text" class="validate">
			        	<label for="residente_search">Nombre Residente</label>
			        </div>

			        <div class="input-field col m12 s12" id="name_sitio">
			        	<input id="sitio_searc" type="text" value="<?php echo $this->nombre_sitio; ?>" class="validate">
			        	<label for="sitio_searc">Nombre Sitio</label>
			        </div>
				</div>

				<div class="col m4 s12 text-center">
					<div class="input-field col m12 s12">
						<a class="btn" id="search"><i class="material-icons right">search</i>Buscar</a>
					</div>
				</div>

			</div>
		</div>
	</div>
	<div class="col m2 s12"></div>
</div>


<div class="row"> 
	<div class="col m12 s12">
		<div class="col m6 s6">
			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de Solicitudes de Caja chica</span>
		</div>
		<div class="col m6 s6 text-right">
			<?php $suma = 0;
			if ($this->paginator) { 
			foreach ($this->paginator as $usr) { ?>
				<?php $suma = $suma + $usr['monto']; ?>
			<?php } }else{ ?>

			<?php } ?>
			<span style="font-size: 19px;">Total de la solicitudes <?php echo $this->nombre_sitio; ?>:</span>
			<span style="font-size: 19px; font-weight: bold;">$<?php echo number_format($suma, 2, '.', ','); ?></span>
		</div>
	</div>

	<div class="col m12 s12">
		<table class="table text-left table-hover">
			<thead>
				<tr>
					<th>NO.</th>
					<th>Usuario</th>
					<th>Sitio</th>		
					<th>Residente</th>
					<th>Monto</th>
					<th>Autorización</th>
					<th>Detalle Solicitud</th>
				</tr> 
			</thead>
			<?php
			if ($this->paginator) { 
			foreach ($this->paginator as $usr) { ?>
			<tbody>
				<tr>
					<td>
						<?php echo $usr['id']; ?>
					</td>
					<td>
						<?php echo $usr['user_solicitud']; ?>
					</td>
					<td>
						<span style="font-weight: bold;"><?php echo $usr['nombre_sitio']; ?> </span> /
						<?php echo $usr['nombre_tipoproyecto']; ?>
					</td>
					<td>
						<?php echo $usr['nombre_residente']; ?>
					</td>
					<td>
						<h5 style="font-weight: bold;">
							$<?php echo number_format($usr['monto'], 2, '.', ','); ?>
						</h5>
					</td>
					<td>
						<?php if($usr['autorizacion_status'] == 0){ ?>
							<a href="#modal1" class="modal-trigger auto-sol" data-id="<?php echo $usr['id']; ?>" data-comentario ="<?php echo $usr['comentario']; ?>">
								<div class="chip" id="inactivo_personal">
							    	<img src="/img/gris.jpg" >
							    	En proceso
							  	</div>
						  	</a>
						<?php } ?>

						<?php if($usr['autorizacion_status'] == 2){ ?>
							<div class="chip" id="activo_personal">
						    	<img src="/img/correct.png" >
						    	Autorizada
						  	</div>
						<?php } ?>

						<?php if($usr['autorizacion_status'] == 1){ ?>
							<div class="chip" id="inactivo_personal">
						    	<img src="/img/rojo.png" >
						    	Rechazada
						  	</div>
						<?php } ?>
						
					</td>
					<td class="text-center">
						<a href="/comprobacion/cajachicadetail/id/<?php echo $usr["id"] ?>/status/<?php echo $status; ?>"><i class="fa fa-2x fa-id-card-o"></i></a>
					</td>
				</tr>

		    <?php } }else{ ?>
		    </tbody> 
		    <tbody>
		        <tr>
		        	<td></td>
		        	<td></td>
		        	<td></td>
		            <td class="text-center" colspan=h4><h4>No hay solicitudes de Caja chica.</h4></td>
		            <td></td>
		            <td></td>
		        </tr>
		    </tbody>
		                
		    <?php } ?>
		</table>
	</div>
</div>

<input type="hidden" id="id_solicitudmodal" value="" name="id_solicitudmodal">

  <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
      <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Proceso de Autorización</span>
      <div class="row text-center" style="margin-top: 20px;">
      	<div class="col m6 s6">
			<div class="chip" id="activo_solicitud">
				<img src="/img/correct.png" >
				Autorizar
			</div>
      	</div>
      	<div class="col m6 s6">
			<div class="chip" id="cancelar_solicitud">
				<img src="/img/rojo.png">
				Rechazar
			</div>
      	</div>
      </div>

  
      	<div class="row oculto" id="comentario-can">
        	<div class="input-field col s12">
          		<input id="cancelar_comentario" placeholder="" type="text" class="validate">
          		<label for="cancelar_comentario">* Motivo de la cancelación</label>
        	</div>

        	<div class="input-field col s12 text-center">
        		<a class="btn" id="solicitud-cancelada">Cancelar Solicitud</a>
        	</div>
      	</div>
    </div>
    <div class="modal-footer">
    	<button  class="modal-close red btn">Cerrar</button>
    </div>
  </div>

<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
               		<?php if($pagina - 1 == 0){ ?>
                    	<li class="page-item disabled">
                        	<span class="page-link">Anterior</span>
                    	</li>
               		<?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
               		<?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
               		<?php if($pagina >= $this->total): ?>
                       	<li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                       	</li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                   	<?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>

<script type="text/javascript">
	$(document).ready(function(){
    	$('.modal').modal();
  	});

  	$(".auto-sol").click(function(){
  		var id_solicitud = $(this).data('id');
  		document.getElementById("id_solicitudmodal").value = id_solicitud;
  	});

  	$("#cancelar_solicitud").click(function(){
  		$("#comentario-can").show();
  	});

  	$("#solicitud-cancelada").click(function(){
  		var comentario = document.getElementById("cancelar_comentario").value;
  		var id = document.getElementById("id_solicitudmodal").value;

		swal({
			title: "Estas seguro de cancelar la solicitud?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
	        swal("Espere un momento, la información esta siendo procesada", {
	         icon: "success",
	         buttons: false,
	        }); 
	    		var dato = "1";
	            var request = $.ajax({
	                url:"/comprobacion/requestchangesolicitudcajachica",
	                method:"POST",
	                data: { id:id, dato:dato, comentario:comentario},
	                processData: true,
	            });
	//-------------------end de ajax---------------------------
	//-------------peticion de respuesta de ajax------------------
	            request.done(function(response) {
	                console.log(response);//imprime lo que responde el ajax
	                // alert
	                window.location.reload(true);
	            });
	//-------------------end de respuesta ajax---------------------
	             return false;

		  	} else {
		    	swal("Accion cancelada!");
		  	}
		  });

  	});

  	$("#activo_solicitud").click(function(){
  		var comentario = document.getElementById("cancelar_comentario").value;
  		var id = document.getElementById("id_solicitudmodal").value;
  		$("#comentario-can").hide();
		swal({
			title: "Estas seguro de autorizar la solicitud?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
	        swal("Espere un momento, la información esta siendo procesada", {
	         icon: "success",
	         buttons: false,
	        });

	    		var dato = "2";
	            var request = $.ajax({
	                url:"/comprobacion/requestchangesolicitudcajachica",
	                method:"POST",
	                data: { id:id, dato:dato, comentario:comentario},
	                processData: true,
	            });
	//-------------------end de ajax---------------------------
	//-------------peticion de respuesta de ajax------------------
	            request.done(function(response) {
	                console.log(response);//imprime lo que responde el ajax
	                // alert
	                window.location.reload(true);
	            });
	//-------------------end de respuesta ajax---------------------
	             return false;
		  	} else {
		    	swal("Accion cancelada!");
		  	}
		  });

  	});

  	$('#buscador').change(function(){
    	var buscador = $(this).val();
    	if(buscador == 1){
    		$("#name_residente").show();
    		$("#name_sitio").hide();
    	}else{
    		$("#name_residente").hide();
    		$("#name_sitio").show();
    	}
	});

  	$("#search").click(function(){
  		var buscador = document.getElementById("buscador").value;
  		var status = document.getElementById("status_cajachica").value;
  		if(buscador == 1){
  			var nombre = document.getElementById("residente_search").value;
  			window.location.href = "/comprobacion/cajachicaresidente/status/"+status+"/residente/"+nombre+"";
  		}else{
  			var nombre = document.getElementById("sitio_searc").value;
  			window.location.href = "/comprobacion/cajachicasitio/status/"+status+"/sitio/"+nombre+"";
  		}
  	});
</script>