<?php 
	$status =  $this->status_documento;
?>

<input type="hidden" id="status_cajachica" value="<?php echo $status; ?>">

<style type="text/css">
	.oculto{display: none;}
	.active_menu{
	-webkit-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	-moz-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	}
</style>

<div class="row" style="margin-top: 20px;">
	<div class="col m12 s12">
  		<ul >
  			<?php if($status == 0){ ?>
	    		<li class="tab col s3 active_menu">
	    			<a class="" href="/comprobacion/consolicitudescajachica/status/0">
	    			<h4>Dirección
	  					<div class="chip">
	    					<?php echo $this->enproceso; ?> 
	  					</div>
	    			</h4>
	    			</a>
	    		</li>
  			<?php }else{ ?>
	    		<li class="tab col s3">
	    			<a class="" href="/comprobacion/consolicitudescajachica/status/0">
	    			<h4>Dirección
	  					<div class="chip">
	    					<?php echo $this->enproceso; ?> 
	  					</div>
	    			</h4>
	    			</a>
	    		</li>
  			<?php } ?>

  			<?php if($status == 2){ ?>
  				<li class="tab col s3 active_menu"><a href="/comprobacion/consolicitudescajachica/status/2"><h4>Pagadas</h4></a></li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/comprobacion/consolicitudescajachica/status/2"><h4>Pagadas</h4></a></li>
  			<?php } ?>

  			<?php if($status == 1){ ?>
  				<li class="tab col s3 active_menu">
  					<a href="/comprobacion/consolicitudescajachica/status/1"><h4>Con Factura</h4></a>
  					<div></div>
  				</li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/comprobacion/consolicitudescajachica/status/1"><h4>Con Factura</h4></a></li>
  			<?php } ?>

  		</ul>
	</div>
</div>


<div class="row" style="margin-top:10px;">
	<div class="col m2 s12"></div>
	<div class="col m8 s12"> 
		<div class="col m12 s12" id="search_nombre">
			<div class="row">
				<div class="col m4 s6">
					<div class="input-field col m12 s12">
	    				<select id="buscador">
	      					<option value="1" selected>Nombre Residente</option>
	      					<option value="2">Nombre Sitio</option>
	    				</select>
    				</div>
				</div>

				<div class="col m4 s6">
			        <div class="input-field col m12 s12" id="name_residente">
			        	<input id="residente_search" type="text" class="validate">
			        	<label for="residente_search">Nombre Residente</label>
			        </div>

			        <div class="input-field col m12 s12 oculto" id="name_sitio">
			        	<input id="sitio_searc" type="text" class="validate">
			        	<label for="sitio_searc">Nombre Sitio</label>
			        </div>
				</div>

				<div class="col m4 s12 text-center">
					<div class="input-field col m12 s12">
						<a class="btn" id="search"><i class="material-icons right">search</i>Buscar</a>
					</div>
				</div>
			</div>
<!-- 			<div class="row">
				<div class="input-field col m12 s12 text-center">
					<a href="/archivos/excelpersonal"> <h4 style="color: green;">Generar Excel<i class="material-icons">insert_drive_file</i></h4></a>
				</div>
			</div> -->
		</div>
	</div>
	<div class="col m2 s12"></div>
</div>

<div class="row"> 
	<div class="col m12 s12">
		<div class="col m6 s6">
			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de Solicitudes de Caja chica</span>
		</div>
		<div class="col m6 s6 text-right">
			<?php $suma = 0;
			if ($this->paginator) { 
			foreach ($this->paginator as $usr) { ?>
				<?php $suma = $suma + $usr['monto']; ?>
			<?php } }else{ ?>

			<?php } ?>
			<span style="font-size: 19px;">Total de la solicitudes <?php echo $this->nombre_sitio; ?>:</span>
			<span style="font-size: 19px; font-weight: bold;">$<?php echo number_format($suma, 2, '.', ','); ?></span>
		</div>
	</div>

	<div class="col m12 s12">
		<table class="table text-left table-hover">
			<thead>
				<tr>
					<th>NO.</th>
					<th>Usuario</th>
					<th>Sitio</th>		
					<th>Residente</th>
					<th>Monto</th>
					<th>Autorización</th>
					<th>Detalle Solicitud</th>
				</tr> 
			</thead>
			<?php
			$total = 0;
			if ($this->paginator) { 
			foreach ($this->paginator as $usr) { ?>
			<tbody>
				<tr>
					<td>
						<?php echo $usr['id']; ?>
					</td>
					<td>
						<?php echo $usr['user_solicitud']; ?>
					</td>
					<td>
						<span style="font-weight: bold;"><?php echo $usr['nombre_sitio']; ?> </span> 
					</td>
					<td>
						<?php echo $usr['nombre_residente']; ?>
					</td>
					<td>
						<h5 style="font-weight: bold;">
							$<?php echo number_format($usr['monto'], 2, '.', ','); ?>
							<?php $total = $total + $usr['monto']; ?>
						</h5>
					</td>
					<td>
						<?php if($usr['autorizacion_status'] == 0){ ?>
							<a href="#modal1" class="modal-trigger auto-sol" data-id="<?php echo $usr['id']; ?>" data-comentario ="<?php echo $usr['comentario']; ?>">
								<div class="chip" id="inactivo_personal">
							    	<img src="/img/gris.jpg" >
							    	En proceso
							  	</div>
						  	</a>
						<?php } ?>

						<?php if($usr['autorizacion_status'] == 2){ ?>
							<div class="chip" id="activo_personal">
						    	<img src="/img/correct.png" >
						    	Autorizada
						  	</div>
						<?php } ?>

						<?php if($usr['autorizacion_status'] == 1){ ?>
							<div class="chip" id="inactivo_personal">
						    	<img src="/img/rojo.png" >
						    	Rechazada
						  	</div>
						<?php } ?>
						
					</td>
					<td class="text-center">
						<a href="/comprobacion/cajachicadetail/id/<?php echo $usr["id"] ?>/status/<?php echo $status; ?>"><i class="fa fa-2x fa-id-card-o"></i></a>
					</td>
				</tr>

		    <?php } }else{ ?>
		    </tbody> 
		    <tbody>
		        <tr>
		        	<td></td>
		        	<td></td>
		        	<td></td>
		            <td class="text-center" colspan=h4><h4>No hay solicitudes de Caja chica.</h4></td>
		            <td></td>
		            <td></td>
		        </tr>
		    </tbody>
		                
		    <?php } ?>
		</table>
	</div>
</div>


