<div class="row" style="margin-top: 10px;">
  <div class="col m12 s12">
    <?php if($this->fk_rol == 4){ ?>
      <a href="/comprobacion/cajachicacontabilidad/status/<?php echo $this->status_documento; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a> 
    <?php }else{ ?>
      <a href="/comprobacion/cajachicacontabilidad/status/<?php echo $this->status_documento; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a> 
    <?php } ?>   
  </div>
</div>

<?php foreach ($this->solicitud as $key){ 
  $id = $key['id'];
  $sitio = $key['nombre_sitio'];
  $residente = $key['nombre_residente'];
  $user = $key['user_solicitud'];
  $monto = $key['monto'];
  $tipo = $key['nombre_tipoproyecto'];
  $autorizacion = $key['autorizacion_status'];
  $pago_status = $key['pago_status'];
  $pago_file = $key['pago_file'];
  $pago_user = $key['pago_user'];
  $pago_fecha = $key['pago_fecha'];
  $monto_comprobado = $key['monto_anterior'];
  $status_resta = $key['status_resta'];

  if($status_resta == 1){
    $total = $monto_comprobado - $monto;
  }else{
    $total = $monto_comprobado;
  }

  
  
}?>

<style type="text/css">
  .titulo{
    font-size: 17px;
    font-weight: bold;
  }

  .facturas_shadow{
    -webkit-box-shadow: 6px 5px 9px -6px rgba(0,0,0,0.75);
    -moz-box-shadow: 6px 5px 9px -6px rgba(0,0,0,0.75);
    box-shadow: 6px 5px 9px -6px rgba(0,0,0,0.75);
  }

  .oculto{
    display: none;
  }
</style>

<input type="hidden" id="id_solicitudmodal" value="<?php echo $this->id_solicitud; ?>">  
  
<div class="row">
  <div class="col s12 m12">
    <div class="card  darken-1 facturas_shadow">
      <div class="card-content">
        <div class="row">
          <div class="col m6 s6">
            <span style="font-size:23px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información de la Solicitud</span>
          </div>
          <?php if($autorizacion == 0){ ?>
            <div class="col m6 s6"> 
              <div class="row">
                <div class="col m6 s6">
                  <div class="chip" id="activo_solicitud">
                    <img src="/img/gris.jpg" >
                    Autorizar
                  </div>
                </div>

                <div class="col m6 s6">
                  <div href="#modal1" class="modal-trigger auto-sol chip">
                    <img src="/img/gris.jpg" >
                    Rechazar
                  </div>
                </div>
              </div>

            </div>
          <?php } ?>

          <?php if($autorizacion == 2){ ?>
            <div class="col m6 s6"> 
              <div class="chip" id="activo_personal">
                <img src="/img/correct.png" >
                Autorizada
              </div>
            </div>
          <?php } ?>

          <?php if($autorizacion == 1){ ?>
            <div class="col m6 s6">
              <div class="chip" id="inactivo_personal">
                  <img src="/img/rojo.png" >
                  Rechazada
              </div>
            </div>
          <?php } ?>

        </div>
        
        <div class="row" style="margin-top: 20px;">
          <div class="col m8 s12">
            <span class="titulo">Residente:</span> <span><?php echo $residente; ?></span> <br>
            <span class="titulo">Sitio:</span> <span><?php echo $sitio; ?></span> <br>
            <span class="titulo">Saldo actual:</span> <span style="font-size: 20px; color: red;">$<?php echo number_format($total, 2, '.', ','); ?></span><br>
            <span class="titulo">Monto solicitado:</span> <span style="font-size: 20px; color: red;">$<?php echo number_format($monto, 2, '.', ','); ?></span>
            
          </div>

          <div class="col m4 s12">
              <div class="row">
                <div class="col m12 s12 text-center">
                  <a class="btn" href="/comprobacion/pdfcontabilidad/id/<?php echo $this->id_solicitud; ?>/status/<?php echo $this->status_documento; ?>"><i class="material-icons left">insert_drive_file</i>Solicitud</a>
                </div>
              </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<!-- <div class="row">
  <div class="col s12 m12">
    <div class="card darken-1">
      <div class="card-content">
        <h3 class="card-title">Agregar comprobante de pago</h3>
        <?php if($this->fk_rol == 4){ ?>
          <div class="row" style="margin-top: 19px;">
              <form action="/comprobacion/requestaddcomprobantepago" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_comprobante">
                <div class="file-field input-field col m8 s6">
                  <div class="btn">
                    <span>Comprobante</span>
                    <input type="file" name="url">
                  </div>
                  <div class="file-path-wrapper">
                    <input class="file-path validate" id="url_validate" type="text">
                  </div>
                </div>

                <input type="hidden" name="id" id="id_solicitudmodal" value="<?php echo $this->id_solicitud; ?>">
              </form>

              <div class="file-field input-field col m4 s6">
                <a class="btn" id="agregar_pago"><i class="material-icons right">send</i>Agregar</a>
              </div>

          </div>
        <?php } ?>

        <div class="row">
          <div class="col m12 s12">
            <table>
              <thead>
                <tr>
                  <th>No. Solicitud</th>
                  <th>Monto</th>
                  <th>Fecha</th>
                  <th>Usuario</th>
                  <th>Archivo</th>
                </tr>
              </thead>

              <tbody>
                <tr>
                  <td>
                    <?php echo $id; ?>
                  </td>
                  <td>
                    <span style="font-weight: bold;">$<?php echo number_format($monto, 2, '.', ','); ?></span>
                  </td>

                  <?php if($pago_fecha == null){ ?>
                    <td>Pendiente</td>
                  <?php }else{ ?>
                    <td><?php echo $pago_fecha; ?></td>
                  <?php } ?>

                  <?php if($pago_user == null){ ?>
                    <td>Pendiente</td>
                  <?php }else{ ?>
                    <td><?php echo $pago_user; ?></td>
                  <?php } ?>


                  <?php if($pago_file == null){ ?>
                    <td>Pendiente</td>
                  <?php }else{ ?>
                    <td>
                      <a title="Descargar Archivo" href="/<?php echo $pago_file; ?>" download="/<?php echo $pago_file; ?>" style="color: blue; font-size:18px;"> <i class="material-icons left">get_app</i> </a>
                    </td>
                  <?php } ?>

                </tr>
              </tbody>
            </table>
          </div> 
        </div>


      </div>
    </div>
  </div>
</div> -->


<div class="row">
  <div class="col s12 m12">
      <div class="card darken-1 facturas_shadow">
        <div class="card-content ">
          <div class="row">
            <div class="col m6 s6">
              <span style="font-size:23px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Facturas anteriores</span>
            </div>

            <div class="col m6 s6 text-right">
              <div class="row">
                <div class="col m6 s6 text-center">
                  <a class="btn green" id="exportBtn1">Generar Excel</a>
                </div>
                <div class="col m6 s6">
                  <a class="btn red" href="/comprobacion/pdfcomprobacion/id/<?php echo $this->id_solicitud; ?>/residente/<?php echo $this->id_residente; ?>/op/3/status/<?php echo $this->status_documento; ?>">Generar PDF</a>
                </div>
              </div>
            </div>
          </div>


          <div class="row"> 
            <div class="col m6 s6">
                <?php $factsi = 0;
                  if ($this->facturable_si) { 
                  foreach ($this->facturable_si as $usr) { ?>
                    <?php $factsi = $factsi + $usr['monto_comprobacion']; ?>
                  <?php } }else{ ?>

                  <?php } ?> 


                <?php $factno = 0;
                  if ($this->facturable_no) { 
                  foreach ($this->facturable_no as $usr) { ?>
                    <?php $factno = $factno + $usr['monto_comprobacion']; ?>
                  <?php } }else{ ?>

                  <?php } ?>
                <div class="row">
                  <div class="col m6 s12">
                    <span style="font-size: 19px;">Facturable:</span>
                    <span style="font-size: 19px; font-weight: bold;">$<?php echo number_format($factsi, 2, '.', ','); ?></span>
                  </div>
                  <div class="col m6 s6">
                    <span style="font-size: 19px; margin-left: 2px;">No facturable:</span>
                    <span style="font-size: 19px; font-weight: bold;">$<?php echo number_format($factno, 2, '.', ','); ?></span>
                  </div>
                </div>
            </div>
            <div class="col m6 s6 text-right">
              <?php $suma = 0;
                if ($this->solicitudes_anteriores) { 
                foreach ($this->solicitudes_anteriores as $usr) { ?>
                  <?php $suma = $suma + $usr['monto_comprobacion']; ?>
                <?php } }else{ ?>

                <?php } ?>

                <span style="font-size: 19px;">Monto Comprobado:</span>
                <span style="font-size: 19px; font-weight: bold;">$<?php echo number_format($suma, 2, '.', ','); ?></span>
            </div>
          </div>


            <table class="table text-left table-hover" style="margin-top: 30px;">
              <thead>
                <tr>
                  <th>Id.</th>
                  <th>Sitio</th> 
                  <th>Monto</th>  
                  <th>Monto comprobado</th>
                  <th>Servicio</th>
                  <th>Factura</th>
                  <th>Autorización</th>
                  <th></th>
                </tr> 
              </thead>
              <?php
              $monto = 0;
              if ($this->solicitudes_anteriores) { 
              foreach ($this->solicitudes_anteriores as $usr) { ?>



              <tbody>
                <tr>
                  <td>
                    <h5><?php echo $usr['id']; ?></h5>
                  </td>
                  <td>
                    <h5><?php echo $usr['nombre']; ?> / <?php echo $usr['nombre_proyecto'] ?> </h5>
                  </td>
                  <td>
                      <span style="font-weight: bold;">$<?php echo number_format($usr["monto_solicitud"], 2, '.', ','); ?></span>
                  </td>

                  <td>
                      <span style="font-weight: bold;">$<?php echo number_format($usr["monto_comprobacion"], 2, '.', ','); ?></span>
                  </td>
                  <td>
                    <h5><?php echo $usr['nameservicio']; ?></h5>
                  </td>

                  <td>
                    <?php if($usr['factura_file'] == NULL ){ ?>
<!--                       <a title="Descargar Archivo"  style="color: gray; font-size:18px;"> <i class="material-icons left">get_app</i> </a> -->
                      <a > <i class="material-icons prefix" style="font-size: 31px; color: gray;">open_with</i></a> 
                    <?php }else{ ?>
<!--                       <a title="Descargar Archivo" href="/<?php echo $usr["factura_file"]; ?>" download="/<?php echo $usr["factura_file"]; ?>" style="color: blue; font-size:18px;"> <i class="material-icons left">get_app</i> </a>  -->
                      <a href="/<?php echo $usr["factura_file"]; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px; color: blue;">open_with</i></a> 
                    <?php } ?>
                    
                  </td>
                  <td>
                    <?php if($usr['autorizacion'] == NULL ){ ?>
<!--                       <a title="Descargar Archivo"  style="color: gray; font-size:18px;"> <i class="material-icons left">get_app</i> </a> -->
                      <a > <i class="material-icons prefix" style="font-size: 31px; color: gray;">open_with</i></a>
                    <?php }else{ ?>
 <!--                    <a title="Descargar Archivo" href="/<?php echo $usr["autorizacion"]; ?>" download="/<?php echo $usr["autorizacion"]; ?>" style="color: blue; font-size:18px;"> <i class="material-icons left">get_app</i> </a> -->
                    <a href="/<?php echo $usr["autorizacion"]; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px; color: blue;">open_with</i></a> 
                  <?php } ?>
                  </td>


                   <?php if($this->status_documento != 0 ){ ?>
                   <?php }else{ ?>
                    <td>
                      <a class="modal-trigger viewinfo" href="#modal2" data-id="<?php echo $usr['id']; ?>" data-sitio="<?php echo $usr['nombre']; ?>" data-proyecto="<?php echo $usr['nombre_proyecto']; ?>" data-nofactura="<?php echo $usr['factura']; ?>" data-monto="<?php echo $usr['monto_solicitud']; ?>" data-montodos="<?php echo $usr['monto_comprobacion']; ?>" data-emisor="<?php echo $usr['rfc_emisor']; ?>" data-lugar="<?php echo $usr['lugar_expedicion'] ?>" data-forma="<?php echo $usr['forma_pago']; ?>" data-cliente="<?php echo $usr['id_cliente']; ?>" data-razon="<?php echo $usr['nombre_emisor']; ?>" data-fechauser="<?php echo $usr['fecha_user'] ?>" data-user="<?php echo $usr['user']; ?>"><i class="fa fa-2x fa-id-card-o"></i></a>
                    </td>
                    <td>
                      <a class="modal-trigger delete" href="#modal3" data-id="<?php echo $usr['id']; ?>"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
                    </td>
                   <?php } ?> 
                </tr>

                <?php } }else{ ?>
                </tbody> 
                <tbody>
                    <tr>
                        <td class="text-center" colspan="6"><h4>No hay comprobaciones pendientes.</h4></td>
                    </tr>
                </tbody>
                            
                <?php } ?>
            </table>
        </div>
      </div>
  </div>
</div>


  <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
      <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Rechazar Autorización</span> 
        <div class="row" style="margin-top: 20px;">
          <div class="input-field col s12">
              <input id="cancelar_comentario" placeholder="" type="text" class="validate">
              <label for="cancelar_comentario">* Motivo de la cancelación</label>
          </div>
        </div>
    </div>
    <div class="modal-footer">
      <a class="btn" id="solicitud-cancelada">Aceptar</a>
      <button  class="modal-close red btn">Cerrar</button>
    </div>
  </div>


  <div id="modal2" class="modal modal-fixed-footer">
    <div class="modal-content">
      <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalle de la Factura</span> 
        <div class="row" style="margin-top: 20px;">
          <div class="input-field col s6 m6">
            <input type="text" placeholder="" id="modal_sitio" value="">
            <label for="modal_sitio">Sitio</label>
          </div>

          <div class="input-field col s6 m6">
            <input type="text" placeholder="" id="modal_proyecto" value="">
            <label for="modal_proyecto">Proyecto</label>
          </div>

          <div class="input-field col s6 m6">
            <input type="text" placeholder="" id="modal_nofactura" value="">
            <label for="modal_nofactura">No.Factura</label>
          </div>

          <div class="input-field col s6 m6">
            <input type="text" placeholder="" id="modal_razon" value="">
            <label for="modal_razon">Razon social</label>
          </div>

          <div class="input-field col s6 m6">
            <input type="text" placeholder="" id="modal_rfc" value="">
            <label for="modal_rfc">RFC emisor</label>
          </div>

          <div class="input-field col s6 m6">
            <input type="text" placeholder="" id="modal_lugar" value="">
            <label for="modal_lugar">Lugar</label>
          </div>

          <div class="input-field col s6 m6">
            <input type="text" placeholder="" id="modal_fecha" value="">
            <label for="modal_fecha">Fecha comprobación</label>
          </div>

          <div class="input-field col s6 m6">
            <input type="text" placeholder="" id="modal_realizada" value="">
            <label for="modal_realizada">Realizada por:</label>
          </div>

        </div>
    </div>
    <div class="modal-footer">
      <button  class="modal-close red btn">Cerrar</button>
    </div>
  </div>


  <div id="modal3" class="modal modal-fixed-footer">
    <div class="modal-content">
      <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Eliminar Comprobación</span> 
        <div class="row" style="margin-top: 20px;">
          <div class="input-field col s12">
              <input id="eliminar_comprobacion" placeholder="" type="text" class="validate">
              <label for="eliminar_comprobacion">* Comentario</label>
          </div>
        </div>
    </div>
    <div class="modal-footer">
      <a class="btn" id="comprobacion-cancelada">Aceptar</a>
      <button  class="modal-close red btn">Cerrar</button>
    </div>
  </div>


<form action="/comprobacion/requestdeletecomprobacion" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_delete">

  <input type="hidden" name="id_solicitud" id="form_sol">
  <input type="hidden" name="actual_id" value="<?php echo $this->id_solicitud; ?>">
  <input type="hidden" name="status" value="<?php echo $this->status_documento; ?>">
  <input type="hidden" name="comentario" id="form_comentario" value="">

</form>


<?php 
$pago = 0;
foreach ($this->solicitud as $key) {
  $pago = $key['pago_status'];
} 
?>


<div class="row">
  <div class="col s12 m12">
    <div class="card">
      <div class="card-content">
        <span style="font-size:23px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Comprobante Pago</span>
        

        <?php if($this->status_documento != 0){ ?>
        <?php }else{ ?>

          <?php if($pago != 1){ ?>
            <div class="row">
              <div class="col m2 12"></div>
              <div class="col m8 s12" style="margin-top: 20px;">
                <form action="/comprobacion/requestaddpagocajachica" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_pago"> 
                  <input type="hidden" name="actual_id" value="<?php echo $this->id_solicitud; ?>">
                  <input type="hidden" name="status" value="<?php echo $this->status_documento; ?>">
                  <div class="file-field input-field col s8">
                    <div class="btn">
                      <span>Comprobante</span>
                      <input type="file" name="url">
                    </div>
                    <div class="file-path-wrapper">
                      <input class="file-path validate" name="file_val" id="validation_url" type="text">
                    </div>
                  </div>
                </form>
                <div class="input-field col s4 text-left">
                  <a class="btn" id="add_pagochica"><i class="material-icons right">send</i>Agregar</a>
                </div>
              </div>
              <div class="col m2 12"></div>
            </div>
          <?php } ?>

        <?php } ?>

        <div class="row">
          <div class="col m12 s12">
            <table class="table text-left table-hover" style="margin-top: 30px;">
              <thead>
                <tr>
                  <th>Fecha Pago</th>
                  <th>Realizado por:</th> 
                  <th>Monto</th>  
                  <th>Descargar</th>
                </tr> 
              </thead>
              <?php
              $monto = 0;
              if ($this->pago_comprobante) { 
              foreach ($this->pago_comprobante as $usr) { ?>

              <tbody>
                <tr>
                  <td>
                    <h5><?php echo $usr['fecha_pago']; ?></h5>
                  </td>
                  <td>
                    <h5><?php echo $usr['user_pago']; ?> </h5>
                  </td>
                  <td>
                     <span style="font-weight: bold;">$<?php echo number_format($usr["monto"], 2, '.', ','); ?></span>
                  </td>
                  <td>
                    <a title="Descargar Archivo" href="/<?php echo $usr["file_pago"]; ?>" download="<?php echo substr(strrchr($usr["file_pago"], "/"), 1); ?>" style="color: blue; font-size:18px;"> <i class="material-icons left">get_app</i> </a>
                  </td>
                </tr>
                <?php } }else{ ?>
                </tbody> 
                <tbody>
                    <tr>
                        <td class="text-center" colspan="6"><h4>No hay un comprobante agregado.</h4></td>
                    </tr>
                </tbody>
                          
                <?php } ?>
            </table>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>


  <div class="row oculto">
<div class="row excel-div" id="tab1">
  <table class="table text-left table-hover" >
                <thead>
                  <tr>
                    <th>Id.</th>
                    <th>Sitio</th> 
                    <th>Monto</th>  
                    <th>Monto comprobado</th>
                    <th>Servicio</th>
                    <th>Facturable</th>
                    <th>Factura</th>
                    <th></th>
                  </tr> 
                </thead>
                <?php
                $monto = 0;
                $monto_comprobado = 0 ;
                if ($this->solicitudes_anteriores) { 
                foreach ($this->solicitudes_anteriores as $usr) { ?>

                <tbody>
                  <tr>
                    <td>
                      <h5><?php echo $usr['id']; ?></h5>
                    </td>
                    <td>
                      <h5><?php echo $usr['nombre']; ?> / <?php echo $usr['nombre_proyecto']; ?> </h5>
                    </td>
                    <td>
                        <span style="font-weight: bold;">$<?php echo number_format($usr["monto_solicitud"], 2, '.', ','); ?></span>
                    </td>

                    <td>
                        <span style="font-weight: bold;">$<?php echo number_format($usr["monto_comprobacion"], 2, '.', ','); ?></span>
                    </td>
                    <td>
                      <h5><?php echo $usr['nameservicio']; ?></h5>
                    </td>
                    <td>
                      <?php if($usr['facturable'] == 1){ ?>
                        <h5>Si</h5>
                      <?php }else{ ?>
                        <h5>No</h5>
                      <?php } ?>
                    </td>
                    <td>
                      <?php echo $usr['factura']; ?>
                    </td>
                  </tr>
                  <?php $monto = $monto + $usr['monto_solicitud']; ?>
                  <?php $monto_comprobado = $monto_comprobado + $usr['monto_comprobacion']; ?>
                  <?php } ?>
                  <tr>
                    <td></td>
                    <td></td>
                    <td>Total: $<?php echo number_format($monto, 2, '.', ','); ?></td>
                    <td>Total: $<?php echo number_format($monto_comprobado, 2, '.', ','); ?></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>Facturable $<?php echo number_format($factsi, 2, '.', ','); ?></td>
                    <td>No Facturable $<?php echo number_format($factno, 2, '.', ','); ?></td>
                  </tr>


                  <?php }else{ ?>
                  </tbody> 
                  <tbody>
                      <tr>
                          <td class="text-center" colspan="6"><h4>No hay comprobaciones pendientes.</h4></td>
                      </tr>
                  </tbody>
                              
                  <?php } ?>
  </table>  
</div>

  </div>


  <input type="hidden" id="name_residente" value="<?php echo $residente; ?>">
  <input type="hidden" id="id_comprobacion" value="<?php echo $this->id_solicitud; ?>">
<script type="text/javascript">
  $(document).ready(function(){
    $('.modal').modal();
  });


    $("#activo_solicitud").click(function(){
      var comentario = document.getElementById("cancelar_comentario").value;
      var id = document.getElementById("id_solicitudmodal").value;
      $("#comentario-can").hide();
    swal({
      title: "Estas seguro de autorizar la solicitud?",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
        if (willDelete) {
          swal("Espere un momento, la información esta siendo procesada", {
           icon: "success",
           buttons: false,
          });

          var dato = "2";
              var request = $.ajax({
                  url:"/comprobacion/requestchangesolicitudcajachica",
                  method:"POST",
                  data: { id:id, dato:dato, comentario:comentario},
                  processData: true,
              });
  //-------------------end de ajax---------------------------
  //-------------peticion de respuesta de ajax------------------
              request.done(function(response) {
                  console.log(response);//imprime lo que responde el ajax
                  // alert
                  window.location.reload(true);
              });
  //-------------------end de respuesta ajax---------------------
               return false;
        } else {
          swal("Accion cancelada!");
        }
      });

    });

    $("#solicitud-cancelada").click(function(){
      var comentario = document.getElementById("cancelar_comentario").value;
      var id = document.getElementById("id_solicitudmodal").value;

    swal({
      title: "Estas seguro de cancelar la solicitud?",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
        if (willDelete) {
          swal("Espere un momento, la información esta siendo procesada", {
           icon: "success",
           buttons: false,
          }); 
          var dato = "1";
              var request = $.ajax({
                  url:"/comprobacion/requestchangesolicitudcajachica",
                  method:"POST",
                  data: { id:id, dato:dato, comentario:comentario},
                  processData: true,
              });
  //-------------------end de ajax---------------------------
  //-------------peticion de respuesta de ajax------------------
              request.done(function(response) {
                  console.log(response);//imprime lo que responde el ajax
                  // alert
                  window.location.reload(true);
              });
  //-------------------end de respuesta ajax---------------------
               return false;

        } else {
          swal("Accion cancelada!");
        }
      });

    });


  $("#agregar_pago").click(function(){
    var documento = document.getElementById("url_validate").value;
    if(documento == ""){
      swal({
        title: "Para continuar debes agregar un documento",
      });
    }else{
      swal("Espere un momento, la información esta siendo procesada", {
        icon: "success",
        buttons: false,
      });  
      setTimeout(submitFormdos, 1500);     
    }
  });
  function submitFormdos() { document.getElementById("submit_comprobante").submit() }


  $(".viewinfo").click(function(){
    var id =$(this).data('id');
    var sitio =$(this).data('sitio');
    var proyecto =$(this).data('proyecto');
    var cliente =$(this).data('cliente');
    var nofactura =$(this).data('nofactura');
    var razon =$(this).data('razon');
    var emisor =$(this).data('emisor');
    var lugar =$(this).data('lugar');
    var monto =$(this).data('monto');
    var montodos =$(this).data('montodos');
    var fechauser =$(this).data('fechauser');
    var user =$(this).data('user');

    document.getElementById("modal_sitio").value = sitio;
    document.getElementById("modal_proyecto").value = proyecto + " / Cliente:" + cliente ;
    document.getElementById("modal_nofactura").value = nofactura;
    document.getElementById("modal_razon").value = razon;
    document.getElementById("modal_rfc").value = emisor;
    document.getElementById("modal_lugar").value = lugar;
    document.getElementById("modal_fecha").value = fechauser;
    document.getElementById("modal_realizada").value = user;
    
  });


  // $(".delete").click(function(){
  //   var id =$(this).data('id');

  //   swal({
  //     title: "Estas seguro de eliminar la comprobación?",
  //     icon: "warning",
  //     buttons: true,
  //     dangerMode: true,
  //   })
  //   .then((willDelete) => {
  //       if (willDelete) {
  //         swal("Espere un momento, la información esta siendo procesada", {
  //          icon: "success",
  //          buttons: false,
  //         });

  //         var dato = "2";
  //             var request = $.ajax({
  //                 url:"/comprobacion/",
  //                 method:"POST",
  //                 data: { id:id},
  //                 processData: true,
  //             });
  // //-------------------end de ajax---------------------------
  // //-------------peticion de respuesta de ajax------------------
  //             request.done(function(response) {
  //                 console.log(response);//imprime lo que responde el ajax
  //                 // alert
  //                 window.location.reload(true);
  //             });
  // //-------------------end de respuesta ajax---------------------
  //              return false;
  //       } else {
  //         swal("Accion cancelada!");
  //       }
  //     });


  // });



    $(".delete").click(function(){
        var id =$(this).data('id');
        document.getElementById("form_sol").value = id;
    });

    $("#comprobacion-cancelada").click(function(){
        id = document.getElementById("form_sol").value;
        comentario = document.getElementById("eliminar_comprobacion").value;

        document.getElementById("form_comentario").value = comentario;
        if(id == ""){
            swal({
              title: "Para agregar un imagen debes seleccionar una tarea ",
            });
        }else{
      swal("Espere un momento, la información esta siendo procesada", {
        icon: "success",
        buttons: false,
      }); 
            setTimeout(submitdelete, 1500);     
        }
    });

     function submitdelete() { document.getElementById("submit_delete").submit() }


    $("#add_pagochica").click(function(){
        var actividad = document.getElementById("validation_url").value;

        if(actividad == ""){
            swal({
              title: "Para agregar el pago es necesario adjuntar el archivo",
            });
        }else{
      swal("Espere un momento, la información esta siendo procesada", {
        icon: "success",
        buttons: false,
      }); 
            setTimeout(submitpago, 1500);     
        }
    });

    function submitpago() { document.getElementById("submit_pago").submit() }

</script>

<script src="https://cdn.jsdelivr.net/gh/linways/table-to-excel@v1.0.4/dist/tableToExcel.js"></script>


<script type="text/javascript">
      $("#exportBtn1").click(function(){
        var residente = document.getElementById("name_residente").value;
        var id = document.getElementById("id_comprobacion").value;
        
        TableToExcel.convert(document.getElementById("tab1"), {
            name: "Comprobacion No. "+id+" -"+residente+" .xlsx",
            sheet: {
              name: "Comprobacion No. "+id+" -"+residente+""
            }
          });
        });
</script>