<div class="row">
    <div class="col m12 s12 text-center" style="margin-top: 40px;">
        <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Terminar Solicitud</span>
    </div>
</div>


<?php foreach ($this->solicitud as $key) {
	$residente = $key['nombre_residente'];
	$monto = $key['monto'];
	$monto_anterior = $key['monto_anterior'] - $monto;
	$total = $monto_anterior + $monto;
} ?>



 <div class="row">
    <div class="col s12 m12">
      <div class="card ">
        <div class="card-content">

        	<div class="row">
        		<div class="col m12 s12">
        			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información de la solicitud</span>
        		</div>
        	</div>

        	<div class="row">
        		<div class="col m12 s12">
        			<h4><?php echo $residente ?></h4>
        			<div class="row">
        				<div class="col m4 s4">
        					<h4>Monto: $<?php echo number_format($monto, 2, '.', ','); ?></h4>
        				</div>
        				<div class="col m4 s4"> 
        					<h4>Saldo anterior $<?php echo number_format($monto_anterior, 2, '.', ','); ?></h4>
        				</div>
        				<div class="col m4 s4"> 
        					<h4>Total: $<?php echo number_format($total, 2, '.', ','); ?></h4>
        				</div>
        			</div>
        			
        		</div>
        	</div>

			<div class="row">
				<div class="col m12 s12">
			  		<div class="input-field col m6 s12">
			  			<form action="/solicitud/requestupdtatenewsolicitudcajachica" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_file_altan">
			  				<input type="hidden" name="id_solicitud" value="<?php echo $this->solicitud_id; ?>">
				    		<select id="sitio" name="sitio">
				      			<option value="0" disabled selected>* Selecciona un Sitio</option>
				      			<option value="oficina" >Oficina</option>
				      			<option value="almacen" >Stock Almacén</option>
				      			<?php foreach ($this->sitios as $key){ ?>
				      				<option value="<?php echo $key['id']; ?>"><?php echo $key['nombre']; ?> - <?php echo $key['id_cliente']; ?></option>
				      			<?php } ?>
				    		</select>
				    		<label>Sitio:</label>
			    	 	</form>	
			  		</div>

			  		<div class="input-field col m6 s12 text-center">
			  			<a class="btn" id="enviar_solicitud"><i class="material-icons right">arrow_forward</i>Terminar</a>
			  		</div>
				</div>
			</div>
        </div>
      </div>
    </div>
  </div>


<script type="text/javascript">
		$("#enviar_solicitud").click(function(){
			var sitio = document.getElementById("sitio").value;

	    	if(sitio == 0){
	            swal({
	             	title: "Para continuar debes agregar un sitio",
	            });

	    	}else{
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				});
	    		setTimeout(submitaltan, 1500);
	    	}
		});

    	function submitaltan() { document.getElementById("submit_file_altan").submit() }
</script>