<html>
<!-- add the at least required css-->  
<!-- start of Kendo UI jQuery related CSS-->  
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2020.1.219/styles/kendo.common.min.css">  
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2020.1.219/styles/kendo.rtl.min.css">  
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2020.1.219/styles/kendo.default.min.css">  
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2020.1.219/styles/kendo.mobile.all.min.css">  
<!-- end of Kendo UI Jquery related CSS-->  
  
<!-- add the kendo ui library-->  
<!-- start of Kendo UI jQuery Scripts-->  
<script src="https://code.jquery.com/jquery-1.12.3.min.js"></script>  
<script src="https://kendo.cdn.telerik.com/2020.1.219/js/jszip.min.js"></script>  
<script src="https://kendo.cdn.telerik.com/2020.1.219/js/kendo.all.min.js"></script>  
<!-- end of Kendo UI jQuery Scripts-->  
    <body>

        <div id="example">
            <?php foreach ($this->residente as $res){ 
                $id_residente = $res['id'];
                $nombre_res = $res['nombre'];
                $apellido_res = $res['apellido_pa']." ".$res['apellido_ma'];
                $telefono_res = $res['telefono'];
                $email_res = $res['email_personal'];
                $tarjeta = $res['tarjeta'];
            } ?>


            <?php
                date_default_timezone_set('America/Mexico_City');
                $hoy = date("d/m/Y");
            ?>


            <div class="row" style="margin-top: 10px;">
                <div class="col m6 s6">

                    <?php if($this->option_back == 1){ ?>
                        <a href="/comprobacion/cajachicadetail/id/<?php echo $this->id_comprobacion; ?>/status/<?php echo $this->status_back; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
                    <?php } ?>

                    <?php if($this->option_back == 2){ ?>
                        <a href="/comprobacion/reportecomprobaciones/id/<?php echo $this->id_comprobacion; ?>/residente/<?php echo $this->residente_id; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
                    <?php } ?>

                    <?php if($this->option_back == 3){ ?>
                        <a href="/comprobacion/detailcontabilidad/id/<?php echo $this->id_comprobacion; ?>/status/<?php echo $this->status_back; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
                    <?php } ?>

                </div>

                <div class="col m6 s6 text-right" id="download" style="display: none;" >
                    <button class="export-pdf btn"  onclick="getPDF('.pdf-page')">Descargar Reporte</button>
                </div>
            </div>


            <div class="row">
                <div class="col m1 s12"></div>
                <div class="col m10 s12">
                    <div class="page-container hidden-on-narrow">
                        <div class="pdf-page size-a4">
                            <div class="pdf-header">
                                
                                <span class="col m6 s6 company-logo">
                                    <img src="/img/head.png" style="width: 130px;" />
                                </span>

                                <span class="col m6 s6 text-right invoice-number">
                                    <img src="/img/logo-2.png" style="width: 220px;" />
                                </span>

                                <div class="row">
                                    <div class="company-logo col m12 s12 text-center">
                                        Reporte de Facturas 
                                    </div>
                                </div>


                                    <?php foreach ($this->info_solicitud as $value) {
                                        $sitio_val = $value['nombre_sitio'];
                                    } ?>


                                <div class="row">
                                    <div class="col m6 s6 for ">
                                        <h3> Datos del Personal</h3>
                                        <p>
                                            <span class="title-pdf">Personal: </span> <?php echo $nombre_res; ?> <?php echo $apellido_res; ?> <br />
                                            <span class="title-pdf">Telefono:</span> <?php echo $telefono_res; ?><br />
                                            <span class="title-pdf">Email:</span> <?php echo $email_res ?><br/>
                                            <span class="title-pdf">No. Tarjeta:</span> <?php echo $tarjeta ?><br/>
                                            <span class="title-pdf">Sitio:</span> <?php echo $sitio_val; ?>
                                        </p>
                                    </div>

                                    <div class="col m6 s6 text-right from">
                                        <h4> Fecha: <?php echo $hoy; ?></h4>
                                        <div>
                                            <h4> Solicitud: <?php echo $this->id_comprobacion; ?></h4> 
                                        </div>
                                    </div>
                                </div>

                                <div class="row">

                                    <?php 
                                        $total = 0;
                                        $total_comprobado = 0;
                                        foreach ($this->solicitudes_anteriores as $key ){
                                            $total = $total+ $key['monto_solicitud'];
                                            $total_comprobado = $total_comprobado + $key['monto_comprobacion'];
                                        } 

                                    ?>

                                        <?php foreach ($this->info_solicitud as $value) {
                                            $id_sol = $value['id'];
                                            $monto_sol = $value['monto'];
                                            $monto_anterior = $value['monto_anterior'];
                                        } ?>

                                      <div class="row"> 
                                        <!-- <div></div> class="col m6 s6"></div> -->
                                        <div class="col m6 s6 text-right">
                                          <?php $suma = 0;
                                            if ($this->solicitudes_anteriores) { 
                                            foreach ($this->solicitudes_anteriores as $usr) { ?>
                                              <?php $suma = $suma + $usr['monto_comprobacion']; ?>
                                            <?php } }else{ ?>

                                            <?php } ?>

                                          <?php $factsi = 0;
                                            if ($this->facturable_si) { 
                                            foreach ($this->facturable_si as $usr) { ?>
                                              <?php $factsi = $factsi + $usr['monto_comprobacion']; ?>
                                            <?php } }else{ ?>

                                            <?php } ?> 


                                          <?php $factno = 0;
                                            if ($this->facturable_no) { 
                                            foreach ($this->facturable_no as $usr) { ?>
                                              <?php $factno = $factno + $usr['monto_comprobacion']; ?>
                                            <?php } }else{ ?>

                                            <?php } ?>
                                        </div>
                                      </div>


                                      <div class="row"> 
                                        <!-- <div></div> class="col m6 s6"></div> -->
                                        <div class="col m6 s6 text-right">
                                          <?php $sumas = 0;
                                            if ($this->solicitudes_anteriores) { 
                                            foreach ($this->solicitudes_anteriores as $usr) { ?>
                                              <?php $sumas = $sumas + $usr['monto_solicitud']; ?>
                                            <?php } }else{ ?>

                                            <?php } ?>

                                          <?php $factsi_ofi = 0;
                                            if ($this->facturable_si) { 
                                            foreach ($this->facturable_si as $usr) { ?>
                                              <?php $factsi_ofi = $factsi_ofi + $usr['monto_solicitud']; ?>
                                            <?php } }else{ ?>

                                            <?php } ?> 


                                          <?php $factno_ofi = 0;
                                            if ($this->facturable_no) { 
                                            foreach ($this->facturable_no as $usr) { ?>
                                              <?php $factno_ofi = $factno_ofi + $usr['monto_solicitud']; ?>
                                            <?php } }else{ ?>

                                            <?php } ?>
                                        </div>
                                      </div>

                                      <!-- <?php echo $sumas; ?> -->
<!--                                       <?php $restante = $monto_anterior - $total_comprobado; 
                                        echo $restante;
                                      ?> -->

                                    <div class="row">
                                        <div class="col m4 s6 text-center">
                                            <span class="title-pdf">Monto Anterior: $<?php echo number_format($monto_anterior, 2, '.', ','); ?></span>
                                        </div>
                                        <div class="col m4 s6 text-center">
                                            <span class="title-pdf">Total Comprobado autorizado: $<?php echo number_format($total_comprobado, 2, '.', ','); ?></span>
                                        </div>

                                        <div class="col m4 s6 text-center">
                                            <span class="title-pdf">Monto Solicitud: $<?php echo number_format($monto_sol, 2, '.', ','); ?></span>
                                        </div>


                                    </div>

                    <div class="row">
                        <div class="col m2 s12"></div>
                        <div class="col m8 s12">
                          <table>
                            <thead>
                              <tr>
                                  <th></th>
                                  <th>Residente</th>
                                  <th>Control Proyectos</th>
                              </tr>
                            </thead>

                            <tbody>
                              <tr>
                                <td>Facturable</td>
                                <td>$<?php echo number_format($factsi_ofi, 2, '.', ','); ?></td>
                                <td>$<?php echo number_format($factsi, 2, '.', ','); ?></td>
                              </tr>

                              <tr>
                                <td>No facturable</td>
                                <td>$<?php echo number_format($factno_ofi, 2, '.', ','); ?></td>
                                <td>$<?php echo number_format($factno, 2, '.', ','); ?></td>
                              </tr>

                              <tr>
                                <td>Total</td>
                                <td>
                                    <?php $suma_re = $factsi_ofi + $factno_ofi; ?>

                                    $<?php echo number_format($suma_re, 2, '.', ','); ?>
                                </td>
                                <td>
                                    <?php $suma_oficina = $factsi + $factno; ?>

                                    $<?php echo number_format($suma_oficina, 2, '.', ','); ?>
                                </td>
                              </tr>

                            </tbody>
                          </table>
                        </div>
                        <div class="col m2 s12"></div>
                    </div>




<!--           <div class="row" style="margin-top: 20px;"> 
            <div class="col m4 s12">
                <span style="font-size: 19px;">Facturable <?php echo $this->nombre_sitio; ?>:</span>
                <span style="font-size: 19px; font-weight: bold;">$<?php echo number_format($factsi, 2, '.', ','); ?></span>   
            </div>
            <div class="col m4 s12">
                <span style="font-size: 19px;">No facturable <?php echo $this->nombre_sitio; ?>:</span>
                <span style="font-size: 19px; font-weight: bold;">$<?php echo number_format($factno, 2, '.', ','); ?></span>
            </div>
          </div> -->


                                    <div class="col m12 s12 text-center">
                                        <span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Facturas Comprobadas
                                        </span><br>
                                    </div>
                                </div>
                            </div>

                            <div class="pdf-body">
                                <div class="grida" id="grid">
                                  <input type="hidden" name="datos" id="datos" value="<?php echo $this->id_comprobacion; ?>">
                                </div>
                            </div>
                    
                            <div class="row" style="margin-top: 10px;">
                                <div class="col m12 s12 ">
                                    <span class="title-pdf">
                                        Gps Constructivos      
                                    </span><br> 
                                    <span class="title-pdf">
                                        Fecha de descarga: <?php echo $hoy; ?>     
                                    </span>
                                </div>
                            </div>

                            <div class="row signature">
          <!--                       <div class="col m6 s6 text-center">
                                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Entregado por:</span><br><br><br>
                                    <hr>
                                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nombre y Firma</span>
                                </div>
                                <div class="col m6 s6 text-center">
                                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Recibido por:</span><br><br>
                                    <?php echo $nombrea; ?> <?php echo $apellido_pa; ?> <?php echo $apellido_ma; ?>
                                    <hr>
                                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nombre y Firma</span>
                                </div> -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col m1 s12"></div>
            </div>



            <div class="responsive-message"></div>
            <div id="pdfPageCopy"></div>


            <!-- Load Pako ZLIB library to enable PDF compression -->
            <script src="../content/shared/js/pako.min.js"></script>

            <script>

                $(document).ready(function(){
                    cpAjax();
                });

                function getPDF(selector) {

                    kendo.drawing.drawDOM($('.pdf-page'), {
                        paperSize: "A4",
                        scale: 0.7})          
                    .then(function(group){
                        return kendo.drawing.exportPDF(group, {
                            margin: { left: "0.6cm", top: "0.6cm", right: "0.6cm", bottom: "0cm" }
                        });
                    })

                    .done(function(data) {
                        kendo.saveAs({
                            dataURI: data,
                            fileName: "Comprobacion No. <?php echo $this->id_comprobacion; ?> - <?php echo $nombre_res; ?> <?php echo $apellido_res; ?> <?php echo $hoy; ?> .pdf"
                        });
                    });
                }

                function herramientas(datost){
                    var data = datost;
                    var grid = $("#grid").kendoGrid({
                        editable: false,
                        sortable: false,
                        dataSource: {
                            data: data
                        }
                    });
                }

                function cpAjax(){ 
                    var download = document.getElementById("download");
                    datos = document.getElementById("datos").value;
                    variable = datos;

                    $.ajax({
                        url: "/comprobacion/datos",
                        data: {
                            variable: variable
                        },

                        type: "POST",

                        success: function( data ) {
                            download.style.display = "block";
                            
                            var aData = JSON.parse( data );
                            herramientas(aData);
                            console.log( aData );
                        },

                        error: function(a, b, c) {

                            console.log(a);

                            console.log(b);

                            console.log(c);
                        }
                    });
                }

            </script>

            <style>

                .title-pdf {
                    font-weight: bold;
                    font-size: 13px;
                }

                .invoice-number {
                    padding-top: .17in;
                    float: right;
                }
                .pdf-footer {
                    position: absolute;
                    bottom: .5in;
                    height: .6in;
                    left: .5in;
                    right: .5in;
                    padding-top: 10px;
                    border-top: 1px solid #e5e5e5;
                    text-align: left;
                    color: #787878;
                    font-size: 12px;
                }
                .pdf-body {
                    
                    top: 3.5in;
                    bottom: 13.2in;
                    left: .5in;
                    right: .5in;
                }

                 .grida {
                     color: red;
                     font-size: 12px;
                }

                .grida th{
                    font-weight: bold;
                    font-size: 16px;
                    background-color: white;
                }

                .grida td{
                  padding-top: 1px;
                  padding-bottom: 1px;
                  height: 25px;
                }

                .size-a5 { width: 8.3in; height: 5.8in; }
                .size-a4 { width: 210mm; height: 310mm; }
                .size-letter { width: 8.5in; height: 11in; }
                .size-executive { width: 7.25in; height: 10.5in; }

                .company-logo {
                    font-size: 30px;
                    font-weight: bold;
                    color: #000080;
                }
                
                .for {
                    width: 3.5in;
                }
                
                .from {
                    width: 3.5in;
                }
                
                .from p, .for p {
                    color: #787878;
                }
                
                .signature {
                    padding-top: .3in;
                }
            </style>
        </div>
    </body>
</html>
