
<div class="row" style="margin-top: 10px;">
  <div class="col m12 s12">
      <a href="/comprobacion/detailreembolso/id/<?php echo $this->id_solicitud; ?>/status/<?php echo $this->status_documento; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a> 
</div>

<html>
<head>
    <!-- <base href="https://demos.telerik.com/kendo-ui/pdf-export/page-layout">
    <style>html { font-size: 14px; font-family: Arial, Helvetica, sans-serif; } --></style>
    <title></title>
   <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.common.min.css" />
<!--      <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.black.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.black.mobile.min.css" /> -->

    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/kendo.all.min.js"></script>
</head>
<body>
<div id="example">
<!--     <div class="box wide hidden-on-narrow">
        <div class="box-col">
            <button class="export-pdf btn" onclick="getPDF('.pdf-page')">Descargar</button>
        </div>
    </div>
 -->

<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12 text-right">
        <button class="export-pdf btn" onclick="getPDF('.pdf-page')">Descargar</button>
    </div>
</div>



<?php foreach ($this->info_solicitud as $key) {
    $residente = $key['nombre_residente'];
    $sitio = "Reembolso";
    $total = $key['monto'];
    $fecha_solicitud = $key['fecha_solicitud'];
} ?>

    <?php 
            date_default_timezone_set('America/Mexico_City');
            $hoy = date("d/m/Y");
     ?>


    <div class="page-container hidden-on-narrow">
        <div class="pdf-page size-a4">
            <div class="pdf-header">
                <span class="company-logo">
                    <img src="/img/head.png" style="width: 120px;" />
                </span>

                <span class="invoice-number">
                    <img src="/img/logo-2.png" style="width: 125px;" /><br/>
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Solicitud No.<?php echo $this->id_solicitud; ?></span>
                </span>
                <div class="row">
                    <div class="company-logo col m12 s12 text-center">
                        Reembolso Caja Chica
                    </div>
                </div>
            </div>
            <div class="pdf-footer">
                <p>Nte 31-A No. 96, col. Lindavista Vallejo III, Gustavo A. Madero, C.P. 07720, CDMX<br />
                    Fecha de descarga: <?php echo $hoy; ?><br />
                </p>
            </div>
            <div class="for" style="margin-top: 110px;">
                <span class="title-pdf">Fecha solicitud :</span> <?php echo $fecha_solicitud; ?><br />
                    <span class="title-pdf">Residente:</span> <?php echo $residente; ?><br />
                    <span class="title-pdf" style="color: red;">Monto:</span>$<?php echo number_format($total, 2, '.', ','); ?><br />
                </p>
            </div>

            <div class="from" style="margin-top: 110px;">
                <?php if($this->pago_if == 2){ ?>
                    <?php foreach ($this->pago_comprobante as $key) {
                        $realizado = $key['user_pago'];
                        $fecha = $key['fecha_pago'];
                    }?>
                    <span class="title-pdf">Pago realziado por:</span> <?php echo $realizado; ?><br />
                    <span class="title-pdf">Fecha pago:</span> <?php echo $fecha; ?>
                    <?php }else{ ?>
                        <span class="title-pdf">El reembolso no se ha realizado:</span> 
                    <?php } ?>
            </div>
            <div class="pdf-body">
<!--                 <div id="grid">
                	
                </div> -->
                <div class="row">
<!--                     <div class="text-center">
                        <span style="color:red; font-size: 10px;">DESCRIPCION BREVE DEL MATERIAL (SE TIENE QUE ADJUNTAR LA COTIZACION DEL PROVEEDOR).</span>
                    </div> -->



                </div>

<!-- <?php 
    $originalDate = $fecha_creacion;
    $newDate = date("d/m/Y H:i", strtotime($originalDate));

    $validacion = $fecha_val; 
    $newDate_val = date("d/m/Y H:i", strtotime($validacion));

    $validacion_jefe = $fecha_jefe;
    $newDate_jefe = date("d/m/Y H:i", strtotime($validacion_jefe));
?> -->



                <div class="row signature">
                    <div class="col m12 s12 text-center">
                        <img src="/img/logo-2.png" style="width: 150px;"><br>
                        Aprobado: ING. Rubén García Guzmán<br /><br />
                        <!-- <?php echo $fecha_autorizacion; ?> -->
                    </div>
                </div>


<!--                 <p class="signature">
                    Signature: ________________ <br /><br />
                    Date: 12.03.2014
                </p> -->
            </div>
        </div>
    </div>


    
    <div class="responsive-message"></div>

    <style>
        /*
            Use the DejaVu Sans font for display and embedding in the PDF file.
            The standard PDF fonts have no support for Unicode characters.
        */
        .pdf-page {
            font-family: "DejaVu Sans", "Arial", sans-serif;
        }
    </style>

    <script>
        // Import DejaVu Sans font for embedding

        // NOTE: Only required if the Kendo UI stylesheets are loaded
        // from a different origin, e.g. cdn.kendostatic.com
        kendo.pdf.defineFont({
            "DejaVu Sans"             : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans.ttf",
            "DejaVu Sans|Bold"        : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Bold.ttf",
            "DejaVu Sans|Bold|Italic" : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf",
            "DejaVu Sans|Italic"      : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf"
        });
    </script>

    <!-- Load Pako ZLIB library to enable PDF compression -->
    <script src="../content/shared/js/pako.min.js"></script>

    <script>
      function getPDF(selector) {
        kendo.drawing.drawDOM($(selector)).then(function(group){
          kendo.drawing.pdf.saveAs(group, "Reembolso NO <?php echo $this->id_solicitud; ?>.pdf");
        });
      }

    $(document).ready(function() {
        var data = [
          { productName: "QUESO CABRALES", unitPrice: 21, qty: 5 },
          { productName: "ALICE MUTTON", unitPrice: 39, qty: 7 },
          { productName: "GENEN SHOUYU", unitPrice: 15.50, qty: 3 },
          { productName: "CHARTREUSE VERTE", unitPrice: 18, qty: 1 },
          { productName: "MASCARPONE FABIOLI", unitPrice: 32, qty: 2 },
          { productName: "VALKOINEN SUKLAA", unitPrice: 16.25, qty: 3 }
        ];
        var schema = {
          model: {
            productName: { type: "string" },
            unitPrice: { type: "number", editable: false },
            qty: { type: "number" }
          },
          parse: function (data) {
                $.each(data, function(){
                    this.total = this.qty * this.unitPrice;
                });
                return data;
          }
        };
        var aggregate = [
          { field: "qty", aggregate: "sum" },
          { field: "total", aggregate: "sum" }
        ];
        var columns = [
          { field: "productName", title: "Product", footerTemplate: "Total"},
          { field: "unitPrice", title: "Price", width: 120},
          { field: "qty", title: "Pcs.", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" },
          { field: "total", title: "Total", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" }
        ];
        var grid = $("#grid").kendoGrid({
          editable: false,
          sortable: true,
          dataSource: {
            data: data,
            aggregate: aggregate,
            schema: schema,
          },
          columns: columns
        });

        $("#paper").kendoDropDownList({
          change: function() {
            $(".pdf-page")
              .removeClass("size-a4")
              .removeClass("size-letter")
              .removeClass("size-executive")
              .addClass(this.value());
          }
        });
    });
    </script>
    <style>

        .title-pdf{
            font-weight: bold;
            font-size: 13px;
        }
        .pdf-page {
            margin: 0 auto;
            box-sizing: border-box;
            box-shadow: 0 5px 10px 0 rgba(0,0,0,.3);
            background-color: #fff;
            color: #333;
            position: relative;
        }
        .pdf-header {
            position: absolute;
            top: .5in;
            height: .6in;
            left: .5in;
            right: .5in;
            /*border-bottom: 1px solid #e5e5e5;*/
        }
        .invoice-number {
            padding-top: .17in;
            float: right;
        }
        .pdf-footer {
            position: absolute;
            bottom: .5in;
            height: .6in;
            left: .5in;
            right: .5in;
            padding-top: 10px;
            border-top: 1px solid #e5e5e5;
            text-align: left;
            color: #787878;
            font-size: 12px;
        }
        .pdf-body {
            position: absolute;
            top: 4.3in;
            bottom: 1.2in;
            left: .5in;
            right: .5in;
        }

        .size-a4 { width: 8.3in; height: 11.7in; }
        .size-letter { width: 8.5in; height: 11in; }
        .size-executive { width: 7.25in; height: 10.5in; }

        .company-logo {
            font-size: 34px;
            font-weight: bold;
            color: #3aabf0;
        }
        .for {
            position: absolute;
            top: 1.5in;
            left: .5in;
            width: 3.5in;
        }
        .from {
            position: absolute;
            top: 1.5in;
            right: .5in;
            width: 3.5in;
        }
        .from p, .for p {
            color: #787878;
        }
        .signature {
            padding-top: .5in;
        }
    </style>

</div>


</body>
