<?php foreach ($this->user as $value) {
    $rol_user = $value['fkroles'];
} ?>

<style type="text/css">
    .table_wrapper{
        overflow-x: auto;
    }
</style>

<?php foreach ($this->personal_epp as $peep) { $id_p = $peep['id'];  } ?>
<input type="hidden" name="id_personal" id="id_personal" value="<?php echo $this->idpersonal; ?>">



<!-- INICIO DETAIL-->
<div class="row" style="margin-top: 10px;">
    <div class="col m5 s5">
        <?php if ($rol_user == 13) { ?>

        <?php } else { ?>       
            <?php foreach ($this->personal_epp as $regresar) { ?>
            <a href="/panel/personaldetail/id/<?php echo $regresar['id']; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
            <?php } ?> 
        <?php } ?>   
    </div>
     <div class="col m7 s7 text-right">
        <?php if ($rol_user == 13 || $rol_user == 1 || $rol_user == 8) { ?>
            <a href="/epp/catalogo" class="waves-effect darken-1 waves-light btn">Inventario</a>
            <a href="/epp/personal" class="waves-effect darken-1 waves-light btn">Buscar Personal</a>
        <?php } else { ?>       
            
        <?php } ?>   
    </div>
</div>

<div class="row">
  <div class="col m12 s12 text-center" style="margin-top: 10px;">
    <span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Epp Asignado
  </div>
</div>

<!-- END INICIO DETAIL-->

<!-- Inicio Tabla Personal -->
<div class="col m12 s12 text-center">
    <div class="row">
        <div class="col s12 m12">
            <div class="row table_wrapper">
                <table class="table text-center table-hover ">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Apellido Paterno</th>
                            <th>Apellido Materno</th>
                            <th>Puesto</th>
                            <th>Telefono</th>
                        </tr>
                    </thead>
                    <?php if ($this->personal_epp) { 
                    foreach ($this->personal_epp as $peep) { ?>
                        <tbody>
                            <tr>
                                <td>
                                    <?php echo $peep['nombre']; ?>
                                </td>
                                <td>
                                    <?php echo $peep['apellido_pa']; ?>
                                </td>
                                <td>
                                    <?php echo $peep['apellido_ma']; ?>
                                </td>   
                                <td>
                                    <?php echo $peep['name_puesto']; ?>
                                </td>
                                <td>
                                    <?php echo $peep['telefono']; ?>
                                </td>
                            </tr>
                        </tbody>
                    <?php } }else{ ?>
                        <tbody>
                            <tr>
                                <td></td>
                                <td></td>
                                <td>No Existe personal</td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
                    <?php } ?>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- End Tabla Personal-->

<!--Inicio Botones -->
<div class="col m12 s12">
    <div class="col m4 s12 text-center"></div>
    <div class="col m8 s12 text-center">
        <div class="col m4 s12">
             <div class="input-field col m12 s12">
                <a class="waves-effect green darken-1 waves-light lighten-4 btn modal-trigger" href="#modalasignaepp">Asignar EPP</a>
            </div>
        </div>
        
        <?php foreach ($this->personal_epp as $peep) {  ?>
            <?php if ($this->eppasignado) {  ?>
        <div class="col m4 s12">
             <div class="input-field col m12 s12">
                <a class="waves-effect darken-1 waves-light lighten-4 btn modal-trigger" href="/epp/responsiva/id/<?php echo $peep['id']; ?>">Responsiva</a>
            </div>
        </div>
            <?php } else {} ?>
        <div class="col m4 s12">
             <div class="input-field col m12 s12">
                <a class="waves-effect darken-1 waves-light lighten-4 btn modal-trigger" href="/epp/historial/id/<?php echo $peep['id']; ?>">Historial Responsiva</a>
            </div>
        </div>
        <?php } ?>
    </div>
</div>

<!--End Botones -->

<!-- Modal Asignar Epp -->
<div id="modalasignaepp" class="modal modal-fixed-footer">
    <div class="modal-content">
        <div class="row">
            <div class="col m12 s12 text-left" style="margin-top: 5px;">
                <span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar EPP
            </div>
        </div>
        <div class="row">
            <form action="/epp/requestasignarepp" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_asigna">

                <?php foreach ($this->personal_epp as $personal) { ?>
                    <input type="hidden" name="idhs" value="<?php echo $personal["id"]; ?>">
                <?php } ?>
                <div class="row">

                    <div class="input-field col m6 s12">
                        <i class="material-icons prefix">today</i>
                        <input type="date" id="fecha" name="fecha"  class="validate">
                        <label for="fecha">*Fecha de entrega: dd/mm/yyyy</label>
                    </div>

                    <div class="input-field col m6 s12">
                        <i class="material-icons prefix">event_available</i>
                        <select id="tipo" name="tipo" required>
                            <option value="0" disabled selected>* Selecciona una opcion:</option>
                            <?php foreach ($this->tipo_epp as $tipo) { ?>
                            <option value="<?php echo $tipo["id_tipo"]; ?>"><?php echo $tipo["nombre"]; ?></option>
                            <?php } ?>
                        </select>
                        <label>Tipo de EPP</label>
                    </div>

                   <div class="input-field col m6 s12">
                        <i class="material-icons prefix">accessibility</i>
                        <select id="epp" name="epp" required>
                            <option value="0" disabled selected>* Selecciona una opcion:</option>
                            <?php foreach ($this->eppn as $epp) { ?>
                            <option value="<?php echo $epp["nombre"]; ?>"><?php echo $epp["nombre"]; ?></option>
                            <?php } ?>
                        </select>
                        <label>EPP</label>
                    </div>

                    <!-- <div class="input-field col m6 s12">
                        <i class="material-icons prefix">photo_size_select_small</i>
                        <input type="text" id="input-tallas" list="tallas_lista" class="validanumeros" name="talla" >
                        <datalist id="tallas_lista"></datalist> 
                        <label>*Talla</label>
                    </div> -->

                    <div class="input-field col m6 s12">
                        <i class="material-icons prefix">format_list_numbered</i>
                        <input type="number" id="cantidad" name="cantidad" min="1" class="validanumeros">
                        <label for="cantidad">Cantidad:</label>
                    </div>

                    <div class="input-field col m6 s12">
                        <div class="col m2 s12">
                            <input type="hidden" id="input-tallas" list="tallas_lista">  
                            <span style="color: #9e9e9e; font-weight: bold;">*Talla</span>
                            <!-- <i class="material-icons prefix">photo_size_select_small</i> -->
                        </div>
                        <div class="col m10 s12">
                            <select style="background: #FAFAFA; border-bottom-color: #686868;" class="browser-default" id="tallas_lista" name="talla" ></select>
                        </div>
                    </div>

                    
                    <!-- <div class="input-field col m6 s12">
                        <i class="material-icons prefix">format_list_numbered</i>
                        <input type="number" id="cantidad" name="cantidad" min="1" class="validanumeros">
                        <label for="cantidad">Cantidad:</label>
                    </div> -->

                    <div class="input-field col m3 s12 text-center">
                        <label>
                            <input type="checkbox"  name="cobro">
                            <span>¿Cobro Extra?</span>
                        </label>
                    </div>

                    <div class="input-field col m3 s12 text-center">
                        <label>
                            <input type="checkbox"  name="campo">
                            <span>Comprado en Campo</span> 
                        </label>
                    </div>
                    <div class="input-field col s12"></div>
                    <div class="input-field col m12 s12">
                        <textarea id="comentarios" name="comentarios" class="materialize-textarea"></textarea>
                        <label for="comentarios">*Comentarios: </label>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" id="asignarepp" class="btn">Guardar</button>
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>
<!-- End Modal Asignar Epp-->

<!-- Inicio Tabla Epp -->
<div class="col m12 s12 text-center">
    <div class="row">
        <div class="col s12 m12">
            <div class="card darken-1">
                <div class="card-content">

                    <div class="row">
                        <div class="col m12 s12 text-left">
                            <h3 class="card-title">EPP</h3>
                        </div>
                    </div>

                    <div class="row table_wrapper">
                        <table class="table text-center table-hover ">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Cantidad</th>
                                    <th>Descripción</th>
                                    <th>Talla</th>
                                    <th>Fecha Entrega</th>
                                    <th>Reposición</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <?php if ($this->eppasignado) { 
                            foreach ($this->eppasignado as $epp) { ?>
                                <tbody>
                                    <tr>
                                        <td>
                                            <?php echo $epp['id']; ?>
                                        </td>
                                        <td>
                                            <?php echo $epp['cantidad']; ?>
                                        </td>
                                        <td>
                                            <?php echo $epp['descripcion']; ?>
                                        </td>
                                         <td>
                                            <?php echo $epp['t_e']; ?>
                                        </td>
                                         <td>
                                            <?php echo $epp['fecha_entrega']; ?>
                                        </td>
                                        <td>
                                            <?php echo $epp['reposicion']; ?>
                                        </td>
                                        <td>
                                            <?php if ($epp['cobro'] == 1) { ?>
                                                <i style="color: blue;" class="material-icons">monetization_on</i>
                                                <a href="/epp/asignadetail/id/<?php echo $epp["id"] ?>"><i class="fa fa-2x fa-id-card-o"></i></a> 
                                            <?php } else {  ?> 
                                                <a href="/epp/asignadetail/id/<?php echo $epp["id"] ?>"><i class="fa fa-2x fa-id-card-o"></i></a>  
                                            <?php } ?>    
                                        </td>
                                        <td>
                                            <a href="/epp/asignaedit/id/<?php echo $epp["id"] ?>"><i class="fa fa-2x fa-edit"></i></a>
                                        </td>
                                        <td>
                                            <a class="delete" data-id="<?php echo $epp["id"]; ?>" data-nombre="<?php echo $epp["descripcion"]; ?>"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
                                        </td>                                            
                                    </tr>
                                </tbody>
                            <?php } }else{ ?>
                                <tbody>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td>No se ha asignado EPP al Personal</td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </tbody>
                            <?php } ?>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

 
<!-- End Tabla Epp-->


<!-- <script src="/js/lightbox.js"></script> -->
<script type="text/javascript">

    // lightbox.option({
    //   'resizeDuration': 200,
    //   'wrapAround': true
    // });

    $(document).ready(function(){
        $('.modal').modal();
        $('select').formSelect();
        $('.datepicker').datepicker();

        $('.validanumeros').keypress(function(e) {
            if(isNaN(this.value + String.fromCharCode(e.charCode))) 
                return false;
        })
        .on("cut copy paste",function(e){
            e.preventDefault();
        });
       
    });


    $("#asignarepp").click(function(){
        var comentarios = document.getElementById("comentarios").value;
        var fecha =  document.getElementById("fecha").value;

        if(comentarios == "" || fecha == ""){
            swal({
                title: "Llena los campos, para asignar el EPP(*)",
            });
        }else{
            swal("Espera un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            });
            setTimeout(submitForm1, 500);     
        }    
    }); 

    function submitForm1() {

        document.getElementById("submit_asigna").submit()

    }
    //Validar Asignar EPP

  
    $('#epp').change(function(){

        limpiar();       

        epp = document.getElementById("epp").value;

        $.ajax({

            url: "/epp/gettallas/",
        
            data: { epp: epp },
        
            type: "POST",

            success: function(data) {

              $("#id-talla").find('option').remove();

              var aData = JSON.parse(data);

              console.log(aData);

              var sOptions = '';

              $.each(aData, function(i, v) {

                sOptions += '<option value="' + v.idepp + '">' + v.talla + '</option>';

                // console.log(sOptions);
              });

              console.log(sOptions);

              $('#tallas_lista').html( sOptions );
            },

            error: function(a, b, c) {

                console.log(a);
        
                console.log(b);
        
                console.log(c);
            }
        });
    });


        //Inicio Delete Ajax
    $(".delete").click(function(){
        id=$(this).data('id');
        nombre=$(this).data('nombre');
        swal({
            title: "Estas seguro de eliminar el EPP "+nombre+"?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })

        .then((willDelete) => {
            if (willDelete) {
                swal("Espera un momento, la información esta siendo procesada", {
                    icon: "success",
                    buttons: false,
                });

                var request = $.ajax({
                    url:"/epp/requesteppdel",
                    method:"POST",
                    data: { id : id },
                    processData: true,
                });
        //-------------------end de ajax---------------------------

        //-------------peticion de respuesta de ajax------------------
                request.done(function(response) {
                    console.log(response);//imprime lo que responde el ajax
                    // alert
                    window.location.reload(true);
                });
        //-------------------end de respuesta ajax---------------------
            return false;

            } else {
                swal("La accion fue cancelada!");
            }
        });
    });
    // End Delete Ajax


    $(".getpdf").click(function(){
        pdf= $(this).data('id');
        name= $(this).data('name');
        var fileURL = pdf;
        var fileName = 'CertificadoMedico_'+name+'.pdf';
        download_file(fileURL, fileName);
    });

    function download_file(fileURL, fileName) {
        var link = document.createElement('a');
        link.href = fileURL;
        link.download = fileName;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }


    function limpiar(){

        document.getElementById('input-tallas').value='';

    }



</script>

