<style type="text/css">
	.table_wrapper{
		overflow-x: auto;
	}
</style>

<!-- INICIO DETAIL-->

<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="/epp/eppcosto/status/1" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a> 
    </div>     
</div>

<div class="row">
	<div class="col m12 s12 text-center" style="margin-top: 10px;">
		<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">EPP POR COBRAR </span>
	</div>
</div>

<div class="row" >
	<div class="col m12 s12 text-left" style="margin-top: 10px;">
		<?php foreach ($this->personal_epp as $per) { ?>
			<span>Personal <br><b><?php echo $per['nombre'];?> <?php echo $per['apellido_pa'];?> <?php echo $per['apellido_ma'];?></b></span>
		<?php } ?>
	</div>
</div>

<!-- END INICIO DETAIL-->


<!-- Inicio Informacion General-->
<div class="col m12 s12 text-center">
	<div class="row">
		<div class="col s12 m12">
			<div class="card darken-1">
				<div class="card-content">
					<div class="row">
						<div class="col m12 s12 text-left">
							<h3 class="card-title">Lista de EPP</h3>
							<hr>
						</div>
					</div>
					<div class="row">
		                    <div class="col m12 s12">
		                        <table style="font-size:15px;">
		                            <thead>
		                                <tr>
		                                    <th class="text-center"><span>Articulo No.</span></th>
		                                    <th class="text-center"><span>Descripción</span></th>
		                                    <th class="text-center"><span>Talla</span></th>
		                                    <th class="text-center"><span>Cantidad</span></th>
		                                    <th class="text-center"><span>Costo Aprobado (C/U)</span></th>
		                                    <th class="text-center"><span>Fecha Asignación</span></th>
		                                </tr>
		                            </thead>
		                            <?php if ($this->eppcobro) { ?>
		                            <?php foreach ($this->eppcobro as $epp){ ?>
		                            	<input type="hidden" name="idp" value="<?php echo $epp['id']; ?>">
		                                <tbody>
		                                    <tr>
		                                        <td class="text-center"><?php echo @$contado+=1; ?></td>
		                                        <td class="text-center"><?php echo $epp['nombre']; ?></td>
		                                        <td class="text-center"><?php echo $epp['t_e']; ?></td>
		                                        <td class="text-center"><?php echo $epp['cantidad']; ?></td>
		                                        <td class="text-center">$<?php echo $epp['costo_aprobado']; ?></td>
		                                        <td class="text-center"><?php echo $epp['fecha_entrega']; ?></td>
		                                    </tr>
		                                </tbody>
		                            <?php } }else{ ?>
										<tbody>
											<tr>
												<td></td>
												<td></td>
												<td>No hay EPP a cobrar</td>
												<td></td>
												<td></td>
											</tr>
										</tbody>
									<?php } ?>
		                        </table>
		                    </div>
		                </form>
					</div>
					<?php if ($this->eppcobro) { ?>
		                <div class="row">
		                	<div class="col s12 m12 text-center">
								<button class="waves-effect btn modal-trigger"  href="#modal1">Liberar Cobro</button>
							</div>
						</div>
					<?php  }else{ }?>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Datos Herramientas-->

<div id="modal1" class="modal modal-fixed-footer">
	<div class="modal-content">
		<div class="col m12 s12" style="margin-top: 10px;">
			<span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Liberar Cobro
      	</div>

      	<div class="col m12 s12">
      		<form action="/epp/requestcosto" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cobro">
      			<?php if ($this->eppcobro) { 
      				foreach ($this->eppcobro as $epp) { ?> 
      					<input type="hidden" name="idpe" value="<?php echo $epp['id_personal']; ?>">
      			<?php } }else{ }?>
      			<div class="row">
      				<div class="input-field col m12 s12">
  						<i class="material-icons prefix">assignment</i>
  						<input id="name" type="text" name="name" class="validate" required>
			          	<label for="name">* Nombre Identificador:</label>
			        </div>

			        <div class="file-field input-field col m12 s12">
				    	<div class="btn">
				        	<span>Comprobante de Descuento</span>
				        	<input type="file" name="url">
				      	</div>
				      	<div class="file-path-wrapper">
				        	<input class="file-path validate" type="text">
				      	</div>
				    </div>
				</div>
		</div>
	</div>

	<div class="modal-footer">
    		</form>
    	<button class=" btn" id="addcosto">Guardar</button>	
    	<button  class="modal-close red btn">Cerrar</button>
    </div>
</div>


<script src="/js/lightbox.js"></script>

<script type="text/javascript">

    lightbox.option({
      'resizeDuration': 200,
      'wrapAround': true
    });

	$(document).ready(function(){
		$('.modal').modal();
		$('.validanumeros').keypress(function(e) {
			if(isNaN(this.value + String.fromCharCode(e.charCode))) 
				return false;
		})
		.on("cut copy paste",function(e){
			e.preventDefault();
		});
	});

 	$("#addcosto").click(function(){
 		var name = document.getElementById("name").value;

 		if(name == ""){
 			swal({
 				title: "Para Liberar un cobro llena los datos requeridos (*)",
            });
        }else{
        	swal("Espera un momento, la información esta siendo procesada", {
				icon: "success",
			 	buttons: false,
			});
                setTimeout(submitForm, 500);     
        }
    });

        function submitForm() {
            document.getElementById("submit_cobro").submit()
      	}
        //Agregar Categoría Script


</script>