<style type="text/css">
	.table_wrapper{
		overflow-x: auto;
	}
</style>

<!-- INICIO DETAIL-->

<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/epp/catalogo" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>   
    </div>
</div>

<div class="row">
  <div class="col m12 s12 text-center" style="margin-top: 10px;">
    <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Características EPP
  </div>
</div>

<div class="row" >
	<div class="col m12 s12 text-right" style="margin-top: 10px;">
		<?php foreach ($this->inf as $detail) { ?>
			<span>Última Modificación<br><b><?php echo $detail['created_at'];  ?></b></span>
		<?php } ?>
	</div>
</div>

<!-- END INICIO DETAIL-->


<!-- Inicio Informacion General-->
<div class="col m12 s12 text-center">
	<div class="row">
		<div class="col s12 m12">
			<div class="card darken-1">
				<div class="card-content">
					<div class="row">
						<div class="col m12 s12 text-left">
							<h3 class="card-title">Informacion General</h3>
							<hr>
						</div>
					</div>
					<div class="row">
						<div class="col m6 s6 text-left">
							<?php foreach ($this->inf as $data ) { ?>
								<h4>
									<strong><span class="font_tittle">Id: </span></strong>
									<?php echo $data['idepp']; ?>
								</h4>
								<h4>
									<strong><span class="font_tittle">Nombre: </span> </strong>
									<?php echo $data['nombre']; ?>
								</h4>
								<h4>
									<strong><span class="font_tittle">Talla: </span> </strong>
									<?php echo $data['talla']; ?>
								</h4>
								<h4>
									<strong><span class="font_tittle">Tiempo Vida: </span> </strong>
									<?php echo $data['tiempo_vida']; ?>
								</h4>
							<?php } ?>
						</div>

						<div class="col m6 s6 text-left">
							<?php foreach ($this->inf as $data ) { ?>
								<br/>
								<h3>
									<strong><span class="font_tittle">Stock: </span></strong>
									<?php echo $data['stock']; ?>
								</h3>
								<h3>
									<strong><span class="font_tittle">Descripción: </span> </strong>
									<?php echo $data['descripcion']; ?>
								</h3>
							<?php } ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Datos Herramientas-->

<script src="/js/lightbox.js"></script>

<script type="text/javascript">

    lightbox.option({
      'resizeDuration': 200,
      'wrapAround': true
    });

	$(document).ready(function(){
		$('.validanumeros').keypress(function(e) {
			if(isNaN(this.value + String.fromCharCode(e.charCode))) 
				return false;
		})
		.on("cut copy paste",function(e){
			e.preventDefault();
		});
	});

 	$("#asignar_h").click(function(){
 		swal({
 			title: "¿Estas seguro que deseas asignar la herramienta ?",
	  		icon: "warning",
	  		buttons: true,
	  		dangerMode: true,
	  	})
	  	.then((willDelete) => {
	  		if (willDelete) {
	  			swal("Bien! la herramienta fue asignada", {
	  				icon: "success",
	  				buttons: false,
	  			});

	  			var responsable =document.getElementById("responsable").value
	    		var	id = document.getElementById("id_herr").value;
	    		var request = $.ajax({
	    			url:"/herramienta/requestasignarherramienta",
                	method:"POST",
                	data: { responsable : responsable, id: id },
                	processData: true,
                // contentType: false,
            	});
				//-------------------end de ajax---------------------------

				//-------------peticion de respuesta de ajax------------------

				request.done(function(response) {
                console.log(response);//imprime lo que responde el ajax
                // alert
                window.location.reload(true);
            	});
				//-------------------end de respuesta ajax---------------------
             	return false;
            } else {
            	swal("¡Verifica antes de hacer el cambio!");
            }
        });
	});


</script>