<style type="text/css">
	.table_wrapper{
		overflow-x: auto;
	}
</style>

<!-- INICIO DETAIL-->

<?php foreach ($this->eppcobro as $key) {
	$id_sol = $key['id'];
	$status_cobro = $key['cobro'];
} ?>


<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="/epp/eppcosto/status/1" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a> 
    </div>     
</div>

<div class="row">
	<div class="col m12 s12 text-center" style="margin-top: 10px;">
		<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">EPP POR COBRAR </span>
	</div>
</div>

<div class="row">
	<div class="col m12 s12 text-left" style="margin-top: 10px;">
		<?php foreach ($this->personal_epp as $per) { ?>
			<span>Personal <br><b><?php echo $per['nombre'];?> <?php echo $per['apellido_pa'];?> <?php echo $per['apellido_ma'];?></b></span>
		<?php } ?>
	</div>
</div>

<!-- END INICIO DETAIL-->
<div class="row">
	<div class="col m6 s12"></div>
	<div class="col m6 s12">
		<div class="row">
			<div class="col m6 s6 text-center">
				<div class="chip modal-trigger" href="#pago" id="agregar_pago">
					<img src="/img/gris.jpg" >
					Agregar pago
				</div>
			</div>
			<div class="col m6 s6 text-center">
				<div class="chip modal-trigger" href="#rechazar" id="rechazar_solicitud">
					<img src="/img/gris.jpg" >
					Rechazar
				</div>
			</div>
		</div>
	</div>
</div>


  	<div id="pago" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<span style="font-size:26px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar Pago </span>

	    	<div class="row" style="margin-top: 20px;">
	    		<form action="/epp/requestaddpagoeppnomina" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_pago">
		    		<input type="hidden" name="id_solicitud" value="<?php echo $this->id_solicitud; ?>">
		    		<div class="col m12 s12">
				        <div class="input-field col m6 s12">
				        	<input id="monto_pago" name="monto" type="number" class="validate">
				        	<label for="monto_pago">* Monto</label>
				        </div>

				        <div class="input-field col m6 s12">
				        	<input id="parcialidad" name="cantidad" type="number" class="validate">
				        	<label for="parcialidad">* Parcialidad</label>
				        </div>

					    <div class="file-field input-field col m12 s12">
					      	<div class="btn">
					        	<span>* Evidencia</span>
					        	<input type="file" name="url">
					      	</div>
					      	<div class="file-path-wrapper">
					        	<input class="file-path validate" id="validate_url" type="text">
					      	</div>
					    </div>

				        <div class="input-field col s12">
				        	<input id="comentario_pago" type="text" class="validate">
				        	<label for="comentario_pago">Comentario</label>
				        </div>
		    		</div>
	    		</form>
	    	</div>
	    </div>

	    <div class="modal-footer">
		    <button type="button" id="add_aplicarpago" class="btn">Guardar</button>
		    <button  class="modal-close red btn">Cerrar</button>
	    </div>
  	</div>

  	<div id="rechazar" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<span style="font-size:26px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Rechazar solicitud </span>

	    	<div class="row" style="margin-top: 20px;">
	    		<form action="/epp/requestadddeleteeppcobro" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_rechazar">
		    		<input type="hidden" name="id_solicitud" value="<?php echo $id_sol; ?>">
		    		<div class="col m12 s12">
				        <div class="input-field col s12">
				        	<input id="motivo_rechazo" name="motivo_rechazo" type="text" class="validate">
				        	<label for="motivo_rechazo">Motivo</label>
				        </div>
		    		</div>
		    	</form>
	    	</div>

	    </div>
	    <div class="modal-footer">
    		<button type="button" id="add_rechazarepp" class="btn">Guardar</button>
    		<button  class="modal-close red btn">Cerrar</button>
	    </div>
  	</div>


<!-- Inicio Informacion General-->
<div class="col m12 s12 text-center">
	<div class="row">
		<div class="col s12 m12">
			<div class="card darken-1">
				<div class="card-content">
					<div class="row">
						<div class="col m12 s12 text-left">
							<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalle del Epp </span>
						</div>
					</div>
					<div class="row">
		                    <div class="col m12 s12">
		                        <table style="font-size:15px;">
		                            <thead>
		                                <tr>
		                                    <th class="text-center"><span>Articulo No.</span></th>
		                                    <th class="text-center"><span>Descripción</span></th>
		                                    <th class="text-center"><span>Talla</span></th>
		                                    <th class="text-center"><span>Cantidad</span></th>
		                                    <th class="text-center"><span>Costo Aprobado (C/U)</span></th>
		                                    <th class="text-center"><span>Fecha Asignación</span></th>
		                                    <th class="text-center"><span>Comentario</span></th>
		                                </tr>
		                            </thead>
		                            <?php if ($this->eppcobro) { ?>
		                            <?php foreach ($this->eppcobro as $epp){ ?>
		                            	<input type="hidden" name="idp" value="<?php echo $epp['id']; ?>">
		                                <tbody>
		                                    <tr>
		                                        <td class="text-center"><?php echo @$contado+=1; ?></td>
		                                        <td class="text-center"><?php echo $epp['nombre']; ?></td>
		                                        <td class="text-center"><?php echo $epp['t_e']; ?></td>
		                                        <td class="text-center"><?php echo $epp['cantidad']; ?></td>
		                                        <td class="text-center">$<?php echo $epp['costo_aprobado']; ?></td>
		                                        <td class="text-center"><?php echo $epp['fecha_entrega']; ?></td>
		                                        <td class="text-center"><?php echo $epp['comentario']; ?></td>
		                                    </tr>
		                                </tbody>
		                            <?php } }else{ ?>
										<tbody>
											<tr>
												<td></td>
												<td></td>
												<td>No hay EPP a cobrar</td>
												<td></td>
												<td></td>
											</tr>
										</tbody>
									<?php } ?>
		                        </table>
		                    </div>
		                </form>
					</div>
					<?php if ($this->eppcobro) { ?>
		                <div class="row">
		                	<div class="col s12 m12 text-center">
								
							</div>
						</div>
					<?php  }else{ }?>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Datos Herramientas-->

<div id="modal1" class="modal modal-fixed-footer">
	<div class="modal-content">
		<div class="col m12 s12" style="margin-top: 10px;">
			<span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Liberar Cobro</span>
      	</div>

      	<div class="col m12 s12">
      		<form action="/epp/requestcosto" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cobro">
      			<?php if ($this->eppcobro) { 
      				foreach ($this->eppcobro as $epp) { ?> 
      					<input type="hidden" name="idpe" value="<?php echo $epp['id_personal']; ?>">
      			<?php } }else{ }?>
      			<div class="row">
      				<div class="input-field col m12 s12">
  						<i class="material-icons prefix">assignment</i>
  						<input id="name" type="text" name="name" class="validate" required>
			          	<label for="name">* Nombre Identificador:</label>
			        </div>

			        <div class="file-field input-field col m12 s12">
				    	<div class="btn">
				        	<span>Comprobante de Descuento</span>
				        	<input type="file" name="url">
				      	</div>
				      	<div class="file-path-wrapper">
				        	<input class="file-path validate" type="text">
				      	</div>
				    </div>
				</div>
		</div>
	</div>

	<div class="modal-footer">
    		</form>
    	<button class=" btn" id="addcosto">Guardar</button>	
    	<button  class="modal-close red btn">Cerrar</button>
    </div>
</div>


<?php if($status_cobro == 3 || $status_cobro == 2){ ?>
	<div class="row">
	    <div class="col s12 m12">
	      	<div class="card">
		        <div class="card-content">
		        	<span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información del pago</span>

		          	<div class="row">
		          		<div class="col m12 s12">
		          			
		          		</div>
		          	</div>

		        </div>
	      	</div>
	    </div>
	</div>
<?php } ?>

<?php if($status_cobro == 4){ ?>
	<div class="row">
	    <div class="col s12 m12">
	      	<div class="card">
		        <div class="card-content">
		        	<span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Solicitud Rechazada</span>

		        	<?php foreach ($this->eppcobro as $key) {
		        		$user_rechazo = $key['user_monto'];
		        		$fecha_monto = $key['fecha_monto'];
		        		$comentario = $key['comentario_rechazo'];
		        	} ?>


		          	<div class="row">
		          		<div class="col m12 s12">
      						<table>
        						<thead>
          							<tr>
              							<th>Usuario</th>
              							<th>Fecha</th>
              							<th>Motivo rechazo</th>
          							</tr>
        						</thead>

        						<tbody>
          							<tr>
            							<td><?php echo $user_rechazo; ?></td>
            							<td><?php echo $fecha_monto; ?></td>
            							<td><?php echo $comentario; ?></td>
          							</tr>
        						</tbody>
      						</table>		          			
		          		</div>
		          	</div>

		        </div>
	      	</div>
	    </div>
	</div>
<?php } ?>



<script src="/js/lightbox.js"></script>

<script type="text/javascript">

    lightbox.option({
      'resizeDuration': 200,
      'wrapAround': true
    });

	$(document).ready(function(){
		$('.modal').modal();
		$('.validanumeros').keypress(function(e) {
			if(isNaN(this.value + String.fromCharCode(e.charCode))) 
				return false;
		})
		.on("cut copy paste",function(e){
			e.preventDefault();
		});
	});

 	$("#addcosto").click(function(){
 		var name = document.getElementById("name").value;

 		if(name == ""){
 			swal({
 				title: "Para Liberar un cobro llena los datos requeridos (*)",
            });
        }else{
        	swal("Espera un momento, la información esta siendo procesada", {
				icon: "success",
			 	buttons: false,
			});
                setTimeout(submitForm, 500);     
        }
    });

        function submitForm() {
            document.getElementById("submit_cobro").submit()
      	}
        //Agregar Categoría Script


    $("#add_aplicarpago").click(function(){
        var monto_pago = document.getElementById("monto_pago").value;
        var parcialidad = document.getElementById("parcialidad").value;
        var validate_url = document.getElementById("validate_url").value;

        if(monto_pago == "" || parcialidad == "" || validate_url == ""){
            swal({
                title: "Para continuar es necesario agregar los datos marcados con un *",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submitaddpago, 1500);     
        }
    });
    function submitaddpago() { document.getElementById("submit_pago").submit() }


    $("#add_rechazarepp").click(function(){
        var motivo = document.getElementById("motivo_rechazo").value;

        if(motivo == ""){
            swal({
                title: "Para continuar es necesario agregar el motivo del rechazo",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submitrechazar, 1500);     
        }
    });
    function submitrechazar() { document.getElementById("submit_rechazar").submit() }
</script>