<?php 
function eliminar_acentos($cadena){
		$cadena = str_replace(
		array('Á', 'À', 'Â', 'Ä', 'á', 'à', 'ä', 'â', 'ª'),
		array('A', 'A', 'A', 'A', 'a', 'a', 'a', 'a', 'a'),
		$cadena
		);

		$cadena = str_replace(
		array('É', 'È', 'Ê', 'Ë', 'é', 'è', 'ë', 'ê'),
		array('E', 'E', 'E', 'E', 'e', 'e', 'e', 'e'),
		$cadena );

		$cadena = str_replace(
		array('Í', 'Ì', 'Ï', 'Î', 'í', 'ì', 'ï', 'î'),
		array('I', 'I', 'I', 'I', 'i', 'i', 'i', 'i'),
		$cadena );

		$cadena = str_replace(
		array('Ó', 'Ò', 'Ö', 'Ô', 'ó', 'ò', 'ö', 'ô'),
		array('O', 'O', 'O', 'O', 'o', 'o', 'o', 'o'),
		$cadena );

		$cadena = str_replace(
		array('Ú', 'Ù', 'Û', 'Ü', 'ú', 'ù', 'ü', 'û'),
		array('U', 'U', 'U', 'U', 'u', 'u', 'u', 'u'),
		$cadena );

		$cadena = str_replace(
		array('Ñ', 'ñ', 'Ç', 'ç'),
		array('N', 'n', 'C', 'c'),
		$cadena
		);
		
		return $cadena;
	}
?>
<style> 
 .table_wrapper{
    overflow-x: auto;
}
</style>

	<div class="row" style="margin-top: 10px;">
		<div class="col m6 s12 text-left">
				<a href="/archivos/reportes" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
		</div>
		<div class="col m6 s12 text-right">
			<a class=" btn" onclick="exportTableToCSV(null,'epp.csv')"><i class="material-icons right">file_download</i>Descargar</a>
		</div>
	</div>

	<div class="row">
		<div class="col m12 s12 text-center" style="margin-top: 20px;">
        	<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Reporte de EPP Asignado </span>
    	</div>
	</div>
<div class="col m12 s12 text-right table_wrapper">
	<table class="table text-left table-hover ">
		<thead>
			<tr>
				<th>Id Personal</th>		
				<th>Nombre Personal</th>
				<th>Apellido Paterno</th>
				<th>Apellido Materno</th>
				<th>Status Personal</th>
				<th>Cantidad EPP</th>
				<th>Nombre EPP</th>
				<th>Talla</th>
        		<th>Fecha Entrega</th>
        		<th>Fecha Reposicion</th>
        		<th>Status EPP</th>
        		<th>Id sitio</th>
        		<th>Nombre sitio</th>
        		<th>Comentarios</th>
			</tr> 
		</thead>
		<?php 
		foreach ($this->excelepp as $epp) { ?> 
		<tbody>
			<tr>
				<td><?php echo $epp["id"]; ?></td>
				<td><?php echo eliminar_acentos( $epp["nombre"]); ?></td>
				<td><?php echo eliminar_acentos( $epp["apellido_pa"]); ?></td>
				<td><?php echo eliminar_acentos( $epp["apellido_ma"]); ?></td>
				<td>
					<?php if ($epp['status_personal'] == 0) { ?>
						Activo
					<?php } ?>
					<?php if ($epp['status_personal'] == 1) { ?>
						Inactivo
					<?php } ?>
					<?php if ($epp['status_personal'] == 2) { ?>
						Baja
					<?php } ?>
				</td>
				<td><?php echo $epp["cantidad"]; ?></td>
				<td><?php echo $epp["descripcion"]; ?></td>
				<td><?php echo $epp["talla"]; ?></td>
				<td><?php echo $epp["fecha_entrega"]; ?></td>
				<td><?php echo $epp["reposicion"]; ?></td>
				<td>
					<?php if ($epp['status_epp'] == 0) { ?>
						Activo
					<?php } else { ?>
						Historico
					<?php } ?>	
				</td>
				<td><?php echo $epp["id_sitiopersonal"]; ?></td>
				<td>
					<?php if ($epp['id_sitiopersonal'] == 0) { ?>
						Sin sitio Asignado
					<?php } else { ?>
						<?php echo $epp["name_sitio"]; ?>
					<?php } ?>	
				</td>
				<td><?php echo eliminar_acentos( $epp["comentario"]); ?></td>
			</tr>
		</tbody>
		<?php } ?>
	</table>
</div>

<script type="text/javascript">
	function exportTableToCSV(html, filename) {
	    var csv = [];
	    var rows = document.querySelectorAll("table tr");
	    for(var i = 0; i < rows.length; i++){
	        var row = [], cols = rows[i].querySelectorAll("td, th");
	        for(var j = 0; j < cols.length; j++){
	            row.push(cols[j].innerText);
	        }
	        csv.push(row.join(","));
	    }
	    downloadCSV(csv.join("\n"), filename);
	}

	function downloadCSV(csv, filename) {
	    var csvFile;
	    var downloadLink;
		if (window.Blob == undefined || window.URL == undefined || window.URL.createObjectURL == undefined) {
			alert("Your browser doesn't support Blobs");
			return;
		}
		
	    csvFile = new Blob([csv], {type:"text/csv"});
	    downloadLink = document.createElement("a");
	    downloadLink.download = filename;
	    downloadLink.href = window.URL.createObjectURL(csvFile);
	    downloadLink.style.display = "none";
	    document.body.appendChild(downloadLink);
	    downloadLink.click();
	}
</script>