<style type="text/css">
	.table_wrapper{
		overflow-x: auto;
	} 

	 .modal-info {
	 	width: 450px !important;
	 	/*height: 300px !important;*/
 /*     max-width: 100% !important;
      max-height: 100% !important; */
    /*  overflow-y: auto;*/
    } 
</style>

<!-- INICIO DETAIL-->
<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
    	<?php foreach ($this->personales as $regresar) { ?>
        <a href="/epp/asignarepp/id/<?php echo $regresar['id'] ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
        <?php } ?>    
    </div>
</div>

<div class="row">
  <div class="col m12 s12 text-center" style="margin-top: 10px;">
    <span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Historial de Responsivas
  </div>
</div>


<div class="row" >
	<div class="col m12 s12 text-left" style="margin-top: 10px;">
		<?php foreach ($this->personales as $per) { ?>
			<span>Responsivas de <br><b><?php echo $per['nombre'];?> <?php echo $per['apellido_pa'];?> <?php echo $per['apellido_ma'];?></b></span>
			  	<?php } ?>
	</div>
</div>
<!-- END INICIO DETAIL-->

<!-- Añadir Responsiva -->

<div class="col m12 s12">
	<form action="/epp/requestresponsiva" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_res">
		<?php foreach ($this->personales as $id_per) { ?>
			<input type="hidden" name="idper" value="<?php echo $id_per["id"]; ?>">
		<?php } ?>
		<div class="file-field input-field col m8 s12">
			<div class="row">
			<div class="btn">
				<span>Añade Responsiva</span>
				<input type="file" name="url">
			</div>
			<div class="file-path-wrapper">
				<input class="file-path validate" type="text">
			</div>
		</div>
		</div>
		<div class="input-field col m4 s12 text-center">
			<div class="row">
				<button  id="b_responsiva" class="waves-effect waves-light btn">Subir Responsiva</button>
			</div>	
		</div>
	</form>
</div>

<!-- End Añadir Responsiva -->

<!-- Inicio Tabla responsivas -->
<div class="col m12 s12 text-center">
	<div class="row">
		<div class="col s12 m12">
			<div class="card darken-1">
				<div class="card-content">

					<div class="row">
						<div class="col m12 s12 text-left">
							<h3 class="card-title">Responsivas</h3>
						</div>
					</div>

					<div class="row table_wrapper">
						<table class="table text-center table-hover ">
							<thead>
								<tr>
									<th>No</th>
									<th>Fecha</th>
									<th>Visualizar</th>
									<th>Descargar Responsiva</th>
								</tr>
							</thead>
							<?php if ($this->responsiva) { 
								foreach ($this->responsiva as $res) { ?>
									<tbody>
										<tr>
											<td>
												Res. <?php echo $res['id_responsiva']; ?>
											</td>
											<td>
												<?php echo $res['fecha']; ?>
											</td>
											<td>
												<a title="Visualizar" href="#modal" class="modal-trigger info_res" data-id="<?php echo $res["id_responsiva"] ?>" data-imagen="<?php echo $res["responsiva"];?>" style="color: blue; font-size:18px;"><i class="material-icons left">gamepad</i> </a>
											</td>	
											<?php if($res["responsiva"] != null){ ?>
												<td>
													<a title="Descargar Archivo" href="/<?php echo $res["responsiva"]; ?>" download="<?php echo substr(strrchr($res["responsiva"], "/"), 1); ?>" style="color: blue; font-size:18px;"> <i class="material-icons left">file_download</i> </a>
												</td>
											<?php }else{ ?>
												<td>
													No Existen Responsivas.
												</td>
											<?php } ?>
										</tr>
									</tbody>
								<?php } }else{ ?>
									<tbody>
										<tr>
											<td></td>
											<td></td>
											<td>No se encontraron datos</td>
											<td></td>
											<td></td>
										</tr>
									</tbody>
								<?php } ?>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
</div>
<!-- End Tabla responsivas-->

<!-- Modal de responsivas -->
<div id="modal" class="modal modal-fixed-footer modal-info">
	<div class="modal-content">
		<div class="row">
            <div class="col m12 s12 text-center" style="margin-top: 5px;">
                <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Vista Responsiva
            </div>
        </div>
		<div class="row">
			<div class="col m12 s12 text-center">
				<a class="example-image-link" href="" id="imagen2" data-lightbox="example-1">
					<img class="example-image" src="" id="imagen" style="width: 240px;  margin-top: 5px;"/>
				</a>
			</div>
		</div>  
    </div>
    
    <div class="modal-footer">
      <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>
  <!-- End Modal de responsivas -->


<script src="/js/lightbox.js"></script>
<script type="text/javascript">

    lightbox.option({
      'resizeDuration': 200,
      'wrapAround': true
    });

    $(document).ready(function(){
    	$('.modal').modal();
  	});


 	$("#b_responsiva").click(function(){
        var responsiva = document.getElementById("responsiva").value;

        if(name == ""){
            swal({
                title: "Añade una Responsiva",
            });
        }else{
             swal("Espera un momento, la información esta siendo procesada", {
				icon: "success",
			 	buttons: false,
			});
            setTimeout(submitForm, 500);     
        }

    });


    function submitForm() {
        document.getElementById("submit_res").submit()
    }

    $(".info_res").click(function(){
      var id = $(this).data('id');
      var imagen = $(this).data('imagen');
      var imagen2 = $(this).data('imagen');
      var img = "/"+imagen;
      var img2 = "/"+imagen2;
     
      document.getElementById("imagen").src = img;
      document.getElementById("imagen2").href = img2;
    }); 

</script>


