<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>


<style type="text/css">
	.oculto{display: none;}
	.active_menu{
		-webkit-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
		-moz-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
		box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	}

	.table_wrapper{
		overflow-x: auto;
	}
</style>


<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12 text-right">
            
    </div>
</div>

<div class="row">
	<div class="col m12 s12 text-center" style="margin-top: 10px;">
		<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> Lista Pedidos EPP </span>
	</div>
</div>


<!-- Buscador -->
<div class="row" style="margin-top:10px;">
	<div class="col m4 s12">
	  	<div class="input-field col s12">
	    	<select id="search_pedido">
	      		<option value="1" selected>Status</option>
	      		<option value="2">Id de la solicitud</option>
	      		<option value="3">Proveedor</option>
	    	</select>
	    	<label>Buscar por:</label>
	  	</div>
	</div>
	<div class="col m8 s12"> 
		<div class="col m12 s12" id="search_status">
		    <div class="input-field col m10 s8">
				<select id="statusped" name="statusped" required>
					<option value="" disabled selected>* Selecciona una opcion:</option>
					<option value="1">Completo</option>
					<option value="2">Incompleto</option>
				</select>
				<label>Status</label>
		    </div>
<!-- 		    <input type="hidden" id="status_search" value="<?php echo $status; ?>"> -->
		    <div class="input-field col m2 s4">
		     	<button tyle="submit" id="buscador" class="waves-effect waves-light btn"><i class="material-icons left">search</i></button>
		    </div>
		</div>

		<div class="col m12 s12 oculto" id="search_solicitud">
		    <div class="input-field col m10 s8">
		        <input placeholder="Ingresa el id del pedido" name="solicitud" id="id_pedido" type="number" class="validate">
		        <label for="id_pedido">Buscar por id del pedido</label>
		    </div>
		    <div class="input-field col m2 s4">
		     	<button tyle="submit" id="buscador_solicitud" class="waves-effect waves-light btn"><i class="material-icons left">search</i></button>
		    </div>
		</div>

		<div class="col m12 s12 oculto" id="search_proveedor">
		    <div class="input-field col m10 s8">
		        <input placeholder="Ingresa el nombre del proveedor" name="proveedor" id="name_proveedor" type="text" class="validate">
		        <label for="name_proveedor">Buscar por Proveedor</label>
		    </div>
		    <div class="input-field col m2 s4">
		     	<button tyle="submit" id="buscador_proveedor" class="waves-effect waves-light btn"><i class="material-icons left">search</i></button>
		    </div>
		</div>
	</div>
</div>
<!-- End Buscador -->
<div class="row">
	<div class="col m12 s12">
		<div class="row">
			<div class="col m8 s8">
				<!-- <h3>Lista de solicitudes de orden de compra </h3> -->
				<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de pedisos de EPP</span>
			</div>
		</div>
		
		<div class="col m12 s12 table_wrapper">
			<table class="table text-left table-hover">
				<thead>
					<tr>
						<th>Id Pedido</th>
						<th>Creada por</th>
						<th>Proveedor</th>
						<th>Fecha Pedido</th>			
						<th>Status Pedido</th>
						<th>Detalle Pedido</th>
					</tr> 
				</thead>
				<?php
				if ($this->paginator) { 
				foreach ($this->paginator as $usr) { ?>
				<tbody>
					<tr>
						<td>
							<h5><?php echo $usr['id']; ?></h5>
						</td>
						<td>
							<h5><?php echo $usr['name_usuario']; ?> </h5>
						</td>
						<td>
							<h5><?php echo $usr['name_proveedor']; ?></h5>
						</td>
						<td>
							<h5><?php echo $usr['fecha_recibido']; ?></h5>
						</td>
						<td>
							<?php if($usr['status_stock'] == 1){ ?>
								<div class="chip" id="inactivo_personal">
							    	<img src="/img/correct.png" >
							    	<span style="font-size: 11px;">Completo</span>
							  	</div>
							<?php } ?>

							<?php if($usr['status_stock'] == 2){ ?>
								<div class="chip" id="activo_personal">
							    	<img src="/img/naranja.png" >
							    	<span style="font-size: 10px;">Incompleto</span>
							  	</div>
							  	
							<?php } ?>
						</td>
				
						<td class="text-center">
							<a href="/epp/pedidodetail/id/<?php echo $usr["id"] ?>"><i class="fa fa-2x fa-id-card-o"></i></a>
						</td>

					</tr>
			    <?php } }else{ ?>
			    </tbody> 
			    <tbody>
			        <tr>
			            <td class="text-center" colspan="6"><h4>No hay pedidos de EPP.</h4></td>
			        </tr>
			    </tbody>
			                
			    <?php } ?>
			</table>
		</div>
	</div>
</div>


<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
               		<?php if($pagina - 1 == 0){ ?>
                    	<li class="page-item disabled">
                        	<span class="page-link">Anterior</span>
                    	</li>
               		<?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
               		<?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
               		<?php if($pagina >= $this->total): ?>
                       	<li class="page-item disabled">
                            <span class="page-link">Siguiente</span>
                       	</li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                   	<?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>

<script type="text/javascript">


	$('#search_pedido').on('change', function() {
		var value = this.value;

		if(value == 1){
			$("#search_status").show();
			$("#search_solicitud").hide();
			$("#search_proveedor").hide();
		}

		if(value == 2){
			$("#search_solicitud").show();	
			$("#search_status").hide();
			$("#search_proveedor").hide();

		}

		if(value == 3){
			$("#search_proveedor").show();
			$("#search_solicitud").hide();
			$("#search_status").hide();

		}
	});



   	$("#buscador").click(function(){
   		var statusped = document.getElementById("statusped").value;
 		swal({
			title: "La busqueda será por el status con id "+statusped+", Desea continuar?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				}); 
			window.location.href = "/epp/listapedidobuscar/statusped/"+statusped+"/op/1";
		  } else {
		    swal("La asignacion fue cancelada!");
		  }
		});
   	});	


   	$("#buscador_solicitud").click(function(){
   		var id = document.getElementById("id_pedido").value;

		swal({
			title: "La busqueda sera por id "+id+", Desea continuar?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				}); 
			window.location.href = "/epp/listapedidobuscar/id/"+id+"/op/2";
		  } else {
		    swal("La asignacion fue cancelada!");
		  }
		});
   	});

   	$("#buscador_proveedor").click(function(){
   		var id = document.getElementById("name_proveedor").value;

		swal({
			title: "La busqueda sera por nombre del proveedor "+id+", Desea continuar?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				}); 
			window.location.href = "/epp/listapedidobuscar/proveedor/"+id+"/op/3";
		  } else {
		    swal("La asignacion fue cancelada!");
		  }
		});

   	});

</script>