<html>
<head>
    <title></title>
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.common.min.css" />
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/kendo.all.min.js"></script>
</head>
<body>
    <div id="example">
        <?php foreach ($this->solicitud as $key){
            $ids= $key ['id'];
        }?>

        <div class="row" style="margin-top: 10px;">
            <div class="col m6 s6">
                <a href="/epp/pedidodetail/id/<?php echo $ids; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
            </div>
            <div class="col m6 s6 text-right">
                <button class="export-pdf btn" onclick="getPDF('.pdf-page')">Descargar</button>
            </div>
        </div>
        <?php 
            foreach ($this->solicitud as $key){
                $idsol = $key ['id'];
                $status_sol = $key['status_stock'];
        }?>

        <?php 
            foreach ($this->detalle as $key){
        
                $idsolicitud = $key ['id']; $id_usuario = $key ['id_usuario']; $comprobante_doc = $key['comprobante_doc'];
                $fecha_recibido = $key ['fecha_recibido']; $status_stock = $key ['status_stock']; $id_proveedor = $key ['id_proveedor'];
                $step_uno = $key ['step_uno']; $comentarios = $key ['comentarios']; $name_usuario = $key ['name_usuario']; 
                $name_proveedor = $key ['name_proveedor'];  $fecha_creacion = $key ['fecha_creacion'];  $nombre_prov = $key ['nombre_prov'];
                $telefono = $key ['telefono'];  $rfc = $key ['rfc']; $datos_banco = $key ['datos_banco']; 
                $cuenta = $key ['cuenta']; $tarjeta = $key ['tarjeta'];  $titular = $key ['titular']; $email = $key ['email']; 
        }?>

        <?php 
            date_default_timezone_set('America/Mexico_City');
            $hoy = date("d-m-Y");
        ?>

        <div class="page-container hidden-on-narrow">
            <div class="pdf-page size-a4">
                
                <div class="pdf-header">
                    
                    <span class="company-logo">
                        <img src="/img/head.png" style="width: 120px;" />
                    </span>

                    <span class="invoice-number">
                            <img src="/img/logo-2.png" style="width: 125px;" /><br/>
                            <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Pedido No.<?php echo $idsol; ?></span>
                    </span>

                    <div class="row">
                        <div class="company-logo col m12 s12 text-center">
                            Pedido/Stock EPP
                        </div>
                    </div>
                
                </div>

                <div class="pdf-footer">
                    <p>Gps Constructivos<br />Fecha de descarga: <?php echo $hoy; ?><br /></p>
                </div>

                <div class="for" style="margin-top: 60px;">
                    <br/><br/>
                    <!-- <h4><b>Fecha de Entrega: <?php echo $fecha_recibido; ?></b></h4>  -->
                    
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Datos del Proveedor</span>
                    <p>
                        <span class="title-pdf">Nombre:</span> <span style="font-size: 14px;"> <?php echo $name_proveedor; ?></span><br />
                        <span class="title-pdf">RFC:</span> <?php echo $rfc; ?><br />
                        <span class="title-pdf">Télefono:</span> <?php echo $telefono; ?><br />
                        <span class="title-pdf">Email:</span > <span style="font-size: 14px;"><?php echo $email; ?></span><br />
                    </p>
                </div>

                <div class="from" style="margin-top: 60px;">
                    <div class="col m12 s12 text-right">
                        <span style="font-size:14px; font-weight: bold;"><b>Entrega: <?php echo $fecha_recibido; ?></b></span>
                    </div><br/><br/>
                    <!-- <h4><b>Fecha de Entrega: <?php echo $fecha_recibido; ?></b></h4>  -->
                    <!-- <br/><br/> -->
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalles Generales</span>
                    
                    <p style="padding-bottom: 10px;">
                        
                        <span class="title-pdf"><b>Solicito:</b></span> <?php echo $name_usuario; ?> <br />
                        <span class="title-pdf"><b>Fecha Creación:</b></span> <?php echo $fecha_creacion; ?><br />
                        <span class="title-pdf"><b>Comentarios:</b></span>
                            <?php if ($comentarios==null) { ?>
                                Sin Comentarios<br />
                            <?php } else { ?>
                                <?php echo $comentarios; ?><br />
                            <?php } ?>                
                    </p>
                </div>

                <div class="pdf-body">

                    <div class="row">
                        <div class="col m12 s12 text-center" style="margin-top: 60px;">
                            <span style="font-size:15px; color: rgb(74,79,84);font-weight: bold; ">EPP Recibido
                            </span><br>
                        </div>  

                        <div class="col m12 s12">
                            <table>
                                <thead>
                                    <tr>
                                        <th class="text-center"><b>Id/Código</b></th>
                                        <th class="text-center"><b>Cantidad</b></th>
                                        <th class="text-center"><b>Descripción</b></th>
                                        <th class="text-center"><b>Talla</b></th>
                                        <th class="text-center"><b>Tipo Epp</b></th>
                                    </tr>
                                </thead>

                                <?php if ($this->eppxpedido) { 
                                    foreach ($this->eppxpedido as $epppedido) { ?>
                                        <tbody>
                                            <tr>
                                                <td class="text-center"><?php echo $epppedido['id_epp']; ?></td>
                                                <td class="text-center">
                                                    <?php echo $epppedido['cantidad']; ?>
                                                </td>
                                                <td class="text-center">
                                                    <?php echo $epppedido['descripcion']; ?>
                                                </td>
                                                 <td class="text-center">
                                                    <?php echo $epppedido['t_e']; ?>
                                                </td>
                                                <td class="text-center">
                                                    <?php echo $epppedido['nombretipo']; ?>
                                                </td>
                                            </tr>
                                        </tbody>
                                <?php } }else{ ?>
                                    <tbody>
                                        <tr>
                                            <td></td>
                                            <td></td>
                                            <td>No se ha entrego nada en este pedido.</td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                    </tbody>
                                <?php } ?>
                            </table>
                        </div>
   
                    </div>

                    <div class="row signature">
                        <div class="col m6 s6 text-center">
                            <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Entregado por:</span><br><br><br>
                            <hr>
                            <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nombre y Firma</span>
                        </div>
                        <div class="col m6 s6 text-center">
                            <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Recibido por:</span><br><br>
                            <?php echo $name_usuario; ?>
                            <hr>
                            <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nombre y Firma</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="responsive-message"></div>


        <style>
            .pdf-page {
               font-family: "DejaVu Sans", "Arial", sans-serif;
            }
        </style>

        <script>
            kendo.pdf.defineFont({
                "DejaVu Sans"             : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans.ttf",
                "DejaVu Sans|Bold"        : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Bold.ttf",
                "DejaVu Sans|Bold|Italic" : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf",
                "DejaVu Sans|Italic"      : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf"
            });
        </script>

        <script src="../content/shared/js/pako.min.js"></script>

        <script>

            function getPDF(selector) {
                kendo.drawing.drawDOM($(selector)).then(function(group){
                    kendo.drawing.pdf.saveAs(group, "Pedido EPP NO <?php echo $idsol; ?>.pdf");
                });
            }

            $(document).ready(function() {
                var data = [
                    { productName: "QUESO CABRALES", unitPrice: 21, qty: 5 },
                    { productName: "ALICE MUTTON", unitPrice: 39, qty: 7 },
                    { productName: "GENEN SHOUYU", unitPrice: 15.50, qty: 3 },
                    { productName: "CHARTREUSE VERTE", unitPrice: 18, qty: 1 },
                    { productName: "MASCARPONE FABIOLI", unitPrice: 32, qty: 2 },
                    { productName: "VALKOINEN SUKLAA", unitPrice: 16.25, qty: 3 }
                ];

                var schema = {
                    model: {
                        productName: { type: "string" },
                        unitPrice: { type: "number", editable: false },
                        qty: { type: "number" }
                    },

                    parse: function (data) {
                        $.each(data, function(){
                            this.total = this.qty * this.unitPrice;
                        });
                        return data;
                    }
                };


                var aggregate = [
                    { field: "qty", aggregate: "sum" },
                    { field: "total", aggregate: "sum" }
                ];

                var columns = [
                    { field: "productName", title: "Product", footerTemplate: "Total"},
                    { field: "unitPrice", title: "Price", width: 120},
                    { field: "qty", title: "Pcs.", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" },
                    { field: "total", title: "Total", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" }
                ];

                var grid = $("#grid").kendoGrid({
                    editable: false,
                    sortable: true,

                    dataSource: {
                        data: data,
                        aggregate: aggregate,
                        schema: schema,
                    },

                    columns: columns
                });


                $("#paper").kendoDropDownList({
                    change: function() {
                        $(".pdf-page")
                        .removeClass("size-a4")
                        .removeClass("size-letter")
                        .removeClass("size-executive")
                        .addClass(this.value());
                    }
                });
            });
        </script>

        <style>

            .title-pdf{
                font-weight: bold;
                font-size: 13px;
            }
            
            .pdf-page {
                margin: 0 auto;
                box-sizing: border-box;
                box-shadow: 0 5px 10px 0 rgba(0,0,0,.3);
                background-color: #fff;
                color: #333;
                position: relative;
            }
                
            .pdf-header {
                position: absolute;
                top: .5in;
                height: .6in;
                left: .5in;
                right: .5in;
                /*border-bottom: 1px solid #e5e5e5;*/
            }
            
            .invoice-number {
                padding-top: .17in;
                float: right;
            }
                
            .pdf-footer {
                position: absolute;
                bottom: .5in;
                height: .6in;
                left: .5in;
                right: .5in;
                padding-top: 10px;
                border-top: 1px solid #e5e5e5;
                text-align: left;
                color: #787878;
                font-size: 12px;
            }
            
            .pdf-body {
                position: absolute;
                top: 4.3in;
                bottom: 1.2in;
                left: .5in;
                right: .5in;
            }

            .size-a4 { width: 8.3in; height: 11.7in; }
            .size-letter { width: 8.5in; height: 11in; }
            .size-executive { width: 7.25in; height: 10.5in; }

            .company-logo {
                font-size: 34px;
                font-weight: bold;
                color: green;
            }
            
            .for {
                position: absolute;
                top: 1.5in;
                left: .5in;
                width: 3.5in;
            }
            
            .from {
                position: absolute;
                top: 1.5in;
                right: .5in;
                width: 3.5in;
            }
            
            .from p, .for p {
                color: #787878;
            }
            
            .signature {
                padding-top: 1.0in;
            }

            td, th{
                padding: 0px 5px;
            }
        </style>
    </div>
</body>
