<html>
<head>
    <title></title>
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.common.min.css" />
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/kendo.all.min.js"></script>
</head>
<body>
<div id="example">
<!--     <div class="box wide hidden-on-narrow">
        <div class="box-col">
            <button class="export-pdf btn" onclick="getPDF('.pdf-page')">Descargar</button>
        </div>
    </div>
 -->
<?php foreach ($this->solicitud as $key){
        $ids= $key ['id'];
}?>

<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="/epp/solicituddetail/id/<?php echo $ids; ?>/status/<?php echo $this->status_back; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
    <div class="col m6 s6 text-right">
        <button class="export-pdf btn" onclick="getPDF('.pdf-page')">Descargar</button>
    </div>
</div>

        <?php foreach ($this->solicitud as $key){
                $idsol = $key ['id'];
                $status_sol = $key['status_solicitud'];
        }?>

        <?php 
        foreach ($this->detalle as $key){
            
            $idsolicitud = $key ['id']; $status_solilitud = $key['status_solicitud']; $id_personal = $key ['id_personal'];
            $fecha_solicitud = $key ['fecha_solicitud']; $fecha_requerida = $key ['fecha_requerida'];
            $id_usuario = $key ['id_usuario']; $name_usuario = $key ['name_usuario']; $step_uno = $key ['step_uno'];
            $status_surtido = $key ['status_surtido']; $comentarios = $key ['comentarios']; $url_responsiva = $key ['url_responsiva'];
            $fecha_aprobada = $key ['fecha_aprobada']; $user_aprobado = $key ['user_aprobado']; 
            $name_useraprobado = $key ['name_useraprobado']; $fecha_rechazado = $key ['fecha_rechazado']; 
            $user_rechazado = $key ['user_rechazado']; $name_userrechazado = $key ['name_userrechazado']; 
            $comentarios_rechazo = $key ['comentarios_rechazo']; $fecha_surtido = $key ['fecha_surtido']; 
            $user_surtido = $key ['user_surtido']; $name_usersurtido = $key ['name_usersurtido']; $pname = $key ['pname'];
            
            $imagen = $key ['imagen']; $nresponsable = $key['nombreres']; $apres = $key['ares']; $amres = $key['amres'];
     
        }?>

        <?php 
                date_default_timezone_set('America/Mexico_City');
                $hoy = date("d-m-Y");
        ?>


        <div class="page-container hidden-on-narrow">
            <div class="pdf-page size-a4">
                
                <div class="pdf-header">
                    
                    <span class="company-logo">
                        <img src="/img/head.png" style="width: 120px;" />
                    </span>

                    <span class="invoice-number">
                            <img src="/img/logo-2.png" style="width: 125px;" /><br/>
                            <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Solicitud No.<?php echo $idsol; ?></span>
                    </span>

                    <div class="row">
                        <div class="company-logo col m12 s12 text-center">
                            Entrega EPP
                        </div>
                    </div>
                
                </div>

                <div class="pdf-footer">
                    <p>Gps Constructivos<br />Fecha de descarga: <?php echo $hoy; ?><br /></p>
                </div>

                <div class="for" style="margin-top: 60px;">
                    <h3>Fecha Requerida : <?php echo $fecha_requerida; ?></h3> 
                    
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Datos de Personal</span>
                    <p>
                        <span class="title-pdf">Nombre:</span> <span style="font-size: 14px;"><?php echo $nresponsable; ?></span><br />
                        <span class="title-pdf">Apellido Paterno:</span> <?php echo $apres; ?><br />
                        <span class="title-pdf">Apellido Materno:</span><?php echo $amres; ?><br />
                        <span class="title-pdf">Puesto:</span> <?php echo $pname; ?><br />
                    </p>
                </div>

                <div class="from" style="margin-top: 60px;">
                    <br/><br/>
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalles Generales</span>
                    
                    <p style="padding-bottom: 10px;">
                        
                        <span class="title-pdf"><b>Solicito:</b></span> <?php echo $name_usuario; ?> <br />
                        <span class="title-pdf"><b>Fecha Creación:</b></span> <?php echo $fecha_solicitud; ?><br />
                        <?php if ($status_sol==1) { ?>
                            <span class="title-pdf"><b>Autorizó:</b></span> <?php echo $name_useraprobado; ?><br />
                            <span class="title-pdf"><b>Fecha Autorización:</b></span> <?php echo $fecha_aprobada; ?><br />
                        <?php } ?>

                        <?php if ($status_sol==2) { ?>
                            <span class="title-pdf"><b>Rechazó:</b></span> <?php echo $name_userrechazado; ?><br />
                            <span class="title-pdf"><b>Fecha Rechazó:</b></span> <?php echo $fecha_rechazado; ?><br />
                        <?php } ?>

                        <?php if ($status_sol == 1 && $status_surtido == 1) { ?>
                            <span class="title-pdf"><b>Surtido por:</b></span> <?php echo $name_usersurtido; ?><br />
                            <span class="title-pdf"><b>Fecha Surtido:</b></span> <?php echo $fecha_surtido; ?><br />
                        <?php } ?>
                                    
                    </p>
                </div>

                <div class="pdf-body">

                    <div class="row">
                        <div class="col m12 s12 text-center" style="margin-top: 22px;">
                            <span style="font-size:15px; color: rgb(74,79,84);font-weight: bold; ">EPP entregado anteriormente
                            </span><br>
                        </div>  

                        <div class="col m12 s12">
                            <table>
                                <thead>
                                    <tr>
                                        <th class="text-center"><b>No.</b></th>
                                        <th class="text-center"><b>Cantidad</b></th>
                                        <th class="text-center"><b>Descripción</b></th>
                                        <th class="text-center"><b>Talla</b></th>
                                        <th class="text-center"><b>Fecha Asignación</b></th>
                                    </tr>
                                </thead>

                                <?php if ($this->eppasignado) { 
                                    foreach ($this->eppasignado as $eppasg) { ?>
                                        <tbody>
                                            <tr>
                                                <td class="text-center"><?php echo @$contar+=1; ?></td>
                                                <td class="text-center">
                                                    <?php echo $eppasg['cantidad']; ?>
                                                </td>
                                                <td class="text-center">
                                                    <?php echo $eppasg['descripcion']; ?>
                                                </td>
                                                 <td class="text-center">
                                                    <?php echo $eppasg['t_e']; ?>
                                                </td>
                                                <td class="text-center">
                                                    <?php echo  date("d-m-Y", strtotime($eppasg['fecha_entrega'])); ?>
                                                </td>
                                            </tr>
                                        </tbody>
                                <?php } }else{ ?>
                                    <tbody>
                                        <tr>
                                            <td>No se ha asignado EPP a este personal</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                    </tbody>
                                <?php } ?>
                            </table>
                        </div>


                        <?php if($status_sol == 1 && $status_surtido ==1) { ?>
                            <div class="col m12 s12" style="margin-top: 20px;">
                                <div class="col m12 s12 text-center">
                                    <span style="font-size:15px; color: rgb(74,79,84);font-weight: bold; ">EPP a entregar</span><br>
                                </div>
                                <table>
                                    <thead>
                                        <tr>
                                            <th class="text-center"><b>Cantidad</b></th>
                                            <th class="text-center"><b>Descripción</b></th>
                                            <th class="text-center"><b>Talla</b></th>
                                            <th class="text-center"><b>Presentación</b></th>
                                            <th class="text-center"><b>Cobro Extra</b></th>
                                            <th class="text-center"><b>Fecha Entrega</b></th>
                                            <th class="text-center"><b>Status</b></th>
                                        </tr>
                                    </thead>
                                    <?php if ($this->epp_surtido) { 
                                        foreach ($this->epp_surtido as $epps) { ?>
                                            <tbody>
                                                <tr>
                                                    <td class="text-center"><?php echo $epps['cantidad']; ?></td>
                                                    <td class="text-center"><?php echo $epps['descripcion']; ?></td>
                                                    <td class="text-center"><?php echo $epps['t_e']; ?></td>
                                                    <td class="text-center">
                                                        <?php if ($epps['presentacion'] == null || $epps['presentacion'] == "" ) { ?>
                                                            Sin dato
                                                        <?php } else { ?>
                                                            <?php echo $epps['presentacion']; ?>
                                                        <?php } ?>
                                                    </td>
                                                    <td class="text-center">
                                                        <?php if ($eppreq['cobro'] == 1) { ?>
                                                           Aplica descuento
                                                        <?php } else { ?>
                                                            Sin descuento
                                                        <?php } ?>
                                                    </td>
                                                    <td class="text-center">
                                                        <?php if ($epps['fecha_entrega'] == null) { ?>
                                                            <?php echo $hoy ?>
                                                        <?php } else { ?>
                                                            <?php echo $epps['fecha_entrega']; ?>
                                                        <?php } ?>
                                                    </td>
                                                    <td class="text-center">Entregado</td>
                                                </tr>
                                            </tbody>
                                    <?php } }else{ ?>
                                        <tbody>
                                            <tr>
                                                <td>No se ha surtido la solicitud</td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            </tr>
                                        </tbody>
                                    <?php } ?>
                                </table>
                            </div>
                        <?php } else { ?>
                            <div class="col m12 s12" style="margin-top: 20px;">
                                <div class="col m12 s12 text-center">
                                    <span style="font-size:15px; color: rgb(74,79,84);font-weight: bold; ">EPP a entregar</span><br>
                                </div>
                                <table>
                                    <thead>
                                        <tr>
                                            <th class="text-center"><b>Cantidad</b></th>
                                            <th class="text-center"><b>Descripción</b></th>
                                            <th class="text-center"><b>Talla</b></th>
                                            <th class="text-center"><b>Presentación</b></th>
                                            <th class="text-center"><b>Cobro Extra</b></th>
                                            <th class="text-center"><b>Fecha Entrega</b></th>
                                        </tr>
                                    </thead>
                                    <?php if ($this->epp_requerido) { 
                                        foreach ($this->epp_requerido as $eppreq) { ?>
                                            <tbody>
                                                <tr>
                                                    <td class="text-center"><?php echo $eppreq['cantidad']; ?></td>
                                                    <td class="text-center"><?php echo $eppreq['descripcion']; ?></td>
                                                    <td class="text-center"><?php echo $eppreq['t_e']; ?></td>
                                                    <td class="text-center">
                                                        <?php if ($eppreq['presentacion'] == null || $eppreq['presentacion'] == "" ) { ?>
                                                            Sin dato
                                                        <?php } else { ?>
                                                            <?php echo $eppreq['presentacion']; ?>
                                                        <?php } ?>
                                                    </td>
                                                    <td class="text-center">
                                                        <?php if ($eppreq['cobro'] == 1) { ?>
                                                           Aplica descuento
                                                        <?php } else { ?>
                                                            Sin descuento
                                                        <?php } ?>
                                                    </td>
                                                    <td class="text-center">
                                                        <?php if ($eppreq['fecha_entrega'] == null) { ?>
                                                            <?php echo $hoy ?>
                                                        <?php } else { ?>
                                                            <?php echo $eppreq['fecha_entrega']; ?>
                                                        <?php } ?>
                                                    </td>
                                                </tr>
                                            </tbody>
                                    <?php } }else{ ?>
                                        <tbody>
                                            <tr>
                                                <td>No se ha surtido la solicitud</td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            </tr>
                                        </tbody>
                                    <?php } ?>
                                </table>
                            </div>
                        <?php } ?>    
                    </div>

                    <div class="row signature">
                        <div class="col m6 s6 text-center">
                            <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Entregado por:</span><br><br><br>
                            <hr>
                            <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nombre y Firma</span>
                        </div>
                        <div class="col m6 s6 text-center">
                            <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Recibido por:</span><br><br>
                            <?php echo $nresponsable; ?> <?php echo $apres; ?> <?php echo $amres; ?>
                            <hr>
                            <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nombre y Firma</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="responsive-message"></div>


        <style>
            .pdf-page {
               font-family: "DejaVu Sans", "Arial", sans-serif;
            }
        </style>

        <script>
            kendo.pdf.defineFont({
                "DejaVu Sans"             : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans.ttf",
                "DejaVu Sans|Bold"        : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Bold.ttf",
                "DejaVu Sans|Bold|Italic" : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf",
                "DejaVu Sans|Italic"      : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf"
            });
        </script>

        <script src="../content/shared/js/pako.min.js"></script>

        <script>

            function getPDF(selector) {
                kendo.drawing.drawDOM($(selector)).then(function(group){
                    kendo.drawing.pdf.saveAs(group, "Solicitud EPP NO <?php echo $idsol; ?>.pdf");
                });
            }

            $(document).ready(function() {
                var data = [
                    { productName: "QUESO CABRALES", unitPrice: 21, qty: 5 },
                    { productName: "ALICE MUTTON", unitPrice: 39, qty: 7 },
                    { productName: "GENEN SHOUYU", unitPrice: 15.50, qty: 3 },
                    { productName: "CHARTREUSE VERTE", unitPrice: 18, qty: 1 },
                    { productName: "MASCARPONE FABIOLI", unitPrice: 32, qty: 2 },
                    { productName: "VALKOINEN SUKLAA", unitPrice: 16.25, qty: 3 }
                ];

                var schema = {
                    model: {
                        productName: { type: "string" },
                        unitPrice: { type: "number", editable: false },
                        qty: { type: "number" }
                    },

                    parse: function (data) {
                        $.each(data, function(){
                            this.total = this.qty * this.unitPrice;
                        });
                        return data;
                    }
                };


                var aggregate = [
                    { field: "qty", aggregate: "sum" },
                    { field: "total", aggregate: "sum" }
                ];

                var columns = [
                    { field: "productName", title: "Product", footerTemplate: "Total"},
                    { field: "unitPrice", title: "Price", width: 120},
                    { field: "qty", title: "Pcs.", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" },
                    { field: "total", title: "Total", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" }
                ];

                var grid = $("#grid").kendoGrid({
                    editable: false,
                    sortable: true,

                    dataSource: {
                        data: data,
                        aggregate: aggregate,
                        schema: schema,
                    },

                    columns: columns
                });


                $("#paper").kendoDropDownList({
                    change: function() {
                        $(".pdf-page")
                        .removeClass("size-a4")
                        .removeClass("size-letter")
                        .removeClass("size-executive")
                        .addClass(this.value());
                    }
                });
            });
        </script>

        <style>

            .title-pdf{
                font-weight: bold;
                font-size: 13px;
            }
            
            .pdf-page {
                margin: 0 auto;
                box-sizing: border-box;
                box-shadow: 0 5px 10px 0 rgba(0,0,0,.3);
                background-color: #fff;
                color: #333;
                position: relative;
            }
                
            .pdf-header {
                position: absolute;
                top: .5in;
                height: .6in;
                left: .5in;
                right: .5in;
                /*border-bottom: 1px solid #e5e5e5;*/
            }
            
            .invoice-number {
                padding-top: .17in;
                float: right;
            }
                
            .pdf-footer {
                position: absolute;
                bottom: .5in;
                height: .6in;
                left: .5in;
                right: .5in;
                padding-top: 10px;
                border-top: 1px solid #e5e5e5;
                text-align: left;
                color: #787878;
                font-size: 12px;
            }
            
            .pdf-body {
                position: absolute;
                top: 4.3in;
                bottom: 1.2in;
                left: .5in;
                right: .5in;
            }

            .size-a4 { width: 8.3in; height: 11.7in; }
            .size-letter { width: 8.5in; height: 11in; }
            .size-executive { width: 7.25in; height: 10.5in; }

            .company-logo {
                font-size: 34px;
                font-weight: bold;
                color: green;
            }
            
            .for {
                position: absolute;
                top: 1.5in;
                left: .5in;
                width: 3.5in;
            }
            
            .from {
                position: absolute;
                top: 1.5in;
                right: .5in;
                width: 3.5in;
            }
            
            .from p, .for p {
                color: #787878;
            }
            
            .signature {
                padding-top: .25in;
            }

            td, th{
                padding: 0px 5px;
            }
        </style>
    </div>
</body>
