<?php $session = new Zend_Session_Namespace("current_session"); ?>
<style type="text/css">
	.font_tittle{ 
		font-weight: bold;
	}
	.font-check{
		font-size: 11px;
	}

	#porcentaje_final{
		font-size: 12px;

	}
	.oculto{
		display: none;
	}
  	.colorbar{
		background-color: white !important;
	}
	.progress{
        width: 130px; height: 130px; line-height: 120px; background: none; margin: 0 auto; box-shadow: none; 
        position: relative;
    }
	.progress:after{
	    content: ""; width: 100%; height: 100%; border-radius: 50%; border: 12px solid #fff; position: absolute;
	    top: 0; left: 0;
	}
	.progress > span{
	    width: 50%; height: 100%; overflow: hidden; position: absolute; top: 0; z-index: 1;
	}

	.numero{
		font-size: 29px !important; margin-left: 25px; height: 90px !important;
	}
	.texto{
		border: 0px !important; width: 165px; margin-top: 50px !important;
	}	
	.progress .progress-left{
	    left: 0;
	}
	.progress .progress-bar{
	    width: 100%; height: 100%; background: none; border-width: 20px; border-style: solid; position: absolute; top: 0;
	}
	.progress .progress-left .progress-bar{
	    left: 100%; border-top-right-radius: 290px; border-bottom-right-radius: 290px; border-left: 0;
	    -webkit-transform-origin: center left; transform-origin: center left;
	}
	.progress .progress-right{
	    right: 0;
	}
	.progress .progress-right .progress-bar{
	    left: -100%; border-top-left-radius: 160px; border-bottom-left-radius: 160px; border-right: 0;
	    -webkit-transform-origin: center right; transform-origin: center right; animation: loading-1 1.8s linear forwards;
	}

	.progress .progress-value{
	    width: 90%; height: 90%; border-radius: 50%; font-size: 24px; color: #fff; line-height: 135px;
	    text-align: center; position: absolute; top: 5%;left: 5%;
	}
	.progress.blue .progress-bar{
	    border-color: #049dff;
	}
	.progress.blue .progress-left .progress-bar{
	    animation: loading-1 1.8s linear forwards 1.8s;
	}
	.progress.yellow .progress-bar{
	    border-color: yellow;
	}
	.progress.yellow .progress-left .progress-bar{
	    animation: loading-1 1.8s linear forwards 1.8s;
	}
	.progress.red .progress-bar{
	    border-color: red;
	}
	.progress.red .progress-left .progress-bar{
	    animation: loading-1 1.8s linear forwards 1.8s;
	}
	.progress.orange .progress-bar{
	    border-color: orange;
	}
	.progress.orange .progress-left .progress-bar{
	    animation: loading-1 1.8s linear forwards 1.8s;
	}
	.progress.pink .progress-bar{
	    border-color: #ed687c;
	}
	.progress.pink .progress-left .progress-bar{
	    animation: loading-4 1.8s linear forwards 1.8s;
	}
	.progress.green .progress-bar{
	    border-color: #1abc9c;
	}
	.progress.green .progress-left .progress-bar{
	    animation: loading-1 1.8s linear forwards 1.8s;
	}

	.numero{
	    background-color: transparent !important; border: 0px !important; width: 145px !important;
	}

	@keyframes loading-1{
	    0%{
	        -webkit-transform: rotate(0deg); transform: rotate(0deg);
	    }
	    100%{
	        -webkit-transform: rotate(180deg); transform: rotate(180deg);
	    }
	}
	@keyframes loading-2{
	    0%{
	        -webkit-transform: rotate(0deg); transform: rotate(0deg);
	    }
	    100%{
	        -webkit-transform: rotate(144deg); transform: rotate(144deg);
	    }
	}
	@keyframes loading-3{
	    0%{
	        -webkit-transform: rotate(0deg); transform: rotate(0deg);
	    }
	    100%{
	        -webkit-transform: rotate(90deg); transform: rotate(90deg);
	    }
	}
	@keyframes loading-4{
	    0%{
	        -webkit-transform: rotate(0deg); transform: rotate(0deg);
	    }
	    100%{
	        -webkit-transform: rotate(36deg); transform: rotate(36deg);
	    }
	}
	@keyframes loading-5{
	    0%{
	        -webkit-transform: rotate(0deg); transform: rotate(0deg);
	    }
	    100%{
	        -webkit-transform: rotate(126deg); transform: rotate(126deg);
	    }
	}
	@media only screen and (max-width: 990px){
	    .progress{ margin-bottom: 20px; }.footer{margin-top: 200px;}
	}

</style>


  <div class="row" style="margin-top: 20px;">
    <div class="col s12 m12">
      <div class="card  darken-1">
        <div class="card-content">
        	<div class="row">
        		<div class="col m6 s6">
        			<a href="/panel/sitiosdetail/id/<?php echo $this->id_sitio; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>  
        		</div>
        		<div class="col m6 s6 text-right">
        			<a class='dropdown-trigger btn green' href='#' style="width: 150px;" data-target='dropdown4'>Menú <i class="material-icons left">apps</i></a> 	
        		</div>
        	</div>

			<div class="row">
			    <div class="col m12 s12 text-center">
			      <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información general</span>
			    </div>
			</div>
        	
          <p>
			<div class="row">
				<div class="col m4 s12">
				  <ul id='dropdown4' class='dropdown-content'>
				  	<?php if($this->rol_user == 13 || $this->rol_user == 2 || $this->rol_user == 17){ ?>
				  	<?php }else{ ?>
				  		<li><a href="/panel/detallesproyecto/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $this->proyecto_id; ?>/sitio/<?php echo $this->idtipo; ?>">Cambiar Status</a></li>
				  	<?php } ?>
				  	
				  	<li class="divider" tabindex="-1"></li>
				    <li><a id="carga_uno">Documentación</a></li>
				    <li class="divider" tabindex="-1"></li>
				    <li><a id="asignar_cuadrilla">Asignar cuadrilla</a></li>
				  </ul>
				</div>
			</div>

          	<div class="row">
				<div class="col m4 s6">
					<?php foreach ($this->sitio as $key ) { ?>
						<h5 class="font_tittle">Nombre sitio: <a href="/panel/sitiosdetail/id/<?php echo $this->id_sitio; ?>"><?php echo $key['nombre']; ?></a></h5>
						<h5><span class="font_tittle">Id cliente:</span> <span><?php echo $key['id_cliente']; ?></span></h5>
						<h5> <span class="font_tittle">Cliente:</span> <?php echo $key['cliente']; ?></h5>
					<?php } ?>
<!-- 					<?php foreach ($this->tipo_sitio as $value) { ?>
						<h5> <span class="font_tittle">Operador:</span> <?php echo $value['operador']; ?></h5>
					<?php } ?> -->
				</div>

				<div class="col m4 s6">
					<?php foreach ($this->tipo_sitio as $value) { ?>
						<h5> <span class="font_tittle">Operador:</span> <?php echo $value['operador']; ?></h5>	
						
					<?php } ?>


					<?php foreach ($this->estructura as $usr) { ?>
						<h5> <span class="font_tittle">Tipo de torre:</span> <?php echo $usr["nombre_estructura"]; ?></h5>	
					<?php } ?>

					
					<?php foreach ($this->sitio as $key ) { ?>
						<h5> <span class="font_tittle">Altura:</span> <?php echo $key['altura']; ?></h5>
					<?php } ?>
				</div>

				<div class="col m4 s12">
					<?php foreach ($this->tipo_sitio as $value) { ?>
						<h5> <span class="font_tittle">Id operador:</span> <?php echo $value['id_operador'] ?></h5>
					<?php } ?>
					<?php foreach ($this->sitio as $key ) { ?>
						<h5><span class="font_tittle">Tipo de sitio:</span> <?php echo $key['tipo_sitio']; ?></h5>
						<h5> <span class="font_tittle">Edificio:</span> <?php echo $key['edificio']; ?></h5>
					<?php } ?>
				</div>
			</div>


			<div class="row">
				<div class="col m6 s6">
					<?php foreach ($this->nombreproyecto as $key){ ?>
						<h5><span class="font_tittle">Proyecto:</span> <?php echo $key['nombre_proyecto']; ?></h5>	
					<?php } ?>
					<h5><span class="font_tittle">Cliente:</span> 
						<?php foreach ($this->tipo_sitio as $usr){ ?>
							<?php foreach ($this->statuscliente as $mar) { 
								 		if ($mar['id']==$usr['status_cliente']) { ?>
								     		<?php echo $mar["nombre_status"]; ?>
							<?php } if ($mar['id']!=$usr['status_cliente']) { ?>
							<?php } } ?>
						<?php } ?>
					</h5>
					
					<h5> <span class="font_tittle">Status GPS:</span>
						<?php foreach ($this->tipo_sitio as $usr){ ?>
							<?php foreach ($this->status as $mar) { 
								if ($mar['id']==$usr['status_proyecto']) { ?>
								    <?php echo $mar["nombre_status"]; ?>
								<?php } if ($mar['id']!=$usr['status_proyecto']) { ?>
							<?php } } ?>
						<?php } ?>

					</h5>
					<h5><span class="font_tittle">Obra civil:</span> </h5>
				</div>
				<div class="col m6 s6">
					<?php foreach ($this->tipo_sitio as $value) { ?>
						<h5><span class="font_tittle">Coordinador:</span> <span><?php echo $value['nombre_coordinador'] ?></span></h5>
						<h5><span class="font_tittle">Ingeniero Proyecto:</span><span><?php echo $value['nombre_ingproyecto'] ?></span></h5>
						<h5><span class="font_tittle">Residente:</span> <span><?php echo $value['nombre_residente'] ?></span></h5>
						<h5><span class="font_tittle">PM Cliente:</span> <span><?php echo $value['pm_cliente'] ?></span></h5>
					<?php } ?>
				</div>
			</div>

			<div class="row">
				<div class="col m6 s12">
					<h5> <span class="font_tittle">Fecha requerida cliente:</span></h5>
				</div>
<!-- 				<div class="col m6 s12">
					<?php foreach ($this->detalles_bts as $value) { ?>
					<h5><span class="font_tittle">Fecha cronograma:</span><span><?php echo $value['inicioobra_baseline'] ?></span> </h5>
					<?php } ?>
				</div> -->
			</div>


          </p>
        </div>
      </div>
    </div>
  </div>


	<?php 
	$torre_status= 0; $simentacion_status=0; $calculo_status=0; $staad_status = 0; $mecanica_status=0;
	$acero_status=0 ; $tornilleria_status = 0; $galvanizado_status = 0; $verticalidad_status = 0;
	$tension_status = 0; $foto_status = 0; $tor_status =0; $pesoacero_status= 0; $torrepdf_status = 0;
	$torredwg_status = 0;
	foreach ($this->torre as $key){ 
		// STATUS
		$torre_status = $key['torre_status']; $simentacion_status = $key['simentacion_status'];
		$calculo_status = $key['calculo_status']; $staad_status = $key['staad_status'];
		$mecanica_status = $key['mecanica_status']; $acero_status =$key['acero_status'];
		$tornilleria_status = $key['tornilleria_status']; $galvanizado_status = $key['galvanizado_status'];
		$verticalidad_status = $key['verticalidad_status']; $tension_status = $key['tension_status'];
		$foto_status = $key['foto_status']; $tor_status= $key['tor_status']; $pesoacero_status=$key['pesoacero_status'];
		$torrepdf_status = $key['torrepdf_status']; $torredwg_status = $key['torredwg_status'];
		$modelotorre_status = $key['modelotorre_status'];

		// ARCHIVO
		$torre_file = $key['torre_file']; $simentacion = $key['simentacion_file'];
		$calculo_file = $key['calculo_file']; $staad_file = $key['staad_file'];
		$mecanica_file = $key['mecanica_file']; $acero_file = $key['acero_file'];
		$tornilleria_file = $key['tornilleria_file']; $galvanizado_file = $key['galvanizado_file'];
		$verticalidad_file = $key['verticalidad_file']; $tension_file = $key['tension_file'];
		$foto_file = $key['foto_file']; $tor_file= $key['tor_file']; $pesoacero_file = $key['pesoacero_file'];
		$torrepdf_file = $key['torrepdf_file']; $torredwg_file = $key['torredwg_file'];
		$modelotorre_file = $key['modelotorre_file'];

		// FECHA
		$fecha_torre = $key['fecha_torre']; $fecha_simentacion = $key['fecha_simentacion'];
		$fecha_staad = $key['fecha_saad']; $fecha_calculo = $key['fecha_calculo'];
		$fecha_mecanica = $key['fecha_mecanica']; $fecha_tornilleria = $key['fecha_tornilleria'];
		$fecha_galvanizado = $key['fecha_galvanizado']; $fecha_verticalidad = $key['fecha_verticalidad'];
		$fecha_tension = $key['fecha_tension']; $fecha_foto = $key['fecha_foto']; $fecha_tor=$key['fecha_tor'];
		$fecha_pesoacero = $key['fecha_pesoacero']; $fecha_torrepdf = $key['fecha_torrepdf']; 
		$fecha_torredwg = $key['fecha_torredwg']; $fecha_acero = $key['fecha_acero'];
		$fecha_torrenueva = $key['fecha_torrenueva'];

		// USUARIO
		$user_torre = $key['user_torre']; $user_simentacion = $key['user_simentacion'];
		$user_calculo = $key['user_calculo']; $user_staad = $key['user_staad'];
		$user_mecanica = $key['user_mecanica']; $user_tornilleria = $key['user_tornilleria'];
		$user_galvanizado = $key['user_galvanizado']; $user_verticalidad = $key['user_verticalidad'];
		$user_tension = $key['user_tension']; $user_foto = $key['user_foto']; $user_tor=$key['user_tor'];
		$user_pesoacero = $key['user_pesoacero']; $user_torrepdf = $key['user_torrepdf']; $user_dwg = $key['user_dwg'];
		$user_acero = $key['user_acero'];
		$user_torrenueva = $key['user_torrenueva'];
	} ?>

<div class="row"> 
	<div class="col m12 s12" style="margin-top: 10px;" id="baselie_cal">
		<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Documentación</span>
	</div>
</div>

<div class="row">
	<div class="col m12 s12">
		<form action="/panel/requestaddfiletorrenueva" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_file">
  		<div class="input-field col m6 s6">
		 	<input type="hidden" name="id_sitio" id="id_sitio_cam" value="<?php echo $this->id_sitio; ?>">
		 	<input type="hidden" name="proyecto" id="proyecto_cam" value="<?php echo $this->proyecto; ?>">
		 	<input type="hidden" name="sitio" id="sitio_cam" value="<?php echo $this->sitio_id; ?>">
	    	<select id="select_file" name="archivo">
	    		<option value="0" disabled selected>Selecciona una opción</option>
	    		<?php if($this->rol_user == 17 || $this->rol_user == 1){ ?>
	    			<!-- <option value="16">Modelo de torre (dwg)</option> -->
		      		<option value="1">Diseño de torre</option>
		      		<option value="2">Diseño de cimentación</option>
		      		<option value="3">Memoria de calculo de torre</option>
		      		<option value="4">STAAD</option>
		      		<option value="16">Modelo de torre (dwg)</option>
	    		<?php } ?>
	      		
	      		<?php if($this->rol_user == 2 || $this->rol_user == 1 || $this->rol_user == 7 ){ ?>
	      			<option value="5">Mecanica de suelos/ Dictamen</option>
		      		<option value="6">Certificado de acero</option>
		      		<option value="7">Certificado de tornilleria</option>
		      		<option value="8">Certificado de galvanizado</option>
		      		<option value="9">Reporte de verticalidad</option>
		      		<option value="10">Reporte de tensión</option>
		      		<option value="11">Reporte fotográfico</option>
		      		<option value="12">Tornilleria</option>
		      		<option value="13">Pesos de acero</option>
		      		<option value="14">Catalogo de torre (pdf)</option>
		      		<option value="15">Catalogo de torre (dwg)</option>
	      		<?php } ?>


	    	</select>
	    	<label>Archivos</label>
  		</div>

		<div class="file-field input-field col s6 m6">
		    <div class="btn">
		       	<span>Archivo</span>
		       	<input type="file" name="url">
		    </div>
		    <div class="file-path-wrapper">
		       	<input class="file-path validate" id="file_validate_torrenueva" type="text">
		    </div>
		</div>
  		</form>
	</div>

 	<div class="row">
 		<div class="col m12 s12 text-center">
 			<a class="btn darken-1" id="subir_archivo"><i class="material-icons right">check</i>Subir</a>
 		</div>
 	</div>
</div>


<div class="row">
	<div class="col m12 s12">
      <table>
        <thead>
          <tr>
              <th>Archivo</th>
              <th>Usuario</th>
              <th>Fecha</th>
          </tr>
        </thead>

        <tbody>



          <tr>
          	<td>Diseño de torre</td>
          	<?php if($torre_status == 0){ ?>
            <td>Sin Información</td>
            <td>  --- </td>
	        <?php }else{ ?>
	        	<td><?php echo $user_torre; ?></td>
	        	<td><?php echo $fecha_torre; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $torre_file; ?>" download="<?php echo substr(strrchr($torre_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $torre_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
	            </td>
	        <?php }?>
          </tr>

          <tr>	
            <td>Diseño de cimentación</td>

            <?php if($simentacion_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_simentacion; ?></td>
	        	<td><?php echo $fecha_simentacion; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $simentacion; ?>" download="<?php echo substr(strrchr($simentacion, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $simentacion; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>

          <tr>	
            <td>Memoria de calculo de torre</td>

            <?php if($calculo_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_calculo; ?></td>
	        	<td><?php echo $fecha_calculo; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $calculo_file; ?>" download="<?php echo substr(strrchr($calculo_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $calculo_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>

          <tr>	
            <td>STAAD</td>

            <?php if($staad_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_staad; ?></td>
	        	<td><?php echo $fecha_staad; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $staad_file; ?>" download="<?php echo substr(strrchr($staad_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $staad_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>

          <tr>	
            <td>Modelo de Torre</td>

            <?php if($modelotorre_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_torrenueva; ?></td>
	        	<td><?php echo $fecha_torrenueva; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $modelotorre_file; ?>" download="<?php echo substr(strrchr($modelotorre_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $modelotorre_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>

          <tr>	
            <td>Mecanica de suelos/ Dictamen</td>

            <?php if($mecanica_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_mecanica; ?></td>
	        	<td><?php echo $fecha_mecanica; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $mecanica_file; ?>" download="<?php echo substr(strrchr($mecanica_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $mecanica_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>

          <tr>	
            <td>Certificado acero</td>

            <?php if($acero_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_acero; ?></td>
	        	<td><?php echo $fecha_acero; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $acero_file; ?>" download="<?php echo substr(strrchr($acero_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $acero_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>

          <tr>	
            <td>Certificado tornilleria</td>

            <?php if($tornilleria_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_tornilleria; ?></td>
	        	<td><?php echo $fecha_tornilleria; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $tornilleria_file; ?>" download="<?php echo substr(strrchr($tornilleria_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $tornilleria_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>

          <tr>	
            <td>Certificado galvanizado</td>

            <?php if($galvanizado_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_galvanizado; ?></td>
	        	<td><?php echo $fecha_galvanizado; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $galvanizado_file; ?>" download="<?php echo substr(strrchr($galvanizado_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $galvanizado_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>

          <tr>	
            <td>Reporte verticalidad</td>

            <?php if($verticalidad_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_verticalidad; ?></td>
	        	<td><?php echo $fecha_verticalidad; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $verticalidad_file; ?>" download="<?php echo substr(strrchr($verticalidad_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $verticalidad_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>

          <tr>	
            <td>Reporte tensión</td>

            <?php if($tension_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_tension; ?></td>
	        	<td><?php echo $fecha_tension; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $tension_file; ?>" download="<?php echo substr(strrchr($tension_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $tension_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>

          <tr>	
            <td>Reporte fotográfico</td>

            <?php if($foto_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_foto; ?></td>
	        	<td><?php echo $fecha_foto; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $foto_file; ?>" download="<?php echo substr(strrchr($foto_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $foto_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>

          <tr>	
            <td>Tornilleria</td>

            <?php if($tor_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_tor; ?></td>
	        	<td><?php echo $fecha_tor; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $tor_file; ?>" download="<?php echo substr(strrchr($tor_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $tor_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>

          <tr>	
            <td>Pesos de acero</td>

            <?php if($pesoacero_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_pesoacero; ?></td>
	        	<td><?php echo $fecha_pesoacero; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $pesoacero_file; ?>" download="<?php echo substr(strrchr($pesoacero_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $pesoacero_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>

          <tr>	
            <td>Catalogo de torre (PDF)</td>

            <?php if($torrepdf_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_torrepdf; ?></td>
	        	<td><?php echo $fecha_torrepdf; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $torrepdf_file; ?>" download="<?php echo substr(strrchr($torrepdf_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $torrepdf_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>

          <tr>	
            <td>Catalogo de torre (dwg)</td>

            <?php if($torredwg_status == 0){ ?>
	            <td>Sin Información</td>
	            <td>  --- </td>  
            <?php }else{ ?>
	        	<td><?php echo $user_dwg; ?></td>
	        	<td><?php echo $fecha_torredwg; ?></td>
	        	<td>
	            	<a title="Descargar Archivo" href="/<?php echo $torredwg_file; ?>" download="<?php echo substr(strrchr($torredwg_file, "/"), 1); ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

	            	<a href="/<?php echo $torredwg_file; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
            	</td>
           	<?php }?>
          </tr>


        </tbody>
      </table>
	</div>
</div>


<div class="row">
	<div class="col m12 s12" id="div_asignar" style="margin-top: 20px;" id="div_asignar">
		<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Asignar Cuadrilla</span>
	</div>
</div>

<div class="row">
	<div class="col m2 s12"></div>
	<div class="col m6 s8">

    		<input type="hidden" id="id_sitio" name="id_sitio" value="<?php echo $this->id_sitio; ?>">
    		<input type="hidden" id="id_tipoproyecto" name="id_tipoproyecto" value="<?php echo $this->proyecto_id; ?>">
    		<input type="hidden" id="sitio_tipoproyecto" name="sitio_tipoproyecto" value="<?php echo $this->idtipo; ?>">
    		<input type="hidden" id="nombre_sitio" name="nombre_sitio" value="<?php echo $this->nombre_sitio; ?>">

    	<select name="personal" id="jspersonal">
    		<option value="" disabled selected>Seleciona al personal</option>
    		<?php foreach ($this->personal as $key){
    			if($key["status_cuadrilla"]== 1) {?>
    			<option disabled value="<?php echo $key['id'] ?>"> <?php echo $key['nombre']; ?> <?php echo $key['apellido_pa']; ?> <?php echo $key['apellido_ma']; ?>  *Asignado a <?php echo $key['name_sitio']; ?></option>
    			<?php }else{ ?>
    			<option value="<?php echo $key['id'] ?>"><?php echo $key['nombre']; ?> <?php echo $key['apellido_pa']; ?> <?php echo $key['apellido_ma']; ?> </option>
    		<?php } } ?>
    	</select>
    	<label>Personal</label>
	</div>
	<div class="col m2 s4">
		<button id="personal_add" class="btn">Asignar</button>
	</div>
	<div class="col m2 s12"></div>
</div>

<div class="row">
	<div class="col m2 s12"></div>
	<div class="col m8 s12">
      	<table>
        	<thead>
          		<tr>
              		<th>Id.</th>
              		<th>Paterno</th>
              		<th>Materno</th>
              		<th>Nombre(s)</th>
              		<th>Puesto</th>
              		<th>Liberar</th>
          		</tr>
        	</thead>

			<?php
			if ($this->personal_proyecto) {
			foreach ($this->personal_proyecto as $usr) { ?>
			<tbody>
				<tr style="height: 20px;">
					<td><?php echo $usr["id_personal"]; ?></td>
					<td><?php echo $usr["apellido_pa"]; ?></td>
					<td><?php echo $usr["apellido_ma"]; ?></td>
					<td><?php echo $usr["nombre"]; ?></td>
					<td><?php echo $usr["name_puesto"]; ?></td>
					<td>
						<a class="liberar_personal" data-id="<?php echo $usr["id_personal"]; ?>" data-nombre="<?php echo $usr["nombre"]; ?>" data-ap="<?php echo $usr["apellido_pa"]; ?>" data-am="<?php echo $usr["apellido_ma"]; ?>"><span class="warning"><i class="fa fa-2x fa-external-link" style="color: red"></i></span></a>
					</td>
				</tr>
	            <?php } }else{ ?>
	            </tbody> 
	            <tbody>
	                <tr>
	                    <td class="text-center" colspan="6"><h3>No hay personal asignado.</h3></td>
	                </tr>
	            </tbody>
	                
	            <?php } ?>
      	</table>
	</div>
	<div class="col m2 s12"></div>
</div>


<div class="row">
	<div class="col m12 s12" id="div_asignar" style="margin-top: 20px;" id="div_avance">
		<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> Avance de Fabricacion</span>
	</div>
</div>


	    <?php 
	    $suministro_materiales = 0;
	    $corte = 0;
	    $soldadura = 0;
	    $galvanizado = 0;
	    	foreach ($this->avances_torre as $key) {
	    		$suministro_materiales = $key['suministro_materiales'];
	    		$corte = $key['corte'];
	    		$soldadura = $key['soldadura'];
	    		$galvanizado = $key['galvanizado'];
	    	} 

	    	$total_avance = $suministro_materiales + $corte + $soldadura + $galvanizado;
	    ?>

<div class="row">
    <div class="col s12 m12">
      	<div class="card">
        	<div class="card-content">
        		<div class="row">

	        		<div class="col m4 s12 text-center">
				        <div class="progress green colorbar">
				            <span class="progress-left">
				                <span class="progress-bar"></span>
				            </span>
				            <span class="progress-right">
				                <span class="progress-bar"></span>
				            </span>
				            <div class="progress-value">
				               	<h5  style="margin-left: 35px">
				               		<input type="text" id="porcentaje_final" class="numero" value="<?php echo $total_avance; ?>%" readonly>
				               	</h5>
				            </div>
				        </div>
	        		</div>

	        		<div class="col m8 s12">
	        			<form action="/panel/requestaddporcentajetorrenueva" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_porcentaje">

	        				<input type="hidden" name="id" value="<?php echo $this->id_sitio; ?>">
	        				<input type="hidden" name="proyecto" value="<?php echo $this->proyecto; ?>">
	        				<input type="hidden" name="sitio" value="<?php echo $this->sitio_id; ?>">

					        <div class="input-field col m6 s12">
					          <input id="suministro" name="suministro" value="<?php echo $suministro_materiales; ?>" type="number" class="validate" min="0" max="25">
					          <label for="suministro">Suministro de materiales</label>
					        </div>

					        <div class="input-field col m6 s12">
					          <input id="corte" name="corte" type="number" value="<?php echo $corte; ?>" class="validate" min="0" max="25">
					          <label for="corte">Corte</label>
					        </div>

					        <div class="input-field col m6 s12">
					          <input id="soldadura" name="soldadura" value="<?php echo $soldadura; ?>" type="number" class="validate" min="0" max="40">
					          <label for="soldadura">Soldadura</label>
					        </div>

					        <div class="input-field col m6 s12">
					          <input id="galvanizado" name="galvanizado" value="<?php echo $galvanizado; ?>" type="number" class="validate" min="0" max="10">
					          <label for="galvanizado">Galvanizado</label>
					        </div>

					        <div class="input-field col m12 s12 text-center">
					        	<a class="btn" id="send_porcentaje">Guardar</a>
					        </div>
				       	</form> 
	        		</div>
        		</div>


        		<div class="row">
        			<div class="col m12 s12">
        				<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Comentarios</span>
        			</div>
        		</div>


        		<div class="row"> 
        			<div class="col m1 s12"></div>
        			<div class="col m10 s12">
        				<div class="row">
        					<div class="col m8 s6">
        						<form action="/panel/requestaddcomentarioavancec" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_comentavance">
			        				<input type="hidden" name="id" value="<?php echo $this->id_sitio; ?>">
			        				<input type="hidden" name="proyecto" value="<?php echo $this->proyecto; ?>">
			        				<input type="hidden" name="sitio" value="<?php echo $this->sitio_id; ?>">

							        <div class="input-field col s12">
							          	<input id="avance_comentario" name="comentario" type="text" class="validate">
							          	<label for="avance_comentario">Comentario</label>
							        </div>
						    	</form>
        					</div>
        					<div class="col m4 s12 text-center">
						        <div class="input-field col s12">
						        	<a class="btn" id="comentario_avance"><i class="material-icons right">add_circle_outline</i>Agregar</a>

						        </div>        						
        					</div>
        				</div>
        			</div>
        			<div class="col m1 s12"></div>
        		</div>


        		<div class="row">
        			<div class="col m12 s12">
				     	<table>
				        	<thead>
				          		<tr>
				              		<th>Comentario</th>
				              		<th>Personal</th>
				              		<th>Fecha</th>
				          		</tr>
				        	</thead>

							<?php
							if ($this->comentario_avance) {
							foreach ($this->comentario_avance as $usr) { ?>
							<tbody>
								<tr style="height: 20px;">
									<td><?php echo $usr["comentario"]; ?></td>
									<td><?php echo $usr["user_comentario"]; ?></td>
									<td><?php echo $usr["fecha_comentario"]; ?></td>
								<td>
									<a class="delete_comentario" data-id="<?php echo $usr["id"]; ?>"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
								</td>
								</tr>
					            <?php } }else{ ?>
					            </tbody> 
					            <tbody>
					                <tr>
					                    <td class="text-center" colspan="6"><h3>No hay comentarios.</h3></td>
					                </tr>
					            </tbody>
					                
					            <?php } ?>
				      </table> 
        			</div>
        		</div>

        	</div>
      	</div>
    </div>
</div>


<div class="row">
	<div class="col m12 s12" id="div_asignar" style="margin-top: 20px;" id="div_asignar">
		<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> Factores de Diseño</span>
	</div>
</div>


<!-- <form action="/panel/requestaddinfotorrenueva" method="POST" enctype="multipart/form-data" class="form-horizontal form-material">
		 	<input type="hidden" name="id_sitio" value="<?php echo $this->id_sitio; ?>">
		 	<input type="hidden" name="proyecto" value="<?php echo $this->proyecto; ?>">
		 	<input type="hidden" name="sitio" value="<?php echo $this->sitio_id; ?>"> -->
<?php 

if($this->torre_doc){
foreach ($this->torre_doc as $key) {?>
<div class="row"> 
	<div class="col m6 s6">
		<div class="row">
			<div class="col m6 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Velocidad Regional km/h</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="velocidad_km" name="velocidad" value="<?php echo $key['velocidad']; ?>" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
	<div class="col m6 s6">
		<div class="row">
			<div class="col m6 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Categoría de Terreno (Exposición)</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="cat_terreno" name="terreno" value="<?php echo $key['terreno']; ?>" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col m6 s6">
		<div class="row">
			<div class="col m6 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Categoría de Rugosidad</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="rugosidad" name="rugosidad" value="<?php echo $key['rugosidad']; ?>" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
	<div class="col m6 s6">
		<div class="row">
			<div class="col m6 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Topography Category (FT)</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="category" name="topography" value="<?php echo $key['topography']; ?>" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
</div>


<div class="row">
	<div class="col m6 s6">
		<div class="row">
			<div class="col m6 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Clasificación de estructura</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="estructura" name="estructura" value="<?php echo $key['estructura']; ?>" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
	<div class="col m6 s6">
		<div class="row">
			<div class="col m6 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Altura sobre el nivel mar (ASNM)</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="mar" name="mar_asnm" value="<?php echo $key['mar_asnm']; ?>" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col m6 s6">
		<div class="row">
			<div class="col m6 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Temp (°C)</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="temp" name="temp" value="<?php echo $key['temp']; ?>" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
	<div class="col m6 s6">
		<div class="row">
			<div class="col 63 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Carga</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="carga" name="carga" value="<?php echo $key['carga']; ?>" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
</div>

<?php } }else{?>
<div class="row"> 
	<div class="col m6 s6">
		<div class="row">
			<div class="col m6 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Velocidad Regional km/h</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="velocidad_km" name="velocidad" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
	<div class="col m6 s6">
		<div class="row">
			<div class="col m6 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Categoría de Terreno (Exposición)</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="cat_terreno" name="terreno" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col m6 s6">
		<div class="row">
			<div class="col m6 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Categoría de Rugosidad</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="rugosidad" name="rugosidad" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
	<div class="col m6 s6">
		<div class="row">
			<div class="col m6 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Topography Category (FT)</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="category" name="topography" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
</div>


<div class="row">
	<div class="col m6 s6">
		<div class="row">
			<div class="col m6 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Clasificación de estructura</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="estructura" name="estructura" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
	<div class="col m6 s6">
		<div class="row">
			<div class="col m6 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Altura sobre el nivel mar (ASNM)</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="mar" name="mar_asnm" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col m6 s6">
		<div class="row">
			<div class="col m6 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Temp (°C)</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="temp" name="temp" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
	<div class="col m6 s6">
		<div class="row">
			<div class="col 63 s6"> 
				<div class="input-field col s12">
					<h5 span class="font_tittle">Carga</h5>
				</div>
			</div>

			<div class="col m6 s6">
		        <div class="input-field col s12">
		        	<input id="carga" name="carga" type="text" class="validate">
		        </div>
			</div>
		</div>
	</div>
</div>

<?php } ?>


<div class="row">
	<div class="col m12 s12 text-center">
		<a class="btn"  id="send_doc"><i class="material-icons right">send</i>Guardar Información</a>
<!-- 
  <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right">send</i>
  </button> -->

	</div>
</div>
<!-- </form> -->


<div class="row"> 
	<div class="col m12 s12" style="margin-top: 10px;" id="">
		<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Descripción cambios:</span>
	</div>
</div>


<?php if($this->rol_user == 17 || $this->rol_user == 1){ ?>
	<!-- <form action="/panel/requestadddescripcioncambios" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_ajaxdetail"> -->
<div class="row">
	<div class="col m12 s12">
        <div class="input-field col s6">
          <input  id="version" type="text" name="version" class="validate">
          <label for="version">Version</label>
        </div>
        <div class="input-field col s6">
          <input id="des_cambio" type="text" name="des_cambio" class="validate">
          <label for="des_cambio">Descripción cambio</label>
        </div>
		 	<input type="hidden" name="id_sitio" id="id_sitio_cam" value="<?php echo $this->id_sitio; ?>">
		 	<input type="hidden" name="proyecto" id="proyecto_cam" value="<?php echo $this->proyecto; ?>">
		 	<input type="hidden" name="sitio" id="sitio_cam" value="<?php echo $this->sitio_id; ?>">
	</div>

	<div class="row">
		<div class="col m12 s12 text-center">
			<a class="btn" type="submit" id="cambios"><i class="material-icons right">send</i>Agregar</a>

<!--   <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right">send</i>
  </button> -->

		</div>
	</div>
</div>
</form>
<?php } ?>


<div class="row">
	<div class="col m12 s12">
      	<table>
        	<thead>
          		<tr>
              		<th>Fecha.</th>
              		<th>Usuario</th>
              		<th>Version</th>
              		<th>Descripción</th>
          		</tr>
        	</thead>

			<?php
			if ($this->torrecambios) {
			foreach ($this->torrecambios as $usr) { ?>
			<tbody>
				<tr style="height: 20px;">
					<td><?php echo $usr["fecha"]; ?></td>
					<td><?php echo $usr["usuario"]; ?></td>
					<td><?php echo $usr["version"]; ?></td>
					<td><?php echo $usr["descripcion"]; ?></td>
				</tr>
	            <?php } }else{ ?>
	            </tbody> 
	            <tbody>
	                <tr>
	                    <td class="text-center" colspan="6"><h3>No hay descripción de cambios.</h3></td>
	                </tr>
	            </tbody>
	                
	            <?php } ?>
      	</table>
	</div>
</div>



<script src="/js/materialize.min.js"></script>
<script src="/js/lightbox.js"></script>
<script type="text/javascript">

  	$(document).ready(function(){
    	$('.modal').modal();
    	// $('.datepicker').datepicker( {"format":'dd-mm-yyyy'});
    	var currentDate = document.getElementById("today_picker").value; 
    	// alert(currentDate);
    	$('.datepicker').datepicker( {"format":'dd-mm-yyyy'} ).datepicker("setDate",currentDate);



    	$('select').formSelect();
    	$('.collapsible').collapsible();
    	$('.dropdown-trigger').dropdown();
  	});

     $("#carga_uno").click(function(){
		var myElement = document.getElementById(''); 
		$('html, body').animate({
		scrollTop: $("#baselie_cal").offset().top
		}, 2000);
    });

     $("#asignar_cuadrilla").click(function(){
		var myElement = document.getElementById(''); 
		$('html, body').animate({
		scrollTop: $("#div_asignar").offset().top
		}, 2000);
    });

    $("#torre").click(function(){
    	var validate = document.getElementById("file_validate_torre").value;
    	if(validate == ""){
            swal({
              title: "Para continuar debes agregar un archivo",
            });
    	}else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
    		setTimeout(addtorre, 1500);   
    	}
    });

    function addtorre() { document.getElementById("submit_torre").submit() }



    $("#memoria").click(function(){
    	var validate = document.getElementById("file_validate_memoria").value;
    	if(validate == ""){
            swal({
              title: "Para continuar debes agregar un archivo",
            });
    	}else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
    		setTimeout(addmemoria, 1500);   
    	}
    });

    function addmemoria() { document.getElementById("submit_memoria").submit() }

    $("#simentacion").click(function(){
    	var validate = document.getElementById("file_validate_simentacion").value;
    	if(validate == ""){
            swal({
              title: "Para continuar debes agregar un archivo",
            });
    	}else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
    		setTimeout(addsimentacion, 1500);   
    	}
    });

    function addsimentacion() { document.getElementById("submit_simentacion").submit() }


    $("#staad").click(function(){
    	var validate = document.getElementById("file_validate_staad").value;
    	if(validate == ""){
            swal({
              title: "Para continuar debes agregar un archivo",
            });
    	}else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
    		setTimeout(addstaad, 1500);   
    	}
    });

    function addstaad() { document.getElementById("submit_staad").submit() }


    $("#mecanica").click(function(){
    	var validate = document.getElementById("file_validate_mecanica").value;
    	if(validate == ""){
            swal({
              title: "Para continuar debes agregar un archivo",
            });
    	}else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
    		setTimeout(addmecanica, 1500);   
    	}
    });

    function addmecanica() { document.getElementById("submit_mecanica").submit() }


    $("#subir_archivo").click(function(){
    	var archivo = document.getElementById("file_validate_torrenueva").value;
    	var select =document.getElementById("select_file").value;

    	if(archivo == "" || select == 0){
            swal({
              title: "Para continuar debes agregar un archivo",
            });
    	}else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
    		setTimeout(addfile, 1500);   
    	}
    });

    function addfile() { document.getElementById("submit_file").submit() }


    $("#personal_add").click(function(){

	swal({
		title: "Estas seguro de agregarlo a la cuadrilla?",
		icon: "warning",
		buttons: true,
		dangerMode: true,
	})
	.then((willDelete) => {
	  	if (willDelete) {
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 

    		var personal = document.getElementById("jspersonal").value;
    		var sitio = document.getElementById("id_sitio").value;
    		var tipo_proyecto = document.getElementById("id_tipoproyecto").value;
    		var sitio_tipoproyecto = document.getElementById("sitio_tipoproyecto").value;
    		var nombre_sitio = document.getElementById("nombre_sitio").value;

            var request = $.ajax({
                url:"/panel/requestchangeaddcuadrilla",
                method:"POST",
                data: { personal : personal, id_sitio: sitio, id_tipoproyecto:tipo_proyecto, sitio_tipoproyecto:sitio_tipoproyecto, name_sitio: nombre_sitio },
                processData: true,
            });
//-------------------end de ajax---------------------------
//-------------peticion de respuesta de ajax------------------
            request.done(function(response) {
                console.log(response);//imprime lo que responde el ajax
                // alert
                window.location.reload(true);
            });
//-------------------end de respuesta ajax---------------------
             return false;


	  } else {
	    swal("La asignacion fue cancelada!");
	  }
	});

  });



    $(".liberar_personal").click(function(){
    	id=$(this).data('id');
    	nombre=$(this).data('nombre');
    	ap=$(this).data('ap');
    	am =$(this).data('am');

		swal({
			title: "Estas seguro de liberar a "+ap+" "+nombre+" del sitio?",
		  	icon: "warning",
		  	buttons: true,
		  	dangerMode: true,
		})
	.then((willDelete) => {
	  if (willDelete) {
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 

            var request = $.ajax({
                url:"/panel/requestliberarpersonal",
                method:"POST",
                data: { id : id },
                processData: true,
            });
//-------------------end de ajax---------------------------

//-------------peticion de respuesta de ajax------------------
            request.done(function(response) {
                console.log(response);//imprime lo que responde el ajax
                // alert
                window.location.reload(true);
            });
//-------------------end de respuesta ajax---------------------
             return false;


	  } else {
	    swal("La accion fue cancelada!");
	  }
	});

    });


    $("#send_doc").click(function(){
    	var id_sitio = document.getElementById("id_sitio").value;
    	var proyecto = document.getElementById("id_tipoproyecto").value;
    	var sitio = document.getElementById("sitio_tipoproyecto").value;

    	var velocidad = document.getElementById("velocidad_km").value;
    	var terreno = document.getElementById("cat_terreno").value;
    	var rugosidad = document.getElementById("rugosidad").value;
    	var topography = document.getElementById("category").value;
    	var estructura = document.getElementById("estructura").value;
    	var mar_asnm = document.getElementById("mar").value;
    	var temp = document.getElementById("temp").value;
    	var carga = document.getElementById("carga").value;

		swal({
			title: "Estas seguro de agregar la informacón",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 

	            var request = $.ajax({
	                url:"/panel/requestaddinfotorrenueva",
	                method:"POST",
	                data: { id_sitio:id_sitio, proyecto:proyecto, sitio:sitio, velocidad,velocidad, terreno:terreno, rugosidad:rugosidad, topography:topography, estructura:estructura, mar_asnm:mar_asnm, temp:temp, carga:carga  },
	                processData: true,
	            });
		//-------------------end de ajax---------------------------
		//-------------peticion de respuesta de ajax------------------
	            request.done(function(response) {
	                console.log(response);//imprime lo que responde el ajax
	                // alert
	                window.location.reload(true);
	            });
		//-------------------end de respuesta ajax---------------------
	             return false;


		  } else {
		    swal("La asignacion fue cancelada!");
		  }
		});

    });


    $("#cambios").click(function(){
    	var version = document.getElementById("version").value;
    	var des_cambio = document.getElementById("des_cambio").value;
    	var id_sitio = document.getElementById("id_sitio_cam").value;
    	var proyecto = document.getElementById("proyecto_cam").value;
    	var sitio = document.getElementById("sitio_cam").value;

		swal({
			title: "Estas seguro de agregar la informacón",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
	            var request = $.ajax({
	                url:"/panel/requestadddescripcioncambios",
	                method:"POST",
	                data: { id_sitio:id_sitio, proyecto:proyecto, sitio:sitio, version:version, des_cambio:des_cambio},
	                processData: true,
	            });

	            request.done(function(response) {
	                console.log(response);
	                window.location.reload(true);
	            });
	            return false;
		  } else {
		    swal("La asignacion fue cancelada!");
		  }
		});
    });


    $("#send_porcentaje").click(function(){
    	var suministro = document.getElementById("suministro").value;
    	var corte = document.getElementById("corte").value;
    	var soldadura = document.getElementById("soldadura").value;
    	var galvanizado = document.getElementById("galvanizado").value;

    	if(suministro < 0 || suministro > 25  || corte < 0 || corte > 25 || soldadura < 0 || soldadura > 40 || galvanizado < 0 || galvanizado > 10){
            swal({
              title: "Verifica los datos",
            });
    	}else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
    		setTimeout(addporcentaje, 1500);   
    	}
    });

     function addporcentaje() { document.getElementById("submit_porcentaje").submit() }



    $("#comentario_avance").click(function(){
    	var comentario = document.getElementById("avance_comentario").value;

    	if(comentario == ""){
            swal({
              title: "Para continuar debes agregar un comentario",
            });
    	}else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
    		setTimeout(addavancecoment, 1500);   
    	}
    });

    function addavancecoment() { document.getElementById("submit_comentavance").submit() }


    $(".delete_comentario").click(function(){
    	var id = $(this).data('id');
	swal({
		title: "Estas seguro de eliminar el comentario?",
		icon: "warning",
		buttons: true,
		dangerMode: true,
	})
	.then((willDelete) => {
	  	if (willDelete) {
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			});
            var request = $.ajax({
                url:"/panel/requestdeletecomentariotorrenueva",
                method:"POST",
                data: { id : id},
                processData: true,
            });
//-------------------end de ajax---------------------------
//-------------peticion de respuesta de ajax------------------
            request.done(function(response) {
                console.log(response);//imprime lo que responde el ajax
                window.location.reload(true);
            });
//-------------------end de respuesta ajax---------------------
             return false;
	  	} else {
	    	swal("La asignacion fue cancelada!");
	  	}
	});
    });

</script>