<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>

<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="javascript:window.history.go(-1);" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
</div>


<div class="row">
    <div class="col m12 s12 text-center">
    	<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">P.O</span>
    </div>
</div>


  <!-- Modal Structure -->
<div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
    	<h2>Agregar una P.O</h2>
		<form action="/panel/requestaddcotizacionsitiopo" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_cotizacion">
			<div class="file-field col m12 s12 input-field">
			    <div class="btn  light-green">
			    	<span>Documento</span>
			    	<input type="file" name="url">
			    </div>
			    <div class="file-path-wrapper">
			    	<input class="file-path validate" id="file_cotizacion" type="text">
			    </div>
			</div>

	        <div class="input-field col s12">
	        	<i class="material-icons prefix">account_circle</i>
	        	<input id="titulo" type="text" name="titulo" class="validate">
	        	<label for="titulo">Titulo de la P.O</label>
	        </div>

	        <div class="input-field col m6 s12">
	        	<i class="material-icons prefix">format_list_numbered</i>
	        	<input id="numero" type="text" name="numero" class="validate">
	        	<label for="numero">Numero P.O</label>
	        </div>

			<div class="input-field col m6 s12">
				<i class="material-icons prefix">date_range</i>
				<input id="fecha_realizada" name="fecha_realizada" type="date" class="fecha_realizada">
				<label for="fecha_realizada">Fecha</label>
			</div>

			<div class="input-field col m6 s12">
				<i class="material-icons prefix">attach_money</i>
				<input id="monto" name="monto" type="number" class="monto">
				<label for="monto">Monto</label>
			</div>

	        <div class="input-field col m6 s12">
	        	<i class="material-icons prefix">format_list_bulleted</i>
	        	<input id="moneda" type="text" name="moneda" class="validate">
	        	<label for="moneda">Tipo de moneda</label>
	        </div>

	        <div class="input-field col s12">
	        	<i class="material-icons prefix">mode_edit</i>
	        	<textarea id="descripcion" name="descripcion" class="materialize-textarea"></textarea>
	        	<label for="descripcion">Descripcion</label>
	        </div>

			<?php 
				date_default_timezone_set('America/Mexico_City');
            	$hoy = date("d-m-Y");
			?>

			<input type="hidden" name="fecha" value="<?php echo $hoy; ?>">
			<input type="hidden" name="id_sitio" value="<?php echo $this->sitio_id; ?>">
			<input type="hidden" name="id_cotizacion" value="<?php echo $this->id; ?>">
			<input type="hidden" name="id_user" value="<?php echo $this->id_user; ?>">
			<input type="hidden" name="name_user" value="<?php echo $this->nombre_user; ?>">

		</form>
    </div>
    <div class="modal-footer">
      	<button id="add_cotizacion" class="btn">Guardar</button>
      	<button class="modal-close red btn">Cerrar</button>
    </div>
</div>

<div class="row">

	<div class="row">
		<div class="col m6 s12">
			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de P.O</span>
		</div>
		<div class="col m6 s12 text-right">
			<a class=" btn modal-trigger" href="#modal1">Agregar P.O</a>
		</div>
	</div>

	<div class="col m12 s12">
		<table class="table text-left table-hover">
			<thead>
				<tr>
					<th>Titulo de P.O</th>
					<th>Numero de P.O</th>
					<th>Fecha</th>	
					<th>Monto</th>
					<th>Documento</th>
					<th>Factura</th>
				</tr> 
			</thead>
		<?php 
		if ($this->cotizaciones) { 
		foreach ($this->cotizaciones as $usr) { ?>
		<tbody>
			<tr>
				<td><?php echo $usr['titulo_po']; ?></td>
				<td><?php echo $usr['numero_po']; ?></td>
				<td><?php echo $usr['fecha_subir']; ?></td>
				<td>$<?php echo $usr['monto'];?></td>
				<td>
					<a title="Descargar Archivo" href="/<?php echo $usr["documento_po"]; ?>" download="/<?php echo $usr["documento_po"]; ?>"> <i class="material-icons prefix" style="width: 42px;font-size: 31px;">file_download</i> </a>

					<a href="/<?php echo $usr["documento_po"]; ?>" target="_blank"> <i class="material-icons prefix" style="font-size: 31px;">open_with</i></a>
        		</td>

        		<td>
        			<?php if($usr['status_factura'] == 0){ ?>
        				<!-- <a href="/panel/documentocotizacion/id/<?php echo $usr['id']; ?>/sitio/<?php echo $this->id; ?>"> -->
							<div class="chip">
						    	<img src="/img/gris.jpg">
						    	Pendiente
						  	</div>
					  	<!-- </a> -->
        			<?php }else{ ?>
						<div class="chip">
					    	<img src="/img/correct.png">
					    	con P.O
					  	</div>
        			<?php } ?>
        		</td>
				<td>
					<a class="edit_cot modal-trigger" data-id="<?php echo $usr["id"] ?>" data-titulo="<?php echo $usr["titulo"] ?>" data-fecha="<?php echo $usr["fecha_cotizacion"] ?>" data-total="<?php echo $usr["total"] ?>" data-comentario="<?php echo $usr["comentario"] ?>" href="#modal_edit"><i class="fa fa-2x fa-edit"></i></a>

				</td>
				<td>
					<a class="delete" href="/panel/requestdeleteproveedor/id/<?php echo $usr["id"]; ?>" ><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
				</td>
			</tr>
		</tbody>
		    <?php } }else{ ?>
		    </tbody> 
		    <tbody>
		        <tr>
		            <td class="text-center" colspan="6"><h4>No hay cotizaciones asignadas al sitio.</h4></td>
		        </tr>
		    </tbody>
		                
		    <?php } ?>
		</table>
	</div>
</div>



<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
               		<?php if($pagina - 1 == 0){ ?>
                    	<li class="page-item disabled">
                        	<span class="page-link">Anterior</span>
                    	</li>
               		<?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
               		<?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
               		<?php if($pagina >= $this->total): ?>
                       	<li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                       	</li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                   	<?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>

<script type="text/javascript">
  	$(document).ready(function(){
    	$('.modal').modal();
  	});

	$("#add_cotizacion").click(function(){
		var documento = document.getElementById("file_cotizacion").value;
		var titulo = document.getElementById("titulo").value;
        if(documento == "" || titulo == ""){
            swal({
              title: "Para agregar una P.O debes llenar todos los campos",
            });
        }else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			});  
            setTimeout(submitForm, 1500);     
        }
	});

    function submitForm() {
        document.getElementById("submit_cotizacion").submit()
    }
</script>