<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>

<style type="text/css">
	.oculto{
		display: none;
	}
</style>


<div class="row mt-4">
	<div class="col m4 s12 text-center">
		<h2>Personal de Campo</h2>
	</div>

	<div class="col m8 s12 text-center" style="margin-top: 15px;">
		<a class="waves-effect red btn modal-trigger" href="#modal1">+ Agregar Personal</a>
	</div>
</div>



<div class="row">
	<div class="col m2 s12">
		<a href="/panel/personal">Mostrar todos</a>
	</div>
	<div class="col m8 s12">
	    <div class="input-field col m8 s8">
	        <input placeholder="Ingresa nombre" name="nombre" value="<?php echo $this->name_search; ?>" id="first_name" type="text" class="validate" disabled>
	        <label for="first_name">El correo agregado ya existe:</label>
	    </div>
	</div>
	<div class="col m2 s12"></div>
</div>

  <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
      <h2>Agregar Personal</h2>
		<div class="col m12 s12">
			<form action="/panel/requestaddpersonalcampo" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="form_user">
				<div class="row">
					<input type="hidden" name="rol" value="6">
				    <div class="file-field input-field col m12 s12">
					    <div class="btn">
					        <span>Foto</span>
					        <input type="file" name="url">
					    </div>
					    <div class="file-path-wrapper">
					        <input class="file-path validate" type="text">
					    </div>
				    </div>

			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">group</i>
			          <input id="icon_prefix" type="text" name="name" class="validate" required>
			          <label for="icon_prefix">Nombre(s):</label>
			        </div>
			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">account_circle</i>
			          <input id="ap" type="text" name="apa" class="validate">
			          <label for="ap">Apellidos Paterno:</label>
			        </div>
			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">account_circle</i>
			          <input id="am" type="text" name="ama" class="validate">
			          <label for="am">Apellidos Materno:</label>
			        </div>
			        <div class="input-field col m6 s12">
			        	<i class="material-icons prefix">event_available</i>
			          	<input id="puesto" type="text" name="puesto" class="validate">
			          	<label for="puesto">Puesto:</label>
			        </div>

					<div class="input-field col m6 s12">
					    <select name="status">
					      <option value="" disabled selected>Selecciona una opcion</option>
					      <option value="1">Expediente Completo</option>
					      <option value="0">Expediente Incompleto</option>
					    </select>
					    <label>Status Expediente</label>
					</div>

			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">event_available</i>
			          <input id="curp" type="text" name="curp" class="validate">
			          <label for="curp">CURP:</label>
			        </div>
			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">event_available</i>
			          <input id="nss" type="text" name="nss" class="validate">
			          <label for="nss">NSS:</label>
			        </div>
			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">event_available</i>
			          <input id="rfc" type="text" name="rfc" class="validate">
			          <label for="rfc">RFC:</label>
			        </div>
			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">phone</i>
			          <input id="icon_telephone" type="text" name="phone" class="validate">
			          <label for="icon_telephone">Telefono</label>
			        </div>
			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">email</i>
			          <input id="mail" type="text" name="mail" class="validate">
			          <label for="mail">Correo Electronico</label>
			        </div>
		      	</div>
			
		</div>
    </div>
    <div class="modal-footer">
      	<button tyle="submit" id="add_user" class="waves-effect waves-light btn">Guardar</button>
      	</form>
      	<button  class="modal-close waves-effect waves-light red btn">Cerrar</button>
    </div>
  </div>
<!-- ================================================================================================= -->

<div class="col m12 s12">
	<h3>Lista del Personal</h3>
	<table class="table text-left table-hover">
		<thead>
			<tr>
				<th>Nombre</th>	
				<th>Apellido Paterno</th>	
				<th>Apellido Materno</th>
				<th>Puesto</th>
				<th>Status</th>
			</tr> 
		</thead>
		<?php foreach ($this->paginator as $usr) { ?>
		<tbody>
			<tr>
				<td><?php echo $usr["nombre"]; ?></td>
				<td><?php echo $usr["apellido_pa"]; ?></td>
				<td><?php echo $usr["apellido_ma"]; ?></td>
				<td><?php echo $usr["puesto"]; ?></td>
				<td><?php echo $usr["status_expediente"]; ?></td>
				<td>
					<a href="/panel/personaldetail/id/<?php echo $usr["id"] ?>"><i class="fa fa-2x fa-id-card-o"></i></a>	
				</td>
				<td>
					<a href="/panel/personaledit/id/<?php echo $usr["id"] ?>"><i class="fa fa-2x fa-edit"></i></a>
				</td>
				<td>
					<a href="/panel/requestdeletepersonal/id/<?php echo $usr["id"]; ?>" ><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
				</td>
			</tr>
		</tbody>
		<?php } ?>
	</table>
</div>



		
<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
               		<?php if($pagina - 1 == 0){ ?>
                    	<li class="page-item disabled">
                        	<span class="page-link">Anterior</span>
                    	</li>
               		<?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
               		<?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
               		<?php if($pagina >= $this->total): ?>
                       	<li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                       	</li>
                    <?php else: ?>
                        <li class="page-item">

<?php if($this->option == 1){ ?>
	<a class="page-link"  href="/panel/searchpersonal/nombre/<?php echo $this->name_per; ?><?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
<?php } ?>
<?php if($this->option == 2){ ?>
	<a class="page-link"  href="/panel/searchpersonal/puesto/<?php echo $this->puesto; ?><?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
<?php } ?>
<?php if($this->option == 3){ ?>
	<a class="page-link"  href="/panel/searchpersonal/status/<?php echo $this->status_per; ?><?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
<?php } ?>
                          
                        </li>
                   	<?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>



<script type="text/javascript">
	$(document).ready(function(){
	    $('.modal').modal();
	    $('select').formSelect();
	});

	$('#mySelect').on('change', function() {
  		var value = $(this).val();
  		if(value==1){
			$("#search_nombre").show();
			$("#search_status").hide();
			$("#search_puesto").hide();
  		}

  		if(value==2){
  			$("#search_puesto").show();
  			$("#search_nombre").hide();
  			$("#search_status").hide();
  		}

  		if(value==3){
  			$("#search_status").show();
  			$("#search_nombre").hide();
  			$("#search_puesto").hide();
  		}
  		// console.log(value);
	});
</script>
