<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>


<div class="row mt-4">
	<div class="col m4 s12 text-center">
		<!-- <h2></h2> -->
	</div>

	<div class="col m8 s12 text-center" style="margin-top: 15px;">
		<div class="row">
			<div class="col m12 s12 text-right">
				<a class="waves-effect green btn modal-trigger" href="#modal1">+ Agregar Estructura</a>
			</div>
		</div>
		
	</div>
</div>

<div class="row">
    <div class="col m12 s12 text-center">
      <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Estructuras de los sitios</span>
    </div>
</div>


  <!-- Modal Structure -->
  <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
      <span style="font-size:25px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar Estructura</span>
      <h2></h2>
  		<div class="col m12 s12">
  			<form action="/panel/requestaddestructurasitio" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_estructura">
  			<div class="row">
          <div class="input-field col m12 s12">
  			    <i class="material-icons prefix">assignment</i>
  			    <input id="name" type="text" name="name" class="validate" required>
  			   	<label for="name">* Nombre:</label>
          </div>
  		  </div>
        </form>
  		</div>
    </div>
    <div class="modal-footer">
      	<button id="addestructura" class="waves-effect waves-light btn">Guardar</button>
      	<button  class="modal-close waves-effect waves-light red btn">Cerrar</button>
    </div>
  </div>

<!-- ================================================================================================= -->


<div class="row">
	<div class="col m2 s12"></div>
	<div class="col m8 s12">
		<form action="/panel/searchestructura" enctype="multipart/form-data" class="form-horizontal form-material">
	        <div class="input-field col m8 s8">
	          <input placeholder="Ingresa el nombre de la estructura" name="nombre" id="first_name" type="text" class="validate">
	          <label for="first_name">Buscar Estructura</label>
	        </div>
	        <div class="input-field col m4 s4">
	        	<button tyle="submit" id="add_user" class="waves-effect waves-light btn">Buscar <i class="material-icons left">search</i></button>
	        </div>
    	</form>
	</div>
	<div class="col m2 s12"></div>
</div>


<div class="row">
	<div class="col m10 s12">
    <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de estructuras de los sitio</span>
		<table class="table text-left table-hover">
			<thead>
				<tr>
					<th>Id</th>		
					<th>Nombre</th>
				</tr> 
			</thead>
			<?php 
			if ($this->paginator) {
			foreach ($this->paginator as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo $usr["id"]; ?></td>
					<td><?php echo $usr["nombre_estructura"]; ?></td>
					<td>
						<a href="/panel/estructurasitiosedit/id/<?php echo $usr["id"]?>"><i class="fa fa-2x fa-edit"></i></a>
					</td>
					<td>
						<a class="delete" href="/panel/requestdeleteestructura/id/<?php echo $usr["id"]; ?>" ><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
					</td>
				</tr>
	            <?php } }else{ ?>
	            </tbody> 
	            <tbody>
	                <tr>
	                    <td class="text-center" colspan="6"><h3>No hay estructuras registradas.</h3></td>
	                </tr>
	            </tbody>
	                
	            <?php } ?>
		</table>
	</div>
	<div class="col m2 s12"></div>
</div>

<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
               		<?php if($pagina - 1 == 0){ ?>
                    	<li class="page-item disabled">
                        	<span class="page-link">Anterior</span>
                    	</li>
               		<?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
               		<?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
               		<?php if($pagina >= $this->total): ?>
                       	<li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                       	</li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                   	<?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>



<script type="text/javascript">
  $(document).ready(function(){
    $('.modal').modal();
     $('select').formSelect();
  });

    $(".delete").click(function(){
        var confirmar=confirm("Esta seguro que deseas eliminar");
        if(confirmar){
          window.location.reload(true);
        }else{
            alert("cancelo la solicitud");
            return false;
        }
    });

    $("#addestructura").click(function(){
        var name = document.getElementById("name").value;

        if(name == ""){
            swal({
              title: "Para agregar una estructura debes llenar todos los campos marcados con un '*'",
            });
        }else{
            swal("Felicidades!", "La estructura se creo de forma correcta!", "success");   
            setTimeout(submitForm, 1500);     
        }
    });


    function submitForm() {
        document.getElementById("submit_estructura").submit()
    }
</script>
