
<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/panel/ordencompraspendiente" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
</div>

<div class="row"> 
	<div class="col m12 s12 text-center" style="margin-top: 30px;">
		<span style="font-size:24px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Paso 2 - Carga de Documentación</span>
	</div>
</div>


<div class="row">
	<div class="col m7 s12">
		<div class="input-field col s6">
			<!-- <a class="btn modal-trigger" href="#modal1">Cotizacion</a> -->
        </div>
		<div class="input-field col s6">
			<!-- <a class="btn modal-trigger" href="#modal2">Comparativa</a> -->
        </div>				 
	</div>
	<div class="col m5 s12">
		<h4><a href="#modal3" class="modal-trigger"><i class="fa fa-edit"></i> Editar solicitud de orden de compra</a></h4>
	</div>
</div>


<div class="row">
	<div class="col m12 s12">
      <div class="card  darken-1">
        <div class="card-content">
		<div class="row">
<!-- 			<div class="col m8 s6">
				<h4>Cotizaciones</h4>
			</div> -->
<!-- 			<div class="col m4 s6">
				<a class="btn modal-trigger" href="#modal1">Cotizacion</a>
			</div> -->
		</div>
<!-- 		<table class="table text-left table-hover">
			<thead>
				<tr>
					<th>Tipo de Documento</th>		
					<th>Documento</th>
					<th>Eliminar</th>
				</tr> 
			</thead>
			<?php
			if ($this->cotizacion) { 
			foreach ($this->cotizacion as $usr) { ?>
			<tbody>
				<tr>
					<td>
						<h4><?php echo $usr["titulo_cotizacion"]; ?></h4>
					</td>
					<td>
						<a title="Descargar Archivo" href="/<?php echo $usr["documento_cotizacion"]; ?>" download="/<?php echo $usr["documento_cotizacion"]; ?>" style="color: blue; font-size:18px;"> <i class="material-icons left">get_app</i> </a>
					</td>
				<td>
					<a class="delete_cotizacion" data-id="<?php echo $usr["id"]; ?>" data-nombre="cotizacion"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
				</td>
				</tr>
		    <?php } }else{ ?>
		    </tbody> 
		    <tbody>
		        <tr>
		            <td class="text-center" colspan="6"><h4>No hay cotizaciones agregadas.</h4></td>
		        </tr>
		    </tbody>
		                
		    <?php } ?>
		</table> -->

		<?php $nombre_prov = ""; foreach ($this->name_prov as $key){ $nombre_prov = $key['nombre_prov']; } ?>
		
			<div class="row">
				<form action="/solicitud/requestadddocumentacionsolicitudordencompra" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_doc">
					<input type="hidden" name="id_solicitud" value="<?php echo $this->orden_id; ?>">
					<div class="col m4 s12 text-center">
				        <div class="input-field col s12">
				        	<input placeholder="Nombre Proveedor" value="<?php echo $nombre_prov; ?>" id="proveedor_opuno" name="proveedor_opuno" type="text">	
				        </div>
				        <div class="input-field col s12">
				        	<input placeholder="Alcance op1" id="alcance_opuno" name="alcance_opuno" type="text">
				        </div>
				        <div class="input-field col s12">
				        	<input placeholder="Tiempo op1" id="tiempo_uno" name="tiempo_uno" type="text">
				        </div>
				        <div class="input-field col s12">
				        	<?php foreach ($this->informacion as $key){ ?>
				        		<div class="col m2 s2">
				        			<div class="row" style="margin-top: 12px;">
				        				<span style="font-size: 19px; font-weight: bold;">$</span>
				        			</div>
				        		</div>
				        		<div class="col m10 s10">
				        			<input placeholder="Costo op1" id="costo_uno" name="costo_uno" value="<?php echo $key['total']; ?>" type="text">	
				        		</div>
				        		
				        	<?php } ?>
				        </div>
	    				<div class="file-field input-field col s12">
	      					<div class="btn light-green">
	        					<span>Cotización</span>
	        					<input type="file" id="file_opuno" name="file_opuno">
	      					</div>
	      					<div class="file-path-wrapper">
	        					<input class="file-path validate" type="text">
	      					</div>
	    				</div>
					</div>
					<div class="col m4 s12 text-center">
				        <div class="input-field col s12">
				        	<input placeholder="Nombre Proveedor" id="proveedor_opdos" name="proveedor_opdos"type="text">
				        </div>
				        <div class="input-field col s12">
				          	<input placeholder="Alcance op2" id="alcance_opdos" name="alcance_opdos" type="text">
				        </div>
				        <div class="input-field col s12">
				          	<input placeholder="Tiempo op2" id="tiempo_dos" name="tiempo_dos" type="text">
				        </div>
				        <div class="input-field col s12">
				        	<div class="col m2 s2">
				        		<div class="row" style="margin-top: 12px;">
				        			<span style="font-size: 19px; font-weight: bold;">$</span>
				        		</div>
				        	</div>
				        	<div class="col m10 s10">
				        		<input placeholder="Costo op2" id="costo_dos" name="costo_dos" type="text">
				        	</div>
				        </div>
	    				<div class="file-field input-field col s12">
	      					<div class="btn light-green">
	        					<span>Cotización</span>
	        					<input type="file" id="file_opdos" name="file_opdos">
	      					</div>
	      					<div class="file-path-wrapper">
	        					<input class="file-path validate" type="text">
	      					</div>
	    				</div>
					</div>
					<div class="col m4 s12 text-center">
				        <div class="input-field col s12">
				        	<input placeholder="Nombre Proveedor" id="proveedor_optres" name="proveedor_optres" type="text">
				        </div>
				        <div class="input-field col s12">
				          	<input placeholder="Alcance op3" id="alcance_optres" name="alcance_optres" type="text">
				        </div>
				        <div class="input-field col s12">
				          	<input placeholder="Tiempo op3" id="tiempo_tres" name="tiempo_tres" type="text">
				        </div>
				        <div class="input-field col s12">
				        	<div class="col m2 s2">
				        		<div class="row" style="margin-top: 12px;">
				        			<span style="font-size: 19px; font-weight: bold;">$</span>
				        		</div>				        		
				        	</div>
				        	<div class="col m10 s10">
				        		<input placeholder="Costo op3" id="costo_tres" name="costo_tres" type="text">
				        	</div>
				        </div>
	    				<div class="file-field input-field col s12">
	      					<div class="btn light-green">
	        					<span>Cotización</span>
	        					<input type="file" id="file_optres" name="file_optres">
	      					</div>
	      					<div class="file-path-wrapper">
	        					<input class="file-path validate" type="text">
	      					</div>
	    				</div>
					</div>

			<?php if($this->if_proyecto == 0){ ?>
				<input type="hidden" id="proyecto" name="proyecto" value="0">
			<?php }else{ ?>
				<div class="row">
					<div class="col m6 s12">
						<span style="font-size: 18px;">* Selecciona el tipo de Proyecto del Sitio</span>
					</div>
					<div class="col m6 s12">
						<div class="input-field col m12 s12">
						    <select id="proyecto" name="proyecto" required>
						      	<option value="" disabled selected>* Selecciona una opcion:</option>
						      	<?php foreach ($this->proyectos as $rl) { ?>
						      	<option value="<?php echo $rl["id"]; ?>">Id: <?php echo $rl["id"]; ?> Proyecto: <?php echo $rl["nombre_proyecto"]; ?></option>
						      	<?php } ?>
						    </select>
						    <label>Tipo de Proyecto</label>
						</div>
					</div>
				</div>		
			<?php } ?>

				</form>
			</div>


        </div>
      </div>


	</div>

<!-- 	<div class="col m6 s12">
      <div class="card  darken-1">
        <div class="card-content ">
		<div class="row">
			<div class="col m8 s6">
				<h4>Comparativas</h4>
			</div>
			<div class="col m4 s6">
				<a class="btn modal-trigger" href="#modal2">Comparativa</a>
			</div>
		</div>
		<table class="table text-left table-hover">
			<thead>
				<tr>
					<th>Tipo de Documento</th>		
					<th>Documento</th>
					<th>Eliminar</th>
				</tr> 
			</thead>
			<?php
			if ($this->comparativa) { 
			foreach ($this->comparativa as $usr) { ?>
			<tbody>
				<tr>
					<td>
						<h4><?php echo $usr["titulo_comparativa"]; ?></h4>
					</td>
					<td>
						<a title="Descargar Archivo" href="/<?php echo $usr["documento_comparativa"]; ?>" download="/<?php echo $usr["documento_comparativa"]; ?>" style="color: blue; font-size:18px;"> <i class="material-icons left">get_app</i> </a>
					</td>
				<td>
					<a class="delete_comparativa" data-id="<?php echo $usr["id"]; ?>" data-nombre="comparativa"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
				</td>
				</tr>
		    <?php } }else{ ?>
		    </tbody> 
		    <tbody>
		        <tr>
		            <td class="text-center" colspan="6"><h4>No hay comparativas agregadas.</h4></td>
		        </tr>
		    </tbody>
		                
		    <?php } ?>
		</table>
        </div>
      </div>

	</div> -->
</div>


<div class="row">
	<div class="col m12 s12 text-center">
		<a class="btn" id="send_doc">Guardar Información</a>
	</div>

<!-- 	<div class="col m12 s12 text-center">
		<a class="red darken-3 btn" href="/panel/successsolicitudordencompras" id="end_proceso">Finalizar Proceso</a>
	</div> -->
</div>


  	<div id="modal1" class="modal modal-fixed-footer">
    	<div class="modal-content">
      		<h4>Cotización</h4>
      		<div class="row">
    			<form action="/panel/requestaddcotizacionordendecompra" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_file_cotizacion">
		    		<div class="file-field col m12 s12 input-field">
		    			<input type="hidden" name="titulo_cotizacion" value="Cotización">
		    			<input type="hidden" name="id_solicitud" value="<?php echo $this->orden_id; ?>">
		      			<div class="btn">
		        			<span>Archivo</span>
		        			<input type="file" name="url">
		      			</div>
		      			<div class="file-path-wrapper">
		        			<input class="file-path validate" id="file_cotizacion" type="text">
		      			</div>
		    		</div>
    			</form>
      		</div>
    	</div>
	    <div class="modal-footer">
	    	<button type="button" id="add_cotizacion" class="waves-effect waves-light btn">Guardar</button>
	      	<button  class="modal-close waves-effect waves-light red btn">Cerrar</button>
	    </div>
  	</div>


  	<div id="modal2" class="modal modal-fixed-footer">
	    <div class="modal-content">
	      	<h4>Comparativa</h4>
	      	<div class="row">
	    		<form action="/panel/requestaddcomparativaordendecompra" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_file_comparativa">
				    <div class="file-field col m12 s12 input-field">
				    	<input type="hidden" name="titulo_comparativa" value="Comparativa">
				    	<input type="hidden" name="id_solicitud" value="<?php echo $this->orden_id; ?>">
				      	<div class="btn">
				        	<span>Archivo</span>
				        	<input type="file" name="url">
				      	</div>
				      	<div class="file-path-wrapper">
				        	<input class="file-path validate" id="file_comparativa" type="text">
				      	</div>
				    </div>
	    		</form>
	      	</div>
	    </div>
	    <div class="modal-footer">
	    	<button type="button" id="add_comparativa" class="waves-effect waves-light btn">Guardar</button>
	      	<button  class="modal-close waves-effect waves-light red btn">Cerrar</button>
	    </div>
  	</div>


  	<div id="modal3" class="modal modal-fixed-footer">
    	<div class="modal-content">
      		<span style="font-size:24px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Solicitud Orden Compra</span>
      		<div class="row" style="margin-top: 20px;">
      		<form action="/panel/requestaupdatesolicitudordencompra" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_file_altan">
	      		<?php foreach ($this->informacion as $key){ ?>
	      			<div>
	      				<input type="hidden" name="id" value="<?php echo $key['id']; ?>">
	      			</div>


				  	<div class="input-field col m6 s12">
				    	<select id="sitio" name="sitio">
				      		<option value="0" disabled>* Selecciona un Sitio</option>
				      		<?php if($key['sitio_id'] == "0"){?>
				      			<option value="oficina" selected>Oficina</option>
				      		<?php }else{ ?>
				      			<option value="oficina">Oficina</option>
				      		<?php } ?>

				      		<?php if($key['sitio_id'] == "10000000"){?>
				      			<option value="almacen" selected>Stock Almacén</option>
				      		<?php }else{ ?>
				      			<option value="almacen" >Stock Almacén</option>
				      		<?php } ?>

					    	<?php foreach ($this->sitios as $mar) { 
					     		if ($mar['id']==$key['sitio_id']) { ?>
					                <option value="<?php echo $mar["id"]; ?>" selected><?php echo $mar["nombre"]; ?></option>
					     	<?php } if ($mar['id']!=$key['sitio_id']) { ?>
					                <option value="<?php echo $mar["id"]; ?>" ><?php echo $mar["nombre"]; ?></option>
					     	<?php } } ?>  
				    	</select>
				    	<label>Sitio:</label>
				  	</div>

				    <div class="input-field col m6 s12">
				        <input id="datepicker" name="fecha" type="text" value="<?php echo $key['fecha_requerida']; ?>" class="datepicker">
				        <label for="datepicker">* Fecha Requerida</label>
				    </div>

				  	<div class="input-field col m6 s12">
				    	<select id="proveedor" name="proveedor">
				      		<option value="0" disabled selected>* Selecciona un Proveedor</option>
					    	<?php foreach ($this->proveedor as $prov) { 
					     		if ($prov['id']==$key['proveedor_id']) { ?>
					               <option value="<?php echo $prov["id"]; ?>" selected><?php echo $prov["nombre_prov"]; ?></option>
					     	<?php } if ($prov['id']!=$key['proveedor_id']) { ?>
					               <option value="<?php echo $prov["id"]; ?>" ><?php echo $prov["nombre_prov"]; ?></option>
					     	<?php } } ?> 
				    	</select>
				    	<label>Proveedor:</label>
				  	</div>

				  	<div class="input-field col m6 s12">
				    	<select id="servicio" name="servicio"> 
				      		<option value="0" disabled selected>* Selecciona un Servicio</option>
					    	<?php foreach ($this->servicio as $serv) { 
					     		if ($serv['id']==$key['servicio_id']) { ?>
					                <option value="<?php echo $serv["id"]; ?>" selected><?php echo $serv["nombre_servicio"]; ?></option>
					     	<?php } if ($serv['id']!=$key['servicio_id']) { ?>
					                <option value="<?php echo $serv["id"]; ?>" ><?php echo $serv["nombre_servicio"]; ?></option>
					     	<?php } } ?>
				    	</select>
				    	<label>Servicio:</label>
				  	</div>

	  				<div class="row">
	  					<div class="col m6 s12">
					        <div class="input-field col s12">
					        	<i class="material-icons prefix">attach_money</i>
					          	<input id="importe" name="importe" type="text" value="<?php echo $key["importe"]; ?>" class="validate">
					          	<label for="importe">* Importe:</label>
					        </div>
					        <div class="input-field col s12">
					          	<i class="material-icons prefix">assignment</i>
					          	<input id="iva" name="iva" type="text" value="<?php echo $key["iva"]; ?>" class="validate">
					          	<label for="iva">IVA:</label>
					        </div>
					        <div class="input-field col s12">
					          	<i class="material-icons prefix">assignment</i>
					          	<input id="isr" name="isr" type="text" value="<?php echo $key["retencion_isr"]; ?>" class="validate">
					          	<label for="isr">Retención ISR:</label>
					        </div>
					        <div class="input-field col s12">
					          	<i class="material-icons prefix">assignment</i>
					          	<input id="ret_iva" name="ret_iva" type="text" value="<?php echo $key["retencion_iva"]; ?>" class="validate">
					          	<label for="ret_iva">Retención IVA:</label>
					        </div>
					        <div class="input-field col s12">
					          	<i class="material-icons prefix">attach_money</i>
					          	<input id="total" name="total" value="<?php echo $key["total"]; ?>" type="text" class="validate">
					          	<label for="total">* Total:</label>
					        </div>
	  					</div>

	  					<div class="col m6 s12">
					        <div class="input-field col s12">
					          	<i class="material-icons prefix">mode_edit</i>
					          	<textarea id="compra" name="compra" value="<?php echo $key["condiciones_compra"]; ?>" class="materialize-textarea"><?php echo $key["condiciones_compra"]; ?></textarea>
					          	<label for="compra">* Condiciones de Compra</label>
					        </div>
					        <div class="input-field col s12">
					          	<i class="material-icons prefix">mode_edit</i>
					          	<textarea id="referencia" name="referencia" class="materialize-textarea"><?php echo $key["referencia"]; ?></textarea>
					          	<label for="referencia">Referencia</label>
					        </div>
			        		<div class="input-field col s12">
			          			<i class="material-icons prefix">assignment</i>
			          			<textarea id="descripcion" name="descripcion" value="<?php echo $key["descripcion"]; ?>" class="materialize-textarea"> <?php echo $key["descripcion"]; ?></textarea>
			          			<label for="descripcion">Descripción</label>
			        		</div>
	  					</div>
	  				</div>
	      		<?php } ?>
	      	</form>
      		</div>

    	</div>
	    <div class="modal-footer">
	    	<button type="button" id="editar_comparativa" class="btn">Guardar</button>
	      	<button  class="modal-close red btn">Cerrar</button>
	    </div>
  	</div>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script type="text/javascript">
  	$( "#datepicker" ).datepicker({
		dateFormat: "dd/mm/yy",
		monthNames: [ "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" ]

	});
  </script>

	<script type="text/javascript">
    	$(document).ready(function(){
    		$('.modal').modal();
  		});

  		$("#add_cotizacion").click(function(){
  			var file =document.getElementById("file_cotizacion").value;
	    	if(file == ""){
	            swal({
	              title: "Para continuar debes agregar un archivo",
	            });
	    	}else{
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				});
	    		setTimeout(submitcotizacionfile, 1500);   
	    	}
  		});

  		function submitcotizacionfile() { document.getElementById("submit_file_cotizacion").submit() }

  		$("#add_comparativa").click(function(){
  			var file =document.getElementById("file_comparativa").value;
	    	if(file == ""){
	            swal({
	              title: "Para continuar debes agregar un archivo",
	            });
	    	}else{
	    		// swal("Felicidades!", "El archivo se subio de forma correcta!", "success"); 
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				});

	    		setTimeout(submitcomparativafile, 1500);   
	    	}
  		});

  		function submitcomparativafile() { document.getElementById("submit_file_comparativa").submit() }

    	$(".delete_cotizacion").click(function(){
    		id=$(this).data('id');
    		nombre=$(this).data('nombre');
			swal({
				title: "Estas seguro de eliminar la "+nombre+"?",
		  		icon: "warning",
		  		buttons: true,
		  		dangerMode: true,
			})
			.then((willDelete) => {
	  			if (willDelete) {
	    			swal("Bien! La "+nombre+" se elimino!", {
	      				icon: "success",
	    			});

            		var request = $.ajax({
	                	url:"/solicitud/requestdeletefilecotizacion",
	                	method:"POST",
	                	data: { id : id },
	                	processData: true,
            		});
					//-------------------end de ajax---------------------------
					//-------------peticion de respuesta de ajax------------------
		            request.done(function(response) {
		                console.log(response);//imprime lo que responde el ajax
		                window.location.reload(true);
		            });
					//-------------------end de respuesta ajax---------------------
             		return false;
	  			} else {
	    			swal("La accion fue cancelada!");
	  			}
			});
    	});

    	$(".delete_comparativa").click(function(){
    		id=$(this).data('id');
    		nombre=$(this).data('nombre');
			swal({
				title: "Estas seguro de eliminar la "+nombre+"?",
		  		icon: "warning",
		  		buttons: true,
		  		dangerMode: true,
			})
			.then((willDelete) => {
	  			if (willDelete) {
	    			swal("Bien! La "+nombre+" se elimino!", {
	      				icon: "success",
	    			});

            		var request = $.ajax({
	                	url:"/panel/requestdeletefilecomparativa",
	                	method:"POST",
	                	data: { id : id },
	                	processData: true,
            		});
					//-------------------end de ajax---------------------------
					//-------------peticion de respuesta de ajax------------------
		            request.done(function(response) {
		                console.log(response);//imprime lo que responde el ajax
		                window.location.reload(true);
		            });
					//-------------------end de respuesta ajax---------------------
             		return false;
	  			} else {
	    			swal("La accion fue cancelada!");
	  			}
			});
    	});

    	$("#end_proceso").click(function(){
    		// alert("Finalizar Proceso");
    	});

    	$("#editar_comparativa").click(function(){
			var sitio = document.getElementById("sitio").value;
			var fecha = document.getElementById("datepicker").value;
			var proveedor = document.getElementById("proveedor").value;
			var servicio = document.getElementById("servicio").value;
			var importe = document.getElementById("importe").value;
			var total = document.getElementById("total").value;
			var compra = document.getElementById("compra").value;

	    	if(sitio == 0 || fecha == "" || proveedor == 0 || importe == "" || compra == "" || total == ""){
	            swal({
	             	title: "Para continuar debes agregar informacion en los campos marcados por un '*'",
	            });
	    	}else{
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				});
	    		setTimeout(submitaltan, 1500);   
	    	}
    	});

    	function submitaltan() { document.getElementById("submit_file_altan").submit() }


    	$("#send_doc").click(function(){
    		var proveedor_opuno = document.getElementById("proveedor_opuno").value;
    		var alcance_opuno = document.getElementById("alcance_opuno").value;
    		var tiempo_opuno = document.getElementById("tiempo_uno").value;
    		var costo_opuno = document.getElementById("costo_uno").value;

    		var proveedor_opdos = document.getElementById("proveedor_opdos").value;
    		var alcance_opdos = document.getElementById("alcance_opdos").value;
    		var tiempo_opdos = document.getElementById("tiempo_dos").value;
    		var costo_opdos = document.getElementById("costo_dos").value;

    		var proveedor_optres = document.getElementById("proveedor_optres").value;
    		var alcance_optres = document.getElementById("alcance_optres").value;
    		var tiempo_optres = document.getElementById("tiempo_tres").value;
    		var costo_optres = document.getElementById("costo_tres").value;
    		var proyecto = document.getElementById("proyecto").value;
    		var file_opuno= document.getElementById("file_opuno").value;

    		if(proveedor_opuno == "" || alcance_opuno =="" || tiempo_opuno=="" || costo_opuno=="" || proyecto =="" || file_opuno== ""){
	            swal({
	             	title: "Para continuar debes agregar informacion completa de al menos columna",
	            });
    		}else{
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				});
	    		setTimeout(submitdocum, 1500); 
    		}
    	});

    	function submitdocum() { document.getElementById("submit_doc").submit() }

	</script>