<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>

<style type="text/css">
	.oculto{
		display: none;
	}
</style>



<div class="row" style="margin-top: 23px;">
	<div class="col m8 s6">
		<!-- <h3></h3> -->
	</div>
	<div class="col m4 s6 text-right">
		<a class="green btn modal-trigger" href="#modal1">+ Agregar Puesto</a>
	</div>
</div>

<div class="row">
    <div class="col m12 s12 text-center">
      <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Puestos del Personal</span>
    </div>
</div>

  <!-- Modal Structure -->
<div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
        <span style="font-size:25px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar Puestos</span>
		<div class="col m12 s12" style="margin-top: 19px;">
			<form action="/panel/requestaddpuestopersonal" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_personal">
				<div class="row">
			        <div class="input-field col m12 s12">
			          <i class="material-icons prefix">build</i>
			          <input id="name" type="text" name="name" class="validate">
			          <label for="name">Nombre del Puesto:</label>
			        </div>
		      	</div>
		    </form>
		</div>
    </div>
    <div class="modal-footer">
      	<button  id="addpersonal" class="waves-effect waves-light btn">Guardar</button>
      	<button  class="modal-close waves-effect waves-light red btn">Cerrar</button>
    </div>
</div>


<div class="row">
	<div class="col m8 s12" style="margin-top: 19px;">
    <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de Puestos</span>
	<table class="table text-left table-hover">
		<thead>
			<tr>
				<th>Nombre</th>	
				<th>Eliminar</th>
			</tr> 
		</thead>
		<?php if ($this->puesto) {
		foreach ($this->puesto as $usr) { ?>
		<tbody>
			<tr>
				<td><?php echo $usr["nombre"]; ?></td>
				<td>
					<a class="delete" data-id="<?php echo $usr["id"]; ?>" data-nombre="<?php echo $usr["nombre"]; ?>"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
				</td>
			</tr>
		</tbody>
		<?php } }else{ ?>
		<tbody>
			<tr>
				<td>No se ha agregado ningun puesto</td>
				<td></td>
			</tr>
		</tbody>
		<?php } ?>
	</table>
	</div>
	<div class="col m4s12"></div>
</div>


<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
               		<?php if($pagina - 1 == 0){ ?>
                    	<li class="page-item disabled">
                        	<span class="page-link">Anterior</span>
                    	</li>
               		<?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
               		<?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
               		<?php if($pagina >= $this->total): ?>
                       	<li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                       	</li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                   	<?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>


<script type="text/javascript">
	$(document).ready(function(){
    	$('.modal').modal();
  	});

    $("#addpersonal").click(function(){
        var name = document.getElementById("name").value;

        if(name == ""){
            swal({
                title: "Para agregar el puesto debes agregar el nombre",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                    icon: "success",
                    buttons: false,
            }); 
            setTimeout(submitForm, 1500);     
        }
    });

    function submitForm() {
        document.getElementById("submit_personal").submit()
    } 


    $(".delete").click(function(){
    	id=$(this).data('id');
    	nombre=$(this).data('nombre');
		swal({
			title: "Estas seguro de eliminar el puesto"+nombre+"?",
		  	icon: "warning",
		  	buttons: true,
		  	dangerMode: true,
		})
	.then((willDelete) => {
	  if (willDelete) {
                swal("Espere un momento, la información esta siendo procesada", {
                    icon: "success",
                    buttons: false,
                }); 

            var request = $.ajax({
                url:"/panel/requestdeletepuestopersonal",
                method:"POST",
                data: { id : id },
                processData: true,
            });
//-------------------end de ajax---------------------------

//-------------peticion de respuesta de ajax------------------
            request.done(function(response) {
                console.log(response);//imprime lo que responde el ajax
                // alert
                window.location.reload(true);
            });
//-------------------end de respuesta ajax---------------------
             return false;


	  } else {
	    swal("La accion fue cancelada!");
	  }
	});

    });

</script>