<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>

<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/panel/servicios" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
</div>

<div class="row">
    <div class="col m12 s12 text-center">
        <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Servicios</span>
    </div>
</div>



<div class="row">
    <div class="col m12 s12">
        <h5>Agregar Servicio</h5>
        <div class="input-field col m5 s6">
            <input placeholder="Agrega el nombre del servicio" id="servicio" type="text" class="validate">
            <label for="servicio">Servicio</label>
        </div>
        <div class="input-field col m5 s6">
            <select id="encargado" name="rol" required>
                <option value="0" disabled selected>Selecciona una opcion:</option>
                <?php foreach ($this->user as $rl) { ?>
                <option value="<?php echo $rl["id"]; ?>"><?php echo $rl["nombre"]; ?></option>
                <?php } ?>
            </select>
            <label>Auditor:</label>
        </div>
        <div class="input-field col m2 s12 text-center">
            <a class="btn" id="add_servicio"><i class="material-icons right">add</i>Agregar</a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col m12 s12">
        <span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Servicios de Solicitudes de orden de compra</span>
        <!-- <h3></h3> -->
        <table class="table text-left table-hover">
            <thead>
                <tr>
                    <th>Nombre del Servico</th> 
                    <th>Auditor</th>    
                    <th>Editar</th>
                    <th>Eliminar</th>
                </tr> 
            </thead>
            <?php
            if ($this->servicio) { 
            foreach ($this->servicio as $usr) { ?>
            <tbody>
                <tr>
                    <td><?php echo $usr["nombre_servicio"]; ?></td>
                    <td><?php echo $usr["nombre"]; ?></td>
                    <td>
                        <a href="/panel/servicioedit/id/<?php echo $usr["id"] ?>"><i class="fa fa-2x fa-edit"></i></a>
                    </td>
                <td>
                    <a class="delete" data-id="<?php echo $usr["id"]; ?>" data-nombre="<?php echo $usr["nombre_servicio"]; ?>"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
                </td>
                </tr>
            <?php } }else{ ?>
            </tbody> 
            <tbody>
                <tr>
                    <td class="text-center" colspan="6"><h3>No hay servicios registrados.</h3></td>
                </tr>
            </tbody>
                        
            <?php } ?>
        </table>
    </div>
</div>


<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
                    <?php if($pagina - 1 == 0){ ?>
                        <li class="page-item disabled">
                            <span class="page-link">Anterior</span>
                        </li>
                    <?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
                    <?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
                    <?php if($pagina >= $this->total): ?>
                        <li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                        </li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>


<script type="text/javascript">

    $(document).ready(function(){
        $('.modal').modal();
    });

    $("#add_servicio").click(function(){
        var servicio = document.getElementById("servicio").value;
        var encargado = document.getElementById("encargado").value;
        if(servicio == ""){
            swal({
                title: "Para agregar un servicio debes agregar una nombre",
            });
        }else{
            swal({
                title: "Estas seguro de agregar la informacion",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
              if (willDelete) {
                swal("Bien!  la informacion se agrego correctamente!", {
                  icon: "success",
                });

                    var request = $.ajax({
                        url:"/panel/requestaddserviciocatalogo",
                        method:"POST",
                        data: { servicio:servicio, encargado:encargado },
                        processData: true,
                        // contentType: false,
                    });
        //-------------------end de ajax---------------------------

        //-------------peticion de respuesta de ajax------------------
                    request.done(function(response) {
                        console.log(response);//imprime lo que responde el ajax
                        // alert
                        window.location.reload(true);
                    });
        //-------------------end de respuesta ajax---------------------
                     return false;


              } else {
                swal("La accion fue cancelada!");
              }
            });   
        }

    });


    $("#servicio_update").click(function(){
        var servicio = document.getElementById("servicio_edit").value;
        var id = document.getElementById("servicio_id").value;
        // alert(servicio);
        if(servicio == ""){
            swal({
                title: "Para editar un servicio debes agregar una nombre",
            });
        }else{
            swal({
                title: "Estas seguro de agregar la informacion",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
              if (willDelete) {
                swal("Bien!  la informacion se agrego correctamente!", {
                  icon: "success",
                });

                    var request = $.ajax({
                        url:"/panel/requestupdateserviciocatalogo",
                        method:"POST",
                        data: { servicio:servicio, id:id },
                        processData: true,
                        // contentType: false,
                    });
        //-------------------end de ajax---------------------------

        //-------------peticion de respuesta de ajax------------------
                    request.done(function(response) {
                        console.log(response);//imprime lo que responde el ajax
                        // alert
                        window.location.reload(true);
                    });
        //-------------------end de respuesta ajax---------------------
                     return false;


              } else {
                swal("La accion fue cancelada!");
              }
            });   
        }

    });

    $(".delete").click(function(){
        id=$(this).data('id');
        nombre=$(this).data('nombre');
        swal({
            title: "Estas seguro de eliminar el servicio "+nombre+"?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
    .then((willDelete) => {
      if (willDelete) {
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            var request = $.ajax({
                url:"/panel/requestdeleteservicioscatalogo",
                method:"POST",
                data: { id : id },
                processData: true,
            });
//-------------------end de ajax---------------------------

//-------------peticion de respuesta de ajax------------------
            request.done(function(response) {
                console.log(response);//imprime lo que responde el ajax
                // alert
                window.location.reload(true);
            });
//-------------------end de respuesta ajax---------------------
             return false;


      } else {
        swal("La accion fue cancelada!");
      }
    });

    });
</script>

