

<div class="row" style="margin-top: 10px;">
	<div class="col m12 s12 text-center">
		<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Servicios</span>
	</div>
</div>

<div class="row">
	<div class="col m6 s12">
	  	<div class="row">
	    	<div class="col s12 m12">
	      		<div class="card">
	        		<div class="card-image">
	          			<img src="/img/proceso_solicitudes.jpg">
	          			<span class="card-title"></span>
	          			<a href="/panel/serviciossolicitudes"  class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">open_in_new</i></a>
	        		</div>
	        		<div class="card-content text-center">
	          			<span style="font-size:19px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Solicitudes de orden de compra</span>
	        		</div>
	      		</div>
	    	</div>
	  	</div>	
	</div>
	<div class="col m6 s12">
	  	<div class="row">
	    	<div class="col s12 m12">
	      		<div class="card">
	        		<div class="card-image">
	          			<img src="/img/comprobaciones1.jpg">
	          			<span class="card-title"></span>
	          			<a href="/panel/servicioscomprobaciones" class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">open_in_new</i></a>
	        		</div>
	        		<div class="card-content text-center">
	        			<div style="margin-top: 25px;"></div>
	          			<span style="font-size:19px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
	          				Comprobaciones
	          			</span>
	        		</div>
	      		</div>
	    	</div>
	  	</div>	
	</div>
</div>
