<style type="text/css">
    #map {
        height: 370px; 
        width: 370px;  
    }
    #camara_div{
    	height: 370px; 
        width: 370px;  
    }
    .oculto{
    	display: none;
    }

	#lightbox {
		display: flex;
		flex-direction: column-reverse;    
	}
#modal1 .modal {
      height: 100%;
  }

  	.title_info{
  		font-size: 15px;
  		font-weight: bold;
  	}

</style>



<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="/panel/sitios" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>

    <div class="col m6 s6 text-right">
    	<h4><a class="modal-trigger" href="#modal_coordenadas" style="color:#039be5;"><i class="fa fa-map-marker"></i> Mostrar Dirección y Coordenadas</a></h4>
    </div>
</div>



<div class="row">
    <div class="col m12 s12 text-center">
    	<?php foreach ($this->sitiodetail as $sitdet) { ?>
      		<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $sitdet["nombre"]; ?></span>
      	<?php } ?>
    </div>
</div>


  <!-- Modal Structure -->
  <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
      	<span style="font-size:25px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Editar sitio</span>
		<form action="/panel/requestupdatesitiosinfo" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_sitios">
			<?php foreach ($this->sitiodetail as $usr) { ?>
			<input type="hidden" name="ids" value="<?php echo $usr["id"]; ?>">
				<div class="row" style="margin-top: 20px;">
			        <div class="input-field col m12 s12">
			          <i class="material-icons prefix">account_circle</i>
			          <input id="name" type="text" name="nombre" value="<?php echo $usr["nombre"]; ?>" class="validate" required>
			          <label for="name">* Nombre:</label>
			        </div>
			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">chevron_right</i>
			          <input id="id_cliente" type="text" name="id_cliente" value="<?php echo $usr["id_cliente"]; ?>" class="validate" required>
			          <label for="id_cliente">* Id cliente:</label>
			        </div>
			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">place</i>
			          <input id="direccion" type="text" name="direccion" class="validate" value="<?php echo $usr["direccion"]; ?>" required>
			          <label for="direccion">Dirección:</label>
			        </div>
			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">account_circle</i>
			          <input id="cliente" type="text" name="cliente" class="validate" value="<?php echo $usr["cliente"]; ?>" required>
			          <label for="cliente">Cliente:</label>
			        </div>
			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">place</i>
			          <input id="ciudad" type="text" name="ciudad" class="validate" value="<?php echo $usr["ciudad"]; ?>" required>
			          <label for="ciudad">Ciudad:</label>
			        </div>
			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">place</i>
			          <input id="estado" type="text" name="estado" class="validate" value="<?php echo $usr["estado"]; ?>">
			          <label for="estado">Estado:</label>
			        </div>
			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">place</i>
			          <input id="region" type="text" name="region" class="validate" value="<?php echo $usr["region"]; ?>">
			          <label for="region">Region:</label>
			        </div>
			        <div class="input-field col m6 s12">
					    <select name="estructura">
			               <?php foreach ($this->estructura_sitio as $mar) { 
			                if ($mar['id']==$usr['estructura']) { ?>
			                    <option value="<?php echo $mar["id"]; ?>" selected><?php echo $mar["nombre_estructura"]; ?></option>
			                <?php } if ($mar['id']!=$usr['estructura']) { ?>
			                    <option value="<?php echo $mar["id"]; ?>" ><?php echo $mar["nombre_estructura"]; ?></option>
			                <?php } } ?>  
					    </select>
					    <label>Tipo de torre</label>
			        </div>

			        <div class="input-field col m6 s12">
			        	<i class="material-icons prefix">business</i>
			          	<input id="edificio" type="text" name="edificio" value="<?php echo $usr["edificio"]; ?>" class="validate">
			          	<label for="edificio">Edificio:</label>
			        </div>

			        <div class="input-field col m6 s12">
					    <select name="tipo_sitio">
					    	<?php if($usr["tipo_sitio"] == "Rooftop"){ ?>
						    	<option value="Rooftop" selected>Rooftop</option>
						    	<option value="Rawland">Rawland</option>
					    	<?php }else{ ?>
						    	<option value="Rooftop">Rooftop</option>
						    	<option value="Rawland" selected>Rawland</option>
					    	<?php } ?>
					    </select>
					    <label>Tipo de Sitio</label>
			        </div>


			        <div class="input-field col m6 s12">
			          <i class="material-icons prefix">place</i>
			          <input id="altura" type="text" name="altura" class="validate" value="<?php echo $usr["altura"]; ?>">
			          <label for="altura">Altura:</label>
			        </div>
			        <div class="input-field col m6 s12">

			        	<h4>Latitud:</h4>
			        	<div class="row">
			        		<div class="col m3 s3">
			        			<input id="grados_lat" type="text" name="grados_lat" placeholder="Grados" class="validate">
			        		</div>
			        		<div class="col m3 s3">
			        			<input id="min_lat" type="text" name="min_lat" placeholder="Minutos" class="validate">
			        		</div>
			        		<div class="col m3 s3">
			        			<input id="seg_lat" type="text" name="seg_lat" placeholder="Segundos" class="validate">
			        		</div>

			        		<div class="col m3 s3">
							    <select name="coordenada1">
							    	<?php if($usr["coor_lat"] == "n"){ ?>
								      <option value="n" selected>N</option>
								      <option value="s">S</option>
							    	<?php }else{ ?>
								      <option value="n">N</option>
								      <option value="s" selected>S</option>
							    	<?php } ?>
							    </select>
			        		</div>
			        	</div>

			        		<input id="latitude" type="text" name="latitude" class="validate" value="<?php echo $usr["latitude"]; ?>">
			        </div>


			        <div class="input-field col m6 s12">
			        	<h4>Longitud:</h4>
			        	<div class="row">
			        		<div class="col m3 s3">
			        			<input id="grados_lon" type="text" name="grados_lon" placeholder="Grados" class="validate">
			        		</div>
			        		<div class="col m3 s3">
			        			<input id="min_lon" type="text" name="min_lon" placeholder="Minutos" class="validate">
			        		</div>
			        		<div class="col m3 s3">
			        			<input id="seg_lon" type="text" name="seg_lon" placeholder="Segundos" class="validate">
			        		</div>

			        		<div class="col m3 s3">
							    <select name="coordenada2">
							    	<?php if($usr["coor_lon"] == "e"){ ?>
								      <option value="e" selected>E</option>
								      <option value="o">O</option>
							    	<?php }else{ ?>
								      <option value="e">E</option>
								      <option value="o" selected>O</option>
							    	<?php } ?>
							    </select>
			        		</div>
			        	</div>

			          		<input id="longitude" type="text" name="longitude" class="validate" value="<?php echo $usr["longitude"]; ?>">
			        </div>
		      	</div>

			<?php } ?>

			</form>

    </div>
    <div class="modal-footer">
    	<button id="editsitios" class="waves-effect waves-light btn">Actualizar</button>
		<a class="modal-close waves-effect red waves-light btn">Cancelar</a>
    </div>
  </div>

<div class="row">
	<div class="col m12 s12">

		<div class="row">
			<div class="col m5 s12 text-center">
				<div id="map"></div>
				<a class="example-image-link" href="/img/broadcast-tower-lease-buyouts.jpg" data-lightbox="example-1"><img class="example-image oculto" src="/img/broadcast-tower-lease-buyouts.jpg" id="camara_div" alt="image-1" /></a>
			</div>

		<div class="col m7 s12 mt-5">

  <div class="row" style=" margin-top: 3px;">
    <div class="col s12 m12">
      <div class="card ">
        <div class="card-content t">
          <!-- <span >Información General del Sitio</span> -->
          <span class="card-title" style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información General del Sitio</span>
				<div class="row">
					<div class="col m6 s12">
						<?php foreach ($this->sitiodetail as $usr) { ?>
							<div class="col m12 s12" style="margin-top: 25px;">
								<span class="title_info">Id Cliente:</span> <span><?php echo $usr["id_cliente"]; ?></span>
							</div>

							<div class="col m12 s12" style="margin-top: 7px;">
								<span class="title_info">Cliente:</span> <span><?php echo $usr["cliente"]; ?></span>
							</div>
						<?php } ?>

						<?php foreach ($this->estructura as $usr) { ?>
							<div class="col m12 s12" style="margin-top: 7px;">
								<span class="title_info">Tipo de torre:</span> <span><?php echo $usr["nombre_estructura"]; ?></span>
							</div>
						<?php } ?>
					</div>

					<div class="col m6 s12">
						<?php foreach ($this->sitiodetail as $usr) { ?>
							<div class="col m12 s12" style="margin-top: 25px;">
								<span class="title_info">Tipo sitio:</span> <span><?php echo $usr["tipo_sitio"]; ?></span>
							</div>
							<div class="col m12 s12" style="margin-top: 7px;">
								<span class="title_info">Altura:</span> <span><?php echo $usr["altura"]; ?></span>
							</div>

							<div class="col m12 s12" style="margin-top: 7px;">
								<span class="title_info">Edificio:</span> <span><?php echo $usr["edificio"]; ?></span>
							</div>
						<?php } ?>
					</div>
				</div>

				<div class="row">
					<div class="col m12 s12">
					<?php foreach ($this->sitiodetail as $usr) { ?>
						<div class="col m12 s12" style="margin-top: 25px;">
							<span class="title_info">Dirección:</span> <span><?php echo $usr["direccion"]; ?></span>
						</div>
					<?php } ?>
					</div>	
				</div>
        </div>
        <div class="card-action text-right">
        	<?php if($this->rol_user == 13 || $this->rol_user == 2 || $this->rol_user == 4){ ?>
        	<?php }else{ ?>
	        	<h4>
	        		<a class="modal-trigger" href="#modal1" style="color:#039be5;"><i class="fa  fa-edit"></i> Editar Información </a>
	        	</h4>
        	<?php } ?>

<!--           <a href="#">This is a link</a>
          <a href="#">This is a link</a> -->
        </div>
      </div>
    </div>
  </div>

			</div>
		</div>
	</div>

	<div class="col m6 s12">
	</div>
</div>

	<div class="col m12 s12" style="margin-top: 15px;">
		<div class="row">
			<div class="col m6 s4">
				<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Proyectos asignados</span>
			</div>
			<div class="col m6 s8 text-right">
				<?php if($this->rol_user == 13 || $this->rol_user == 2 || $this->rol_user == 17 || $this->rol_user == 4 || $this->rol_user == 7){ ?>
				<?php }else{ ?>
					<a class="waves-effect red btn modal-trigger text-left" href="#modal_proyectos">+ Asignacion de proyectos</a>
				<?php } ?>
			</div>
		</div>
	</div>


  <div id="modal_proyectos" class="modal modal-fixed-footer">
    <div class="modal-content">
    	<span style="font-size:24px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar un proyecto</span>
      <!-- <h2></h2> -->
		<div class="col m12 s12" style="margin-top: 20px;">
			<form action="/panel/requestaddproyectositio" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="form_user">
				<div class="row">
					<input type="hidden" name="sitio" value="<?php echo $this->id_sitio; ?>">
			        <div class="input-field col m6 s12">
			        	<i class="material-icons prefix">account_circle</i>
					    <select name="tipo_proyecto" id="id_proyecto">
					      	<option value="0" disabled selected>* Tipos de proyecto:</option>
					      	<?php foreach ($this->tipo as $rl) { ?>
					      	<option value="<?php echo $rl["id"]; ?>"><?php echo $rl["nombre_proyecto"]; ?></option>
					      	<?php } ?>					      	
					    </select>
					    <label>Tipos de proyectos</label>
			        </div>

			        <div class="input-field col m6 s12">
<!-- 			          	<i class="material-icons prefix">date_range</i>
			          	<input id="fecha_inicio" placeholder="dd/mm/yyyy" type="text" name="fecha_inicio">
			          	<label for="fecha_inicio">Fecha de Inicio:</label> -->
			          	<input type="date" name="fecha_inicio" id="fecha_inicio">
			        </div>
			        <div class="input-field col m6 s12">
			        	<i class="material-icons prefix">account_circle</i>
					    <select name="residente">
					      	<option value="0" disabled selected>Selecciona una opcion:</option>
					      	<?php foreach ($this->residentes as $res) { ?>
					      	<option value="<?php echo $res["id"]; ?>"><?php echo $res["nombre"]; ?> <?php echo $res["apellido_pa"]; ?> <?php echo $res["apellido_ma"]; ?></option>
					      	<?php } ?>					      	
					    </select>
					    <label>Residentes</label>
			        </div>

			        <div class="input-field col m6 s12">
			          	<i class="material-icons prefix">account_circle</i>
			          	<input id="id_operador" placeholder="Ingrese el id del operador" type="text" name="id_operador" >
			          	<label for="operador">Id operador:</label>
			        </div>

			        <div class="input-field col m6 s12">
			          	<i class="material-icons prefix">account_circle</i>
			          	<input id="operador" placeholder="Ingrese el nombre del operador" type="text" name="operador" class="validate">
			          	<label for="operador">Operador:</label>
			        </div>

			        <div class="input-field col m6 s12">
			          	<i class="material-icons prefix">account_circle</i>
			          	<input id="pm_cliente" placeholder="Ingrese el nombre de PM cliente" type="text" name="pm_cliente" >
			          	<label for="operador">PM cliente:</label>
			        </div>

			        <div class="input-field col m6 s12">
			        	<i class="material-icons prefix">account_circle</i>
					    <select name="coordinador">
					      	<option value="" disabled selected> Coordinadores:</option>
					      	<?php foreach ($this->coordinador as $rl) { ?>
					      	<option value="<?php echo $rl["id"]; ?>"><?php echo $rl["nombre"]; ?></option>
					      	<?php } ?>					      	
					    </select>
					    <label>Coordinador</label>
			        </div>
			        <div class="input-field col m6 s12">
			        	<i class="material-icons prefix">account_circle</i>
					    <select name="ingproyecto">
					      	<option value="0" disabled selected>Ingenieros de proyecto:</option>
					      	<?php foreach ($this->ing as $rl) { ?>
					      	<option value="<?php echo $rl["id"]; ?>"><?php echo $rl["nombre"]; ?></option>
					      	<?php } ?>					      	
					    </select>
					    <label>Ingeniero de proyecto</label>
			        </div>

			        <div class="input-field col m6 s12">
			          	<input id="data_cliente" placeholder="Ingrese el id del operador" type="date" name="fecha_cliente" >
			          	<label for="data_cliente">* Fecha Requerida por el cliente:</label>
			        </div>

		      	</div>
		</div>
		</form>

    </div>
    <div class="modal-footer">
      	<button tyle="submit" id="add_proyectositio" class="waves-effect waves-light btn">Guardar</button>
      	<button  class="modal-close waves-effect waves-light red btn">Cerrar</button>
    </div>
  </div>


<!-- ================================================================================================= -->

  <div id="modal_coordenadas" class="modal modal-fixed-footer">
    <div class="modal-content">
      <span style="font-size:25px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Dirección y Coordenadas</span>
		<div class="col m6 s12" style="margin-top: 20px;">
			<?php foreach ($this->sitiodetail as $usr) { ?>
				<div>
					<span class="title_info">Latitude:</span> <span><?php echo $usr["latitude"]; ?></span>
				</div>

				<div style="margin-top: 7px;">
					<span class="title_info">Longitude:</span> <span><?php echo $usr["longitude"]; ?></span>
				</div>

				<div style="margin-top: 7px;">
					<span class="title_info">Región:</span> <span><?php echo $usr["region"]; ?></span>
				</div>

				<div style="margin-top: 7px;">
					<span class="title_info">Direccion:</span> <span><?php echo $usr["direccion"]; ?></span>
				</div>

				<div style="margin-top: 7px;">
					<span class="title_info">Ciudad:</span> <span><?php echo $usr["ciudad"]; ?></span>
				</div>				

				<div style="margin-top: 7px;">
					<span class="title_info">Estado:</span> <span><?php echo $usr["estado"]; ?></span>
				</div>					
			<?php } ?>	
		</div>
		<div class="col m6 s12">
			<div style="margin-top: 30px;">
				<img src="/img/logo-2.png" style="width: 320px;">
			</div>
		</div>
    </div>
    <div class="modal-footer">
      	<button  class="modal-close  red btn">Cerrar</button>
    </div>
  </div>


<div class="row">
	<div class="col m12 s12">
		<div class="row">
			<table class="table text-left table-hover responsive-table">
				<thead>
					<tr>
						<table class="table text-left table-hover ">
							<thead>
								<tr>
									<th>Proyecto</th>	
									<th>Status Gps</th>
									<th>Status cliente</th>
									<th>Coordinador</th>
									<th>Ing. Proyecto</th>
									<th>Porcentaje</th>
								</tr> 
							</thead>
							<?php foreach ($this->tipos as $usr) { ?>
							<tbody>
								<tr>
									<td><a href="/panel/asignardetallesview/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><?php echo $usr["nombre_proyecto"]; ?></a></td>
									<td><span style="color: black;"><?php echo $usr["statusproyecto"]; ?></span></td>
									<td><span style="color: black;"><?php echo $usr["statuscliente"]; ?></span></td>
									<td><span style="color: black;"><?php echo $usr["nombre_coordinador"]; ?> </span></td>
									<td><span style="color: black;"><?php echo $usr["nombre_ingproyecto"]; ?></span></td>

									<td class="text-center">
										<?php if($usr["porcentaje_proyecto"] == NULL){ ?>
											<div class="progress">
	      										<div class="determinate orange" style="width: 0%"></div>
	  										</div>
	  										0%
										<?php }else{ ?>
											<div class="progress">
	      										<div class="determinate orange" style="width: <?php echo $usr["porcentaje_proyecto"]; ?>%"></div>
	  										</div>
	  										<?php echo $usr["porcentaje_proyecto"]; ?>%
										<?php } ?>



									</td>
									<?php if($this->rol_user == 13 || $this->rol_user == 17 || $this->rol_user == 4){ ?>
									<?php }else{ ?>
									<?php if($usr["id_tipoproyecto"] == 1){ ?>
										<td>
											<a href="/panel/asignardetalles/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-folder-open"></i></a>
										</td>

									<?php } ?>	

									<?php if($usr["id_tipoproyecto"] == 2){ ?>
										<td>
											<a href="/panel/detallescolocacion/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-folder-open"></i></a>
										</td>
									<?php } ?>

									<?php if($usr["id_tipoproyecto"] == 3){ ?>
										<td>
											<a href="/panel/detallesreforzamiento/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-folder-open"></i></a>
										</td>
									<?php } ?>	


									<?php if($usr["id_tipoproyecto"] == 4){ ?>
										<td>
											<a href="/panel/detallescambiotorre/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-folder-open"></i></a>
										</td>
									<?php } ?>	

									<?php if($usr["id_tipoproyecto"] == 5){ ?>
										<td>
											<a href="/panel/detallestorrenueva/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-folder-open"></i></a>
										</td>
									<?php } ?>	
											
									<?php } ?>


									<?php if($this->rol_user == 17){ ?>
									<?php if($usr["id_tipoproyecto"] == 5){ ?>
										<td>
											<a href="/panel/detallestorrenueva/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-folder-open"></i></a>
										</td>
									<?php } ?>	

									<?php }else{ ?>
									<?php } ?>

									
									<?php if($this->rol_user == 13 || $this->rol_user == 2 || $this->rol_user == 17 || $this->rol_user == 4 || $this->rol_user == 7){ ?>
<!-- 										<td>
											<a href="/panel/asignardetallesview/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-id-card-o"></i></a>	
										</td>
 -->

									<?php }else{ ?>
										<td>
											<a href="/panel/detallesproyecto/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-id-card-o"></i></a>	
										</td>
										<td>
											<a href="/panel/sitiosdetailedit/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-edit"></i></a>
										</td>
									<?php } ?>

									<?php if($this->rol_user != 13 || $this->rol_user != 2 || $this->rol_user != 17 || $this->rol_user != 4 || $this->rol_user == 7){ ?>
										<?php if($usr["id_tipoproyecto"] == 1){ ?>
											<td><a href="/grafica/btsproject/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-bar-chart"></i></a></td>
										<?php } ?>

										<?php if($usr["id_tipoproyecto"] == 2){ ?>
											<td><a href="/grafica/colocacionproject/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-bar-chart"></i></a></td>
										<?php } ?>

										<?php if($usr["id_tipoproyecto"] == 3){ ?>
											<td><a href="/grafica/reforzamientoproject/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-bar-chart"></i></a></td>
										<?php } ?>

										<?php if($usr["id_tipoproyecto"] == 4){ ?>
											<td><a href="/grafica/cambiotorreproject/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-bar-chart"></i></a></td>
										<?php } ?>

										<?php if($usr["id_tipoproyecto"] == 5){ ?>
											<td><a href="/grafica/torrenuevaproject/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-bar-chart"></i></a></td>
										<?php } ?>

										<?php if($usr["id_tipoproyecto"] == 6){ ?>
											<td><a href="/grafica/mapeotorreproject/id/<?php echo $this->id_sitio; ?>/proyecto/<?php echo $usr["id_tipoproyecto"]; ?>/sitio/<?php echo $usr["idtipo"]; ?>"><i class="fa fa-2x fa-bar-chart"></i></a></td>
										<?php } ?>

									<?php } ?>
								</tr>
							</tbody>
							<?php } ?>
						</table>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>


<input type="hidden" id="latitude" value="<?php echo $this->latitude; ?>">
<input type="hidden" id="longitude"  value="<?php echo $this->longitude; ?>">


<script defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyATUo4TcyPlXnq2ry_FWKIqT-KN5K4jVbU&callback=initMap"> </script>
<script type="text/javascript">
	var latitude = document.getElementById("latitude").value;
	function initMap() {
		var uluru = {lat: <?php echo $this->latitude; ?>, lng: <?php echo $this->longitude; ?>};
		var map = new google.maps.Map(
		document.getElementById('map'), {zoom: 16, center: uluru});
		var marker = new google.maps.Marker({position: uluru, map: map});
	}

    var marker = new google.maps.Marker({
        position: {lat: <?php echo $this->latitude; ?>, lng: <?php echo $this->longitude; ?>},
        map: map,
		title: 'Acuario de Gijón'
    });

</script>


<script src="/js/lightbox.js"></script>
	<script type="text/javascript">

	document.addEventListener('DOMContentLoaded', function() {
	    var elems = document.querySelectorAll('.datepicker');
	    var instances = M.Datepicker.init(elems,{});
	    var elems = document.querySelectorAll('.modal');
	    var instances = M.Modal.init(elems);
	});

	$(document).ready(function(){
	    $('.modal').modal();
	    $('select').formSelect();
	    // $('#fecha_inicio').datepicker( {"format":'dd-mm-yyyy'});
	});

	$("#camera").click(function(){
	  	$("#camara_div").show();
	  	$("#map").hide();
	});

	$("#place_map").click(function(){
	  	$("#camara_div").hide();
	  	$("#map").show();
	});


    $(".img").wrap('<div class="alt-wrap"/>');

    $(".img").each(function() {
        $(this).after('<p class="alt">' + $(this).attr('alt') + '</p>');
    });


    lightbox.option({
      'resizeDuration': 200,
      'wrapAround': true
    });

     $("#editsitios").click(function(){
    	var id_cliente = document.getElementById("id_cliente").value;

    	if(id_cliente == ""){
            swal({
              title: "Para continuar debes agregar informacion en los campos marcados con un * ",
            });
    	}else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
    		setTimeout(editarsubmit, 1500);   
    	}
    });

    function editarsubmit() { document.getElementById("submit_sitios").submit() }


    $("#add_proyectositio").click(function(){
     	var tipo = document.getElementById("id_proyecto").value;
        var fecha = document.getElementById("data_cliente").value;

        if(tipo == 0 || fecha == "" ){
            swal({
                title: "Para continuar es necesario llenar los campos marcados por un '*'",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            });    
            setTimeout(submitForm, 1500);     
        }

    });

    function submitForm() {
        document.getElementById("form_user").submit()
    }
</script>


