<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="/panel/statustipo/id/<?php echo $this->tipo; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
</div>

<div class="row">
    <div class="col m12 s12 text-center">
      <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Editar status del Proyecto</span>
    </div>
</div>


<div class="col m12 s12" style="margin-top: 18px;">
	<form action="/panel/requestupdatestatusproyecto" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_personal">
		<input type="hidden" name="id_proyecto" value="<?php echo $this->id_proyecto; ?>">
		<?php foreach ($this->proyecto as $key){ ?>
			<div class="row">
			    <div class="input-field col m6 s12">
			      	<i class="material-icons prefix">assignment</i>
			        <input id="status" type="text" name="status" class="validate" value="<?php echo $key['nombre_status']; ?>">
			        <label for="status">Nombre status:</label>
			    </div>

			    <div class="input-field col m6 s12">
			      	<i class="material-icons prefix">assignment</i>
			        <input id="prioridad" type="text" name="prioridad" class="validate" value="<?php echo $key['prioridad']; ?>">
			        <label for="prioridad">Prioridad:</label>
			    </div>
		    </div>
		 	<input type="hidden" name="status_proyecto" value="<?php echo $key['tipo_proyecto']; ?>">
		<?php } ?>
	</form>
</div>

<div class="input-field col m12 s12 text-right">
	<div class="row">
		<a href="/panel/personal" class="waves-effect red waves-light btn">Cancelar</a>
		<button id="addpersonal" class="waves-effect waves-light btn">Actualizar</button>
	</div>	
</div>

<script type="text/javascript">
    $("#addpersonal").click(function(){
     	var status = document.getElementById("status").value;
        var prioridad = document.getElementById("prioridad").value;

	swal({
	  title: "Estas seguro de editar el status?",
	  icon: "warning",
	  buttons: true,
	  dangerMode: true,
	})
	.then((willDelete) => {
	  if (willDelete) {
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			});  
			setTimeout(submitForm, 1500); 

	  } else {
	    swal("La asignacion fue cancelada!");
	  }
	});
    });

    function submitForm() {
        document.getElementById("submit_personal").submit()
    } 




</script>