
<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="/panel/statusproyecto" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
    <div class="col m6 s6 text-right">
    	<a class="waves-effect green btn modal-trigger" href="#modal1">+ Agregar status</a>
    </div>
</div>



<div class="row">
    <div class="col m12 s12 text-center">
      <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Status del Proyecto</span>
    </div>
</div>


  <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
    	<span style="font-size:25px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar Status</span>
      <!-- <h2></h2> -->
		<div class="col m12 s12" style="margin-top: 10px;">
			<form action="/panel/requestaddstatusproyecto" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="form_user">
				<input type="hidden" name="id_proyecto" value="<?php echo $this->id_proyecto; ?>">
				<div class="row">
			        <div class="input-field col m6 s12">
			        	<i class="material-icons prefix">assignment</i>
			          	<input id="icon_prefix" type="text" name="name" class="validate" required>
			          	<label for="icon_prefix">Nombre status:</label>
			        </div>

			        <div class="input-field col m6 s12">
			        	<i class="material-icons prefix">assignment</i>
			          	<input id="prioridad" type="text" name="prioridad" class="validate" required>
			          	<label for="prioridad">Prioridad:</label>
			        </div>
		      	</div>
		</div>
    </div>
    <div class="modal-footer">
      	<button tyle="submit" id="add_user" class="btn">Guardar</button>
      	</form>
      	<button  class="modal-close red btn">Cerrar</button>
    </div>
  </div>
<!-- ================================================================================================= -->

<div class="col m10 s12" style="margin-top: 15px;">
	<!-- <h3></h3> -->
	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de Proyectos</span>
	<table class="table text-left table-hover">
		<thead>
			<tr>
				<th>Tipo proyecto</th>		
				<th>Prioridad</th>
			</tr> 
		</thead>
		<?php
		if ($this->proyecto) { 
		foreach ($this->proyecto as $usr) { ?>
		<tbody>
			<tr>
				<td><?php echo $usr["nombre_status"]; ?></td>
				<td><?php echo $usr["prioridad"]; ?></td>
				<td>
					<a href="/panel/statustipoedit/id/<?php echo $usr["id"]?>/tipo/<?php echo $this->id_proyecto; ?>"><i class="fa fa-2x fa-edit"></i></a>
				</td>
				<td>
					<a class="delete_status" data-id="<?php echo $usr["id"]; ?>" data-proyecto="<?php echo $this->id_proyecto; ?>"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
				</td>
			</tr>
	    <?php } }else{ ?>
	    </tbody> 
	    <tbody>
	        <tr>
	            <td class="text-center" colspan="6"><h3>No hay status registrados.</h3></td>
	        </tr>
	    </tbody>
	                
	    <?php } ?>
	</table>
</div>



<script type="text/javascript">
  	$(document).ready(function(){
    	$('.modal').modal();
    	$('select').formSelect();
  	});

    $(".delete_status").click(function(){
    	var id = $(this).data('id');
    	var proyecto = $(this).data('proyecto');
	swal({
	  title: "Estas seguro de eliminar el status?",
	  icon: "warning",
	  buttons: true,
	  dangerMode: true,
	})
	.then((willDelete) => {
	  if (willDelete) {
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			});  
            var request = $.ajax({
                url:"/panel/requestdeletestatusproyecto",
                method:"POST",
                data: { id : id, proyecto: proyecto},
                processData: true,
                // contentType: false,
            });
//-------------------end de ajax---------------------------
//-------------peticion de respuesta de ajax------------------
            request.done(function(response) {
                console.log(response);//imprime lo que responde el ajax
                // alert
                window.location.reload(true);
            });
//-------------------end de respuesta ajax---------------------
             return false;
      
	  } else {
	    swal("La asignacion fue cancelada!");
	  }
	});
    });
</script>
