<div class="row mt-4">
	<div class="col m4 s12 text-center">
		<!-- <h2>Status del Proyecto</h2> -->
	</div>
	<div class="col m8 s12 text-center" style="margin-top: 15px;">
		<div class="row">
			<div class="col m12 s12  text-right">
				<a class="waves-effect green btn modal-trigger" href="#modal1">+ Agregar status</a>
			</div>
		</div>
	</div>
</div>

<div class="row">
    <div class="col m12 s12 text-center">
      <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Estructuras de los sitios</span>
    </div>
</div>


  <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
    	<span style="font-size:25px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar Status</span>
      <!-- <h2></h2> -->
		<div class="col m12 s12">
			<form action="/panel/requestaddstatusproyecto" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="form_user">
				<input type="hidden" name="id_proyecto" value="<?php echo $this->id_proyecto; ?>">
				<div class="row">
			        <div class="input-field col m6 s12">
			        	<i class="material-icons prefix">assignment</i>
			          	<input id="icon_prefix" type="text" name="name" class="validate" required>
			          	<label for="icon_prefix">Nombre status:</label>
			        </div>

			        <div class="input-field col m6 s12">
			        	<i class="material-icons prefix">assignment</i>
			          	<input id="prioridad" type="text" name="prioridad" class="validate" required>
			          	<label for="prioridad">Prioridad:</label>
			        </div>
		      	</div>
		</div>
    </div>
    <div class="modal-footer">
      	<button tyle="submit" id="add_user" class="waves-effect waves-light btn">Guardar</button>
      	</form>
      	<button  class="modal-close waves-effect waves-light red btn">Cerrar</button>
    </div>
  </div>
<!-- ================================================================================================= -->

<div class="col m10 s12" style="margin-top: 15px;">
	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de Proyectos</span>
	<!-- <h3></h3> -->
	<table class="table text-left table-hover">
		<thead>
			<tr>
				<th>Tipo proyecto</th>		
				<th>Descripcion</th>
				<th>Status</th>
			</tr> 
		</thead>
		<?php
		if ($this->tipo) { 
		foreach ($this->tipo as $usr) { ?>
		<tbody>
			<tr>
				<td><?php echo $usr["nombre_proyecto"]; ?></td>
				<td><?php echo $usr["descripcion"]; ?></td>
				<td>
					<a href="/panel/statustipo/id/<?php echo $usr["id"]?>"><i class="fa fa-2x fa-share"></i></a>
				</td>
			</tr>
	    <?php } }else{ ?>
	    </tbody> 
	    <tbody>
	        <tr>
	            <td class="text-center" colspan="6"><h3>No hay status registrados.</h3></td>
	        </tr>
	    </tbody>
	                
	    <?php } ?>
	</table>
</div>



<script type="text/javascript">
  	$(document).ready(function(){
    	$('.modal').modal();
    	$('select').formSelect();
  	});
</script>
