<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>


<div class="row mt-4">
  <div class="col m4 s12 text-center">
    <h2></h2>
  </div>

  <div class="col m8 s12 text-center" style="margin-top: 15px;">
    <div class="row">
      <div class="col m12 s12 text-right">
        <a class="waves-effect green btn modal-trigger" href="#modal1">+ Agregar Proyecto</a>
      </div>
    </div>
    
  </div>
</div>


<div class="row">
    <div class="col m12 s12 text-center">
      <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Tipo de Proyecto</span>
    </div>
</div>



<div class="row">
	<div class="col m2 s12"></div>
	<div class="col m8 s12">
		<form action="/panel/searchtipoproyecto" enctype="multipart/form-data" class="form-horizontal form-material">
	        <div class="input-field col m8 s8">
	          <input placeholder="Ingresa tipo de proyecto" name="nombre" id="first_name" type="text" class="validate">
	          <label for="first_name">Buscar por el tipo de proyecto</label>
	        </div>
	        <div class="input-field col m4 s4">
	        	<button tyle="submit" id="add_user" class="waves-effect waves-light btn">Buscar <i class="material-icons left">search</i></button>
	        </div>
    	</form>
	</div>
	<div class="col m2 s12"></div>
</div>


  <!-- Modal Structure -->
  <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
      <div class="row">
        <span style="font-size:25px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar Proyecto</span>
      </div>
      <!-- <h2>Agregar Proyecto</h2> -->
  		<div class="col m12 s12">
  			<form action="/panel/requestaddtipoproyecto" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_proyecto">
  				<div class="row">
            <div class="input-field col m12 s12">
              <i class="material-icons prefix">assignment</i>
              <input id="name" type="text" name="name" class="validate" required>
              <label for="name">* Nombre:</label>
            </div>
            <div class="input-field col m12 s12">
              <i class="material-icons prefix">event_available</i>
              <textarea id="textarea1" name="desc" class="materialize-textarea"></textarea>
              <label for="textarea1">Descripcion</label>
            </div>
  		    </div>
        </form>
  		</div>
    </div>
    <div class="modal-footer">
      	<button id="addproyecto" class="waves-effect waves-light btn">Guardar</button>
      	<button  class="modal-close waves-effect waves-light red btn">Cerrar</button>
    </div>
  </div>
<!-- ================================================================================================= -->
<div class="col m12 s12">
	<!-- <h3>Lista de Proyectos</h3> -->
  <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de Proyecto</span>
	<table class="table text-left table-hover">
		<thead>
			<tr>
				<th>Nombre del proyecto</th>		
				<th>Descripcion</th>
				<th>Status</th>
			</tr> 
		</thead>
		<?php foreach ($this->paginator as $usr) { ?>
		<tbody>
			<tr>
				<td><?php echo $usr["nombre_proyecto"]; ?></td>
				<td><?php echo $usr["descripcion"]; ?></td>

<!-- 				<td>
					<a href="/panel/statusproyecto/id/<?php echo $usr["id"] ?>"><i class="fa fa-2x fa-id-card-o"></i></a>	
				</td> -->

				<td>
					<a href="/panel/tipoproyectoedit/id/<?php echo $usr["id"] ?>"><i class="fa fa-2x fa-edit"></i></a>
				</td>
				<td>
					<a class="delete" href="/panel/requestdeleteproyecto/id/<?php echo $usr["id"]; ?>" ><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
				</td>
			</tr>
			</tbody>
		<?php } ?>
	</table>
</div>




<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
               		<?php if($pagina - 1 == 0){ ?>
                    	<li class="page-item disabled">
                        	<span class="page-link">Anterior</span>
                    	</li>
               		<?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
               		<?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
               		<?php if($pagina >= $this->total): ?>
                       	<li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                       	</li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                   	<?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>



<script type="text/javascript">
  $(document).ready(function(){
    $('.modal').modal();
     $('select').formSelect();
  });

    $(".delete").click(function(){
        var confirmar=confirm("Esta seguro que deseas eliminar");
        if(confirmar){
          window.location.reload(true);
        }else{
            alert("cancelo la solicitud");
            return false;
        }
    });

    $("#addproyecto").click(function(){
        var name = document.getElementById("name").value;

        if(name == ""){
            swal({
              title: "Para agregar un proyecto debes llenar todos los campos marcados con un '*'",
            });
        }else{
          swal("Espere un momento, la información esta siendo procesada", {
           icon: "success",
           buttons: false,
          });   
            setTimeout(submitForm, 1500);     
        }
    });


    function submitForm() {
        document.getElementById("submit_proyecto").submit()
    }
</script>
