<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="/panel/tipoproyecto" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
</div>

<div class="row">
  <div class="col m12 s12 text-center" style="margin-top: 10px;">
    <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Editar tipo de proyecto</span>
  </div>
</div>


<div class="col m12 s12">
	<div class="white-box">
		<form action="/panel/requestupdateproyecto" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_proyecto">
			<?php foreach ($this->proyecto as $usr) { ?>
			<input type="hidden" name="ids" value="<?php echo $usr["id"]; ?>">
			<div class="input-field col m12 s12">
			    <i class="material-icons prefix">account_circle</i>
			    <input id="name" type="text" name="name" class="validate" value="<?php echo $usr["nombre_proyecto"]; ?>" required>
			    <label for="name">* Nombre del Proyecto:</label>
			</div>

			<div class="input-field col m12 s12">
			    <i class="material-icons prefix">event_available</i>
			    <textarea id="textarea1" name="desc" value="<?php echo $usr["descripcion"]; ?>" class="materialize-textarea"><?php echo $usr["descripcion"]; ?></textarea>
			    <label for="textarea1">Descripcion</label>
			</div>
			<?php } ?>
		</form>
			<div class="input-field col m12 s12 text-right">
				<div class="row">
					<a href="/panel/tipoproyecto" class="waves-effect red waves-light btn">Cancelar</a>
					<button id="addproyecto" class="waves-effect waves-light btn">Actualizar</button>
				</div>	
			</div>
	</div>
</div>
</div>


<script type="text/javascript">
    $("#addproyecto").click(function(){
        var name = document.getElementById("name").value;

        if(name == ""){
            swal({
              title: "Para editar un proyecto debes llenar todos los campos marcados con un '*'",
            });
        }else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
            setTimeout(submitForm, 1500);     
        }
    });


    function submitForm() {
        document.getElementById("submit_proyecto").submit()
    }
</script>