<?php 

function eliminar_acentos($cadena){
		$cadena = str_replace(
		array('Á', 'À', 'Â', 'Ä', 'á', 'à', 'ä', 'â', 'ª'),
		array('A', 'A', 'A', 'A', 'a', 'a', 'a', 'a', 'a'),
		$cadena
		);

		$cadena = str_replace(
		array('É', 'È', 'Ê', 'Ë', 'é', 'è', 'ë', 'ê'),
		array('E', 'E', 'E', 'E', 'e', 'e', 'e', 'e'),
		$cadena );

		$cadena = str_replace(
		array('Í', 'Ì', 'Ï', 'Î', 'í', 'ì', 'ï', 'î'),
		array('I', 'I', 'I', 'I', 'i', 'i', 'i', 'i'),
		$cadena );

		$cadena = str_replace(
		array('Ó', 'Ò', 'Ö', 'Ô', 'ó', 'ò', 'ö', 'ô'),
		array('O', 'O', 'O', 'O', 'o', 'o', 'o', 'o'),
		$cadena );

		$cadena = str_replace(
		array('Ú', 'Ù', 'Û', 'Ü', 'ú', 'ù', 'ü', 'û'),
		array('U', 'U', 'U', 'U', 'u', 'u', 'u', 'u'),
		$cadena );

		$cadena = str_replace(
		array('Ñ', 'ñ', 'Ç', 'ç'),
		array('N', 'n', 'C', 'c'),
		$cadena
		);
		
		return $cadena;
	}
?>


  <style type="text/css">
  	.oculto{display: none;}
    .title-pdf{ font-weight: bold; font-size: 14px; }
  	.colorbar{ background-color: white !important; }
	.progress{
        width: 130px; height: 130px; line-height: 120px; background: none; margin: 0 auto; box-shadow: none; 
        position: relative;
    }
	.progress:after{
	    content: ""; width: 100%; height: 100%; border-radius: 50%; border: 12px solid #fff; position: absolute;
	    top: 0; left: 0;
	}
	.progress > span{ width: 50%; height: 100%; overflow: hidden; position: absolute; top: 0; z-index: 1; }
	.numero{ font-size: 23px !important; margin-left: 25px; height: 90px !important; }
	.texto{ border: 0px !important; width: 165px; margin-top: 50px !important; }	
	.progress .progress-left{ left: 0; }
	.progress .progress-bar{
	    width: 100%; height: 100%; background: none; border-width: 20px; border-style: solid; position: absolute; top: 0;
	}
	.progress .progress-left .progress-bar{
	    left: 100%; border-top-right-radius: 290px; border-bottom-right-radius: 290px; border-left: 0;
	    -webkit-transform-origin: center left; transform-origin: center left;
	}
	.progress .progress-right{ right: 0; }
	.progress .progress-right .progress-bar{
	    left: -100%; border-top-left-radius: 160px; border-bottom-left-radius: 160px; border-right: 0;
	    -webkit-transform-origin: center right; transform-origin: center right; animation: loading-1 1.8s linear forwards;
	}
	.progress .progress-value{
	    width: 90%; height: 90%; border-radius: 50%; font-size: 24px; color: #fff; line-height: 135px;
	    text-align: center; position: absolute; top: 5%;left: 5%;
	}
	.progress.blue .progress-bar{ border-color: #049dff; }
	.progress.blue .progress-left .progress-bar{ animation: loading-1 1.8s linear forwards 1.8s; }
	.progress.yellow .progress-bar{ border-color: yellow; }
	.progress.yellow .progress-left .progress-bar{ animation: loading-1 1.8s linear forwards 1.8s; }
	.progress.red .progress-bar{ border-color: red; }
	.progress.red .progress-left .progress-bar{ animation: loading-1 1.8s linear forwards 1.8s; }
	.progress.orange .progress-bar{ border-color: orange; }
	.progress.orange .progress-left .progress-bar{ animation: loading-1 1.8s linear forwards 1.8s; }
	.progress.pink .progress-bar{ border-color: #ed687c; }
	.progress.pink .progress-left .progress-bar{ animation: loading-4 1.8s linear forwards 1.8s; }
	.progress.green .progress-bar{ border-color: #1abc9c; }
	.progress.green .progress-left .progress-bar{ animation: loading-1 1.8s linear forwards 1.8s; }
	.numero{ background-color: transparent !important; border: 0px !important; width: 145px !important; }

	@keyframes loading-1{
	    0%{ -webkit-transform: rotate(0deg); transform: rotate(0deg); }
	    100%{ -webkit-transform: rotate(180deg); transform: rotate(180deg); }
	}
	@keyframes loading-2{
	    0%{ -webkit-transform: rotate(0deg); transform: rotate(0deg); }
	   	100%{ -webkit-transform: rotate(144deg); transform: rotate(144deg); }
	}
	@keyframes loading-3{
	    0%{ -webkit-transform: rotate(0deg); transform: rotate(0deg); }
	    100%{ -webkit-transform: rotate(90deg); transform: rotate(90deg); }
	}
	@keyframes loading-4{
	    0%{ -webkit-transform: rotate(0deg); transform: rotate(0deg); }
	    100%{ -webkit-transform: rotate(36deg); transform: rotate(36deg); }
	}
	@keyframes loading-5{
	    0%{ -webkit-transform: rotate(0deg); transform: rotate(0deg); }
	    100%{ -webkit-transform: rotate(126deg); transform: rotate(126deg); }
	}
	@media only screen and (max-width: 990px){ .progress{ margin-bottom: 20px; }.footer{margin-top: 200px;}
	}
  </style>

<!--  -->


<?php  $suma_enero = 0; foreach ($this->enero as $usr) { $suma_enero = $suma_enero + $usr['total']; } ?>
<?php  $suma_febrero = 0; foreach ($this->febrero as $usr) { $suma_febrero = $suma_febrero + $usr['total']; } ?>
<?php  $suma_marzo = 0; foreach ($this->marzo as $usr) { $suma_marzo = $suma_marzo + $usr['total']; } ?>
<?php  $suma_abril = 0; foreach ($this->abril as $usr) { $suma_abril = $suma_abril + $usr['total']; } ?>
<?php  $suma_mayo = 0; foreach ($this->mayo as $usr) { $suma_mayo = $suma_mayo + $usr['total']; } ?>
<?php  $suma_junio = 0; foreach ($this->junio as $usr) { $suma_junio = $suma_junio + $usr['total']; } ?>
<?php  $suma_julio = 0; foreach ($this->julio as $usr) { $suma_julio = $suma_julio + $usr['total']; } ?>
<?php  $suma_agosto = 0; foreach ($this->agosto as $usr) { $suma_agosto = $suma_agosto + $usr['total']; } ?>
<?php  $suma_septiembre = 0; foreach ($this->septiembre as $usr) { $suma_septiembre = $suma_septiembre + $usr['total']; } ?>
<?php  $suma_octubre = 0; foreach ($this->octubre as $usr) { $suma_octubre = $suma_octubre + $usr['total']; } ?>
<?php  $suma_noviembre = 0; foreach ($this->noviembre as $usr) { $suma_noviembre = $suma_noviembre + $usr['total']; } ?>
<?php  $suma_diciembre = 0; foreach ($this->diciembre as $usr) { $suma_diciembre = $suma_diciembre + $usr['total']; } ?>

<?php $suma_total = $suma_enero+ $suma_febrero+ $suma_marzo+ $suma_abril+ $suma_mayo+ $suma_junio+ $suma_julio+ $suma_agosto+$suma_septiembre+ $suma_octubre + $suma_noviembre +$suma_diciembre ;
 ?>


<?php  $sugas_enero = 0; foreach ($this->gas_enero as $usr) { $sugas_enero = $sugas_enero + $usr['importe']; } ?>
<?php  $sugas_febrero = 0; foreach ($this->gas_febrero as $usr) { $sugas_febrero = $sugas_febrero + $usr['importe']; } ?>
<?php  $sugas_marzo = 0; foreach ($this->gas_marzo as $usr) { $sugas_marzo = $sugas_marzo + $usr['importe']; } ?>
<?php  $sugas_abril = 0; foreach ($this->gas_abril as $usr) { $sugas_abril = $sugas_abril + $usr['importe']; } ?>
<?php  $sugas_mayo = 0; foreach ($this->gas_mayo as $usr) { $sugas_mayo = $sugas_mayo + $usr['importe']; } ?>
<?php  $sugas_junio = 0; foreach ($this->gas_junio as $usr) { $sugas_junio = $sugas_junio + $usr['importe']; } ?>

<?php  $sugas_julio = 0; foreach ($this->gas_julio as $usr) { $sugas_julio = $sugas_julio + $usr['importe']; } ?>
<?php  $sugas_agosto = 0; foreach ($this->gas_agosto as $usr) { $sugas_agosto = $sugas_agosto + $usr['importe']; } ?>
<?php  $sugas_septiembre = 0; foreach ($this->gas_septiembre as $usr) { $sugas_septiembre = $sugas_septiembre + $usr['importe']; } ?>
<?php  $sugas_octubre = 0; foreach ($this->gas_octubre as $usr) { $sugas_octubre = $sugas_octubre + $usr['importe']; } ?>
<?php  $sugas_noviembre = 0; foreach ($this->gas_noviembre as $usr) { $sugas_noviembre = $sugas_noviembre + $usr['importe']; } ?>
<?php  $sugas_diciembre = 0; foreach ($this->gas_diciembre as $usr) { $sugas_diciembre = $sugas_diciembre + $usr['importe']; } ?>

<?php $suma_totalgas = $sugas_enero+ $sugas_febrero+ $sugas_marzo+ $sugas_abril+ $sugas_mayo+ $sugas_junio+ $sugas_julio+ $sugas_agosto+$sugas_septiembre+ $sugas_octubre + $sugas_noviembre +$sugas_diciembre ;
 ?>



<?php  $cajachica_enero=0; foreach($this->cajachica_enero as $usr){ $cajachica_enero=$cajachica_enero+$usr['monto_comprobacion']; } ?>
<?php  $cajachica_febrero=0; foreach($this->cajachica_febrero as $usr){ $cajachica_febrero=$cajachica_febrero+$usr['monto_comprobacion']; } ?>
<?php  $cajachica_marzo=0; foreach($this->cajachica_marzo as $usr){ $cajachica_marzo=$cajachica_marzo+$usr['monto_comprobacion']; } ?>
<?php  $cajachica_abril=0; foreach($this->cajachica_abril as $usr){ $cajachica_abril=$cajachica_abril+$usr['monto_comprobacion']; } ?>
<?php  $cajachica_mayo=0; foreach($this->cajachica_mayo as $usr){ $cajachica_mayo=$cajachica_mayo+$usr['monto_comprobacion']; } ?>
<?php  $cajachica_junio=0; foreach($this->cajachica_junio as $usr){ $cajachica_junio=$cajachica_junio+$usr['monto_comprobacion']; } ?>
<?php  $cajachica_julio=0; foreach($this->cajachica_julio as $usr){ $cajachica_julio=$cajachica_julio+$usr['monto_comprobacion']; } ?>
<?php  $cajachica_agosto=0; foreach($this->cajachica_agosto as $usr){ $cajachica_agosto=$cajachica_agosto+$usr['monto_comprobacion']; } ?>
<?php  $cajachica_septiembre=0; foreach($this->cajachica_septiembre as $usr){ $cajachica_septiembre=$cajachica_septiembre+$usr['monto_comprobacion']; } ?>
<?php  $cajachica_octubre=0; foreach($this->cajachica_octubre as $usr){ $cajachica_octubre=$cajachica_octubre+$usr['monto_comprobacion']; } ?>

<?php  $cajachica_noviembre=0; 
    foreach($this->cajachica_noviembre as $usr){ 
        $cajachica_noviembre=$cajachica_noviembre+$usr['monto_comprobacion']; 
    } 
?>
<?php  $cajachica_diciembre=0; foreach($this->cajachicadiciembre as $usr){ $cajachica_diciembre=$cajachica_diciembre+$usr['monto_comprobacion']; } 

	$suma_cajachica = $cajachica_enero+ $cajachica_febrero+ $cajachica_marzo+ $cajachica_abril+ $cajachica_mayo + $cajachica_junio + $cajachica_julio + $cajachica_agosto + $cajachica_septiembre + $cajachica_octubre + $cajachica_noviembre + $cajachica_diciembre;

// N O M I N A
 $nomina_enero=0; foreach($this->nomina_enero as $usr){ $nomina_enero=$nomina_enero+$usr['monto_pago']; } ?>
<?php  $nomina_febrero=0; foreach($this->nomina_febrero as $usr){$nomina_febrero=$nomina_febrero+$usr['monto_pago']; } ?>
<?php  $nomina_marzo=0; foreach($this->nomina_marzo as $usr){ $nomina_marzo=$nomina_marzo+$usr['monto_pago']; } ?>
<?php  $nomina_abril=0; foreach($this->nomina_abril as $usr){ $nomina_abril=$nomina_abril+$usr['monto_pago']; } ?>
<?php  $nomina_mayo=0; foreach($this->nomina_mayo as $usr){ $nomina_mayo=$nomina_mayo+$usr['monto_pago']; } ?>
<?php  $nomina_junio=0; foreach($this->nomina_junio as $usr){ $nomina_junio=$nomina_junio+$usr['monto_pago']; } ?>
<?php  $nomina_julio=0; foreach($this->nomina_julio as $usr){ $nomina_julio=$nomina_julio+$usr['monto_pago']; } ?>
<?php  $nomina_agosto=0; foreach($this->nomina_agosto as $usr){ $nomina_agosto=$nomina_agosto+$usr['monto_pago']; } ?>
<?php  $nomina_septiembre=0; foreach($this->nomina_septiembre as $usr){ $nomina_septiembre=$nomina_septiembre+$usr['monto_pago']; } ?>
<?php  $nomina_octubre=0; foreach($this->nomina_octubre as $usr){ $nomina_octubre=$nomina_octubre+$usr['monto_pago']; } ?>

<?php  $nomina_noviembre=0; 
    foreach($this->nomina_noviembre as $usr){ 
        $nomina_noviembre=$nomina_noviembre+$usr['monto_pago']; 
    } 
?>
<?php  $nomina_diciembre=0; foreach($this->nomina_diciembre as $usr){ $nomina_diciembre=$nomina_diciembre+$usr['monto_pago']; } 

	$suma_nomina = $nomina_enero+ $nomina_febrero+ $nomina_marzo+ $nomina_abril+ $nomina_mayo + $nomina_junio + $nomina_julio + $nomina_agosto + $nomina_septiembre + $nomina_octubre + $nomina_noviembre + $nomina_diciembre;
?>
<!-- // E N D  N O M I N A -->


<!-- C A R G O S  T A G -->

<?php  $tag_enero=0; foreach($this->tag_enero as $usr){ $tag_enero=$tag_enero+$usr['importe']; } ?>
<?php  $tag_febrero=0; foreach($this->tag_febrero as $usr){ $tag_febrero=$tag_febrero+$usr['importe']; } ?>
<?php  $tag_marzo=0; foreach($this->tag_marzo as $usr){ $tag_marzo=$tag_marzo+$usr['importe']; } ?>
<?php  $tag_abril=0; foreach($this->tag_abril as $usr){ $tag_abril=$tag_abril+$usr['importe']; } ?>
<?php  $tag_mayo=0; foreach($this->tag_mayo as $usr){ $tag_mayo=$tag_mayo+$usr['importe']; } ?>
<?php  $tag_junio=0; foreach($this->tag_junio as $usr){ $tag_junio=$tag_junio+$usr['importe']; } ?>
<?php  $tag_julio=0; foreach($this->tag_julio as $usr){ $tag_julio=$tag_julio+$usr['importe']; } ?>
<?php  $tag_agosto=0; foreach($this->tag_agosto as $usr){ $tag_agosto=$tag_agosto+$usr['importe']; } ?>
<?php  $tag_septiembre=0; foreach($this->tag_septiembre as $usr){ $tag_septiembre=$tag_septiembre+$usr['importe']; } ?>
<?php  $tag_octubre=0; foreach($this->tag_octubre as $usr){ $tag_octubre=$tag_octubre+$usr['importe']; } ?>
<?php  $tag_noviembre=0; foreach($this->tag_noviembre as $usr){  $tag_noviembre=$tag_noviembre+$usr['importe']; }?>
<?php  $tag_diciembre=0; foreach($this->tag_diciembre as $usr){ $tag_diciembre=$tag_diciembre+$usr['importe']; } ?>

<?php $suma_cargastag = $tag_enero+ $tag_febrero+ $tag_marzo+ $tag_abril+ $tag_mayo+ $tag_junio+ $tag_julio+ $tag_agosto+ $tag_septiembre+ $tag_octubre + $tag_noviembre +$tag_diciembre ;
 ?>

<?php	

    $sum_enero = $suma_enero + $sugas_enero + $cajachica_enero + $nomina_enero + $tag_enero;
    $sum_feb = $suma_febrero + $sugas_febrero + $cajachica_febrero + $nomina_febrero + $tag_febrero;
    $sum_marz = $suma_marzo + $sugas_marzo + $cajachica_marzo + $nomina_marzo + $tag_marzo;
    $sum_abril = $suma_abril + $sugas_abril + $cajachica_abril + $nomina_abril + $tag_abril;
    $sum_mayo = $suma_mayo + $sugas_mayo + $cajachica_mayo + $nomina_mayo + $tag_mayo;
    $sum_junio = $suma_junio + $sugas_junio + $cajachica_junio + $nomina_junio + $tag_junio;
    $sum_julio = $suma_julio + $sugas_julio + $cajachica_julio + $nomina_julio + $tag_julio;
    $sum_agosto = $suma_agosto + $sugas_agosto + $cajachica_agosto + $nomina_agosto + $tag_agosto;
    $sum_septiembre = $suma_septiembre + $sugas_septiembre + $cajachica_septiembre + $nomina_septiembre + $tag_septiembre;
    $sum_octubre = $suma_octubre + $sugas_octubre + $cajachica_octubre + $nomina_octubre + $tag_octubre;
    $sum_noviembre = $suma_noviembre + $sugas_noviembre + $cajachica_noviembre + $nomina_noviembre + $tag_noviembre;
    $sum_diciembre = $suma_diciembre + $sugas_diciembre + $cajachica_diciembre + $nomina_diciembre + $tag_diciembre;

    $total = $suma_cajachica + $suma_totalgas + $suma_total + $suma_nomina + $suma_cargastag;
 ?>


<?php 

$count_sol = $this->count_enero + $this->count_febreo + $this->count_marzo + $this->count_abril + $this->count_mayo + $this->count_junio + $this->count_julio +$this->count_agosto + $this->count_septiembre + $this->count_octubre + $this->count_noviembre + $this->count_diciembre;

$count_cajachica = $this->count_cajachicaenero + $this->count_cajachicafebrero + $this->count_cajachicamarzo + $this->count_cajachicaabril + $this->count_cajachicamayo + $this->count_cajachicajunio + $this->count_cajachicajulio + $this->count_cajachicaagosto + $this->count_cajachicaseptiembre + $this->count_cajachicaoctubre + $this->count_cajachicanoviembre + $this->count_cajachicadiciembre;     

$count_gas = $this->count_gasenero + $this->count_gasfebrero + $this->count_gasmarzo + $this->count_gasabril + $this->count_gasmayo + $this->count_gasjunio + $this->count_gasjulio + $this->count_gasagosto + $this->count_gasseptiembre + $this->count_gasoctubre + $this->count_gasnoviembre + $this->count_gasdiciembre; 

$count_nomina = $this->count_nominaenero + $this->count_nominafebrero + $this->count_nominamarzo + $this->count_nominaabril + $this->count_nominamayo + $this->count_nominajunio + $this->count_nominajulio + $this->count_nominaagosto + $this->count_nominaseptiembre + $this->count_nominaoctubre + $this->count_nominanoviembre + $this->count_nominadiciembre; 

$count_tag = $this->count_tagenero + $this->count_tagfebrero + $this->count_tagmarzo + $this->count_tagabril + $this->count_tagmayo + $this->count_tagjunio + $this->count_tagjulio + $this->count_tagagosto + $this->count_tagseptiembre + $this->count_tagoctubre + $this->count_tagnoviembre + $this->count_tagdiciembre;
?>



<?php if($this->rol_user == 1 || $this->rol_user == 8 || $this->rol_user == 4){ ?>

<div class="row">
    <div class="col s12 m12" id="gastos_div">
	    <div class="card">
	        <div class="card-content">
	        	<div class="row">
	        		<div class="col m6 s6">
	        			<span style="font-size:23px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> Reporte de Gastos</span>
	        		</div>
	        		<div class="col m6 s6 text-right">
	        			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
	        				<!-- Total: $<?php echo number_format($total, 2, '.', ','); ?> -->
	        			</span>
	        		</div>
	        	</div>
		        <div class="row">
		        	<div class="col m4 s12 text-center">
		        		<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
		        			Cotización: $<?php echo number_format($this->suma_cotizacion, 2, '.', ','); ?> 
		        		</span>
		        	</div>

		        	<div class="col m4 s12 text-center">
		        		<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
		        			PO: $<?php echo number_format($this->suma_po, 2, '.', ','); ?> 
		        		</span>
		        	</div>

		        	<div class="col m4 s12 text-center">
		        		<span style="font-size:16px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
		        			Gastos: $<?php echo number_format($total, 2, '.', ','); ?> 
		        		</span>
		        	</div>
		        </div>

		        <?php $total_suma = $this->suma_po - $total; ?>
		        <div class="row">
		        	<div class="col m4 s12"></div>
		        	<div class="col m4 s12"></div>
		        	<div class="col m4 s12 text-center">
		        		<?php if($total_suma >= $this->suma_po){ ?>
		        		<span style="font-size:16px; color:red; letter-spacing: 0.1em; font-weight: bold;">
		        			Total: $<?php echo number_format($total_suma, 2, '.', ','); ?> 
		        		</span>		
		        		<?php }else{ ?>
		        		<span style="font-size:16px; color: green; letter-spacing: 0.1em; font-weight: bold;">
		        			Total: $<?php echo number_format($total_suma, 2, '.', ','); ?> 
		        		</span>		
		        		<?php } ?>
        		
		        	</div>
		        </div>
	        </div>
	        
	        <div class="card-action">
	        	<div class="row">
	        		<div class="col m12 s12">
	        			<canvas id="gastos" style="width: 100px;"></canvas>	
	        		</div>
	        	</div>
	        </div>
	    </div>
    </div>
</div>

<div class="row">
    <div class="col s12 m6">
	    <div class="card">
	        <div class="card-content">
	        	<div class="row">
	        		<div class="col m12 s12">
	        			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> Solicitudes de Compra</span>
	        		</div>
	        	</div>
	        </div>
	        <div class="card-action">
	        	<div class="row">

	        		<div class="col m6 s6 text-center">
	        			<span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
	        				$<?php echo number_format($suma_total, 2, '.', ','); ?>
	        			</span>

	        			<div style="margin-top: 20px;">
	        				<a class="btn green" id="exportBtn1">Excel</a><br>
	        				<span>Solicitudes</span>
	        			</div>
	        		</div>

	        		<div class="col m6 s6 text-center">
				        <div class="progress green colorbar">
				            <span class="progress-left">
				                <span class="progress-bar"></span>
				            </span>
				            <span class="progress-right">
				                <span class="progress-bar"></span>
				            </span>
				            <div class="progress-value">
				               	<h2 class="barra" style="margin-left: 45px">
				               		<input type="text" value="<?php echo $count_sol; ?>" class="numero" readonly>
				               	</h2>
				            </div>
				        </div>	
				        Total de Solicitudes
	        		</div>
	        	</div>
	        	<div class="row">
	        		<div class="col m12 s12">
	        			<canvas id="solicitudes" style="width: 100px;"></canvas>
	        		</div>
	        	</div>
	        </div>
	    </div>
    </div>

    <div class="col s12 m6">
	    <div class="card">
	        <div class="card-content">
	        	<div class="row">
	        		<div class="col m12 s12">
	        			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> Caja Chica</span>
	        		</div>
	        	</div>
	        </div>
	        <div class="card-action">
	        	<div class="row">
	        		<div class="col m6 s6 text-center">
	        			<span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
	        				$<?php echo number_format($suma_cajachica, 2, '.', ','); ?>
	        			</span>

	        			<div style="margin-top: 20px;">
	        				<div class="row"> 
<!-- 	        					<div class="col m6 s12">
	        						<a class="btn green" id="exportBtn2">Excel</a><br>
	        						<span>Solicitudes</span>	        						
	        					</div> -->
	        					<div class="col m12 s12">
	        						<a class="btn green" id="exportBtn2">Excel</a><br>
	        						<span>Facturas</span>
	        					</div>
	        				</div>
	        			</div>

	        		</div>

	        		<div class="col m6 s6 text-center">
				        <div class="progress green colorbar">
				            <span class="progress-left">
				                <span class="progress-bar"></span>
				            </span>
				            <span class="progress-right">
				                <span class="progress-bar"></span>
				            </span>
				            <div class="progress-value">
				               	<h2 class="barra" style="margin-left: 45px">
				               		<input type="text" value="<?php echo $count_cajachica; ?>" class="numero" readonly>
				               	</h2>
				            </div>
				        </div>	
				        Total de Solicitudes
	        		</div>

	        	</div>

	        	<div class="row">
	        		<div class="col m12 s12">
	        			<canvas id="cajachica" style="width: 100px;"></canvas>
	        		</div>
	        	</div> 
	        </div>
	    </div>
    </div>

    <div class="col s12 m6">
	    <div class="card">
	        <div class="card-content">
	        	<div class="row">
	        		<div class="col m12 s12">
	        			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> Carga Gasolina</span>
	        		</div>
	        	</div>
	        </div>
	        <div class="card-action">
	        	<div class="row">
	        		<div class="col m6 s6 text-center">
	        			<span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
	        				$<?php echo number_format($suma_totalgas, 2, '.', ','); ?>
	        			</span>

	        			<div style="margin-top: 10px;">
	        				<a class="btn green" id="exportBtn3">Excel</a><br>
	        				<span>Gasolina</span>
	        			</div>

	        		</div>

	        		<div class="col m6 s6 text-center">
				        <div class="progress green colorbar">
				            <span class="progress-left">
				                <span class="progress-bar"></span>
				            </span>
				            <span class="progress-right">
				                <span class="progress-bar"></span>
				            </span>
				            <div class="progress-value">
				               	<h2 class="barra" style="margin-left: 45px">
				               		<input type="text" value="<?php echo $count_gas; ?>" class="numero" readonly>
				               	</h2>
				            </div>
				        </div>	
				        Total de cargas
	        		</div>


	        	</div>
	        	<div class="row">
	        		<div class="col m12 s12">
	        			<canvas id="gasolina" style="width: 100px;"></canvas>
	        		</div>
	        	</div>
	        </div>
	    </div>
    </div>


    <div class="col s12 m6">
	    <div class="card">
	        <div class="card-content">
	        	<div class="row">
	        		<div class="col m12 s12">
	        			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nomina</span>
	        		</div>
	        	</div>
	        </div>
	        <div class="card-action">
	        	<div class="row">
	        		<div class="col m6 s6 text-center">
	        			<span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
	        				$<?php echo number_format($suma_nomina, 2, '.', ','); ?>
	        			</span>

	        			<div style="margin-top: 10px;">
	        				<a class="btn green" id="exportBtn4">Excel</a><br>
	        				<span>Nomina</span>
	        			</div>

	        		</div>

	        		<div class="col m6 s6 text-center">
				        <div class="progress green colorbar">
				            <span class="progress-left">
				                <span class="progress-bar"></span>
				            </span>
				            <span class="progress-right">
				                <span class="progress-bar"></span>
				            </span>
				            <div class="progress-value">
				               	<h2 class="barra" style="margin-left: 45px">
				               		<input type="text" value="<?php echo $count_nomina; ?>" class="numero" readonly>
				               	</h2>
				            </div>
				        </div>	
				        Total de Nomina
	        		</div>


	        	</div>
	        	<div class="row">
	        		<div class="col m12 s12">
	        			<canvas id="nominas" style="width: 100px;"></canvas>
	        		</div>
	        	</div>
	        </div>
	    </div>
    </div>


    <div class="col s12 m6">
	    <div class="card">
	        <div class="card-content">
	        	<div class="row">
	        		<div class="col m12 s12">
	        			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Consumos TAG</span>
	        		</div>
	        	</div>
	        </div>
	        <div class="card-action">
	        	<div class="row">
	        		<div class="col m6 s6 text-center">
	        			<span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
	        				$<?php echo number_format($suma_cargastag, 2, '.', ','); ?>
	        			</span>

	        			<div style="margin-top: 10px;">
	        				<a class="btn green" id="exportBtn5">Excel</a><br>
	        				<span>TAG</span>
	        			</div>

	        		</div>

	        		<div class="col m6 s6 text-center">
				        <div class="progress green colorbar">
				            <span class="progress-left">
				                <span class="progress-bar"></span>
				            </span>
				            <span class="progress-right">
				                <span class="progress-bar"></span>
				            </span>
				            <div class="progress-value">
				               	<h2 class="barra" style="margin-left: 45px">
				               		<input type="text" value="<?php echo $count_tag; ?>" class="numero" readonly>
				               	</h2>
				            </div>
				        </div>	
				        Consumos TAG
	        		</div>


	        	</div>
	        	<div class="row">
	        		<div class="col m12 s12">
	        			<canvas id="taggrafica" style="width: 100px;"></canvas>
	        		</div>
	        	</div>
	        </div>
	    </div>
    </div>

</div>
<?php } ?>


<!-- E X C E L  S O L I C I T U D E S   O R D E N   C O M P R A -->
<div class="row oculto">
	<div class="row excel-div" id="tab1">
		<table class="table text-left table-hover" >
			<thead>
				<tr>
					<th>Id Solicitud</th>
					<th>Id cliente</th>
					<th>Nombre sitio</th>
					<th>Proveedor</th>
					<th>Servicio</th>
					<th>Nombre solicitante</th>
					<th>Importe</th>
					<th>IVA</th>
					<th>Retencion IVA</th>
					<th>Retencion ISR</th>
					<th>Total</th>
					<th>Descripcion</th>
					<th>Condicion de compra</th>
					<th>Referencia</th>
					<th>Fecha Creacion</th>
					<th>Fecha Auditoria</th>
					<th>Fecha Direccion</th>
					<th>Fecha Pago</th>
					<th>Status Auditoria</th>
					<th>Status Direccion</th>
					<th>Status Pago</th>
					<th>Mes</th>
				</tr> 
			</thead>
			<?php 
			foreach ($this->enero as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["idsolicitud"]); ?></td>
					<td><?php echo eliminar_acentos($usr["id_cliente"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_prov"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_servicio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?> <?php echo eliminar_acentos($usr["apellido"]); ?></td>
					<td><?php echo $usr['importe']; ?></td>
					<td><?php echo $usr['iva']; ?></td>
					<td><?php echo $usr['retencion_iva']; ?></td>
					<td><?php echo $usr['retencion_isr']; ?></td>
					<td><?php echo $usr['total']; ?></td>
					<td><?php echo eliminar_acentos($usr["descripcion"]); ?></td>
					<td><?php echo eliminar_acentos($usr["condiciones_compra"]); ?></td>
					<td><?php echo eliminar_acentos($usr["referencia"]); ?></td>				
					<td><?php echo $usr['fecha_creacion']; ?></td>
					<td><?php echo $usr['fecha_auditoria']; ?></td>
					<td><?php echo $usr['fecha_direccion']; ?></td>
					<td><?php echo $usr['fecha_pago'] ?></td>
					<td>
						<?php if($usr['auditoria'] == 0){ ?> En Proceso <?php } ?>
						<?php if($usr['auditoria'] == 1){ ?> Autorizada <?php } ?>	
						<?php if($usr['auditoria'] == 2){ ?> Rechazada <?php } ?>			
					</td>
					<td>
						<?php if($usr['direccion'] == 0){ ?> En Proceso <?php }?>
						<?php if($usr['direccion'] == 1){ ?> Autorizada <?php }?>
						<?php if($usr['direccion'] == 2){ ?> Rechazada <?php }?>
					</td>
					<td>
						<?php if($usr['status_pago'] == 0){ ?> No Pagada <?php } ?>
						<?php if($usr['status_pago'] == 1){ ?> Pagada <?php } ?>
						<?php if($usr['status_pago'] == 2){ ?> En pagos / No liquidada <?php } ?>
					</td>
					<td>Enero</td>
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->febrero as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["idsolicitud"]); ?></td>
					<td><?php echo eliminar_acentos($usr["id_cliente"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_prov"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_servicio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?> <?php echo eliminar_acentos($usr["apellido"]); ?></td>
					<td><?php echo $usr['importe']; ?></td>
					<td><?php echo $usr['iva']; ?></td>
					<td><?php echo $usr['retencion_iva']; ?></td>
					<td><?php echo $usr['retencion_isr']; ?></td>
					<td><?php echo $usr['total']; ?></td>
					<td><?php echo eliminar_acentos($usr["descripcion"]); ?></td>
					<td><?php echo eliminar_acentos($usr["condiciones_compra"]); ?></td>
					<td><?php echo eliminar_acentos($usr["referencia"]); ?></td>				
					<td><?php echo $usr['fecha_creacion']; ?></td>
					<td><?php echo $usr['fecha_auditoria']; ?></td>
					<td><?php echo $usr['fecha_direccion']; ?></td>
					<td><?php echo $usr['fecha_pago'] ?></td>
					<td>
						<?php if($usr['auditoria'] == 0){ ?> En Proceso <?php } ?>
						<?php if($usr['auditoria'] == 1){ ?> Autorizada <?php } ?>	
						<?php if($usr['auditoria'] == 2){ ?> Rechazada <?php } ?>			
					</td>
					<td>
						<?php if($usr['direccion'] == 0){ ?> En Proceso <?php }?>
						<?php if($usr['direccion'] == 1){ ?> Autorizada <?php }?>
						<?php if($usr['direccion'] == 2){ ?> Rechazada <?php }?>
					</td>
					<td>
						<?php if($usr['status_pago'] == 0){ ?> No Pagada <?php } ?>
						<?php if($usr['status_pago'] == 1){ ?> Pagada <?php } ?>
						<?php if($usr['status_pago'] == 2){ ?> En pagos / No liquidada <?php } ?>
					</td>
					<td>Febrero</td>
				</tr>
			</tbody>
			<?php } ?>
			<?php 
			foreach ($this->marzo as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["idsolicitud"]); ?></td>
					<td><?php echo eliminar_acentos($usr["id_cliente"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_prov"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_servicio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?> <?php echo eliminar_acentos($usr["apellido"]); ?></td>
					<td><?php echo $usr['importe']; ?></td>
					<td><?php echo $usr['iva']; ?></td>
					<td><?php echo $usr['retencion_iva']; ?></td>
					<td><?php echo $usr['retencion_isr']; ?></td>
					<td><?php echo $usr['total']; ?></td>
					<td><?php echo eliminar_acentos($usr["descripcion"]); ?></td>
					<td><?php echo eliminar_acentos($usr["condiciones_compra"]); ?></td>
					<td><?php echo eliminar_acentos($usr["referencia"]); ?></td>				
					<td><?php echo $usr['fecha_creacion']; ?></td>
					<td><?php echo $usr['fecha_auditoria']; ?></td>
					<td><?php echo $usr['fecha_direccion']; ?></td>
					<td><?php echo $usr['fecha_pago'] ?></td>
					<td>
						<?php if($usr['auditoria'] == 0){ ?> En Proceso <?php } ?>
						<?php if($usr['auditoria'] == 1){ ?> Autorizada <?php } ?>	
						<?php if($usr['auditoria'] == 2){ ?> Rechazada <?php } ?>			
					</td>
					<td>
						<?php if($usr['direccion'] == 0){ ?> En Proceso <?php }?>
						<?php if($usr['direccion'] == 1){ ?> Autorizada <?php }?>
						<?php if($usr['direccion'] == 2){ ?> Rechazada <?php }?>
					</td>
					<td>
						<?php if($usr['status_pago'] == 0){ ?> No Pagada <?php } ?>
						<?php if($usr['status_pago'] == 1){ ?> Pagada <?php } ?>
						<?php if($usr['status_pago'] == 2){ ?> En pagos / No liquidada <?php } ?>
					</td>
					<td>Marzo</td>
				</tr>
			</tbody>
			<?php } ?>


			<?php 
			foreach ($this->abril as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["idsolicitud"]); ?></td>
					<td><?php echo eliminar_acentos($usr["id_cliente"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_prov"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_servicio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?> <?php echo eliminar_acentos($usr["apellido"]); ?></td>
					<td><?php echo $usr['importe']; ?></td>
					<td><?php echo $usr['iva']; ?></td>
					<td><?php echo $usr['retencion_iva']; ?></td>
					<td><?php echo $usr['retencion_isr']; ?></td>
					<td><?php echo $usr['total']; ?></td>
					<td><?php echo eliminar_acentos($usr["descripcion"]); ?></td>
					<td><?php echo eliminar_acentos($usr["condiciones_compra"]); ?></td>
					<td><?php echo eliminar_acentos($usr["referencia"]); ?></td>				
					<td><?php echo $usr['fecha_creacion']; ?></td>
					<td><?php echo $usr['fecha_auditoria']; ?></td>
					<td><?php echo $usr['fecha_direccion']; ?></td>
					<td><?php echo $usr['fecha_pago'] ?></td>
					<td>
						<?php if($usr['auditoria'] == 0){ ?> En Proceso <?php } ?>
						<?php if($usr['auditoria'] == 1){ ?> Autorizada <?php } ?>	
						<?php if($usr['auditoria'] == 2){ ?> Rechazada <?php } ?>			
					</td>
					<td>
						<?php if($usr['direccion'] == 0){ ?> En Proceso <?php }?>
						<?php if($usr['direccion'] == 1){ ?> Autorizada <?php }?>
						<?php if($usr['direccion'] == 2){ ?> Rechazada <?php }?>
					</td>
					<td>
						<?php if($usr['status_pago'] == 0){ ?> No Pagada <?php } ?>
						<?php if($usr['status_pago'] == 1){ ?> Pagada <?php } ?>
						<?php if($usr['status_pago'] == 2){ ?> En pagos / No liquidada <?php } ?>
					</td>
					<td>Abril</td>
				</tr>
			</tbody>
			<?php } ?>
			<?php 
			foreach ($this->mayo as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["idsolicitud"]); ?></td>
					<td><?php echo eliminar_acentos($usr["id_cliente"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_prov"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_servicio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?> <?php echo eliminar_acentos($usr["apellido"]); ?></td>
					<td><?php echo $usr['importe']; ?></td>
					<td><?php echo $usr['iva']; ?></td>
					<td><?php echo $usr['retencion_iva']; ?></td>
					<td><?php echo $usr['retencion_isr']; ?></td>
					<td><?php echo $usr['total']; ?></td>
					<td><?php echo eliminar_acentos($usr["descripcion"]); ?></td>
					<td><?php echo eliminar_acentos($usr["condiciones_compra"]); ?></td>
					<td><?php echo eliminar_acentos($usr["referencia"]); ?></td>				
					<td><?php echo $usr['fecha_creacion']; ?></td>
					<td><?php echo $usr['fecha_auditoria']; ?></td>
					<td><?php echo $usr['fecha_direccion']; ?></td>
					<td><?php echo $usr['fecha_pago'] ?></td>
					<td>
						<?php if($usr['auditoria'] == 0){ ?> En Proceso <?php } ?>
						<?php if($usr['auditoria'] == 1){ ?> Autorizada <?php } ?>	
						<?php if($usr['auditoria'] == 2){ ?> Rechazada <?php } ?>			
					</td>
					<td>
						<?php if($usr['direccion'] == 0){ ?> En Proceso <?php }?>
						<?php if($usr['direccion'] == 1){ ?> Autorizada <?php }?>
						<?php if($usr['direccion'] == 2){ ?> Rechazada <?php }?>
					</td>
					<td>
						<?php if($usr['status_pago'] == 0){ ?> No Pagada <?php } ?>
						<?php if($usr['status_pago'] == 1){ ?> Pagada <?php } ?>
						<?php if($usr['status_pago'] == 2){ ?> En pagos / No liquidada <?php } ?>
					</td>
					<td>Mayo</td>
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->junio as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["idsolicitud"]); ?></td>
					<td><?php echo eliminar_acentos($usr["id_cliente"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_prov"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_servicio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?> <?php echo eliminar_acentos($usr["apellido"]); ?></td>
					<td><?php echo $usr['importe']; ?></td>
					<td><?php echo $usr['iva']; ?></td>
					<td><?php echo $usr['retencion_iva']; ?></td>
					<td><?php echo $usr['retencion_isr']; ?></td>
					<td><?php echo $usr['total']; ?></td>
					<td><?php echo eliminar_acentos($usr["descripcion"]); ?></td>
					<td><?php echo eliminar_acentos($usr["condiciones_compra"]); ?></td>
					<td><?php echo eliminar_acentos($usr["referencia"]); ?></td>				
					<td><?php echo $usr['fecha_creacion']; ?></td>
					<td><?php echo $usr['fecha_auditoria']; ?></td>
					<td><?php echo $usr['fecha_direccion']; ?></td>
					<td><?php echo $usr['fecha_pago'] ?></td>
					<td>
						<?php if($usr['auditoria'] == 0){ ?> En Proceso <?php } ?>
						<?php if($usr['auditoria'] == 1){ ?> Autorizada <?php } ?>	
						<?php if($usr['auditoria'] == 2){ ?> Rechazada <?php } ?>			
					</td>
					<td>
						<?php if($usr['direccion'] == 0){ ?> En Proceso <?php }?>
						<?php if($usr['direccion'] == 1){ ?> Autorizada <?php }?>
						<?php if($usr['direccion'] == 2){ ?> Rechazada <?php }?>
					</td>
					<td>
						<?php if($usr['status_pago'] == 0){ ?> No Pagada <?php } ?>
						<?php if($usr['status_pago'] == 1){ ?> Pagada <?php } ?>
						<?php if($usr['status_pago'] == 2){ ?> En pagos / No liquidada <?php } ?>
					</td>
					<td>Junio</td>
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->julio as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["idsolicitud"]); ?></td>
					<td><?php echo eliminar_acentos($usr["id_cliente"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_prov"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_servicio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?> <?php echo eliminar_acentos($usr["apellido"]); ?></td>
					<td><?php echo $usr['importe']; ?></td>
					<td><?php echo $usr['iva']; ?></td>
					<td><?php echo $usr['retencion_iva']; ?></td>
					<td><?php echo $usr['retencion_isr']; ?></td>
					<td><?php echo $usr['total']; ?></td>
					<td><?php echo eliminar_acentos($usr["descripcion"]); ?></td>
					<td><?php echo eliminar_acentos($usr["condiciones_compra"]); ?></td>
					<td><?php echo eliminar_acentos($usr["referencia"]); ?></td>				
					<td><?php echo $usr['fecha_creacion']; ?></td>
					<td><?php echo $usr['fecha_auditoria']; ?></td>
					<td><?php echo $usr['fecha_direccion']; ?></td>
					<td><?php echo $usr['fecha_pago'] ?></td>
					<td>
						<?php if($usr['auditoria'] == 0){ ?> En Proceso <?php } ?>
						<?php if($usr['auditoria'] == 1){ ?> Autorizada <?php } ?>	
						<?php if($usr['auditoria'] == 2){ ?> Rechazada <?php } ?>			
					</td>
					<td>
						<?php if($usr['direccion'] == 0){ ?> En Proceso <?php }?>
						<?php if($usr['direccion'] == 1){ ?> Autorizada <?php }?>
						<?php if($usr['direccion'] == 2){ ?> Rechazada <?php }?>
					</td>
					<td>
						<?php if($usr['status_pago'] == 0){ ?> No Pagada <?php } ?>
						<?php if($usr['status_pago'] == 1){ ?> Pagada <?php } ?>
						<?php if($usr['status_pago'] == 2){ ?> En pagos / No liquidada <?php } ?>
					</td>
					<td>Julio</td>
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->agosto as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["idsolicitud"]); ?></td>
					<td><?php echo eliminar_acentos($usr["id_cliente"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_prov"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_servicio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?> <?php echo eliminar_acentos($usr["apellido"]); ?></td>
					<td><?php echo $usr['importe']; ?></td>
					<td><?php echo $usr['iva']; ?></td>
					<td><?php echo $usr['retencion_iva']; ?></td>
					<td><?php echo $usr['retencion_isr']; ?></td>
					<td><?php echo $usr['total']; ?></td>
					<td><?php echo eliminar_acentos($usr["descripcion"]); ?></td>
					<td><?php echo eliminar_acentos($usr["condiciones_compra"]); ?></td>
					<td><?php echo eliminar_acentos($usr["referencia"]); ?></td>				
					<td><?php echo $usr['fecha_creacion']; ?></td>
					<td><?php echo $usr['fecha_auditoria']; ?></td>
					<td><?php echo $usr['fecha_direccion']; ?></td>
					<td><?php echo $usr['fecha_pago'] ?></td>
					<td>
						<?php if($usr['auditoria'] == 0){ ?> En Proceso <?php } ?>
						<?php if($usr['auditoria'] == 1){ ?> Autorizada <?php } ?>	
						<?php if($usr['auditoria'] == 2){ ?> Rechazada <?php } ?>			
					</td>
					<td>
						<?php if($usr['direccion'] == 0){ ?> En Proceso <?php }?>
						<?php if($usr['direccion'] == 1){ ?> Autorizada <?php }?>
						<?php if($usr['direccion'] == 2){ ?> Rechazada <?php }?>
					</td>
					<td>
						<?php if($usr['status_pago'] == 0){ ?> No Pagada <?php } ?>
						<?php if($usr['status_pago'] == 1){ ?> Pagada <?php } ?>
						<?php if($usr['status_pago'] == 2){ ?> En pagos / No liquidada <?php } ?>
					</td>
					<td>Agosto</td>
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->septiembre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["idsolicitud"]); ?></td>
					<td><?php echo eliminar_acentos($usr["id_cliente"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_prov"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_servicio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?> <?php echo eliminar_acentos($usr["apellido"]); ?></td>
					<td><?php echo $usr['importe']; ?></td>
					<td><?php echo $usr['iva']; ?></td>
					<td><?php echo $usr['retencion_iva']; ?></td>
					<td><?php echo $usr['retencion_isr']; ?></td>
					<td><?php echo $usr['total']; ?></td>
					<td><?php echo eliminar_acentos($usr["descripcion"]); ?></td>
					<td><?php echo eliminar_acentos($usr["condiciones_compra"]); ?></td>
					<td><?php echo eliminar_acentos($usr["referencia"]); ?></td>				
					<td><?php echo $usr['fecha_creacion']; ?></td>
					<td><?php echo $usr['fecha_auditoria']; ?></td>
					<td><?php echo $usr['fecha_direccion']; ?></td>
					<td><?php echo $usr['fecha_pago'] ?></td>
					<td>
						<?php if($usr['auditoria'] == 0){ ?> En Proceso <?php } ?>
						<?php if($usr['auditoria'] == 1){ ?> Autorizada <?php } ?>	
						<?php if($usr['auditoria'] == 2){ ?> Rechazada <?php } ?>			
					</td>
					<td>
						<?php if($usr['direccion'] == 0){ ?> En Proceso <?php }?>
						<?php if($usr['direccion'] == 1){ ?> Autorizada <?php }?>
						<?php if($usr['direccion'] == 2){ ?> Rechazada <?php }?>
					</td>
					<td>
						<?php if($usr['status_pago'] == 0){ ?> No Pagada <?php } ?>
						<?php if($usr['status_pago'] == 1){ ?> Pagada <?php } ?>
						<?php if($usr['status_pago'] == 2){ ?> En pagos / No liquidada <?php } ?>
					</td>
					<td>Septiembre</td>
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->octubre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["idsolicitud"]); ?></td>
					<td><?php echo eliminar_acentos($usr["id_cliente"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_prov"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_servicio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?> <?php echo eliminar_acentos($usr["apellido"]); ?></td>
					<td><?php echo $usr['importe']; ?></td>
					<td><?php echo $usr['iva']; ?></td>
					<td><?php echo $usr['retencion_iva']; ?></td>
					<td><?php echo $usr['retencion_isr']; ?></td>
					<td><?php echo $usr['total']; ?></td>
					<td><?php echo eliminar_acentos($usr["descripcion"]); ?></td>
					<td><?php echo eliminar_acentos($usr["condiciones_compra"]); ?></td>
					<td><?php echo eliminar_acentos($usr["referencia"]); ?></td>				
					<td><?php echo $usr['fecha_creacion']; ?></td>
					<td><?php echo $usr['fecha_auditoria']; ?></td>
					<td><?php echo $usr['fecha_direccion']; ?></td>
					<td><?php echo $usr['fecha_pago'] ?></td>
					<td>
						<?php if($usr['auditoria'] == 0){ ?> En Proceso <?php } ?>
						<?php if($usr['auditoria'] == 1){ ?> Autorizada <?php } ?>	
						<?php if($usr['auditoria'] == 2){ ?> Rechazada <?php } ?>			
					</td>
					<td>
						<?php if($usr['direccion'] == 0){ ?> En Proceso <?php }?>
						<?php if($usr['direccion'] == 1){ ?> Autorizada <?php }?>
						<?php if($usr['direccion'] == 2){ ?> Rechazada <?php }?>
					</td>
					<td>
						<?php if($usr['status_pago'] == 0){ ?> No Pagada <?php } ?>
						<?php if($usr['status_pago'] == 1){ ?> Pagada <?php } ?>
						<?php if($usr['status_pago'] == 2){ ?> En pagos / No liquidada <?php } ?>
					</td>
					<td>Octubre</td>
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->noviembre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["idsolicitud"]); ?></td>
					<td><?php echo eliminar_acentos($usr["id_cliente"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_prov"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_servicio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?> <?php echo eliminar_acentos($usr["apellido"]); ?></td>
					<td><?php echo $usr['importe']; ?></td>
					<td><?php echo $usr['iva']; ?></td>
					<td><?php echo $usr['retencion_iva']; ?></td>
					<td><?php echo $usr['retencion_isr']; ?></td>
					<td><?php echo $usr['total']; ?></td>
					<td><?php echo eliminar_acentos($usr["descripcion"]); ?></td>
					<td><?php echo eliminar_acentos($usr["condiciones_compra"]); ?></td>
					<td><?php echo eliminar_acentos($usr["referencia"]); ?></td>				
					<td><?php echo $usr['fecha_creacion']; ?></td>
					<td><?php echo $usr['fecha_auditoria']; ?></td>
					<td><?php echo $usr['fecha_direccion']; ?></td>
					<td><?php echo $usr['fecha_pago'] ?></td>
					<td>
						<?php if($usr['auditoria'] == 0){ ?> En Proceso <?php } ?>
						<?php if($usr['auditoria'] == 1){ ?> Autorizada <?php } ?>	
						<?php if($usr['auditoria'] == 2){ ?> Rechazada <?php } ?>			
					</td>
					<td>
						<?php if($usr['direccion'] == 0){ ?> En Proceso <?php }?>
						<?php if($usr['direccion'] == 1){ ?> Autorizada <?php }?>
						<?php if($usr['direccion'] == 2){ ?> Rechazada <?php }?>
					</td>
					<td>
						<?php if($usr['status_pago'] == 0){ ?> No Pagada <?php } ?>
						<?php if($usr['status_pago'] == 1){ ?> Pagada <?php } ?>
						<?php if($usr['status_pago'] == 2){ ?> En pagos / No liquidada <?php } ?>
					</td>
					<td>Noviembre</td>
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->diciembre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["idsolicitud"]); ?></td>
					<td><?php echo eliminar_acentos($usr["id_cliente"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_prov"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre_servicio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?> <?php echo eliminar_acentos($usr["apellido"]); ?></td>
					<td><?php echo $usr['importe']; ?></td>
					<td><?php echo $usr['iva']; ?></td>
					<td><?php echo $usr['retencion_iva']; ?></td>
					<td><?php echo $usr['retencion_isr']; ?></td>
					<td><?php echo $usr['total']; ?></td>
					<td><?php echo eliminar_acentos($usr["descripcion"]); ?></td>
					<td><?php echo eliminar_acentos($usr["condiciones_compra"]); ?></td>
					<td><?php echo eliminar_acentos($usr["referencia"]); ?></td>				
					<td><?php echo $usr['fecha_creacion']; ?></td>
					<td><?php echo $usr['fecha_auditoria']; ?></td>
					<td><?php echo $usr['fecha_direccion']; ?></td>
					<td><?php echo $usr['fecha_pago'] ?></td>
					<td>
						<?php if($usr['auditoria'] == 0){ ?> En Proceso <?php } ?>
						<?php if($usr['auditoria'] == 1){ ?> Autorizada <?php } ?>	
						<?php if($usr['auditoria'] == 2){ ?> Rechazada <?php } ?>			
					</td>
					<td>
						<?php if($usr['direccion'] == 0){ ?> En Proceso <?php }?>
						<?php if($usr['direccion'] == 1){ ?> Autorizada <?php }?>
						<?php if($usr['direccion'] == 2){ ?> Rechazada <?php }?>
					</td>
					<td>
						<?php if($usr['status_pago'] == 0){ ?> No Pagada <?php } ?>
						<?php if($usr['status_pago'] == 1){ ?> Pagada <?php } ?>
						<?php if($usr['status_pago'] == 2){ ?> En pagos / No liquidada <?php } ?>
					</td>
					<td>Diciembre</td>
				</tr>
			</tbody>
			<?php } ?>


		</table>	
	</div>
</div>
<!-- E N D    E X C E L  S O L I C I T U D E S   O R D E N   C O M P R A -->

<div class="row oculto">
	<div class="row excel-div" id="tab2">
		<table class="table text-left table-hover" >
			<thead>
				<tr>
					<th>Id Factura</th>
					<th>Id Solicitud</th>
					<th>Sitio</th>
					<th>Cliente</th>
					<th>Proyecto</th>
					<th>Residente</th>
					<th>Razon social</th>
					<th>Monto Factura</th>
					<th>Factura</th>
					<th>Monto comprobacion</th>
				</tr> 
			</thead>
			<?php 
			foreach ($this->cajachica_factura as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["id_comprobacion"]); ?></td>
					<td><?php echo eliminar_acentos($usr["sitio"]); ?></td>
					<td><?php echo $usr['id_cliente']; ?></td>	
					<td><?php echo eliminar_acentos($usr["nombre_proyecto"]); ?></td>
					<td>
						<?php echo eliminar_acentos($usr["nombre"]); ?> 
						<?php echo eliminar_acentos($usr["apellido_pa"]); ?>
						<?php echo eliminar_acentos($usr["apellido_ma"]); ?>
					</td>	
					<td><?php echo eliminar_acentos($usr["razon_social"]); ?></td>	
					<td><?php echo $usr['monto_solicitud']; ?></td>	
					<td><?php echo $usr['factura']; ?></td>	
					<td><?php echo $usr['monto_comprobacion']; ?></td>		
				</tr>
			</tbody>
			<?php } ?>
		</table>	
	</div>
</div>
 <!-- E N D   E X C E L  S O L I C I T U D E S   C O M P R O B A C I O N E S  -->


<!-- E X C E L  G A S O L I N A -->
<div class="row oculto">
	<div class="row excel-div" id="tab3">
		<table class="table text-left table-hover" >
			<thead>
				<tr>
					<th>Id carga</th>
					<th>Sitio</th>
					<th>Responsable</th>
					<th>Fecha Carga</th>
					<th>Placas Vehiculo</th>
					<th>Estacion</th>
					<th>Forma Pago</th>
					<th>Importe</th>
					<th>Consumo</th>
					<th>Odometro Inicial</th>
					<th>Odometro Final</th>
					<th>Tarjeta Efecticard</th>
				</tr> 
			</thead>
			<?php 
			foreach ($this->gas_enero as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_responsable"]); ?></td>
					<td><?php echo $usr['fecha_requerida']; ?></td>	
					<td><?php echo $usr['placas']; ?></td>	
					<td><?php echo eliminar_acentos($usr["estacion"]); ?></td>
					<td>
						<?php if($usr['forma_pago']== 1){ ?> Efecticard <?php } ?>
						<?php if($usr['forma_pago']== 2){ ?> Tarjeta de Debito <?php } ?>
						<?php if($usr['forma_pago']== 3){ ?> Otra... <?php } ?>
					</td>
					<td><?php echo $usr['importe']; ?></td>	
					<td><?php echo eliminar_acentos($usr["consumo"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_inicial"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_final"]); ?></td>
					<td><?php echo $usr['tarjeta']; ?></td>					
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->gas_febrero as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_responsable"]); ?></td>
					<td><?php echo $usr['fecha_requerida']; ?></td>	
					<td><?php echo $usr['placas']; ?></td>	
					<td><?php echo eliminar_acentos($usr["estacion"]); ?></td>
					<td>
						<?php if($usr['forma_pago']== 1){ ?> Efecticard <?php } ?>
						<?php if($usr['forma_pago']== 2){ ?> Tarjeta de Debito <?php } ?>
						<?php if($usr['forma_pago']== 3){ ?> Otra... <?php } ?>
					</td>
					<td><?php echo $usr['importe']; ?></td>	
					<td><?php echo eliminar_acentos($usr["consumo"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_inicial"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_final"]); ?></td>
					<td><?php echo $usr['tarjeta']; ?></td>					
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->gas_marzo as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_responsable"]); ?></td>
					<td><?php echo $usr['fecha_requerida']; ?></td>	
					<td><?php echo $usr['placas']; ?></td>	
					<td><?php echo eliminar_acentos($usr["estacion"]); ?></td>
					<td>
						<?php if($usr['forma_pago']== 1){ ?> Efecticard <?php } ?>
						<?php if($usr['forma_pago']== 2){ ?> Tarjeta de Debito <?php } ?>
						<?php if($usr['forma_pago']== 3){ ?> Otra... <?php } ?>
					</td>
					<td><?php echo $usr['importe']; ?></td>	
					<td><?php echo eliminar_acentos($usr["consumo"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_inicial"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_final"]); ?></td>
					<td><?php echo $usr['tarjeta']; ?></td>					
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->gas_abril as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_responsable"]); ?></td>
					<td><?php echo $usr['fecha_requerida']; ?></td>	
					<td><?php echo $usr['placas']; ?></td>	
					<td><?php echo eliminar_acentos($usr["estacion"]); ?></td>
					<td>
						<?php if($usr['forma_pago']== 1){ ?> Efecticard <?php } ?>
						<?php if($usr['forma_pago']== 2){ ?> Tarjeta de Debito <?php } ?>
						<?php if($usr['forma_pago']== 3){ ?> Otra... <?php } ?>
					</td>
					<td><?php echo $usr['importe']; ?></td>	
					<td><?php echo eliminar_acentos($usr["consumo"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_inicial"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_final"]); ?></td>
					<td><?php echo $usr['tarjeta']; ?></td>					
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->gas_mayo as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_responsable"]); ?></td>
					<td><?php echo $usr['fecha_requerida']; ?></td>	
					<td><?php echo $usr['placas']; ?></td>	
					<td><?php echo eliminar_acentos($usr["estacion"]); ?></td>
					<td>
						<?php if($usr['forma_pago']== 1){ ?> Efecticard <?php } ?>
						<?php if($usr['forma_pago']== 2){ ?> Tarjeta de Debito <?php } ?>
						<?php if($usr['forma_pago']== 3){ ?> Otra... <?php } ?>
					</td>
					<td><?php echo $usr['importe']; ?></td>	
					<td><?php echo eliminar_acentos($usr["consumo"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_inicial"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_final"]); ?></td>
					<td><?php echo $usr['tarjeta']; ?></td>					
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->gas_junio as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_responsable"]); ?></td>
					<td><?php echo $usr['fecha_requerida']; ?></td>	
					<td><?php echo $usr['placas']; ?></td>	
					<td><?php echo eliminar_acentos($usr["estacion"]); ?></td>
					<td>
						<?php if($usr['forma_pago']== 1){ ?> Efecticard <?php } ?>
						<?php if($usr['forma_pago']== 2){ ?> Tarjeta de Debito <?php } ?>
						<?php if($usr['forma_pago']== 3){ ?> Otra... <?php } ?>
					</td>
					<td><?php echo $usr['importe']; ?></td>	
					<td><?php echo eliminar_acentos($usr["consumo"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_inicial"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_final"]); ?></td>
					<td><?php echo $usr['tarjeta']; ?></td>					
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->gas_julio as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_responsable"]); ?></td>
					<td><?php echo $usr['fecha_requerida']; ?></td>	
					<td><?php echo $usr['placas']; ?></td>	
					<td><?php echo eliminar_acentos($usr["estacion"]); ?></td>
					<td>
						<?php if($usr['forma_pago']== 1){ ?> Efecticard <?php } ?>
						<?php if($usr['forma_pago']== 2){ ?> Tarjeta de Debito <?php } ?>
						<?php if($usr['forma_pago']== 3){ ?> Otra... <?php } ?>
					</td>
					<td><?php echo $usr['importe']; ?></td>	
					<td><?php echo eliminar_acentos($usr["consumo"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_inicial"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_final"]); ?></td>
					<td><?php echo $usr['tarjeta']; ?></td>					
				</tr>
			</tbody>
			<?php } ?>


			<?php 
			foreach ($this->gas_agosto as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_responsable"]); ?></td>
					<td><?php echo $usr['fecha_requerida']; ?></td>	
					<td><?php echo $usr['placas']; ?></td>	
					<td><?php echo eliminar_acentos($usr["estacion"]); ?></td>
					<td>
						<?php if($usr['forma_pago']== 1){ ?> Efecticard <?php } ?>
						<?php if($usr['forma_pago']== 2){ ?> Tarjeta de Debito <?php } ?>
						<?php if($usr['forma_pago']== 3){ ?> Otra... <?php } ?>
					</td>
					<td><?php echo $usr['importe']; ?></td>	
					<td><?php echo eliminar_acentos($usr["consumo"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_inicial"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_final"]); ?></td>
					<td><?php echo $usr['tarjeta']; ?></td>					
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->gas_septiembre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_responsable"]); ?></td>
					<td><?php echo $usr['fecha_requerida']; ?></td>	
					<td><?php echo $usr['placas']; ?></td>	
					<td><?php echo eliminar_acentos($usr["estacion"]); ?></td>
					<td>
						<?php if($usr['forma_pago']== 1){ ?> Efecticard <?php } ?>
						<?php if($usr['forma_pago']== 2){ ?> Tarjeta de Debito <?php } ?>
						<?php if($usr['forma_pago']== 3){ ?> Otra... <?php } ?>
					</td>
					<td><?php echo $usr['importe']; ?></td>	
					<td><?php echo eliminar_acentos($usr["consumo"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_inicial"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_final"]); ?></td>
					<td><?php echo $usr['tarjeta']; ?></td>					
				</tr>
			</tbody>
			<?php } ?>


			<?php 
			foreach ($this->gas_octubre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_responsable"]); ?></td>
					<td><?php echo $usr['fecha_requerida']; ?></td>	
					<td><?php echo $usr['placas']; ?></td>	
					<td><?php echo eliminar_acentos($usr["estacion"]); ?></td>
					<td>
						<?php if($usr['forma_pago']== 1){ ?> Efecticard <?php } ?>
						<?php if($usr['forma_pago']== 2){ ?> Tarjeta de Debito <?php } ?>
						<?php if($usr['forma_pago']== 3){ ?> Otra... <?php } ?>
					</td>
					<td><?php echo $usr['importe']; ?></td>	
					<td><?php echo eliminar_acentos($usr["consumo"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_inicial"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_final"]); ?></td>
					<td><?php echo $usr['tarjeta']; ?></td>					
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->gas_noviembre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_responsable"]); ?></td>
					<td><?php echo $usr['fecha_requerida']; ?></td>	
					<td><?php echo $usr['placas']; ?></td>	
					<td><?php echo eliminar_acentos($usr["estacion"]); ?></td>
					<td>
						<?php if($usr['forma_pago']== 1){ ?> Efecticard <?php } ?>
						<?php if($usr['forma_pago']== 2){ ?> Tarjeta de Debito <?php } ?>
						<?php if($usr['forma_pago']== 3){ ?> Otra... <?php } ?>
					</td>
					<td><?php echo $usr['importe']; ?></td>	
					<td><?php echo eliminar_acentos($usr["consumo"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_inicial"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_final"]); ?></td>
					<td><?php echo $usr['tarjeta']; ?></td>					
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->gas_diciembre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_sitio"]); ?></td>
					<td><?php echo eliminar_acentos($usr["name_responsable"]); ?></td>
					<td><?php echo $usr['fecha_requerida']; ?></td>	
					<td><?php echo $usr['placas']; ?></td>	
					<td><?php echo eliminar_acentos($usr["estacion"]); ?></td>
					<td>
						<?php if($usr['forma_pago']== 1){ ?> Efecticard <?php } ?>
						<?php if($usr['forma_pago']== 2){ ?> Tarjeta de Debito <?php } ?>
						<?php if($usr['forma_pago']== 3){ ?> Otra... <?php } ?>
					</td>
					<td><?php echo $usr['importe']; ?></td>	
					<td><?php echo eliminar_acentos($usr["consumo"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_inicial"]); ?></td>
					<td><?php echo eliminar_acentos($usr["odometro_final"]); ?></td>
					<td><?php echo $usr['tarjeta']; ?></td>					
				</tr>
			</tbody>
			<?php } ?>

		</table>	
	</div>
</div>

<!-- E N D   E X C E L  G A S O L I N A -->


<!-- N O M I N A -->
<div class="row oculto">
	<div class="row excel-div" id="tab4">
		<table class="table text-left table-hover" >
			<thead>
				<tr>
					<th>Usuario</th>
					<th>Sitio</th>
					<th>Asistencia</th>
					<th>Hora entrada</th>
					<th>Hora salida</th>
					<th>Pago</th>
				</tr> 
			</thead>
			<?php 
			foreach ($this->nomina_enero as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["personal"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?></td>
					<td><?php echo eliminar_acentos($usr["dia"]); ?></td>
				    <td>
				        <?php if($usr['status_tipos'] == 0){ ?>
				            <?php echo eliminar_acentos($usr["hora_entrada"]); ?>
				        <?php }?>

				        <?php if($usr['status_tipos'] == 1){ ?>
				            Descuento
				        <?php }?>

				        <?php if($usr['status_tipos'] == 2){ ?>
				            Descuento Herramientas
				        <?php }?>

				        <?php if($usr['status_tipos'] == 3){ ?>
				            Descuento EPP
				        <?php }?>
				    </td>
					<td><?php echo eliminar_acentos($usr["hora_salida"]); ?></td>
					<td>$<?php echo number_format($usr["monto_pago"], 2, '.', ','); ?> </td>	
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->nomina_febrero as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["personal"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?></td>
					<td><?php echo eliminar_acentos($usr["dia"]); ?></td>
				    <td>
				        <?php if($usr['status_tipos'] == 0){ ?>
				            <?php echo eliminar_acentos($usr["hora_entrada"]); ?>
				        <?php }?>

				        <?php if($usr['status_tipos'] == 1){ ?>
				            Descuento
				        <?php }?>

				        <?php if($usr['status_tipos'] == 2){ ?>
				            Descuento Herramientas
				        <?php }?>

				        <?php if($usr['status_tipos'] == 3){ ?>
				            Descuento EPP
				        <?php }?>
				    </td>
					<td><?php echo eliminar_acentos($usr["hora_salida"]); ?></td>
					<td>$<?php echo number_format($usr["monto_pago"], 2, '.', ','); ?> </td>	
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->nomina_marzo as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["personal"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?></td>
					<td><?php echo eliminar_acentos($usr["dia"]); ?></td>
				    <td>
				        <?php if($usr['status_tipos'] == 0){ ?>
				            <?php echo eliminar_acentos($usr["hora_entrada"]); ?>
				        <?php }?>

				        <?php if($usr['status_tipos'] == 1){ ?>
				            Descuento
				        <?php }?>

				        <?php if($usr['status_tipos'] == 2){ ?>
				            Descuento Herramientas
				        <?php }?>

				        <?php if($usr['status_tipos'] == 3){ ?>
				            Descuento EPP
				        <?php }?>
				    </td>
					<td><?php echo eliminar_acentos($usr["hora_salida"]); ?></td>
					<td>$<?php echo number_format($usr["monto_pago"], 2, '.', ','); ?> </td>	
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->nomina_abril as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["personal"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?></td>
					<td><?php echo eliminar_acentos($usr["dia"]); ?></td>
				    <td>
				        <?php if($usr['status_tipos'] == 0){ ?>
				            <?php echo eliminar_acentos($usr["hora_entrada"]); ?>
				        <?php }?>

				        <?php if($usr['status_tipos'] == 1){ ?>
				            Descuento
				        <?php }?>

				        <?php if($usr['status_tipos'] == 2){ ?>
				            Descuento Herramientas
				        <?php }?>

				        <?php if($usr['status_tipos'] == 3){ ?>
				            Descuento EPP
				        <?php }?>
				    </td>
					<td><?php echo eliminar_acentos($usr["hora_salida"]); ?></td>
					<td>$<?php echo number_format($usr["monto_pago"], 2, '.', ','); ?> </td>	
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->nomina_mayo as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["personal"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?></td>
					<td><?php echo eliminar_acentos($usr["dia"]); ?></td>
				    <td>
				        <?php if($usr['status_tipos'] == 0){ ?>
				            <?php echo eliminar_acentos($usr["hora_entrada"]); ?>
				        <?php }?>

				        <?php if($usr['status_tipos'] == 1){ ?>
				            Descuento
				        <?php }?>

				        <?php if($usr['status_tipos'] == 2){ ?>
				            Descuento Herramientas
				        <?php }?>

				        <?php if($usr['status_tipos'] == 3){ ?>
				            Descuento EPP
				        <?php }?>
				    </td>
					<td><?php echo eliminar_acentos($usr["hora_salida"]); ?></td>
					<td>$<?php echo number_format($usr["monto_pago"], 2, '.', ','); ?> </td>	
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->nomina_junio as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["personal"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?></td>
					<td><?php echo eliminar_acentos($usr["dia"]); ?></td>
				    <td>
				        <?php if($usr['status_tipos'] == 0){ ?>
				            <?php echo eliminar_acentos($usr["hora_entrada"]); ?>
				        <?php }?>

				        <?php if($usr['status_tipos'] == 1){ ?>
				            Descuento
				        <?php }?>

				        <?php if($usr['status_tipos'] == 2){ ?>
				            Descuento Herramientas
				        <?php }?>

				        <?php if($usr['status_tipos'] == 3){ ?>
				            Descuento EPP
				        <?php }?>
				    </td>
					<td><?php echo eliminar_acentos($usr["hora_salida"]); ?></td>
					<td>$<?php echo number_format($usr["monto_pago"], 2, '.', ','); ?> </td>	
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->nomina_julio as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["personal"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?></td>
					<td><?php echo eliminar_acentos($usr["dia"]); ?></td>
				    <td>
				        <?php if($usr['status_tipos'] == 0){ ?>
				            <?php echo eliminar_acentos($usr["hora_entrada"]); ?>
				        <?php }?>

				        <?php if($usr['status_tipos'] == 1){ ?>
				            Descuento
				        <?php }?>

				        <?php if($usr['status_tipos'] == 2){ ?>
				            Descuento Herramientas
				        <?php }?>

				        <?php if($usr['status_tipos'] == 3){ ?>
				            Descuento EPP
				        <?php }?>
				    </td>
					<td><?php echo eliminar_acentos($usr["hora_salida"]); ?></td>
					<td>$<?php echo number_format($usr["monto_pago"], 2, '.', ','); ?> </td>	
				</tr>
			</tbody>
			<?php } ?>


			<?php 
			foreach ($this->nomina_agosto as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["personal"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?></td>
					<td><?php echo eliminar_acentos($usr["dia"]); ?></td>
				    <td>
				        <?php if($usr['status_tipos'] == 0){ ?>
				            <?php echo eliminar_acentos($usr["hora_entrada"]); ?>
				        <?php }?>

				        <?php if($usr['status_tipos'] == 1){ ?>
				            Descuento
				        <?php }?>

				        <?php if($usr['status_tipos'] == 2){ ?>
				            Descuento Herramientas
				        <?php }?>

				        <?php if($usr['status_tipos'] == 3){ ?>
				            Descuento EPP
				        <?php }?>
				    </td>
					<td><?php echo eliminar_acentos($usr["hora_salida"]); ?></td>
					<td>$<?php echo number_format($usr["monto_pago"], 2, '.', ','); ?> </td>	
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->nomina_septiembre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["personal"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?></td>
					<td><?php echo eliminar_acentos($usr["dia"]); ?></td>
				    <td>
				        <?php if($usr['status_tipos'] == 0){ ?>
				            <?php echo eliminar_acentos($usr["hora_entrada"]); ?>
				        <?php }?>

				        <?php if($usr['status_tipos'] == 1){ ?>
				            Descuento
				        <?php }?>

				        <?php if($usr['status_tipos'] == 2){ ?>
				            Descuento Herramientas
				        <?php }?>

				        <?php if($usr['status_tipos'] == 3){ ?>
				            Descuento EPP
				        <?php }?>
				    </td>
					<td><?php echo eliminar_acentos($usr["hora_salida"]); ?></td>
					<td>$<?php echo number_format($usr["monto_pago"], 2, '.', ','); ?> </td>	
				</tr>
			</tbody>
			<?php } ?>


			<?php 
			foreach ($this->nomina_octubre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["personal"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?></td>
					<td><?php echo eliminar_acentos($usr["dia"]); ?></td>
				    <td>
				        <?php if($usr['status_tipos'] == 0){ ?>
				            <?php echo eliminar_acentos($usr["hora_entrada"]); ?>
				        <?php }?>

				        <?php if($usr['status_tipos'] == 1){ ?>
				            Descuento
				        <?php }?>

				        <?php if($usr['status_tipos'] == 2){ ?>
				            Descuento Herramientas
				        <?php }?>

				        <?php if($usr['status_tipos'] == 3){ ?>
				            Descuento EPP
				        <?php }?>
				    </td>
					<td><?php echo eliminar_acentos($usr["hora_salida"]); ?></td>
					<td>$<?php echo number_format($usr["monto_pago"], 2, '.', ','); ?> </td>	
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->nomina_noviembre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["personal"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?></td>
					<td><?php echo eliminar_acentos($usr["dia"]); ?></td>
				    <td>
				        <?php if($usr['status_tipos'] == 0){ ?>
				            <?php echo eliminar_acentos($usr["hora_entrada"]); ?>
				        <?php }?>

				        <?php if($usr['status_tipos'] == 1){ ?>
				            Descuento
				        <?php }?>

				        <?php if($usr['status_tipos'] == 2){ ?>
				            Descuento Herramientas
				        <?php }?>

				        <?php if($usr['status_tipos'] == 3){ ?>
				            Descuento EPP
				        <?php }?>
				    </td>
					<td><?php echo eliminar_acentos($usr["hora_salida"]); ?></td>
					<td>$<?php echo number_format($usr["monto_pago"], 2, '.', ','); ?> </td>	
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->nomina_diciembre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["personal"]); ?></td>
					<td><?php echo eliminar_acentos($usr["nombre"]); ?></td>
					<td><?php echo eliminar_acentos($usr["dia"]); ?></td>
				    <td>
				        <?php if($usr['status_tipos'] == 0){ ?>
				            <?php echo eliminar_acentos($usr["hora_entrada"]); ?>
				        <?php }?>

				        <?php if($usr['status_tipos'] == 1){ ?>
				            Descuento
				        <?php }?>

				        <?php if($usr['status_tipos'] == 2){ ?>
				            Descuento Herramientas
				        <?php }?>

				        <?php if($usr['status_tipos'] == 3){ ?>
				            Descuento EPP
				        <?php }?>
				    </td>
					<td><?php echo eliminar_acentos($usr["hora_salida"]); ?></td>
					<td>$<?php echo number_format($usr["monto_pago"], 2, '.', ','); ?> </td>	
				</tr>
			</tbody>
			<?php } ?>

		</table>	
	</div>
</div>
<!-- E  N D  N O M I N A -->

<!-- T A G -->
<div class="row oculto">
	<div class="row excel-div" id="tab5">
		<table class="table text-left table-hover" >
			<thead>
				<tr>
					<th>ID</th>
					<th>No TAG</th>
					<th>Fecha</th>
					<th>Concesionaria</th>
					<th>Entrada</th>
					<th>Salida</th>
					<th>Importe</th>
					<th>Sitio</th>
					<th>Id Cliente</th>
					<th>Tipo Proyecto</th>

				</tr> 
			</thead>
			<?php 
			foreach ($this->tag_enero as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["tag"]); ?></td>
					<td><?php echo eliminar_acentos($usr["fecha"]); ?></td>

					<td><?php echo eliminar_acentos($usr["concesionaria"]); ?></td>
					<td><?php echo eliminar_acentos($usr["entrada"]); ?></td>
					<td><?php echo eliminar_acentos($usr["salida"]); ?></td>
					<td>$<?php echo number_format($usr["importe"], 2, '.', ','); ?> </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["id_cliente"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre_proyecto"]); ?>
				        <?php } ?>
				    </td>
						
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->tag_febrero as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["tag"]); ?></td>
					<td><?php echo eliminar_acentos($usr["fecha"]); ?></td>

					<td><?php echo eliminar_acentos($usr["concesionaria"]); ?></td>
					<td><?php echo eliminar_acentos($usr["entrada"]); ?></td>
					<td><?php echo eliminar_acentos($usr["salida"]); ?></td>
					<td>$<?php echo number_format($usr["importe"], 2, '.', ','); ?> </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["id_cliente"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre_proyecto"]); ?>
				        <?php } ?>
				    </td>
						
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->tag_marzo as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["tag"]); ?></td>
					<td><?php echo eliminar_acentos($usr["fecha"]); ?></td>

					<td><?php echo eliminar_acentos($usr["concesionaria"]); ?></td>
					<td><?php echo eliminar_acentos($usr["entrada"]); ?></td>
					<td><?php echo eliminar_acentos($usr["salida"]); ?></td>
					<td>$<?php echo number_format($usr["importe"], 2, '.', ','); ?> </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["id_cliente"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre_proyecto"]); ?>
				        <?php } ?>
				    </td>
						
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->tag_abril as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["tag"]); ?></td>
					<td><?php echo eliminar_acentos($usr["fecha"]); ?></td>

					<td><?php echo eliminar_acentos($usr["concesionaria"]); ?></td>
					<td><?php echo eliminar_acentos($usr["entrada"]); ?></td>
					<td><?php echo eliminar_acentos($usr["salida"]); ?></td>
					<td>$<?php echo number_format($usr["importe"], 2, '.', ','); ?> </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["id_cliente"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre_proyecto"]); ?>
				        <?php } ?>
				    </td>
						
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->tag_mayo as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["tag"]); ?></td>
					<td><?php echo eliminar_acentos($usr["fecha"]); ?></td>

					<td><?php echo eliminar_acentos($usr["concesionaria"]); ?></td>
					<td><?php echo eliminar_acentos($usr["entrada"]); ?></td>
					<td><?php echo eliminar_acentos($usr["salida"]); ?></td>
					<td>$<?php echo number_format($usr["importe"], 2, '.', ','); ?> </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["id_cliente"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre_proyecto"]); ?>
				        <?php } ?>
				    </td>
						
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->tag_junio as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["tag"]); ?></td>
					<td><?php echo eliminar_acentos($usr["fecha"]); ?></td>

					<td><?php echo eliminar_acentos($usr["concesionaria"]); ?></td>
					<td><?php echo eliminar_acentos($usr["entrada"]); ?></td>
					<td><?php echo eliminar_acentos($usr["salida"]); ?></td>
					<td>$<?php echo number_format($usr["importe"], 2, '.', ','); ?> </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["id_cliente"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre_proyecto"]); ?>
				        <?php } ?>
				    </td>
						
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->tag_julio as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["tag"]); ?></td>
					<td><?php echo eliminar_acentos($usr["fecha"]); ?></td>

					<td><?php echo eliminar_acentos($usr["concesionaria"]); ?></td>
					<td><?php echo eliminar_acentos($usr["entrada"]); ?></td>
					<td><?php echo eliminar_acentos($usr["salida"]); ?></td>
					<td>$<?php echo number_format($usr["importe"], 2, '.', ','); ?> </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["id_cliente"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre_proyecto"]); ?>
				        <?php } ?>
				    </td>
						
				</tr>
			</tbody>
			<?php } ?>


			<?php 
			foreach ($this->tag_agosto as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["tag"]); ?></td>
					<td><?php echo eliminar_acentos($usr["fecha"]); ?></td>

					<td><?php echo eliminar_acentos($usr["concesionaria"]); ?></td>
					<td><?php echo eliminar_acentos($usr["entrada"]); ?></td>
					<td><?php echo eliminar_acentos($usr["salida"]); ?></td>
					<td>$<?php echo number_format($usr["importe"], 2, '.', ','); ?> </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["id_cliente"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre_proyecto"]); ?>
				        <?php } ?>
				    </td>
						
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->tag_septiembre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["tag"]); ?></td>
					<td><?php echo eliminar_acentos($usr["fecha"]); ?></td>

					<td><?php echo eliminar_acentos($usr["concesionaria"]); ?></td>
					<td><?php echo eliminar_acentos($usr["entrada"]); ?></td>
					<td><?php echo eliminar_acentos($usr["salida"]); ?></td>
					<td>$<?php echo number_format($usr["importe"], 2, '.', ','); ?> </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["id_cliente"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre_proyecto"]); ?>
				        <?php } ?>
				    </td>
						
				</tr>
			</tbody>
			<?php } ?>


			<?php 
			foreach ($this->tag_octubre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["tag"]); ?></td>
					<td><?php echo eliminar_acentos($usr["fecha"]); ?></td>

					<td><?php echo eliminar_acentos($usr["concesionaria"]); ?></td>
					<td><?php echo eliminar_acentos($usr["entrada"]); ?></td>
					<td><?php echo eliminar_acentos($usr["salida"]); ?></td>
					<td>$<?php echo number_format($usr["importe"], 2, '.', ','); ?> </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["id_cliente"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre_proyecto"]); ?>
				        <?php } ?>
				    </td>
						
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->tag_noviembre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["tag"]); ?></td>
					<td><?php echo eliminar_acentos($usr["fecha"]); ?></td>

					<td><?php echo eliminar_acentos($usr["concesionaria"]); ?></td>
					<td><?php echo eliminar_acentos($usr["entrada"]); ?></td>
					<td><?php echo eliminar_acentos($usr["salida"]); ?></td>
					<td>$<?php echo number_format($usr["importe"], 2, '.', ','); ?> </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["id_cliente"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre_proyecto"]); ?>
				        <?php } ?>
				    </td>
						
				</tr>
			</tbody>
			<?php } ?>

			<?php 
			foreach ($this->tag_diciembre as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo eliminar_acentos($usr["id"]); ?></td>
					<td><?php echo eliminar_acentos($usr["tag"]); ?></td>
					<td><?php echo eliminar_acentos($usr["fecha"]); ?></td>

					<td><?php echo eliminar_acentos($usr["concesionaria"]); ?></td>
					<td><?php echo eliminar_acentos($usr["entrada"]); ?></td>
					<td><?php echo eliminar_acentos($usr["salida"]); ?></td>
					<td>$<?php echo number_format($usr["importe"], 2, '.', ','); ?> </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["id_cliente"]); ?>
				        <?php } ?>
				    </td>

				    <td>
				        <?php if($usr['id_sitio'] == 0){ ?>
				            Oficina
				        <?php } else { ?>
				        	<?php echo eliminar_acentos($usr["nombre_proyecto"]); ?>
				        <?php } ?>
				    </td>
						
				</tr>
			</tbody>
			<?php } ?>

		</table>	
	</div>
</div>
<!-- E  N D  T A G -->

    <input type="hidden" id="enero" value="<?php echo $sum_enero; ?> ">
    <input type="hidden" id="febrero" value="<?php echo $sum_feb; ?>">
    <input type="hidden" id="marzo" value="<?php echo $sum_marz; ?>">
    <input type="hidden" id="abril" value="<?php echo $sum_abril; ?>">
    <input type="hidden" id="mayo" value="<?php echo $sum_mayo; ?>">
    <input type="hidden" id="junio" value="<?php echo $sum_junio; ?>">
    <input type="hidden" id="julio" value="<?php echo $sum_julio; ?>">
    <input type="hidden" id="agosto" value="<?php echo $sum_agosto; ?>">
    <input type="hidden" id="septiembre" value="<?php echo $sum_septiembre; ?>">
    <input type="hidden" id="octubre" value="<?php echo $sum_octubre; ?>">
    <input type="hidden" id="noviembre" value="<?php echo $sum_noviembre ?>">
    <input type="hidden" id="diciembre" value="<?php echo $sum_diciembre; ?>">

<!-- Solicitudes orden Compra -->
    <input type="hidden" id="enero_sol" value="<?php echo $suma_enero; ?> ">
    <input type="hidden" id="febrero_sol" value="<?php echo $suma_febrero; ?>">
    <input type="hidden" id="marzo_sol" value="<?php echo $suma_marzo; ?>">
    <input type="hidden" id="abril_sol" value="<?php echo $suma_abril; ?>">
    <input type="hidden" id="mayo_sol" value="<?php echo $suma_mayo; ?>">
    <input type="hidden" id="junio_sol" value="<?php echo $suma_junio; ?>">
    <input type="hidden" id="julio_sol" value="<?php echo $suma_julio; ?>">
    <input type="hidden" id="agosto_sol" value="<?php echo $suma_agosto; ?>">
    <input type="hidden" id="septiembre_sol" value="<?php echo $suma_septiembre; ?>">
    <input type="hidden" id="octubre_sol" value="<?php echo $suma_octubre; ?>">
    <input type="hidden" id="noviembre_sol" value="<?php echo $suma_noviembre ?>">
    <input type="hidden" id="diciembre_sol" value="<?php echo $suma_diciembre; ?>">

<!-- Caja Chica -->
    <input type="hidden" id="enero_caja" value="<?php echo $cajachica_enero; ?> ">
    <input type="hidden" id="febrero_caja" value="<?php echo $cajachica_febrero; ?>">
    <input type="hidden" id="marzo_caja" value="<?php echo $cajachica_marzo; ?>">
    <input type="hidden" id="abril_caja" value="<?php echo $cajachica_abril; ?>">
    <input type="hidden" id="mayo_caja" value="<?php echo $cajachica_mayo; ?>">
    <input type="hidden" id="junio_caja" value="<?php echo $cajachica_junio; ?>">
    <input type="hidden" id="julio_caja" value="<?php echo $cajachica_julio; ?>">
    <input type="hidden" id="agosto_caja" value="<?php echo $cajachica_agosto; ?>">
    <input type="hidden" id="septiembre_caja" value="<?php echo $cajachica_septiembre; ?>">
    <input type="hidden" id="octubre_caja" value="<?php echo $cajachica_octubre; ?>">
    <input type="hidden" id="noviembre_caja" value="<?php echo $cajachica_noviembre ?>">
    <input type="hidden" id="diciembre_caja" value="<?php echo $cajachica_diciembre; ?>">

<!-- // GASOLINA -->
    <input type="hidden" id="enero_gas" value="<?php echo $sugas_enero; ?> ">
    <input type="hidden" id="febrero_gas" value="<?php echo $sugas_febrero; ?>">
    <input type="hidden" id="marzo_gas" value="<?php echo $sugas_marzo; ?>">
    <input type="hidden" id="abril_gas" value="<?php echo $sugas_abril; ?>">
    <input type="hidden" id="mayo_gas" value="<?php echo $sugas_mayo; ?>">
    <input type="hidden" id="junio_gas" value="<?php echo $sugas_junio; ?>">
    <input type="hidden" id="julio_gas" value="<?php echo $sugas_julio; ?>">
    <input type="hidden" id="agosto_gas" value="<?php echo $sugas_agosto; ?>">
    <input type="hidden" id="septiembre_gas" value="<?php echo $sugas_septiembre; ?>">
    <input type="hidden" id="octubre_gas" value="<?php echo $sugas_octubre; ?>">
    <input type="hidden" id="noviembre_gas" value="<?php echo $sugas_noviembre ?>">
    <input type="hidden" id="diciembre_gas" value="<?php echo $sugas_diciembre; ?>">

    <input type="hidden" id="enero_nomina" value="<?php echo $nomina_enero; ?> ">
    <input type="hidden" id="febrero_nomina" value="<?php echo $nomina_febrero; ?>">
    <input type="hidden" id="marzo_nomina" value="<?php echo $nomina_marzo; ?>">
    <input type="hidden" id="abril_nomina" value="<?php echo $nomina_abril; ?>">
    <input type="hidden" id="mayo_nomina" value="<?php echo $nomina_mayo; ?>">
    <input type="hidden" id="junio_nomina" value="<?php echo $nomina_junio; ?>">
    <input type="hidden" id="julio_nomina" value="<?php echo $nomina_julio; ?>">
    <input type="hidden" id="agosto_nomina" value="<?php echo $nomina_agosto; ?>">
    <input type="hidden" id="septiembre_nomina" value="<?php echo $nomina_septiembre; ?>">
    <input type="hidden" id="octubre_nomina" value="<?php echo $nomina_octubre; ?>">
    <input type="hidden" id="noviembre_nomina" value="<?php echo $nomina_noviembre ?>">
    <input type="hidden" id="diciembre_nomina" value="<?php echo $nomina_diciembre; ?>">

     <!-- T A G -->
    <input type="hidden" id="enero_tag" value="<?php echo $tag_enero; ?> ">
    <input type="hidden" id="febrero_tag" value="<?php echo $tag_febrero; ?>">
    <input type="hidden" id="marzo_tag" value="<?php echo $tag_marzo; ?>">
    <input type="hidden" id="abril_tag" value="<?php echo $tag_abril; ?>">
    <input type="hidden" id="mayo_tag" value="<?php echo $tag_mayo; ?>">
    <input type="hidden" id="junio_tag" value="<?php echo $tag_junio; ?>">
    <input type="hidden" id="julio_tag" value="<?php echo $tag_julio; ?>">
    <input type="hidden" id="agosto_tag" value="<?php echo $tag_agosto; ?>">
    <input type="hidden" id="septiembre_tag" value="<?php echo $tag_septiembre; ?>">
    <input type="hidden" id="octubre_tag" value="<?php echo $tag_octubre; ?>">
    <input type="hidden" id="noviembre_tag" value="<?php echo $tag_noviembre ?>">
    <input type="hidden" id="diciembre_tag" value="<?php echo $tag_diciembre; ?>">

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.js"></script>
    <script type="text/javascript">

    var enero = document.getElementById("enero").value;
    var febrero = document.getElementById("febrero").value;
    var marzo = document.getElementById("marzo").value;
    var abril = document.getElementById("abril").value;
    var mayo = document.getElementById("mayo").value;
    var junio = document.getElementById("junio").value;
    var julio = document.getElementById("julio").value;
    var agosto = document.getElementById("agosto").value;
    var septiembre = document.getElementById("septiembre").value;
    var octubre = document.getElementById("octubre").value;
    var noviembre = document.getElementById("noviembre").value;
    var diciembre = document.getElementById("diciembre").value;

	var ctx = document.getElementById('gastos').getContext('2d');
	var myChartsemanados = new Chart(ctx, {
	    type: 'bar',
	    data: {
	        labels:['Enero','Febrero','Marzo', 'Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
	        datasets: [{
	            label: 'Gastos',
	            data: [enero, febrero, marzo, abril, mayo, junio, julio, agosto, septiembre,octubre,noviembre,diciembre],
	            backgroundColor: [
	                'rgba(255, 99, 132, 0.2)',
	                'rgba(54, 162, 235, 0.2)',
	                'rgba(255, 206, 86, 0.2)',
	                'rgba(75, 192, 192, 0.2)',
	                'rgba(153, 102, 255, 0.2)',
	                'rgba(255, 159, 64, 0.2)'
	            ],
	            borderColor: [
	                'rgba(255, 99, 132, 1)',
	                'rgba(54, 162, 235, 1)',
	                'rgba(255, 206, 86, 1)',
	                'rgba(75, 192, 192, 1)',
	                'rgba(153, 102, 255, 1)',
	                'rgba(255, 159, 64, 1)'
	            ],
	            borderWidth: 1
	        }]
	    },
	    options: {
	        scales: {
	            yAxes: [{
	                ticks: {
	                    beginAtZero: true
	                }
	            }]
	        }
	    }
	});



    var enero = document.getElementById("enero_sol").value;
    var febrero = document.getElementById("febrero_sol").value;
    var marzo = document.getElementById("marzo_sol").value;
    var abril = document.getElementById("abril_sol").value;
    var mayo = document.getElementById("mayo_sol").value;
    var junio = document.getElementById("junio_sol").value;
    var julio = document.getElementById("julio_sol").value;
    var agosto = document.getElementById("agosto_sol").value;
    var septiembre = document.getElementById("septiembre_sol").value;
    var octubre = document.getElementById("octubre_sol").value;
    var noviembre = document.getElementById("noviembre_sol").value;
    var diciembre = document.getElementById("diciembre_sol").value;

	var ctx = document.getElementById('solicitudes').getContext('2d');
	var myChartsemanados = new Chart(ctx, {
	    type: 'bar',
	    data: {
	        labels:['Enero','Febrero','Marzo', 'Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
	        datasets: [{
	            label: 'Gastos',
	            data: [enero, febrero, marzo, abril, mayo, junio, julio, agosto, septiembre,octubre,noviembre,diciembre],
	            backgroundColor: [
	                'rgba(255, 99, 132, 0.2)',
	                'rgba(54, 162, 235, 0.2)',
	                'rgba(255, 206, 86, 0.2)',
	                'rgba(75, 192, 192, 0.2)',
	                'rgba(153, 102, 255, 0.2)',
	                'rgba(255, 159, 64, 0.2)'
	            ],
	            borderColor: [
	                'rgba(255, 99, 132, 1)',
	                'rgba(54, 162, 235, 1)',
	                'rgba(255, 206, 86, 1)',
	                'rgba(75, 192, 192, 1)',
	                'rgba(153, 102, 255, 1)',
	                'rgba(255, 159, 64, 1)'
	            ],
	            borderWidth: 1
	        }]
	    },
	    options: {
	        scales: {
	            yAxes: [{
	                ticks: {
	                    beginAtZero: true
	                }
	            }]
	        }
	    }
	});

    var enero = document.getElementById("enero_caja").value;
    var febrero = document.getElementById("febrero_caja").value;
    var marzo = document.getElementById("marzo_caja").value;
    var abril = document.getElementById("abril_caja").value;
    var mayo = document.getElementById("mayo_caja").value;
    var junio = document.getElementById("junio_caja").value;
    var julio = document.getElementById("julio_caja").value;
    var agosto = document.getElementById("agosto_caja").value;
    var septiembre = document.getElementById("septiembre_caja").value;
    var octubre = document.getElementById("octubre_caja").value;
    var noviembre = document.getElementById("noviembre_caja").value;
    var diciembre = document.getElementById("diciembre_caja").value;

	var ctx = document.getElementById('cajachica').getContext('2d');
	var myChartsemanados = new Chart(ctx, {
	    type: 'bar',
	    data: {
	        labels:['Enero','Febrero','Marzo', 'Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
	        datasets: [{
	            label: 'Gastos',
	            data: [enero, febrero, marzo, abril, mayo, junio, julio, agosto, septiembre,octubre,noviembre,diciembre],
	            backgroundColor: [
	                'rgba(255, 99, 132, 0.2)',
	                'rgba(54, 162, 235, 0.2)',
	                'rgba(255, 206, 86, 0.2)',
	                'rgba(75, 192, 192, 0.2)',
	                'rgba(153, 102, 255, 0.2)',
	                'rgba(255, 159, 64, 0.2)'
	            ],
	            borderColor: [
	                'rgba(255, 99, 132, 1)',
	                'rgba(54, 162, 235, 1)',
	                'rgba(255, 206, 86, 1)',
	                'rgba(75, 192, 192, 1)',
	                'rgba(153, 102, 255, 1)',
	                'rgba(255, 159, 64, 1)'
	            ],
	            borderWidth: 1
	        }]
	    },
	    options: {
	        scales: {
	            yAxes: [{
	                ticks: {
	                    beginAtZero: true
	                }
	            }]
	        }
	    }
	});

    var enero = document.getElementById("enero_gas").value;
    var febrero = document.getElementById("febrero_gas").value;
    var marzo = document.getElementById("marzo_gas").value;
    var abril = document.getElementById("abril_gas").value;
    var mayo = document.getElementById("mayo_gas").value;
    var junio = document.getElementById("junio_gas").value;
    var julio = document.getElementById("julio_gas").value;
    var agosto = document.getElementById("agosto_gas").value;
    var septiembre = document.getElementById("septiembre_gas").value;
    var octubre = document.getElementById("octubre_gas").value;
    var noviembre = document.getElementById("noviembre_gas").value;
    var diciembre = document.getElementById("diciembre_gas").value;

	var ctx = document.getElementById('gasolina').getContext('2d');
	var myChartsemanados = new Chart(ctx, {
	    type: 'bar',
	    data: {
	        labels:['Enero','Febrero','Marzo', 'Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
	        datasets: [{
	            label: 'Gastos',
	            data: [enero, febrero, marzo, abril, mayo, junio, julio, agosto, septiembre,octubre,noviembre,diciembre],
	            backgroundColor: [
	                'rgba(255, 99, 132, 0.2)',
	                'rgba(54, 162, 235, 0.2)',
	                'rgba(255, 206, 86, 0.2)',
	                'rgba(75, 192, 192, 0.2)',
	                'rgba(153, 102, 255, 0.2)',
	                'rgba(255, 159, 64, 0.2)'
	            ],
	            borderColor: [
	                'rgba(255, 99, 132, 1)',
	                'rgba(54, 162, 235, 1)',
	                'rgba(255, 206, 86, 1)',
	                'rgba(75, 192, 192, 1)',
	                'rgba(153, 102, 255, 1)',
	                'rgba(255, 159, 64, 1)'
	            ],
	            borderWidth: 1
	        }]
	    },
	    options: {
	        scales: {
	            yAxes: [{
	                ticks: {
	                    beginAtZero: true
	                }
	            }]
	        }
	    }
	});



    var enero = document.getElementById("enero_nomina").value;
    var febrero = document.getElementById("febrero_nomina").value;
    var marzo = document.getElementById("marzo_nomina").value;
    var abril = document.getElementById("abril_nomina").value;
    var mayo = document.getElementById("mayo_nomina").value;
    var junio = document.getElementById("junio_nomina").value;
    var julio = document.getElementById("julio_nomina").value;
    var agosto = document.getElementById("agosto_nomina").value;
    var septiembre = document.getElementById("septiembre_nomina").value;
    var octubre = document.getElementById("octubre_nomina").value;
    var noviembre = document.getElementById("noviembre_nomina").value;
    var diciembre = document.getElementById("diciembre_nomina").value;

	var ctx = document.getElementById('nominas').getContext('2d');
	var myChartsemanados = new Chart(ctx, {
	    type: 'bar',
	    data: {
	        labels:['Enero','Febrero','Marzo', 'Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
	        datasets: [{
	            label: 'Gastos',
	            data: [enero, febrero, marzo, abril, mayo, junio, julio, agosto, septiembre,octubre,noviembre,diciembre],
	            backgroundColor: [
	                'rgba(255, 99, 132, 0.2)',
	                'rgba(54, 162, 235, 0.2)',
	                'rgba(255, 206, 86, 0.2)',
	                'rgba(75, 192, 192, 0.2)',
	                'rgba(153, 102, 255, 0.2)',
	                'rgba(255, 159, 64, 0.2)'
	            ],
	            borderColor: [
	                'rgba(255, 99, 132, 1)',
	                'rgba(54, 162, 235, 1)',
	                'rgba(255, 206, 86, 1)',
	                'rgba(75, 192, 192, 1)',
	                'rgba(153, 102, 255, 1)',
	                'rgba(255, 159, 64, 1)'
	            ],
	            borderWidth: 1
	        }]
	    },
	    options: {
	        scales: {
	            yAxes: [{
	                ticks: {
	                    beginAtZero: true
	                }
	            }]
	        }
	    }
	});


	var enero = document.getElementById("enero_tag").value;
    var febrero = document.getElementById("febrero_tag").value;
    var marzo = document.getElementById("marzo_tag").value;
    var abril = document.getElementById("abril_tag").value;
    var mayo = document.getElementById("mayo_tag").value;
    var junio = document.getElementById("junio_tag").value;
    var julio = document.getElementById("julio_tag").value;
    var agosto = document.getElementById("agosto_tag").value;
    var septiembre = document.getElementById("septiembre_tag").value;
    var octubre = document.getElementById("octubre_tag").value;
    var noviembre = document.getElementById("noviembre_tag").value;
    var diciembre = document.getElementById("diciembre_tag").value;

	var ctx = document.getElementById('taggrafica').getContext('2d');
	var myChartsemanados = new Chart(ctx, {
	    type: 'bar',
	    data: {
	        labels:['Enero','Febrero','Marzo', 'Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
	        datasets: [{
	            label: 'Gastos',
	            data: [enero, febrero, marzo, abril, mayo, junio, julio, agosto, septiembre,octubre,noviembre,diciembre],
	            backgroundColor: [
	                'rgba(255, 99, 132, 0.2)',
	                'rgba(54, 162, 235, 0.2)',
	                'rgba(255, 206, 86, 0.2)',
	                'rgba(75, 192, 192, 0.2)',
	                'rgba(153, 102, 255, 0.2)',
	                'rgba(255, 159, 64, 0.2)'
	            ],
	            borderColor: [
	                'rgba(255, 99, 132, 1)',
	                'rgba(54, 162, 235, 1)',
	                'rgba(255, 206, 86, 1)',
	                'rgba(75, 192, 192, 1)',
	                'rgba(153, 102, 255, 1)',
	                'rgba(255, 159, 64, 1)'
	            ],
	            borderWidth: 1
	        }]
	    },
	    options: {
	        scales: {
	            yAxes: [{
	                ticks: {
	                    beginAtZero: true
	                }
	            }]
	        }
	    }
	});


</script>

<script src="https://cdn.jsdelivr.net/gh/linways/table-to-excel@v1.0.4/dist/tableToExcel.js"></script>
<script type="text/javascript">
    $("#exportBtn1").click(function(){

        TableToExcel.convert(document.getElementById("tab1"), {
            name: "Solicitudes orden de compra.xlsx",
            sheet: {
            	name: "Solicitudes orden de compra "
            }
        });
    });

    $("#exportBtn2").click(function(){

        TableToExcel.convert(document.getElementById("tab2"), {
            name: "Caja chica.xlsx",
            sheet: {
            	name: "Caja chica "
            }
        });
    });

    $("#exportBtn3").click(function(){

        TableToExcel.convert(document.getElementById("tab3"), {
            name: "Gasolina.xlsx",
            sheet: {
            	name: "Gasolina"
            }
        });
    });


    $("#exportBtn4").click(function(){
        TableToExcel.convert(document.getElementById("tab4"), {
            name: "Nomina.xlsx",
            sheet: {
            	name: "Nomina"
            }
        });
    });

    
    $("#exportBtn5").click(function(){
        TableToExcel.convert(document.getElementById("tab5"), {
            name: "ConsumosTAG.xlsx",
            sheet: {
            	name: "Consumos TAG"
            }
        });
    });

</script>