<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
    	<a href="/campamentos/statusc" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
    </div>
</div>

<div class="row">
	<div class="col m12 s12 text-center" style="margin-top: 10px;">
		<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Editar Status</span>
	</div>
</div>


<div class="col m12 s12">
	<form action="/campamentos/requestupdatestatus" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submitupd">
		<?php foreach ($this->status_camp as $sc) { ?>
			<input type="hidden" name="ids" value="<?php echo $sc["id_status"]; ?>">
			<div class="row">
				<div class="input-field col m12 s12">
					<i class="material-icons prefix">account_circle</i>
			        <input id="name" type="text" name="name" value="<?php echo $sc["nombre"]; ?>" class="validate" required>
			        <label for="name">* Nombre: </label>
			    </div> 
		    </div>
		<?php } ?>
	</form>
</div>

<div class="input-field col m12 s12 text-right">
	<div class="row">
		<a href="/campamentos/statusc" class="waves-effect red waves-light btn">Cancelar</a>
		<button  id="updstatus" class="waves-effect waves-light btn">Actualizar</button>
	</div>	
</div>


<script type="text/javascript">
    $("#updstatus").click(function(){
        var name = document.getElementById("name").value;

        if(name == ""){
            swal({
                title: "Para editar un grupo debes agregarle un nombre",
            });
        }else{
             swal("Espera un momento, la información esta siendo procesada", {
				icon: "success",
			 	buttons: false,
			});
            setTimeout(submitForm, 500);     
        }
    });

    function submitForm() {
        document.getElementById("submitupd").submit()
    }
</script>