<?php 
function eliminar_acentos($cadena){
		
		//Reemplazamos la A y a
		$cadena = str_replace(
		array('Á', 'À', 'Â', 'Ä', 'á', 'à', 'ä', 'â', 'ª'),
		array('A', 'A', 'A', 'A', 'a', 'a', 'a', 'a', 'a'),
		$cadena
		);

		//Reemplazamos la E y e
		$cadena = str_replace(
		array('É', 'È', 'Ê', 'Ë', 'é', 'è', 'ë', 'ê'),
		array('E', 'E', 'E', 'E', 'e', 'e', 'e', 'e'),
		$cadena );

		//Reemplazamos la I y i
		$cadena = str_replace(
		array('Í', 'Ì', 'Ï', 'Î', 'í', 'ì', 'ï', 'î'),
		array('I', 'I', 'I', 'I', 'i', 'i', 'i', 'i'),
		$cadena );

		//Reemplazamos la O y o
		$cadena = str_replace(
		array('Ó', 'Ò', 'Ö', 'Ô', 'ó', 'ò', 'ö', 'ô'),
		array('O', 'O', 'O', 'O', 'o', 'o', 'o', 'o'),
		$cadena );

		//Reemplazamos la U y u
		$cadena = str_replace(
		array('Ú', 'Ù', 'Û', 'Ü', 'ú', 'ù', 'ü', 'û'),
		array('U', 'U', 'U', 'U', 'u', 'u', 'u', 'u'),
		$cadena );

		//Reemplazamos la N, n, C y c
		$cadena = str_replace(
		array('Ñ', 'ñ', 'Ç', 'ç'),
		array('N', 'n', 'C', 'c'),
		$cadena
		);
		
		$cadena = str_replace(
		array(',', ',', ',', ','),
		array(',', ',', ',', ','),
		$cadena
		);
		

		return $cadena;
	}
?>
<style type="text/css">
.excel-div {
    width: 98%;
    height: 70em;
    overflow-x: auto;
    white-space: nowrap;
}
.oculto{
	display: none;
}
</style>

<div class="row" style="margin-top: 10px;">
	<div class="col m6 s6">
			<a href="/archivos/reportes" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>  
	</div>
	<div class="col m6 s6 text-right">
		<a class=" btn" onclick="exportTableToCSV(null,'Reporte de Facturas.csv')"><i class="material-icons right">file_download</i>Descargar</a>
	</div>
</div>

<div class="row">
    <div class="col m12 s12 text-center" style="margin-top: 20px;">
        <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Reporte de Comprobaciones</span>
    </div>
</div>


<div class="row excel-div" id="tab1">
	<table class="table text-left table-hover">
		<thead>
			<tr>
				<th>Id</th>		
				<th>Sitio</th>
				<th>Proyecto</th>
				<th>Servicio</th>
        		<th>Fecha factura</th>
        		<th>Monto factura</th>
        		<th>Razon social</th>
        		<th>Facturable</th>
        		<th>Factura</th>
        		<th>Monto comprobado</th>
        		<th>Vobo</th>
        		<th>Comentarios</th>
        		<th>Status comprobacion</th>
        		<th>Solicitud Caja chica</th>
        		<th>Residente</th>
			</tr> 
		</thead>
		<?php 
		foreach ($this->comprobaciones as $usr) { ?>
		<tbody>
			<tr>
				<td><?php echo eliminar_acentos($usr["id"]); ?></td>
				<td><?php echo eliminar_acentos($usr["nombre"]); ?></td>
				<td><?php echo eliminar_acentos($usr["nombre_proyecto"]); ?></td>
				<td><?php echo eliminar_acentos($usr["nameservicio"]); ?></td>
        		<td><?php echo eliminar_acentos($usr["fecha_del"]); ?></td>
        		<td><?php echo $usr['monto_solicitud'] ?></td>
        		<td><?php echo eliminar_acentos(str_replace(',','',$usr['razon_social'])); ?></td>
        		<td>
        			<?php if($usr['facturable'] == 1){ ?>
        				Facturable
        			<?php }else{ ?>
        				No facturable
        			<?php } ?>
        		</td>
        		<td><?php echo $usr['factura']; ?></td>
        		<td><?php echo $usr['monto_comprobacion'] ?></td>
        		<td><?php echo $usr['vo_bo']; ?></td>
        		<td><?php echo eliminar_acentos(str_replace(',','',$usr['comentarios_comprobacion']));?></td>
        		<td>
        			<?php if($usr['status_comprobacion'] == 1){ ?>
        				Comprobada
        			<?php }else{ ?>
        				En proceso
        			<?php } ?>
        		</td>
        		<td><?php echo $usr['id_comprobacion'] ?></td>
        		<td><?php echo eliminar_acentos($usr["residente"]); ?></td>
			</tr>
		</tbody>
		<?php } ?>
	</table>/


<script type="text/javascript">
function exportTableToCSV(html, filename) {
    var csv = [];
    var rows = document.querySelectorAll("table tr");

    for(var i = 0; i < rows.length; i++){
        var row = [], cols = rows[i].querySelectorAll("td, th");
        for(var j = 0; j < cols.length; j++){
            row.push(cols[j].innerText);
        }
        csv.push(row.join(","));
    }

    // download csv file
    downloadCSV(csv.join("\n"), filename);
}

function downloadCSV(csv, filename) {
    var csvFile;
    var downloadLink;

	if (window.Blob == undefined || window.URL == undefined || window.URL.createObjectURL == undefined) {
		alert("Your browser doesn't support Blobs");
		return;
	}
	
    csvFile = new Blob([csv], {type:"text/csv"});
    downloadLink = document.createElement("a");
    downloadLink.download = filename;
    downloadLink.href = window.URL.createObjectURL(csvFile);
    downloadLink.style.display = "none";
    document.body.appendChild(downloadLink);
    downloadLink.click();
}
</script>