<style type="text/css">
    .oculto{
        display: none;
    }
    
    .table_wrapper{
        overflow-x: auto;
    }
</style>

<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="/asistencia/cuadrillas" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>

    <div class="col m6 s6 text-right">
        <a class="btn red modal-trigger" href="#finalizar"><i class="material-icons right">warning</i>Finalizar Proceso</a>
    </div>
</div>

  <!-- Modal Structure -->
<div id="finalizar" class="modal modal-fixed-footer">
    <div class="modal-content">
        <span style="font-size:28px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Finalizar Asistencia</span>
        <?php 
            if($this->op_solicitud == 1){
                foreach ($this->solicitud as $key) {
                    $id_solicitud = $key['id'];
                    $nombre_sitio = $key['nombre_sitio'];
                    $user_solicitud = $key['user_solicitud'];
                    $status_auditoria = $key['status'];
                    $status_asistencia = $key['asistencia_status'];
                }
            } else{
                $id_solicitud = 0;
            }
        ?>

        <div class="row">
            <div class="col m12 s12">
                <span>
                    
                </span>
            </div>
        </div>


        <form action="/asistencia/requestaddfinalziarproceso" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_finalizar">
            <div class="row">
                <div class="col m12 s12">
                    <input type="hidden" name="id_solicitudextra" value="<?php echo $id_solicitud; ?>">
                    <input type="hidden" name="sitio" id="sitio_finalizar" value="<?php echo $this->sitio; ?>">
                    <input type="hidden" name="proyecto" value="<?php echo $this->proyecto; ?>">
                </div>
            </div>
        </form>
    </div>

    <div class="modal-footer">
        <button type="button" id="finalizar_proceso" class="btn">Guardar</button>
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>


<div class="row"> 
    <div class="col m12 s12 text-center" style="margin-top: 30px;">
        <span style="font-size:28px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Asistencia</span><br>
        <span  style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $this->sitio; ?></span>
    </div>
</div>

<?php if($this->op_solicitud == 1){ ?>

    <?php 
        foreach ($this->solicitud as $key) {
            $id_solicitud = $key['id'];
            $nombre_sitio = $key['nombre_sitio'];
            $user_solicitud = $key['user_solicitud'];
            $status_auditoria = $key['status'];
            $status_asistencia = $key['asistencia_status'];
        }
    ?>

    <div class="row">
    <!-- <div class="col m12 s12"></div> -->
        <div class="col s12 m12">
            <div class="card">
                <div class="card-content">
                    <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Solicitud horas extra</span>
                    <div class="row"> 
                        <div class="col m12 s12 table_wrapper">
                            <table>
                                <thead>
                                    <tr style="background-color: #EDEDED">
                                        <th>No.</th>
                                        <th>Sitio</th>
                                        <th>Usuario</th>
                                        <th>Status Auditoria</th>
                                        <th>Status Asistencia</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><?php echo $id_solicitud; ?></td>
                                        <td><?php echo $nombre_sitio; ?></td>
                                        <td><?php echo $user_solicitud; ?></td>
                                        <td>
                                            <?php if($status_auditoria == 0){ ?>
                                                <div class="chip modal-trigger" id="sitio_op">
                                                    <img src="/img/gris.jpg" class="sitio_dos">
                                                    Pendiente
                                                </div>
                                            <?php }else{ ?>
                                                <div class="chip modal-trigger" id="sitio_op">
                                                    <img src="/img/correct.png" class="sitio_dos">
                                                    Auditada
                                                </div>
                                            <?php } ?>
                                        </td>
                                        <td>
                                            <?php if($status_asistencia == 0){ ?>
                                                <div class="chip modal-trigger" id="sitio_op">
                                                    <img src="/img/gris.jpg" class="sitio_dos">
                                                    Pendiente
                                                </div>
                                            <?php }else{ ?>
                                                <div class="chip modal-trigger" id="sitio_op">
                                                    <img src="/img/correct.png" class="sitio_dos">
                                                    Auditada
                                                </div>
                                            <?php } ?>
                                        </td>

                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col m12 s12 text-right">
                            <span>Las Horas extra mostradas por personal corresponden a esta solicitud.</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

<div class="row">
    <div class="col m6 s12"></div>
    <div class="col m6 s12 text-right">
        <a class="orange btn modal-trigger" href="#modalmore"><i class="material-icons right">add</i>Agregar Personal</a>
    </div>
</div>

<!-- Modal Structure -->
<div id="modalmore" class="modal modal-fixed-footer">
    <div class="modal-content">
        <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar personal a la cuadrilla</span>

        <form action="/asistencia/requestaddmorepersoncuadrilla" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_addmore">
            <div class="row">
                <div class="input-field col s12">
                    <select id="person_more" name="person_more" required>
                        <option value="0" disabled selected>* Selecciona una opcion:</option>
                        <?php foreach ($this->personal_dis as $rl) { ?>
                        <option value="<?php echo $rl["id"]; ?>"><?php echo $rl["nombre"]; ?> <?php echo $rl["apellido_pa"]; ?> <?php echo $rl["apellido_ma"]; ?> / Puesto: <?php echo $rl["name_puesto"]; ?></option>
                        <?php } ?>
                    </select>
                    <label>Personal</label>
                </div>

                <input type="hidden" name="sitio" value="<?php echo $this->sitio; ?>">
                <input type="hidden" name="proyecto" value="<?php echo $this->proyecto; ?>">
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button type="button" id="add_personalmore" class="btn">Guardar</button>
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>


<div class="row" style="margin-top: 40px;">
	<!-- <div class="col m1 s12"></div> -->
	<div class="col m12 s12">
<!-- 		<div class="row">
			<div class="col m4 s6 text-right">
		        <div class="input-field col m12 s12">
		          <input type="time" id="todos" value="" oninput="actualizarValorMunicipioInm()">
		          <label for="todos">Hora de entrada</label>
		        </div>
			</div>
			<div class="col m4 s6">
			    <div class="file-field input-field">
			      <div class="btn">
			        <span>Foto</span>
			        <input type="file">
			      </div>
			      <div class="file-path-wrapper">
			        <input class="file-path validate" type="text">
			      </div>
			    </div>
			</div>

			<div class="col m4 s6 text-right">
				<div class="input-field col m12 s12">
					<a class="btn" id="hora_extrapersonal"><i class="material-icons right">access_time</i>Guardar</a>
				</div>
			</div>
		</div> -->
        <form action="/asistencia/requestaddasistenciapersonal" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_asignar">
            <input type="hidden" name="op_asistencia" id="op_asistencia">
            <input type="hidden" name="proyecto" value="<?php echo $this->proyecto; ?>">

            <div class="row">
                <div class="col s12 m12">
                    <div class="card">
                        <div class="card-content">
                            <div class="row">
                                <div class="col m6 s12">
                                    <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Opciones</span>
                                </div>

                                <div class="col m6 s12 text-right">
                                    <div class="row">
                                        <div class="col m6 s6">
                                            <a class="btn green" id="op_entrada">Hora Entrada</a>
                                        </div>
                                        
                                        <div class="col m6 s6">
                                            <a class="btn green" id="op_salida">Hora Salida</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row oculto" id="div_entrada">
                                <div class="col m s6 text-right">
                                    <div class="input-field col m12 s12">
                                      <input type="time" id="h_entrada" name="h_entrada" value="">
                                      <label for="h_entrada">Hora de entrada</label>
                                    </div>
                                </div>
                                <div class="col m s6">
                                    <div class="file-field input-field">
                                        <div class="btn">
                                            <span>Evidencia Entrada</span>
                                            <input type="file" name="url_entrada">
                                        </div>
                                    
                                        <div class="file-path-wrapper">
                                            <input class="file-path validate" type="text">
                                        </div>
                                    </div>
                                </div>
                            </div> 

                            <div class="row oculto" id="div_salida">
                                <div class="col m s6 text-right">
                                    <div class="input-field col m12 s12">
                                        <input type="time" id="h_salida" name="h_salida" value="">
                                        <label for="h_salida">Hora de salida</label>
                                    </div>
                                </div>
                                <div class="col m s6">
                                    <div class="file-field input-field">
                                        <div class="btn">
                                            <span>Evidencia Salida</span>
                                            <input type="file" name="url_salida">
                                        </div>

                                        <div class="file-path-wrapper">
                                            <input class="file-path validate" type="text">
                                        </div>
                                    </div>
                                </div>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>

            <input  name="act_todos" id="act_todos" value="" type="hidden">
            <input type="hidden" name="sitio" value="<?php echo $this->sitio; ?>"></input>

            <div class="row">
                <div class="col m12 s12 table_wrapper">
                    <table class="table text-left table-hover">
                        <thead>
                            <tr style="background-color: #EDEDED">
                                <th>Liberar</th>
            					<th>id</th>
            					<th>Nombre</th>
            					<th>Puesto</th>
            					<th>Foto</th>
            					<th>Horas extra</th>
            					<th>Hora Entrada</th>
            					<th>Hora Salida</th>
                                <th>Horas Trabajadas</th>
            					<th></th>
                                <th></th>
                                <th></th>
                            </tr> 
                        </thead>
                        <?php if ($this->personal) { 
                            foreach ($this->personal as $usr) { ?>
                                <tbody>
                                    <tr>
                                        <td>
                                            <a class="liberar_personal" data-id="<?php echo $usr["id"]; ?>" data-nombre="<?php echo $usr["nombre"]; ?>" data-ap="<?php echo $usr["apellido_pa"]; ?>" data-am="<?php echo $usr["apellido_ma"]; ?>"><span class="warning"><i class="fa fa-2x fa-external-link" style="color: red"></i></span></a>
                                        </td>
                                    	<td>
                                    		<?php echo $usr['id']; ?>
                                    	</td>
                                        <td>
                                        	<a href="/asistencia/personalasistencia/id/<?php echo $usr['id']; ?>/sitio/<?php echo $this->sitio; ?>/proyecto/<?php echo $this->proyecto; ?>">
                                        		<?php echo $usr['nombre'] ?> <?php echo $usr['apellido_pa'] ?> <?php echo $usr['apellido_ma'] ?> 
                                        	</a>
                                        </td>

                                        <td>
                                        	<?php echo $usr['name_puesto']; ?>
                                        </td>
                                        <td>
                                        	<?php if($usr['imagen'] == NULL){ ?>
                                        		<img src="/img/no_disponible1.png"style="width: 70px; height: 70px;">
                                        	<?php }else{ ?>
                    	                    	<a class="example-image-link" href="/<?php echo $usr['imagen']; ?>" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $usr['imagen']; ?>"  alt="image-1" style="width: 70px; height: 70px;"/>
                    	                    	</a>
                                        	<?php } ?>
                                        </td>
                                        <td>
                                            <span  style="font-size:13px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $usr['hora_extra']; ?> Horas</span>
                                        </td>

                                        <?php if($usr['status_asistencia'] == 0){ ?>
                                            <td>
                            	               <?php echo $usr['hora_inicio']; ?>
                                            </td>
                                            <td>
                            	               <?php echo $usr['hora_final']; ?>
                                            </td>
                                            <?php
                                                $datetime1 = new DateTime($usr['hora_inicio']);
                                                $datetime2 = new DateTime($usr['hora_final']);
                                                $interval = $datetime1->diff($datetime2);
                                                $diferencia = $interval->format("%H:%I");
                                            ?>

                                            <td>
                                                <?php if($usr['hora_final'] == NULL || $usr['hora_final'] == ""){ ?>
                                                <?php }else{ ?>
                                                    <?php echo $diferencia; ?> Hrs
                                                <?php } ?>
                                            </td>
                                        <?php }else{ ?>
                                            <td>
                                                Inasistencia
                                            </td>
                                            <td>
                                                Inasistencia
                                            </td>
                                            <td>
                                                --
                                            </td>
                                        <?php } ?>
                                        <td>
                                            <p>
                                                <label>
                                                    <input type="checkbox" class="type_check" name="ids[]" value="<?php echo $usr["id"]; ?>" />
                                                    <span></span>
    						                    </label>
                                            </p>
                                        </td>
                                        <td>
                                            <a class="delete modal-trigger" data-id="<?php echo $usr["id"]; ?>" href="#modaldelete"><span class="warning"><i class="fa fa-2x fa-user-times" style="color: red"></i></span></a>
                                        </td>
                                        <!-- <td>
                                            <a class="add_monto modal-trigger" data-id="<?php echo $usr["id"]; ?>" href="#modaladdmonto"><span class="warning"><i class="fa fa-2x fa fa-user-plus" style="color: green"></i></span></a> 
                                        </td> -->
                                    </tr>
                                </tbody>
                        <?php } }else{ ?>
                            <tbody>
                                <tr>
                                    <td>No se ha agregado personal </td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            </tbody>
                        <?php } ?>
                    </table>
                </div>
            </div>
       </form> 
	</div>
	<!-- <div class="col m1 s12"></div> -->
</div>


<div class="row oculto" id="btn_op">
    <div class="col m12 s12 text-center">
        <div class="input-field col m12 s12">
            <a class="btn" id="hora_extrapersonal"><i class="material-icons right">access_time</i>Guardar</a>
        </div>
    </div> 
</div>


<!-- Modal Structure -->
<div id="modaldelete" class="modal modal-fixed-footer">
    <div class="modal-content">
        <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Inasistencia</span>
        <div class="row">
            <form action="/asistencia/requestaddinasistenciapersonal" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_inasistencia">
                <div class="col m12 s12" style="margin-top: 30px;">
                    <div class="input-field col s12">
                        <input type="hidden" name="sitio" value="<?php echo $this->sitio; ?>"></input>
                        <input type="hidden" name="proyecto" value="<?php echo $this->proyecto; ?>">
                        <input type="hidden" name="ids" id="id_userinasistencia">
                        <input placeholder="Agregar el motivo de la inasistencia" name="motivo" id="motivo_form" type="text" class="validate">
                      <label for="motivo_form">Motivo</label>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" id="add_inasistencia" class="btn">Guardar</button>
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>


<!-- Modal Structure -->
<div id="modaladdmonto" class="modal modal-fixed-footer">
    <div class="modal-content">
        <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Bonificación</span>
        <div class="row">
            <form action="/asistencia/requestaddinasistenciapersonal" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_inasistencia">
                <div class="col m12 s12" style="margin-top: 30px;">

                    <div class="input-field col m6 s12">
                        <input name="monto_add" id="monto" type="number" class="validate">
                      <label for="monto">Motivo</label>
                    </div>


                    <div class="input-field col m6 s12">
                        <input type="hidden" name="sitio" value="<?php echo $this->sitio; ?>"></input>
                        <input type="hidden" name="proyecto" value="<?php echo $this->proyecto; ?>">
                        <input type="hidden" name="ids" id="id_userinasistencia">
                        <input placeholder="Agregar el motivo de la inasistencia" name="motivo" id="motivo_form" type="text" class="validate">
                      <label for="motivo_form">Motivo</label>
                    </div>                    
                </div>
            </form>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" id="add_inasistencia" class="btn">Guardar</button>
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>


<input type="hidden" id="actividad" value="1">
<script src="/js/lightbox.js"></script>
<script src="/js/materialize.min.js"></script>
<script type="text/javascript">
  	$(document).ready(function(){
    	$('.datepicker').datepicker( {"format":'dd/mm/yyyy'});
    	$('select').formSelect();
    	$('.modal').modal();
    	$('.timepicker').timepicker();
    	var currentDate = document.getElementById("today_picker").value; 
    	$('.datepicker').datepicker( {"format":'dd/mm/yyyy'} ).datepicker("setDate",currentDate);
  	});

    function actualizarValorMunicipioInm() {
		let todos = document.getElementById("todos").value;
		document.getElementById("act_todos").value = todos;
	}

    $("#hora_extrapersonal").click(function(){
        var actividad = document.getElementById("actividad").value;
        if(actividad == ""){
            swal({
            	title: "Para agregar un imagen debes seleccionar una tarea ",
            });
        }else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
            setTimeout(submitpersonal, 1500);     
        }
    });
    function submitpersonal() { document.getElementById("submit_asignar").submit() }


    $("#op_entrada").click(function(){
        $("#div_entrada").show();
        $("#div_salida").hide();
        $("#btn_op").show();

        var asistencia = 0;
        document.getElementById("op_asistencia").value = asistencia;
    });

    $("#op_salida").click(function(){
        $("#div_salida").show();
        $("#div_entrada").hide();
        $("#btn_op").show();

        var asistencia = 1;
        document.getElementById("op_asistencia").value = asistencia;
    });

    $(".delete").click(function(){
        var id = $(this).data('id');
        document.getElementById("id_userinasistencia").value = id;
    });

    $("#add_inasistencia").click(function(){
        var user = document.getElementById("id_userinasistencia").value;
        var motvo = document.getElementById("motivo_form").value;
        if(user == "" || motvo == ""){
            swal({
                title: "Para continuar es necesario agregar el motivo de la inasistencia",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submitinasistencia, 1500);     
        }
    });
    function submitinasistencia() { document.getElementById("submit_inasistencia").submit() }


    $("#finalizar_proceso").click(function(){
        var sitio_finalizar = document.getElementById("sitio_finalizar").value;
        if(sitio_finalizar == "" ){
            swal({
                title: "Para continuar es necesario agregar el motivo de la inasistencia",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submitfinalizar, 1500);     
        }
    });
    function submitfinalizar() { document.getElementById("submit_finalizar").submit() }


    $(".liberar_personal").click(function(){
        id=$(this).data('id');
        nombre=$(this).data('nombre');
        ap=$(this).data('ap');
        am =$(this).data('am');

        swal({
            title: "Estas seguro de liberar a "+ap+" "+nombre+" del sitio?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete) {
                swal("Espere un momento, "+ap+" "+nombre+"  se liberara del sitio", {
                    icon: "success",
                    buttons: false,
                });

                var request = $.ajax({
                    url:"/panel/requestliberarpersonal",
                    method:"POST",
                    data: { id : id },
                    processData: true,
                });
    //-------------------end de ajax---------------------------

    //-------------peticion de respuesta de ajax------------------
                request.done(function(response) {
                    console.log(response);//imprime lo que responde el ajax
                    // alert
                    window.location.reload(true);
                });
    //-------------------end de respuesta ajax---------------------
                 return false;
            } else {
                swal("La accion fue cancelada!");
            } 
        });

    });


    $("#add_personalmore").click(function(){
        var person_more = document.getElementById("person_more").value;
        if(person_more == 0){
            swal({
                title: "Para continuar es necesario seleccionar al personal",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submitmoreperson, 1500);     
        }
    });
    function submitmoreperson() { document.getElementById("submit_addmore").submit() }
</script>
