<div class="row"> 
    <div class="col m12 s12 text-center" style="margin-top: 30px;">
        <span style="font-size:24px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Cuadrillas</span>
    </div>
</div>


<div class="row">
	<div class="col m2 s12"></div>
	<div class="col m8 s12">
        <table class="table text-left table-hover">
            <thead>
                <tr style="background-color: #EDEDED">
					<th>Sitio</th>
					<th class="text-center">Hora Extra</th>
					<th class="text-center">Asistencia</th>
                </tr> 
            </thead>
            <?php if ($this->sitios) { 
                foreach ($this->sitios as $usr) { ?>
            <tbody>
                <tr>
                    <?php if($usr["nombre_sitio"] == "Compensacion"){ ?>
                        <td>
                            <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Compensación</span>
                        </td>
                    <?php } elseif($usr["nombre_sitio"] == "Taller"){ ?>
                        <td>
                            <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Taller</span>
                        </td>
                    <?php }else{ ?>
                        <td>
                            <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $usr["nombre_sitio"]; ?>: <?php echo $usr["proyecto"]; ?>/ Id Cliente: <?php echo $usr["cliente"]; ?> </span>
                        </td>
                    <?php } ?>

                    <td class="text-center">
                    	<a href="/asistencia/horaextra/sitio/<?php echo $usr["nombre_sitio"]; ?>/proyecto/<?php echo $usr['id_proyecto'] ?>"><i class="material-icons">access_time</i></a>
                    </td>

                    <td class="text-center">
                    	<a href="/asistencia/asistencia/sitio/<?php echo $usr["nombre_sitio"]; ?>/proyecto/<?php echo $usr['id_proyecto'] ?>"><i class="material-icons">event_available</i></a>
                    </td>

                </tr>
            </tbody>
            <?php } }else{ ?>
            <tbody>
                <tr>
                    <td>No se ha agregado personal </td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
            <?php } ?>
        </table>
	</div>
	<div class="col m2 s12"></div>
</div>