<?php 
	foreach ($this->solicitud as $key) {
 		$id = $key['id'];
 		$name_sitio = $key['nombre_sitio'];
 		$user = $key['user_solicitud'];
 		$fecha = $key['user_fecha'];
 		$motivo = $key['motivo'];
 		$status_solicitud = $key['status'];
 		$user_validacion = $key['validacion_user'];
 		$fecha_validacion = $key['fecha_validacion'];
 		$comentario_rechazo = $key['comentario'];
 	} 
?>

<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="javascript:window.history.go(-1);" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
    <div class="col m6 s6 text-right">
    	<a class="btn" href="/asistencia/pdfasistenciasolicitud/id/<?php echo $this->id_solicitud; ?>"><i class="material-icons right">insert_drive_file</i>Documento</a>
    </div>
</div>


<div class="row"> 
    <div class="col m12 s12 text-center" style="margin-top: 30px;">
        <span style="font-size:28px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Solicitud Hora Extra</span>
    </div>
</div>

<!-- <div class="row">
	<div class="col m6 s12"></div>
	<div class="col m6 s12">
		<?php if($status_solicitud == 0){ ?>
			<div class="row">
				<div class="col m6 s6 text-center">
	              <div class="chip" id="autorizar_solicitud">
	                  <img src="/img/gris.jpg" >
	                  Autorizar
	              </div>
				</div>
				<div class="col m6 s6 text-center">
	              <div class="chip modal-trigger" href="#modal1">
	                  <img src="/img/gris.jpg" >
	                  Rechazar
	              </div>
				</div>
			</div>
		<?php } ?>
	</div>
</div>
 -->

<!-- RECHAZAR SOLICITUD  -->
<div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
    	<span  style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Rechazar Solicitud: </span>

    	<div class="row">
    		<div class="col m12 s12">
		        <div class="input-field col s12">
		        	<input id="comentario_rechazo" type="text" class="validate">
		        	<label for="comentario_rechazo">Comentario del Rechazo</label>
		        </div>
    		</div>
    	</div>

    </div>
    <div class="modal-footer">
		<button type="button" id="rechazar_solicitud" class="btn">Guardar</button>
		<button  class="modal-close red btn">Cerrar</button>
    </div>
</div>
<!-- END RECHAZAR SOLICITUD -->


<div class="row" style="margin-top: 25px;">
    <div class="col s12 m6">
      	<div class="card ">
		    <div class="card-content">
				<span  style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información Solicitud</span>

				<div class="row" style="margin-top: 20px;">
					<div class="col m12 s12">
						<span  style="font-size:17px;">Sitio: </span> 
						<span  style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $name_sitio; ?></span> 
						<br> 
						<span  style="font-size:17px;">Usuario: </span>
						<span  style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> <?php echo $user; ?></span>
						<br> 
						<span  style="font-size:17px;">Fecha: </span>
						<span  style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $fecha; ?></span>
					</div>
				</div>

	        </div>
      	</div>
    </div>


    <div class="col s12 m6">
      	<div class="card ">
		    <div class="card-content">
				<span  style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> Solicitud</span>

				<div class="row" style="margin-top: 20px;">
					<div class="col m12 s12">
						<?php if($status_solicitud == 0){ ?>
							<span  style="font-size:17px;">Status: </span>
							<span  style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Pendiente</span>
							<br>
							<span  style="font-size:17px;">Fecha: </span>
							<span  style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">---</span>
							<br>
							<span  style="font-size:17px;">Usuario: </span>
							<span  style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">---</span>
						<?php } ?>

						<?php if($status_solicitud == 1){ ?>
							<span  style="font-size:17px;">Status: </span>
							<span  style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Autorizada</span>
							<br>
							<span  style="font-size:17px;">Fecha: </span>
							<span  style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $user_validacion; ?></span>
							<br>
							<span  style="font-size:17px;">Usuario: </span>
							<span  style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $fecha_validacion; ?></span>
						<?php } ?>

						<?php if($status_solicitud == 2){ ?>
							<span  style="font-size:17px;">Autorizada: </span>
							<span  style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Rechazada</span>
							<br>
							<span  style="font-size:17px;">Fecha: </span>
							<span  style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $user_validacion; ?></span>
							<br>
							<span  style="font-size:17px;">Usuario: </span>
							<span  style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $fecha_validacion; ?></span>
						<?php } ?>
					</div>
				</div>

	        </div>
      	</div>
    </div>
</div>


<div class="row">
	<div class="col m12 s12">
		<span  style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Motivo de las horas extra: </span><br>
		<span  style="font-size:15px; color: red; letter-spacing: 0.1em; font-weight: bold;">
			<?php echo $motivo; ?>
		</span>
	</div>
</div>

<?php 
	foreach ($this->solicitud as $key) {
		$status_solicitud = $key['status'];
		$asistencia_status = $key['asistencia_status'];
	}

?>
<div class="row">
    <div class="col s12 m12">
	    <div class="card">
	        <div class="card-content">
	        	<div class="row">
	        		<div class="col m6 s6">
	        			<span  style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> Personal</span>
	        		</div>
	        		<div class="col m6 s6 text-right">
	        			<?php if($asistencia_status == 0){ ?>
<!-- 	        				<a class="btn modal-trigger" href="#modal4"><i class="material-icons left">access_time</i>Modificar Horas</a> -->
	        			<?php } ?>
	        		</div>
	        	</div>
	        	<form action="/asistencia/requestvaldiarusuarios" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_asignar">
	        	<input type="hidden" name="solicitud" value="<?php echo $this->id_solicitud; ?>">

	        	<?php if($asistencia_status == 0){ ?>
	        		<input type="hidden" name="op_status" value="0">
	        	<?php }else{ ?>
	        		<input type="hidden" name="op_status" value="1">
	        	<?php } ?>

	        	<div class="row" style="margin-top: 20px;">
	        		<div class="col m12 s12">
					    <table class="table text-left table-hover">
					      <thead>
					        <tr>
					          <th>Nombre</th>
					          <th>Puesto</th>
					          <th>Imagen</th>
					          <th>Horas extras</th>
					          <th></th>
					        </tr> 
					      </thead>
					      <?php
					      if ($this->personal) { 
					      foreach ($this->personal as $usr) { ?>
					      <tbody>
			                <tr>
			                    <td>
			                    	<?php echo $usr['nombre'] ?> <?php echo $usr['apellido_pa'] ?> <?php echo $usr['apellido_ma'] ?> 
			                    </td>
			                    <td>
			                    	<?php echo $usr['puesto']; ?>
			                    </td>
			                    <td>
			                    	<?php if($usr['imagen'] == NULL){ ?>
			                    		<img src="/img/no_disponible1.png"style="width: 70px; height: 70px;">
			                    	<?php }else{ ?>
				                    	<a class="example-image-link" href="/<?php echo $usr['imagen']; ?>" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $usr['imagen']; ?>"  alt="image-1" style="width: 70px; height: 70px;"/>
				                    	</a>
			                    	<?php } ?>
			                    </td>
			                    <td class="text-center">
			                    	<span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> <?php echo $usr['hora_extra']; ?> Horas</span>
			                    </td>

			                    <td>
<!-- 							        <div class="input-field col s12">
							          <input id="first_name" name="hora_extra[]" value="<?php echo $usr['hora_extra']; ?>" max="100" min="0" type="hidden" class="validate">

							          <input type="hidden" name="personal[]" value="<?php echo $usr['id_user']; ?>">
 -->			
 									<?php if($asistencia_status == 0){ ?>
 										<?php if($usr['status_user'] == 1){ ?>
	 									    <p>
										      <label>
										        <input type="checkbox" checked name="validar[]" value="<?php echo $usr['id_sol']; ?>" />
										        <span></span>
										      </label>
										    </p>
 										<?php }else{ ?>
 									    	<p>
										      <label>
										        <input type="checkbox" name="validar[]" value="<?php echo $usr['id_sol']; ?>" />
										        <span></span>
										      </label>
										    </p>
 										<?php } ?>
									<?php }else{ ?>
										<?php if($usr['status_user'] == 1){ ?>
										    <p>
										      <label>
										        <input type="checkbox" checked disabled />
										        <span></span>
										      </label>
										    </p>
										<?php }else{ ?>
										    <p>
										      <label>
										        <input type="checkbox" disabled />
										        <span></span>
										      </label>
										    </p>
										<?php } ?>
									<?php } ?>
			                    </td>

			                </tr>
					        <?php } }else{ ?>
					        </tbody> 
					        <tbody>
					            <tr>
					                <td class="text-center" colspan="6"><h4>No se encontro personal asignado.</h4></td>
					            </tr>
					        </tbody>
					                    
					        <?php } ?>
					    </table>
	        		</div>
	        	</div>
	        	</form>


	        	<?php if($asistencia_status == 1){ ?>
	        	<?php }else{ ?>
		        	<div class="row">
		        		<div class="col m12 s12 text-center">
		        			<a class="btn" id="hora_extrapersonal"><i class="material-icons right">send</i>Guardar</a>
		        		</div>
		        	</div>
	        	<?php } ?>

	        </div>
	    </div>
    </div>
</div>

  <!-- Modal Structure -->
<div id="modal4" class="modal modal-fixed-footer">
    <div class="modal-content">
    	<div class="row">
    		<div class="col m12 s12">
    			<span  style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> Modificar Horas</span>
    		</div>
    	</div>

    	<div class="row">
    		<div class="col m12 s12">
    			<form action="/asistencia/requestchangehoraextrapersonal" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_changehora">
    				<input type="hidden" name="id_solicitud" value="<?php echo $this->id_solicitud; ?>">
				<table class="table text-left table-hover">
					<thead>
					    <tr>
					        <th>Nombre</th>
					        <th>Puesto</th>
					        <th>Imagen</th>
					        <th>Horas extras</th>
					    </tr> 
					</thead>
					<?php if ($this->personal) { 
					foreach ($this->personal as $usr) { ?>
					<tbody>
			            <tr>
			                <td>
			                   	<?php echo $usr['nombre'] ?> <?php echo $usr['apellido_pa'] ?> <?php echo $usr['apellido_ma'] ?> 
			                </td>
			                <td>
			                    <?php echo $usr['puesto']; ?>
			                </td>
			                <td>
			                   	<?php if($usr['imagen'] == NULL){ ?>
			                    	<img src="/img/no_disponible1.png"style="width: 70px; height: 70px;">
			                   	<?php }else{ ?>
				                    <a class="example-image-link" href="/<?php echo $usr['imagen']; ?>" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $usr['imagen']; ?>"  alt="image-1" style="width: 70px; height: 70px;"/>
				                    </a>
			                   	<?php } ?>
			                </td>
			                <td class="text-center">
			                    <span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> <?php echo $usr['hora_extra']; ?> Horas</span>
			                </td>

			                <td>
				          		<input id="first_name" name="hora_extra[]" value="<?php echo $usr['hora_extra']; ?>" max="100" min="0" type="number" class="validate">
				          		<input type="hidden" name="personal[]" value="<?php echo $usr['id_sol']; ?>">
			                </td>
			            </tr>
					<?php } }else{ ?>
					</tbody> 
					<tbody>
					    <tr>
					        <td class="text-center" colspan="6"><h4>No se encontro personal asignado.</h4></td>
					    </tr>
					</tbody>
					                    
					<?php } ?>
				</table>
				</form>
    		</div>
    	</div>
    </div>
    <div class="modal-footer">
      	<button class=" btn" id="editar_horaextra">Guardar</button>
      	<button  class="modal-close red btn">Cerrar</button>
    </div>
</div>



	<input type="hidden" id="id_solicitud" value="<?php echo $this->id_solicitud; ?>">
	<input type="hidden" id="id_user" name="id_user" value="<?php echo $this->id_user; ?>">

	<input type="hidden" id="actividad" value="yes">
<script src="/js/lightbox.js"></script>
<script type="text/javascript">
  	$(document).ready(function(){
    	$('.modal').modal();
  	});

    $("#autorizar_solicitud").click(function(){
    	var id = document.getElementById("id_solicitud").value;
    	var id_user = document.getElementById("id_user").value;
		swal({
			title: "Estas seguro de cambiar el status de la solicitud?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
		        swal("Espere un momento, la información esta siendo procesada", {
		          icon: "success",
		          buttons: false,
		        });  

		    	var dato = "1";
		    	var comentario = null;
		        var request = $.ajax({
		            url:"/asistencia/requestupdatesolicitudhorasextra",
		            method:"POST",
		            data: {dato:dato, id:id, id_user:id_user,comentario:comentario},
		            processData: true,
		        });
	//-------------------end de ajax---------------------------
	//-------------peticion de respuesta de ajax------------------
		        request.done(function(response) {
		            console.log(response);//imprime lo que responde el ajax
		            window.location.reload(true);
		        });
	//-------------------end de respuesta ajax---------------------
	        	return false;
		  	} else {
		    	swal("Accion cancelada!");
		  	}
		});

    });


    $("#rechazar_solicitud").click(function(){
    	var id = document.getElementById("id_solicitud").value;
    	var id_user = document.getElementById("id_user").value;
		swal({
			title: "Estas seguro de cambiar el status de la solicitud?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
		        swal("Espere un momento, la información esta siendo procesada", {
		          icon: "success",
		          buttons: false,
		        });  

	    		var dato = "2";
	    		var comentario = document.getElementById("comentario_rechazo").value;
	            var request = $.ajax({
	                url:"/asistencia/requestupdatesolicitudhorasextra",
	                method:"POST",
	                data: {dato:dato, id:id, id_user:id_user,comentario:comentario},
	                processData: true,
	            });
			//-------------------end de ajax---------------------------
			//-------------peticion de respuesta de ajax------------------
	            request.done(function(response) {
	                console.log(response);//imprime lo que responde el ajax
	                // alert
	                window.location.reload(true);
	            });
			//-------------------end de respuesta ajax---------------------
	             return false;
			} else {
		    	swal("Accion cancelada!");
		  	}
		});

    });


    $("#hora_extrapersonal").click(function(){
        var actividad = document.getElementById("actividad").value;
        if(actividad == "" ){
            swal({
            	title: "Es necesario agregar un motivo a la solicitud",
            });
        }else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
            setTimeout(submitpersonal, 1500);     
        }
    });

    function submitpersonal() { document.getElementById("submit_asignar").submit() }

    $("#editar_horaextra").click(function(){
        var actividad = document.getElementById("actividad").value;
        if(actividad == "" ){
            swal({
            	title: "Es necesario agregar un motivo a la solicitud",
            });
        }else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
            setTimeout(submitchangehora, 1500);     
        }
    });

    function submitchangehora() { document.getElementById("submit_changehora").submit() }
</script>