<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/asistencia/personalasistencia/id/<?php echo $this->personal_id ?>/sitio/<?php echo $this->sitio_name; ?>/proyecto/<?php echo$this->proyecto ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>   
    </div>
</div>


<div class="row"> 
    <div class="col m12 s12 text-center" style="margin-top: 30px;">
        <span style="font-size:24px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Registro</span>
    </div>
</div>


<div class="row">
	<div class="col m12 s12">
		<form action="/asistencia/requestaupdatesolicitudnomina" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_updatenomina">
		<?php foreach ($this->asistencia as $key) { ?>
			<?php 
				$year_uno = substr($key['dia'], 6); 
        		$mes_uno = substr($key['dia'], 3,2); 
        		$day_uno = substr($key['dia'], 0,2); 
        		$date = $day_uno."/".$mes_uno."/".$year_uno;
			?>

	        <div class="input-field col  m6 s12">
	        	<input id="day_registro" name="day" type="date">
	        	<label for="day_registro">Día: <?php echo $date; ?></label>
	        	<input type="hidden" name="dia_registro" value="<?php echo $key['dia']; ?>">

	        	<input type="hidden" name="id_solicitud" value="<?php echo $this->id_solicitud; ?>">
	        	<input type="hidden" name="user" value="<?php echo $this->personal_id; ?>">
	        	<input type="hidden" name="proyecto" value="<?php echo $this->proyecto; ?>">
	        	<input type="hidden" name="sitio" value="<?php echo $this->sitio_name; ?>">
	        </div>

<!-- 	        <div class="input-field col  m6 s6">

	        </div> -->

			<div class="input-field col m6 s12">
			    <input id="new_horaentrada" value="<?php echo $key['hora_entrada']; ?>" name="hora_entrada" type="time">
			    <label for="new_horaentrada">Hora de entrada</label>
			</div>	

			<?php foreach ($this->asistencia as $key) {
				$pro1 = $key['id_proyecto'];	
				$pro2 = $key['id_proyecto_salida'];	
			} ?>


				<div class="input-field col m6 s12">
					<?php if($pro1 == 0){ ?>
					    <select id="sitio_entrada" name="sitio_entrada" required>
					      	<option value="0" selected>Taller</option>
					      	<?php foreach ($this->proyectos as $mar) { ?>
					      	<option value="<?php echo $mar["id"]; ?>"><?php echo $mar['nombre']; ?> / <?php echo $mar['nombre_proyecto']; ?> - Cliente: <?php echo $mar['id_cliente']; ?></option>
					      	<?php } ?>
					    </select>
					<?php }else{ ?>
						<select id="sitio_entrada" name="sitio_entrada" required>
							<option value="0" >Taller</option>
					    	<?php foreach ($this->proyectos as $mar) { 
					     		if ($mar['id']==$key['id_proyecto']) { ?>
					                <option value="<?php echo $mar["id"]; ?>" selected><?php echo $mar['nombre']; ?> / <?php echo $mar['nombre_proyecto']; ?> - Cliente: <?php echo $mar['id_cliente']; ?></option>
					     	<?php } if ($mar['id']!=$key['id_proyecto']) { ?>
					                <option value="<?php echo $mar["id"]; ?>" ><?php echo $mar['nombre']; ?> / <?php echo $mar['nombre_proyecto']; ?> - Cliente: <?php echo $mar['id_cliente']; ?></option>
					     	<?php } 
					     	} ?>  
						</select>
					<?php } ?>
					<label>Sitio Entrada</label>
				</div>


			<div class="input-field col m6 s12">
			    <input id="new_horasalida" value="<?php echo $key['hora_salida']; ?>" name="hora_salida" type="time">
			    <label for="new_horasalida">Hora de Salida</label>
			</div>	


	<!-- 			<div class="input-field col m6 s12">
					<select id="sitio_entrada" name="sitio_salida" required>
				    	<?php foreach ($this->proyectos as $mar) { 
				     		if ($mar['id']==$key['id_proyecto_salida']) { ?>
				                <option value="<?php echo $mar["id"]; ?>" selected><?php echo $mar['nombre']; ?> / <?php echo $mar['nombre_proyecto']; ?> - Cliente: <?php echo $mar['id_cliente']; ?></option>
				     	<?php } if ($mar['id']!=$key['id_proyecto_salida']) { ?>
				                <option value="<?php echo $mar["id"]; ?>" ><?php echo $mar['nombre']; ?> / <?php echo $mar['nombre_proyecto']; ?> - Cliente: <?php echo $mar['id_cliente']; ?></option>
				     	<?php } } ?>  
					</select>
					<label>Sitio Salida</label>
				</div>
 -->

				<div class="input-field col m6 s12">
					<?php if($pro2 == 0){ ?>
					    <select id="sitio_salida" name="sitio_salida" required>
					      	<option value="0" selected>Taller</option>
					      	<?php foreach ($this->proyectos as $mar) { ?>
					      	<option value="<?php echo $mar["id"]; ?>"><?php echo $mar['nombre']; ?> / <?php echo $mar['nombre_proyecto']; ?> - Cliente: <?php echo $mar['id_cliente']; ?></option>
					      	<?php } ?>
					    </select>
					<?php }else{ ?>
						<select id="sitio_salida" name="sitio_salida" required>
							<option value="0" >Taller</option>
					    	<?php foreach ($this->proyectos as $mar) { 
					     		if ($mar['id']==$key['id_proyecto_salida']) { ?>
					                <option value="<?php echo $mar["id"]; ?>" selected><?php echo $mar['nombre']; ?> / <?php echo $mar['nombre_proyecto']; ?> - Cliente: <?php echo $mar['id_cliente']; ?></option>
					     	<?php } if ($mar['id']!=$key['id_proyecto_salida']) { ?>
					                <option value="<?php echo $mar["id"]; ?>" ><?php echo $mar['nombre']; ?> / <?php echo $mar['nombre_proyecto']; ?> - Cliente: <?php echo $mar['id_cliente']; ?></option>
					     	<?php } 
					     	} ?>  
						</select>
					<?php } ?>
					<label>Sitio Salida</label>
				</div>



		    <div class="file-field input-field col m6 s12">
		      	<div class="btn">
		        	<span>Evidencia Entrada</span>
		        	<input type="file" name="evi_entrada">
		      	</div>
			    <div class="file-path-wrapper">
			        <input class="file-path validate" type="text">
			        <input type="hidden" name="validate_entrada" value="<?php echo $key["ev_entrada"]; ?>">
			    </div>
		    </div>


		    <div class="file-field input-field col m6 s12">
		      	<div class="btn">
		        	<span>Evidencia Salida</span>
		        	<input type="file" name="evi_salida">
		      	</div>
			    <div class="file-path-wrapper">
			        <input class="file-path validate" type="text">
			        <input type="hidden" name="validate_salida" value="<?php echo $key["ev_salida"]; ?>">
			    </div>
		    </div>


    	<?php } ?>
    	</form>

    	<div class="input-field col m6 s12 text-center">
    		<a class="btn" id="add_generarnomina"><i class="material-icons right">send</i>Guardar</a>
    	</div>

	</div>
</div>

<div class="row">
	<?php foreach ($this->asistencia as $key) { ?>
	<div class="col m6 s12 text-center">
		<a class="example-image-link" href="/<?php echo $key['ev_entrada']; ?>" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $key['ev_entrada']; ?>"  alt="image-1" style="width: 220px; height: 150px;"/></a>
	</div>
	<div class="col m6 s12 text-center">
		<a class="example-image-link" href="/<?php echo $key['ev_salida']; ?>" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $key['ev_salida']; ?>"  alt="image-1" style="width: 220px; height: 150px;"/></a>
	</div>
	<?php } ?>
</div>


<script src="/js/lightbox.js"></script>
<script type="text/javascript">
    $("#add_generarnomina").click(function(){
    	var new_horaentrada = document.getElementById("new_horaentrada").value;
    	var new_horasalida = document.getElementById("new_horasalida").value;

        if(new_horaentrada == "" ||  new_horasalida== ""){
            swal({
                title: "Para continuar es neceario agregar la información solicitada",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submitnomina, 1500);     
        }
    });
    function submitnomina() { document.getElementById("submit_updatenomina").submit() }
</script>