<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/asistencia/cuadrillas" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
</div>

<div class="row"> 
    <div class="col m12 s12 text-center" style="margin-top: 30px;">
        <span style="font-size:28px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Horas Extra</span><br>
        <span  style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $this->sitio; ?></span>
    </div>
</div>

<?php if($this->op_solicitud == 1){ ?>

<?php 
	foreach ($this->solicitud as $key) {
		$id_solicitud = $key['id'];
		$nombre_sitio = $key['nombre_sitio'];
		$user_solicitud = $key['user_solicitud'];
		$status_auditoria = $key['status'];
		$status_asistencia = $key['asistencia_status'];
	}
?>

<div class="row">
    <div class="col s12 m12">
      	<div class="card">
	        <div class="card-content">
	        	<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Solicitud horas extra</span>
	        	<div class="row"> 
	        		<div class="col m12 s12">
				      	<table>
					        <thead>
					          	<tr>
					              <th>No.</th>
					              <th>Sitio</th>
					              <th>Usuario</th>
					              <th>Status Auditoria</th>
					              <th>Status Asistencia</th>
					          	</tr>
					        </thead>

				        	<tbody>
					          	<tr>
					            	<td><?php echo $id_solicitud; ?></td>
					            	<td><?php echo $nombre_sitio; ?></td>
					            	<td><?php echo $user_solicitud; ?></td>
					            	<td>
					            		<?php if($status_auditoria == 0){ ?>
							                <div class="chip modal-trigger" id="sitio_op">
							                    <img src="/img/gris.jpg" class="sitio_dos">
							                    Pendiente
							                </div>
						            	<?php }else{ ?>
							                <div class="chip modal-trigger" id="sitio_op">
							                    <img src="/img/correct.png" class="sitio_dos">
							                    Auditada
							                </div>
						            	<?php } ?>
					            	</td>
					            	<td>
					            		<?php if($status_asistencia == 0){ ?>
							                <div class="chip modal-trigger" id="sitio_op">
							                    <img src="/img/gris.jpg" class="sitio_dos">
							                    Pendiente
							                </div>
						            	<?php }else{ ?>
							                <div class="chip modal-trigger" id="sitio_op">
							                    <img src="/img/correct.png" class="sitio_dos">
							                    Auditada
							                </div>
						            	<?php } ?>
					            	</td>

					          	</tr>
				        	</tbody>
				      	</table>
	        		</div>
	        	</div>
	        </div>
      	</div>
    </div>
</div>
<?php }else{ ?>
<div class="row">
    <div class="col s12 m12">
      	<div class="card">
	        <div class="card-content">
	        	<span  style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Crear Solicitud de horas extra</span>
				<div class="row">
					<div class="col m12 s12 text-center">
						<div class="input-field col m12 s12">
						    <input type="text" id="motivo" value="">
						    <label for="motivo">Motivo</label>
						</div>

					</div>
					<div class="col m4 s6 text-right">
				<!-- 		<div class="input-field col m12 s12">
						    <input type="text" id="todos" value="" oninput="actualizarValorMunicipioInm()">
						    <label for="todos">Horas extra para todos</label>
						</div> -->
					</div>
				</div>
	        </div>
      	</div>
    </div>
</div>
<?php } ?>

<div class="row" style="margin-top: 40px;">
	<div class="col m1 s12"></div>
	<div class="col m10 s12">


		<form action="/asistencia/requestaddhoraextrapersonal" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_asignar">
		<input  name="act_todos" id="act_todos" value="" type="hidden">
		<input type="hidden" name="sitio" value="<?php echo $this->sitio; ?>">
		<input type="hidden" name="proyecto" value="<?php echo $this->proyecto; ?>">
            </input>
        <input type="hidden" name="motivo" id="motivo_sol">
        <table class="table text-left table-hover">
            <thead>
                <tr >
					<th>id</th>
					<th>Nombre</th>
					<th>Puesto</th>
					<th>Foto</th>
					<th>Horas Extra</th>
                </tr> 
            </thead>

            <?php if ($this->personal) { 
                foreach ($this->personal as $usr) { ?>
            <tbody>
                <tr>
                	<td>
                		<?php echo $usr['id']; ?>
                	</td>
                    <td>
                    	<?php echo $usr['nombre'] ?> <?php echo $usr['apellido_pa'] ?> <?php echo $usr['apellido_ma'] ?> 
                    </td>

                    <td>
                    	<?php echo $usr['name_puesto']; ?>
                    </td>
                    <td>
                    	<?php if($usr['imagen'] == NULL){ ?>
                    		<img src="/img/no_disponible1.png"style="width: 70px; height: 70px;">
                    	<?php }else{ ?>
	                    	<a class="example-image-link" href="/<?php echo $usr['imagen']; ?>" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $usr['imagen']; ?>"  alt="image-1" style="width: 70px; height: 70px;"/>
	                    	</a>
                    	<?php } ?>
                    </td>
                    <td>
				        <div class="input-field col s12">
				          <input id="first_name" name="hora_extra[]" value="<?php echo $usr['hora_extra']; ?>" max="100" min="0" type="number" class="validate">

				          <input type="hidden" name="personal[]" value="<?php echo $usr['id']; ?>">
				        </div>
                    </td>
                </tr>
            </tbody>
            <?php } }else{ ?>
            <tbody>
                <tr>
                    <td>No se ha agregado personal </td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
            <?php } ?>
        </table>
       </form> 
	</div>
	<div class="col m1 s12"></div>
</div>

<?php if($this->op_solicitud == 1){ ?>

	<div class="col m12 s12 text-center">
		<div class="input-field col m12 s12">
			<a onclick="M.toast({html: 'Ya existe una solicitud'})" class="btn"><i class="material-icons right">access_time</i>Autorizar</a>
		</div>
	</div>
<?php }else{ ?>
<div class="row">
	<div class="col m12 s12 text-center">
		<div class="input-field col m12 s12">
			<a class="btn" id="hora_extrapersonal"><i class="material-icons right">access_time</i>Autorizar</a>
		</div>
	</div>
</div>
<?php } ?>



<input type="hidden" id="actividad" value="1">
<script src="/js/lightbox.js"></script>
<script type="text/javascript">
    function actualizarValorMunicipioInm() {
		let todos = document.getElementById("todos").value;
		document.getElementById("act_todos").value = todos;
	}

    $("#hora_extrapersonal").click(function(){
        var actividad = document.getElementById("actividad").value;
        var motivo = document.getElementById("motivo").value;
        document.getElementById("motivo_sol").value=motivo;
        if(actividad == "" || motivo == ""){
            swal({
            	title: "Es necesario agregar un motivo a la solicitud",
            });
        }else{
			swal("Espere un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			}); 
            setTimeout(submitpersonal, 1500);     
        }
    });

    function submitpersonal() { document.getElementById("submit_asignar").submit() }
</script>