<html>
<head>
    <!-- <base href="https://demos.telerik.com/kendo-ui/pdf-export/page-layout">
    <style>html { font-size: 14px; font-family: Arial, Helvetica, sans-serif; } --></style>
    <title></title>
   <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.common.min.css" />
<!--      <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.black.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.black.mobile.min.css" /> -->

    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/kendo.all.min.js"></script>
</head>
<body>
<div id="example">
<!--     <div class="box wide hidden-on-narrow">
        <div class="box-col">
            <button class="export-pdf btn" onclick="getPDF('.pdf-page')">Descargar</button>
        </div>
    </div>
 -->

<?php 
    foreach ($this->solicitud as $key) {
        $id = $key['id'];
        $name_sitio = $key['nombre_sitio'];
        $user = $key['user_solicitud'];
        $fecha = $key['user_fecha'];
        $motivo = $key['motivo'];
        $status_solicitud = $key['status'];
        $user_validacion = $key['validacion_user'];
        $fecha_validacion = $key['fecha_validacion'];
        $comentario_rechazo = $key['comentario'];
    } 
?>



<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12 text-right">
        <button class="export-pdf btn" onclick="getPDF('.pdf-page')">Descargar</button>
    </div>
</div>

    <?php 
            date_default_timezone_set('America/Mexico_City');
            $hoy = date("d/m/Y");
     ?>


    <div class="page-container hidden-on-narrow">
        <div class="pdf-page size-a4">
            <div class="pdf-header">
                <span class="company-logo">
                    <img src="/img/head.png" style="width: 120px;" />
                </span>

                <span class="invoice-number">
                    <img src="/img/logo-2.png" style="width: 125px;" /><br/>
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Solicitud No.<?php echo $this->id_solicitud; ?></span>
                </span>
                <div class="row">
                    <div class="company-logo col m12 s12 text-center">
                        Solicitud Horas Extra
                    </div>
                </div>
            </div>
            <div class="pdf-footer">
                <p>Nte 31-A No. 96, col. Lindavista Vallejo III, Gustavo A. Madero, C.P. 07720, CDMX<br />
                    Fecha de descarga: <?php echo $hoy; ?><br />
                </p>
            </div>
            <div class="for" style="margin-top: 70px;">
                    <div class="col m12 s12">
                        <span  style="font-size:14px;">Sitio: </span> 
                        <span  style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $name_sitio; ?></span> 
                        <br> 
                        <span  style="font-size:14px;">Usuario: </span>
                        <span  style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> <?php echo $user; ?></span>
                        <br> 
                        <span  style="font-size:14px;">Fecha: </span>
                        <span  style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $fecha; ?></span>
                    </div>
            </div>

            <div class="from" style="margin-top: 60px;">
                <!-- <h3>Proveedor</h3> -->
                <p style="padding-bottom: 17px;">
<!--                     <span class="title-pdf">Nombre:</span> <?php echo $nombre_prov; ?> <br />
                    <span class="title-pdf">Telefono:</span> <?php echo $telefono_prov; ?><br />
                    <span class="title-pdf">RFC:</span> <?php echo $rfc_prov; ?><br />
                    <span class="title-pdf">Datos Banco:</span> <?php echo $datos_prov; ?> <br />
                    <span class="title-pdf">Cuenta: <?php echo $cuenta_prov; ?></span> </br>
                    <span class="title-pdf">Tarjeta: <?php echo $tarjeta; ?></span></br>
                    <span class="title-pdf">Email:</span> <?php echo $email_prov; ?><br /> -->


                </p>

            </div>
            <div class="pdf-body">
<!--                 <div id="grid">
                	
                </div> -->
                <div class="row">
<!--                     <div class="text-center">
                        <span style="color:red; font-size: 10px;">DESCRIPCION BREVE DEL MATERIAL (SE TIENE QUE ADJUNTAR LA COTIZACION DEL PROVEEDOR).</span>
                    </div> -->
                	<div class="col m12 s12" style="margin-top: 35px;">
                         <table>
                            <thead>
                              <tr>
                                  <th><span class="title-pdf">Personal en la Cuadrilla</span></th>
                              </tr>
                            </thead>

                            <tbody>
                              <tr>
                                <!-- <td class="text-center"><?php echo $condiciones_compra; ?></td> -->
                              </tr>
                            </tbody>
                          </table>
                	</div>


                    <div class="col m12 s12">
                        <table class="table text-left table-hover">
                          <thead>
                            <tr>
                              <th>Nombre</th>
                              <th>Puesto</th>
                              <th>Horas extras</th>
                            </tr> 
                          </thead>
                          <?php
                          if ($this->personal) { 
                          foreach ($this->personal as $usr) { ?>
                          <tbody>
                            <tr>
                                <td>
                                    <span class="text-table"><?php echo $usr['nombre'] ?> <?php echo $usr['apellido_pa'] ?> <?php echo $usr['apellido_ma'] ?> </span>
                                </td>
                                <td>
                                    <span class="text-table"><?php echo $usr['puesto']; ?></span>
                                </td>

                                <td class="text-center">
                                    <span  style="font-size:12px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"> <?php echo $usr['hora_extra']; ?> Horas</span>
                                </td>

                                <td>
<!--                                    <div class="input-field col s12">
                                      <input id="first_name" name="hora_extra[]" value="<?php echo $usr['hora_extra']; ?>" max="100" min="0" type="hidden" class="validate">

                                      <input type="hidden" name="personal[]" value="<?php echo $usr['id_user']; ?>">
 -->            
                                    <?php if($status_solicitud == 0){ ?>
                                        <p>
                                          <label>
                                            <input type="checkbox" name="validar[]" value="<?php echo $usr['id_sol']; ?>" />
                                            <span></span>
                                          </label>
                                        </p>
                                    <?php }else{ ?>
                                        <?php if($usr['status_user'] == 1){ ?>
                                            <p>
                                              <label>
                                                <input type="checkbox" checked disabled />
                                                <span></span>
                                              </label>
                                            </p>
                                        <?php }else{ ?>
                                            <p>
                                              <label>
                                                <input type="checkbox" disabled />
                                                <span></span>
                                              </label>
                                            </p>
                                        <?php } ?>
                                    <?php } ?>
                                </td>

                            </tr>
                            <?php } }else{ ?>
                            </tbody> 
                            <tbody>
                                <tr>
                                    <td class="text-center" colspan="6"><h4>No se encontro personal asignado.</h4></td>
                                </tr>
                            </tbody>
                                        
                            <?php } ?>
                        </table>
                    </div>
                </div>

                <div class="row">
                </div>

                <div class="row signature">
                    <div class="col m12 s12 text-center">
                        <img src="/img/logo-2.png" style="width: 150px;"><br>
                        Aprobado: ING. Javier Morales Aguilera<br /><br />
                        <!-- <?php echo $newDate_jefe; ?> -->
                    </div>
                </div>


<!--                 <p class="signature">
                    Signature: ________________ <br /><br />
                    Date: 12.03.2014
                </p> -->
            </div>
        </div>
    </div>


    
    <div class="responsive-message"></div>

    <style>
        /*
            Use the DejaVu Sans font for display and embedding in the PDF file.
            The standard PDF fonts have no support for Unicode characters.
        */
        .pdf-page {
            font-family: "DejaVu Sans", "Arial", sans-serif;
        }
    </style>

    <script>
        // Import DejaVu Sans font for embedding

        // NOTE: Only required if the Kendo UI stylesheets are loaded
        // from a different origin, e.g. cdn.kendostatic.com
        kendo.pdf.defineFont({
            "DejaVu Sans"             : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans.ttf",
            "DejaVu Sans|Bold"        : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Bold.ttf",
            "DejaVu Sans|Bold|Italic" : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf",
            "DejaVu Sans|Italic"      : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf"
        });
    </script>

    <!-- Load Pako ZLIB library to enable PDF compression -->
    <script src="../content/shared/js/pako.min.js"></script>

    <script>
      function getPDF(selector) {
        kendo.drawing.drawDOM($(selector)).then(function(group){
          kendo.drawing.pdf.saveAs(group, "Solicitud Horas Extra No.<?php echo $this->id_solicitud; ?> .pdf");
        });
      }

    $(document).ready(function() {
        var data = [
          { productName: "QUESO CABRALES", unitPrice: 21, qty: 5 },
          { productName: "ALICE MUTTON", unitPrice: 39, qty: 7 },
          { productName: "GENEN SHOUYU", unitPrice: 15.50, qty: 3 },
          { productName: "CHARTREUSE VERTE", unitPrice: 18, qty: 1 },
          { productName: "MASCARPONE FABIOLI", unitPrice: 32, qty: 2 },
          { productName: "VALKOINEN SUKLAA", unitPrice: 16.25, qty: 3 }
        ];
        var schema = {
          model: {
            productName: { type: "string" },
            unitPrice: { type: "number", editable: false },
            qty: { type: "number" }
          },
          parse: function (data) {
                $.each(data, function(){
                    this.total = this.qty * this.unitPrice;
                });
                return data;
          }
        };
        var aggregate = [
          { field: "qty", aggregate: "sum" },
          { field: "total", aggregate: "sum" }
        ];
        var columns = [
          { field: "productName", title: "Product", footerTemplate: "Total"},
          { field: "unitPrice", title: "Price", width: 120},
          { field: "qty", title: "Pcs.", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" },
          { field: "total", title: "Total", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" }
        ];
        var grid = $("#grid").kendoGrid({
          editable: false,
          sortable: true,
          dataSource: {
            data: data,
            aggregate: aggregate,
            schema: schema,
          },
          columns: columns
        });

        $("#paper").kendoDropDownList({
          change: function() {
            $(".pdf-page")
              .removeClass("size-a4")
              .removeClass("size-letter")
              .removeClass("size-executive")
              .addClass(this.value());
          }
        });
    });
    </script>
    <style>

        .title-pdf{
            font-weight: bold;
            font-size: 13px;
        }
        .pdf-page {
            margin: 0 auto;
            box-sizing: border-box;
            box-shadow: 0 5px 10px 0 rgba(0,0,0,.3);
            background-color: #fff;
            color: #333;
            position: relative;
        }
        .pdf-header {
            position: absolute;
            top: .5in;
            height: .6in;
            left: .5in;
            right: .5in;
            /*border-bottom: 1px solid #e5e5e5;*/
        }
        .invoice-number {
            padding-top: .17in;
            float: right;
        }
        .pdf-footer {
            position: absolute;
            bottom: .5in;
            height: .6in;
            left: .5in;
            right: .5in;
            padding-top: 10px;
            border-top: 1px solid #e5e5e5;
            text-align: left;
            color: #787878;
            font-size: 12px;
        }
        .pdf-body {
            position: absolute;
            top: 2.9in;
            bottom: 1.2in;
            left: .5in;
            right: .5in;
        }

        .size-a4 { width: 8.3in; height: 11.7in; }
        .size-letter { width: 8.5in; height: 11in; }
        .size-executive { width: 7.25in; height: 10.5in; }

        .company-logo {
            font-size: 34px;
            font-weight: bold;
            color: #3aabf0;
        }
        .for {
            position: absolute;
            top: 1.5in;
            left: .5in;
            width: 3.5in;
        }
        .from {
            position: absolute;
            top: 1.5in;
            right: .5in;
            width: 3.5in;
        }
        .from p, .for p {
            color: #787878;
        }
        .signature {
            padding-top: .5in;
        }

        .text-table{
            font-size: 12px;
        }

.table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
    padding: 0px 10px;

    </style>

</div>


</body>
