<style type="text/css">
	.oculto{
		display: none;
	}
</style>
<?php foreach ($this->info_personal as $key) {
	$id = $key['id'];
	$nombre = $key['nombre'];
	$apellido_pa = $key['apellido_pa'];
	$apellido_ma = $key['apellido_ma'];
	$imagen = $key['imagen'];
	$telefono = $key['telefono'];
	$correo =$key['email_personal'];

} ?>

<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/asistencia/asistencia/sitio/<?php echo $this->sitio_name; ?>/proyecto/<?php echo $this->proyecto ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
</div>

<div class="row"> 
    <div class="col m12 s12 text-center" style="margin-top: 30px;">
        <span style="font-size:24px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Asistencia del Personal</span>
    </div>
</div>


<div class="row">
    <div class="col s12 m6">
      	<div class="card" style="height: 300px">
	        <div class="card-content" >
	        	<span style="font-size:19px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información del Personal</span>

	        	<div class="row" style="margin-top: 30px;">
	        		<div class="col m6 s6 text-center">
	        			<!-- <img src="/<?php echo $imagen;?>" style="width: 100px;">  -->
	        			<a class="example-image-link" href="/<?php echo $imagen; ?>" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $imagen; ?>"  alt="image-1" style="width: 100px;"/></a>
	        		</div>

	        		<div class="col m6 s6">
	        			<div class="row">
	        				<div class="col m12 s12 text-center">
			        			<span style="font-size:18px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
			        				<?php echo $nombre; ?>
			        			</span><br>
			        			<span style="font-size:18px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
			        				<?php echo $apellido_pa; ?> <?php echo $apellido_ma; ?>
			        			</span>
	        				</div>
	        			</div>
		        		<div class="row">
		        			<div class="col m12 s12">
		        				<span style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
			        				Puesto:
			        			</span> <?php echo $this->puesto_info; ?><br>
			        			<span style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
			        				Telefono:
			        			</span>  <?php echo $telefono; ?><br>
			        			<span style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
			        				Correo: 
			        			</span><?php echo $correo; ?> 
		        			</div>
		        		</div>
	        		</div>
	        	</div>
	        </div>
      </div>
    </div>


    <div class="col s12 m6">
      	<div class="card" style="height: 300px">
	        <div class="card-content">
	        	<span style="font-size:19px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Información del Sitio</span>

	        	<div class="row">
	        		<div class="col m12 s12" style="margin-top: 19px;">
	        			<?php if($this->if_sitio == 0){ ?>
	        			<?php }else{ ?>
	        				<?php foreach ($this->sitio_info as $key) {
	        					$nombre_sitio = $key['nombre'];
	        					$direccion = $key['direccion'];
	        					$estado = $key['estado'];
	        					$ciudad = $key['ciudad'];
	        				} ?>
	        				<span style="font-size:19px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $nombre_sitio; ?></span>

			        		<div class="row" style="margin-top: 20px;">
			        			<div class="col m12 s12">
				        			<span style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
				        				Ciudad: 
				        			</span> <?php echo $ciudad; ?> <br>
				        			<span style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
				        				Estado: 
				        			</span> <?php echo $estado; ?> <br>
				        			<span style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
				        				Dirección: 
				        			</span> <?php echo $direccion; ?>
			        			</div>
			        		</div>
	        			<?php } ?>
	        		</div>
	        	</div>
	        </div>
      	</div>
    </div>
</div>

<div class="row">
	<div class="col m6 s12">
		<div class="col m6 s6 text-center">
			<?php if($this->epp_op == 1){ ?>
				<a class="red btn modal-trigger" href="#modalepp">+ Cobro Epp</a>
			<?php } ?>
		</div>
		<div class="col m6 s6 text-center">
			<?php if($this->herramienta_op == 1){ ?>
				<a class="red btn modal-trigger" href="#modalherramienta">+ Cobro Herramienta</a>
			<?php } ?>
		</div>
	</div>
	<div class="col m6 s12 text-right">
		<div class="col m6 s6 text-center">
			<?php if($this->op_solicitud == 1){ ?>
				<a class="red btn modal-trigger" href="#modalprestamo">+ Descuento pendiente</a>
			<?php } ?>
		</div>
		<div class="col m6 s6 text-center">
			<a class=" btn modal-trigger" href="#modalasistencia">+ Horas Extra</a>
		</div>
	</div>
</div>

<!-- Modal Structure -->
<div id="modalasistencia" class="modal modal-fixed-footer">
    <div class="modal-content">
    	<span style="font-size:21px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar Asistencia</span>
	    <div class="row" style="margin-top: 30px;">
	        <form action="/personal/requestasistencia" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_adddayextra">
	        	<input type="hidden" name="user" value="<?php echo $this->personal_id; ?>">
	        	<input type="hidden" name="sitio" value="<?php echo $this->sitio_name; ?>">
	        	<input type="hidden" name="id_proyecto" value="<?php echo $this->proyecto; ?>">

	          	<div class="col m12 s12">
	          		<div class="row">
				        <div class="input-field col m6 s12">
				        	<input placeholder="" id="new_day" name="day" type="date" class="validate">
				        	<label for="edit_day">Día</label>
				        </div>    			
	          		</div>

			        <div class="row">
			        	<div class="col m6 s12">
			        		<div class="row">
			        			<div class="col m12 s12">
			        				<span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Datos Entrada</span>
			        			</div>
			        		</div>
							<div class="input-field col m12 s12">
							    <select id="new_proyecto" name="proyecto_entrada">
							      	<option value="0" disabled selected>* Selecciona un Proyecto</option>
							      	<?php foreach ($this->proyectos as $key){ ?>
							      		<option value="<?php echo $key['id']; ?>"><?php echo $key['nombre']; ?> / <?php echo $key['nombre_proyecto']; ?> - Cliente: <?php echo $key['id_cliente']; ?></option>
							      	<?php } ?>
							    </select>
							    <label>Proyecto entrada:</label>
							</div>
					        <div class="input-field col m12 s12">
					        	<input id="new_horaentrada" name="hora_entrada" type="time">
					        	<label for="new_horaentrada">Hora de entrada</label>
					        </div>

						    <div class="file-field input-field col m12 s12">
						    	<div class="btn">
						        	<span>Evidencia</span>
						        	<input type="file" name="url_entrada">
						    	</div>
						    	<div class="file-path-wrapper">
						        	<input class="file-path validate" type="text">
						    	</div>
						    </div>

			        	</div>

			        	<div class="col m6 s12">
			        		<div class="row">
			        			<div class="col m12 s12">
			        				<span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Datos Salida</span>
			        			</div>
			        		</div>

							<div class="input-field col m12 s12">
							    <select id="new_proyectosalida" name="proyecto_salida">
							      	<option value="0" disabled selected>* Selecciona un Proyecto</option>
							      	<?php foreach ($this->proyectos as $key){ ?>
							      		<option value="<?php echo $key['id']; ?>"><?php echo $key['nombre']; ?> / <?php echo $key['nombre_proyecto']; ?> - Cliente: <?php echo $key['id_cliente']; ?></option>
							      	<?php } ?>
							    </select>
							    <label>Proyecto entrada:</label>
							</div>

					        <div class="input-field col m12 s12">
					        	<input id="new_horasalida" name="hora_salida" type="time" >
					        	<label for="new_horasalida">Hora de Salida</label>
					        </div>	

						    <div class="file-field input-field col m12 s12">
						    	<div class="btn">
						        	<span>Evidencia</span>
						        	<input type="file" name="url_salida">
						    	</div>
						    	<div class="file-path-wrapper">
						        	<input class="file-path validate" type="text">
						    	</div>
						    </div>
			        	</div>
	
			        </div>
	          	</div>
	        </form>
	    </div>  
    </div>
    <div class="modal-footer">
        <button type="button" id="add_newasistencia" class="btn">Guardar</button>
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>
          

  <div id="modalprestamo" class="modal modal-fixed-footer">
    <div class="modal-content">
    	<span style="font-size:21px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Descuento</span>
    	<div class="row">
    		<div class="col m12 s12">
		    <form action="/prestamo/requestaplicarprestamo" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_addprestamo">
		        	<input type="hidden" id="user_prestamo" name="user" value="<?php echo $this->personal_id; ?>">
		        	<input type="hidden" name="sitio" value="<?php echo $this->sitio_name; ?>">
		        	<input type="hidden" name="id_proyecto" value="<?php echo $this->proyecto; ?>">
		      <table class="table text-left table-hover">
		          <thead>
		            <tr style="background-color: #EDEDED">
		                <th>NO.</th>
		                <th>Fecha Descuento</th>
		                <th>Monto Total</th> 
		                <th>Cantidad</th>
		                <th>Pagos</th>
		                <th>Descuento</th>
		                <th></th>
		            </tr> 
		          </thead>
		          <?php
		          if ($this->solicitud_prestamo) { 
		          foreach ($this->solicitud_prestamo as $usr) { ?>
		          <tbody>
		            <tr>
		              <td><?php echo $usr['id']; ?></td>
		              <td><?php echo $usr['fecha_prestamo']; ?></td>
		              <td>
		                <span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($usr['monto'], 2, '.', ','); ?></span>
		              </td>
		              <td>
		                <?php echo $usr['cantidad_pagos']; ?>
		              </td>
		              <td>
		                <?php echo $usr['cantidad_saldada']; ?>
		              </td>
		              	<?php 
		              		$monto_pago = $usr['monto'] / $usr['cantidad_pagos'];
		              	?>

		              <td>
		              	<span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($monto_pago, 2, '.', ','); ?></span>
		              </td>
		              <td>
		              	<?php if($usr['cantidad_pagos'] == $usr['cantidad_saldada']){ ?>
		              	<?php }else{ ?>
		 					<p>
								<label>
									<input type="checkbox" class="check_prestamo" name="validar[]" value="<?php echo $usr['id']; ?>" />
									<span></span>
								</label>
							</p>
						<?php } ?>
		              </td>
		            </tr>
		          <?php } }else{ ?>
		          </tbody> 
		        <tbody>
		            <tr>
		                <td class="text-center" colspan="6"><h4>No hay solicitudes de Prestamos.</h4></td>
		            </tr>
		        </tbody>
		                    
		        <?php } ?>
		    </table>
		  	</form>
    	</div>
    	</div>
    </div>
    <div class="modal-footer">
    	<button type="button" id="add_newprestamo" class="btn oculto">Aplicar Descuento</button>
        <button  class="modal-close red btn">Cerrar</button>
    </div>
  </div>

  <!-- Modal Structure -->
  	<div id="modalherramienta" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<div class="row">
	    		<div class="col m12 s12">
	    			<span style="font-size:21px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Herramienta</span>
	    		</div>
	    	</div>

	    	<div class="row">
	    		<div class="col m12 s12">
		    		<form action="/herramienta/requestaplicarcobroherramienta" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_addherramienta">
		        	<input type="hidden" id="user_prestamo" name="user" value="<?php echo $this->personal_id; ?>">
		        	<input type="hidden" name="sitio" value="<?php echo $this->sitio_name; ?>">
		        	<input type="hidden" name="id_proyecto" value="<?php echo $this->proyecto; ?>">
				    <table class="table text-left table-hover">
				          <thead>
				            <tr style="background-color: #EDEDED">
				                <th>NO.</th>
				                <th>Codigo Herramienta</th>
				                <th>Herramienta</th> 
				                <th>Monto</th>
				                <th>Parcialidad</th>
				                <th>Pagos</th>
				                <th>Descuento</th>
				                <th></th>
				            </tr> 
				          </thead>
				          <?php
				          if ($this->herramienta_cobro) { 
				          foreach ($this->herramienta_cobro as $usr) { ?>
				          <tbody>
				            <tr>
				              <td><?php echo $usr['id_cobro']; ?></td>
				              <td><?php echo $usr['codigo']; ?></td>
				              <td><?php echo $usr['nombre']; ?></td>
				              <td>
				                <span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($usr['monto_pago'], 2, '.', ','); ?></span>
				              </td>
				              <td>
				                <?php echo $usr['parcialidad']; ?>
				              </td>
				              <td>
				                <?php echo $usr['cantidad_pago']; ?>
				              </td>
				              	<?php 
				              		$monto_pago = $usr['monto_pago'] / $usr['parcialidad'];
				              	?>

				              <td>
				              	<span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($monto_pago, 2, '.', ','); ?></span>
				              </td>
				              <td>
				              	<?php if($usr['parcialidad'] == $usr['cantidad_pago']){ ?>
				              	<?php }else{ ?>
				 					<p>
										<label>
											<input type="checkbox" class="check_herramienta" name="validar[]" value="<?php echo $usr['id_cobro']; ?>" />
											<span></span>
										</label>
									</p>
								<?php } ?>
				              </td>
				            </tr>
				          <?php } }else{ ?>
				          </tbody> 
				        <tbody>
				            <tr>
				                <td class="text-center" colspan="6"><h4>No hay herramientas por cobrar.</h4></td>
				            </tr>
				        </tbody>
				                    
				        <?php } ?>
				    </table>
					</form>
	    		</div>
	    	</div>
	    </div>
	    <div class="modal-footer">
	    	<button type="button" id="add_newherramienta" class="btn oculto">Aplicar Descuento</button>
	     	<button  class="modal-close red btn">Cerrar</button>
	    </div>
  	</div>


  	<div id="modalepp" class="modal modal-fixed-footer">
	    <div class="modal-content">
	    	<div class="row">
	    		<div class="col m12 s12">
	    			<span style="font-size:21px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Cobro EPP</span>
	    		</div>
	    	</div>

	    	<div class="row">
	    		<div class="col m12 s12">
		    		<form action="/epp/requestaddeppnominauser" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_addepp">
		        	<input type="hidden" id="user_prestamo" name="user" value="<?php echo $this->personal_id; ?>">
		        	<input type="hidden" name="sitio" value="<?php echo $this->sitio_name; ?>">
		        	<input type="hidden" name="id_proyecto" value="<?php echo $this->proyecto; ?>">
				    <table class="table text-left table-hover">
				          <thead>
				            <tr style="background-color: #EDEDED">
				                <th>NO.</th>
				                <th>Cantidad</th>
				                <th>Descripción</th> 
				                <th>Talla</th>
				                <th>Monto</th>
				                <th>Parcialidad</th>
				                <th>Pagos</th>
				                <th>Descuento</th>
				                <th></th>
				            </tr> 
				          </thead>
				          <?php
				          if ($this->nomina_epp) { 
				          foreach ($this->nomina_epp as $usr) { ?>
				          <tbody>
				            <tr>
				              <td><?php echo $usr['id']; ?></td>
				              <td><?php echo $usr['cantidad']; ?></td>
				              <td><?php echo $usr['descripcion']; ?></td>
				              <td><?php echo $usr['talla']; ?></td>
				              <td>
				                <span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($usr['monto_pago'], 2, '.', ','); ?></span>
				              </td>
				              <td>
				                <?php echo $usr['parcialidad']; ?>
				              </td>
				              <td>
				                <?php echo $usr['cantidad_pago']; ?>
				              </td>
				              	<?php 
				              		$monto_pago = $usr['monto_pago'] / $usr['parcialidad'];
				              	?>

				              <td>
				              	<span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($monto_pago, 2, '.', ','); ?></span>
				              </td>
				              <td>
				              	<?php if($usr['parcialidad'] == $usr['cantidad_pago']){ ?>
				              	<?php }else{ ?>
				 					<p>
										<label>
											<input type="checkbox" class="check_epp" name="validar[]" value="<?php echo $usr['id']; ?>" />
											<span></span>
										</label>
									</p>
								<?php } ?>
				              </td>
				            </tr>
				          <?php } }else{ ?>
				          </tbody> 
					        <tbody>
					            <tr>
					                <td class="text-center" colspan="6"><h4>No hay herramientas por cobrar.</h4></td>
					            </tr>
					        </tbody>
				                    
				        	<?php } ?>
				    </table>
					</form>
	    		</div>
	    	</div>
	    </div>
	    <div class="modal-footer">
	    	<button type="button" id="add_newepp" class="btn oculto">Aplicar Descuento</button>
	     	<button  class="modal-close red btn">Cerrar</button>
	    </div>
  	</div>

<!-- <div class="row">
    <div class="col s12 m12">
      	<div class="card">
	        <div class="card-content">
	          <span style="font-size:19px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Asistencia</span>
	          <div class="row">
	          	<form action="/personal/requestasistencia" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_addperson">
	          	<div class="col m12 s12">
			        <div class="input-field col m6 s12">
			        	<input id="hora_entrada" name="hora_entrada" type="time">
			        	<label for="hora_entrada">Hora de entrada</label>
			        </div>	

			        <div class="input-field col m6 s12">
			        	<input id="hora_salida" name="hora_salida" type="time" >
			        	<label for="hora_salida">Hora de Salida</label>
			        </div>	
	          	</div>
	          	</form>
	          </div>

	          <div class="row">
	          	<div class="col m12 s12 text-center">
	          		<a class="btn" id="addhoras"><i class="material-icons right">access_time</i>Guardar</a>
	          	</div>
	          </div>

	        </div>
      	</div>
    </div>
</div> -->


<div class="row">
    <div class="col s12 m12">
      <div class="card">
        <div class="card-content">
        	<div class="row">
				<div class="col m6 s6">
					<span  style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Registro de la asistencia</span>
				</div>
				<div class="col m6 s6 text-right">
					  <!-- <a class="btn-floating btn-medium green" href="/asistencia/historialnomina/id/<?php echo $this->personal_id ?>"><i class="material-icons">access_time</i></a> -->
				</div>
        	</div>
			<div class="row">
				<div class="col m12 s12"> 
			        <table class="table text-left table-hover">
			            <thead>
			                <tr style="background-color: #EDEDED">
								<th>Sitio</th>
								<th>Asistencia</th>
								<th>Entrada</th>
								<th>Salida</th>
								<th>Horas trabajadas</th>
								<th>Pago</th>
								<th></th>
								<th></th>
			                </tr> 
			            </thead>

			            <?php 
			            $montos = 0;
			            if ($this->asistencia) { 
			                foreach ($this->asistencia as $usr) { ?>
			            <tbody>
			                <tr>
			                	<td>
			                		<?php echo $usr['nombre']; ?>
			                	</td>
			                	<td>
			                		<?php echo $usr['dia']; ?>
			                	</td>

			                	<?php if($usr['status_asistencia'] == 0){ ?>
			                	<td>
			                		<?php if($usr['status_tipos'] == 0){ ?>
			                			<?php echo $usr['hora_entrada']; ?>
			                		<?php }?>

			                		<?php if($usr['status_tipos'] == 1){ ?>
			                			Descuento
			                		<?php }?>

			                		<?php if($usr['status_tipos'] == 2){ ?>
			                			Herramientas
			                		<?php }?>

			                		<?php if($usr['status_tipos'] == 3){ ?>
			                			EPP
			                		<?php }?>
			                	</td>
			                	<td>
			                		<?php if($usr['solicitud_prestamo'] == 0){ ?>
			                			<?php echo $usr['hora_salida']; ?>
			                		<?php }?>

			                		<?php if($usr['status_tipos'] == 1){ ?>
			                			Descuento
			                		<?php }?>

			                		<?php if($usr['status_tipos'] == 2){ ?>
			                			Herramientas
			                		<?php }?>

			                		<?php if($usr['status_tipos'] == 3){ ?>
			                			EPP
			                		<?php }?>

			                	</td>
			                        <?php 
			                            $datetime1 = new DateTime($usr['hora_entrada']);
			                            $datetime2 = new DateTime($usr['hora_salida']);
			                            $interval = $datetime1->diff($datetime2);
			                            $diferencia = $interval->format("%H:%I");
			                        ?>
			                  	<td>
			                  		<?php echo $diferencia; ?> Hrs
			                  	</td>

			                  	<td>
			                  	<?php if($usr['solicitud_prestamo'] == 0){ ?>
			                  		<?php if($usr['status_extra'] == 0){ ?>

			                  		<?php 
				                  		if($usr['dia_pago'] == "" || $usr['dia_pago'] == NULL){
				                  			$dia_pago = 0;
				                  		}else{
				                  			$dia_pago = $usr['dia_pago'];
				                  		} 
			                  		?>

		                  			<?php 
				                  		if($usr['hora_pago'] == "" || $usr['hora_pago'] == NULL){
				                  			$hora_pago = 0;
				                  		}else{
				                  			$hora_pago = $usr['hora_pago'];
				                  		} 
			                  		?>

			                  		<?php 
			                  			if($usr['day_num'] == 6 || $usr['day_num'] == 7){
			                  				$rest = substr($diferencia, 0, -3);

			                  				if($rest == 5){
			                  					$monto = $dia_pago;
			                  				}

				                  			if($rest <= 9){
				                  				$total = $rest - 5;
				                  				$suma = $total * $hora_pago;
				                  				$monto = $dia_pago + $suma;
				                  				// echo "menor";
				                  			}

			                  				if($rest == 10){
			                  					$monto = $dia_pago * 2;
			                  				}

				                  			if($rest > 10){
				                  				$total = $rest - 10;
				                  				$suma = $total * $hora_pago;
				                  				$dia = $dia_pago*2;

				                  				$monto = $dia + $suma;
				                  				// echo "menor";
				                  			}


			                  			}else{
				                  			$rest = substr($diferencia, 0, -3);
				                  			if($rest < 10){
				                  				$total = $rest - 2;
				                  				$monto = $total * $hora_pago;
				                  				// echo "menor";
				                  			}

				                  			if($rest > 10){
				                  				$total = $rest - 10;
				                  				$multi = $total * $hora_pago;
				                  				$monto = $dia_pago + $multi;
				                  				// echo "mayor";
				                  			}

				                  			if($rest == 10){
				                  				$monto = $dia_pago;
				                  				// echo "igual";
				                  			}

			                  			}
			                  		?>

			                  	<?php }else{ ?>
			                  		<!-- D I A  E X T R A -->
			                  		<?php 
			                  			if($usr['day_num'] == 6 || $usr['day_num'] == 7){
			                  				$rest = substr($diferencia, 0, -3);

			                  				if($rest == 5){
			                  					$monto = 0;
			                  				}

				                  			if($rest <= 9){
				                  				$total = $rest - 5;
				                  				$monto = $total * $hora_pago;
				                  				// echo "menor";
				                  			}

			                  				if($rest == 10){
			                  					$monto = 0;
			                  				}

				                  			if($rest > 10){
				                  				$total = $rest - 10;
				                  				$suma = $total * $hora_pago;
				                  				$dia = $dia_pago*2;

				                  				$monto = $suma;
				                  				// echo "menor";
				                  			}


			                  			}else{
				                  			$rest = substr($diferencia, 0, -3);
				                  			if($rest < 10){
				                  				$total = $rest - 2;
				                  				$monto = $total * $hora_pago;
				                  				// echo "menor";
				                  			}

				                  			if($rest > 10){
				                  				$total = $rest - 10;
				                  				$multi = $total * $hora_pago;
				                  				$monto = $multi;
				                  				// echo "mayor";
				                  			}

				                  			if($rest == 10){
				                  				$monto = 0;
				                  				// echo "igual";
				                  			}

			                  			}
			                  		?>

			                  	<?php  } ?>
			                <?php }else{ ?>

			                	<?php $monto = $usr['monto_pago']; ?>
			                <?php } ?>

			                  	<?php if($usr['status_extra'] == 0){ ?>	
			                  		<span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($monto, 2, '.', ','); ?></span>
			                  	<?php }else{ ?>
			                  		<span  style="font-size:15px; color: green; letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($monto, 2, '.', ','); ?></span>
			                  	<?php } ?>
			                  		
			                  	</td>
			                  <?php }else{ ?>
			                  	<td>00:00</td>
			                  	<td>00:00</td>
			                  	<td>Inasistencia</td>
			                  	<td>
			                  		<?php $monto = 0; ?>
			                  		<span  style="font-size:15px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">$<?php echo number_format($monto, 2, '.', ','); ?></span>
			                  	</td>
			                  <?php } ?>
			                  	<td>
			                  		<a class="delete modal-trigger" data-id="<?php echo $usr["id_pa"]; ?>" data-name="<?php echo $usr['name_personal']; ?> <?php echo $usr['apellido_pa']; ?> <?php echo $usr['apellido_ma']; ?>" data-sitio="<?php echo $usr['nombre']; ?>" data-diapago="<?php echo $usr['dia_pago']; ?>" data-horapago="<?php echo $usr['hora_pago']; ?>" data-dia="<?php echo $usr['day_num']; ?>" data-today="<?php echo $usr['dia']; ?>" data-eventrada="/<?php echo $usr['ev_entrada']; ?>" data-hentrada="<?php echo $usr['hora_entrada']; ?>" data-evsalida="/<?php echo $usr['ev_salida']; ?>" data-hsalida="<?php echo $usr['hora_salida']; ?>" href="#modaldelete"><span class="warning"><i class="fa fa-2x fa-address-card-o" ></i></span></a>
			                  	</td>

			                  	<td>
			                		<?php if($usr['status_tipos'] == 0){ ?>
			                			<a href="/asistencia/editregistroasistencia/user/<?php echo $this->personal_id; ?>/sitio/<?php echo $this->sitio_name; ?>/id/<?php echo $usr['id_pa'] ?>/proyecto/<?php echo $this->proyecto ?>"><i class="fa fa-2x fa-pencil-square-o" ></i></a>
			                			<a class="delete_registro" data-id="<?php echo $usr["id_pa"]; ?>" data-op="2"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red; padding-left: 7px;"></i></span></a>
			                		<?php }?>

			                		<?php if($usr['status_tipos'] == 1){ ?>
			                			<a class="delete_file" data-id="<?php echo $usr["id_pa"]; ?>" data-op="1"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
			                			<!-- DESCUENTO -->
			                		<?php }?>

			                		<?php if($usr['status_tipos'] == 2){ ?>
			                			<a class="delete_file" data-id="<?php echo $usr["id_pa"]; ?>" data-op="2"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
			                			<!-- HERRAMIENTA -->
			                		<?php }?>

			                		<?php if($usr['status_tipos'] == 3){ ?>
			                			<a class="delete_file" data-id="<?php echo $usr["id_pa"]; ?>" data-op="3"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
			                			<!-- EPP -->
			                		<?php }?>
			                  	</td>

			                  	<?php $montos = $montos + $monto; ?>
			                </tr>
			            </tbody>
			            <?php } }else{ ?>
			            <tbody>
			                <tr>
			                    <td><h3>No hay registros de la asistencia</h3> </td>
			                    <td></td>
			                    <td></td>
			                    <td></td>
			                    <td></td>
			                </tr>
			            </tbody>
			            <?php } ?>
			        </table>
				</div>
			</div>

        	<div class="row">
        		<div class="col m6 s6"></div>
        		<div class="col m6 s6 text-right">
        			<span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Total: <!-- $<?php echo $montos; ?> -->
        				$<?php echo number_format($montos, 2, '.', ','); ?>
        			</span>
        		</div>
        	</div>

        </div>


        <div class="card-action">
        	<div class="row">
        		<div class="col m12 s12 text-center">
					<a class="btn modal-trigger" href="#modal1">Generar Nomina</a>
        		</div>
        	</div>
        </div>

      </div>
    </div>
</div>

<div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
    	<span style="font-size:24px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Generar Nomina</span>

    	<div class="row">
    		<div class="col m12 s12">
    			<form action="/asistencia/requestaddsolicitudnomina" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_addnomina">
    				<input type="hidden" name="sitio" id="form_sitio" value="<?php echo $this->sitio_name; ?>">
    				<input type="hidden" name="user" id="form_user" value="<?php echo $this->personal_id; ?>">
    				<input type="hidden" name="id_proyecto" id="form_proyecto" value="<?php echo $this->proyecto; ?>">
    				<input type="hidden" name="monto" value="<?php echo $montos; ?>">
    			</form>
    		</div>
    	</div>

    </div>
    <div class="modal-footer">
        <button type="button" id="add_generarnomina" class="btn">Generar</button>
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>


<!-- Modal Structure -->
<div id="modaldelete" class="modal modal-fixed-footer">
    <div class="modal-content">
        <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Detalle de la Asistencia</span>
        <div class="row div_info">
        	<div class="col m8 s12" style="margin-top: 20px;">
				<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Sitio Actual:</span> <span id="sitio_modal"></span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nombre:</span> <span id="name_modal"></span> <br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Día Pago:</span> $<span id="diapago_modal"></span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Hora Pago:</span> $<span id="horapago_modal"></span><br>

        		<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Día Asistencia:</span> <span id="dia_modal"></span> <span id="today_modal"></span><br>
        	</div>

        	<div class="col m4 s12 text-center">
        		
        	</div>
        </div>

        <div class="row div_info">
        	<div class="col m6 s12 text-center">
        		<div>
        			<span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Entrada:</span> 
        		</div>
        		<div>
        			<span id="hentrada_modal"></span>
        		</div>
        		<a class="example-image-link" id="href_entrada" data-lightbox="example-1"><img class="example-image" id="img_entrada" alt="image-1" style="width: 250px; height: 150px;"/></a>	  
        	</div>
        	<div class="col m6 s12 text-center">
        		<div>
        			<span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Salida:</span> 
        		</div>
        		<div>
        			<span id="hsalida_modal"></span>
        		</div>
        		<a class="example-image-link" id="href_salida" data-lightbox="example-1"><img class="example-image" id="img_salida" alt="image-1" style="width: 250px; height: 150px;"/></a>	  
        	</div>
        </div>

        <div class="row div_editinfo oculto">
        	<div class="col m12 s12"  style="margin-top: 20px;">
        		<a id="back_info" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>   
        	</div>
        </div>

        <div class="row div_editinfo oculto">
        	<div class="col m12 s12" style="margin-top: 20px;">
		        <div class="input-field col s6">
		        	<input placeholder="" id="edit_day" type="date" class="validate">
		        	<label for="edit_day">Día</label>
		        </div>
				<div class="input-field col s6">
				    <select id="proyecto" name="proyecto">
				      	<option value="0" disabled selected>* Selecciona un Proyecto</option>
				      	<?php foreach ($this->proyectos as $key){ ?>
				      		<option value="<?php echo $key['id']; ?>"><?php echo $key['nombre']; ?> / <?php echo $key['nombre_proyecto']; ?> - Cliente: <?php echo $key['id_cliente']; ?></option>
				      	<?php } ?>
				    </select>
				    <label>Proyecto:</label>
				</div>

			    <div class="input-field col m6 s12">
			        <input id="hora_entrada" name="hora_entrada" type="time">
			        <label for="hora_entrada">Hora de entrada</label>
			    </div>	

			    <div class="input-field col m6 s12">
			       	<input id="hora_salida" name="hora_salida" type="time" >
			       	<label for="hora_salida">Hora de Salida</label>
			    </div>

        	</div>
        </div>

    </div>
    <div class="modal-footer">
        <!-- <button type="button" id="add_inasistencia" class="btn">Guardar</button> -->
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>


<script src="/js/lightbox.js"></script>
<script type="text/javascript">
  	$(document).ready(function(){
  		$('.timepicker').timepicker();
    	$('.modal').modal();
    	$('.datepicker').datepicker( {"format":'dd-mm-yyyy'});
    	var currentDate = document.getElementById("today_picker").value; 
    	$('.datepicker').datepicker( {"format":'dd-mm-yyyy'} ).datepicker("setDate",currentDate);

    	$('select').formSelect();
    	$('.collapsible').collapsible();
    	$('.dropdown-trigger').dropdown();
  	});


    $("#addhoras").click(function(){
        var hora_entrada = document.getElementById("hora_entrada").value;
        var hora_salida = document.getElementById("hora_salida").value;

        if(hora_entrada == "" ||  hora_salida == ""){
            swal({
                title: "Para asignar al personal es necesario llenar los datos",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submitForm, 1500);     
        }
    });
    function submitForm() { document.getElementById("submit_addperson").submit() }

    $(".delete").click(function(){
    	var id = $(this).data('id');
    	var name = $(this).data('name');
    	document.getElementById("name_modal").innerHTML=name;

    	var sitio = $(this).data('sitio');
    	document.getElementById("sitio_modal").innerHTML=sitio;

    	var diapago = $(this).data('diapago');
    	document.getElementById("diapago_modal").innerHTML=diapago;

    	var horapago = $(this).data('horapago');
    	document.getElementById("horapago_modal").innerHTML=horapago;

    	var dia = $(this).data('dia');
    	if(dia == 1){ day = "Lunes";} if(dia == 2){ day = "Martes";} if(dia == 3){ day = "Miercoles";}
    	if(dia == 4){ day = "Jueves";} if(dia == 5){ day = "Viernes";} if(dia == 6){ day = "Sabado";}
    	if(dia == 7){ day = "Domingo";}
    	document.getElementById("dia_modal").innerHTML=day;

    	var today = $(this).data('today');
    	document.getElementById("today_modal").innerHTML= "("+today+")";
    	document.getElementById("edit_day").value = today;

    	var img = document.getElementById("img_entrada");
    	var entrada = $(this).data('eventrada');
    	img.src=entrada;

    	var element =document.getElementById("href_entrada");
    	element.href =entrada;

    	var hentrada = $(this).data('hentrada');
    	document.getElementById("hentrada_modal").innerHTML=hentrada;

    	var imgs = document.getElementById("img_salida");
    	var salida = $(this).data('evsalida');
    	imgs.src=salida;

    	var elements =document.getElementById("href_salida");
    	elements.href =salida;

    	var hsalida = $(this).data('hsalida');
    	document.getElementById("hsalida_modal").innerHTML=hsalida;
    });


    $("#edit_registro").click(function(){
    	$(".div_info").hide();
    	$(".div_editinfo").show();
    });

    $("#back_info").click(function(){
    	$(".div_info").show();
    	$(".div_editinfo").hide();
    });

    $("#add_newasistencia").click(function(){
    	var day = document.getElementById("new_day").value;
    	var proyecto = document.getElementById("new_proyecto").value;
    	var entrada = document.getElementById("new_horaentrada").value;
    	var salida = document.getElementById("new_horasalida").value;

        if(day == "" ||  proyecto== 0 || entrada == "" || salida == ""){
            swal({
                title: "Para continuar es neceario agregar la información solicitada",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submitnewhoraextra, 1500);     
        }
    });
    function submitnewhoraextra() { document.getElementById("submit_adddayextra").submit() }


    $("#add_generarnomina").click(function(){
    	var form_sitio = document.getElementById("form_sitio").value;
    	var form_user = document.getElementById("form_user").value;
    	var form_proyecto = document.getElementById("form_proyecto").value;

        if(form_sitio == "" ||  form_user== "" || form_proyecto == "" ){
            swal({
                title: "Para continuar es neceario agregar la información solicitada",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submitnomina, 1500);     
        }
    });
    function submitnomina() { document.getElementById("submit_addnomina").submit() }

    $(".check_prestamo").click(function(){
    	$("#add_newprestamo").show();
    });

    $("#add_newprestamo").click(function(){
    	var user_prestamo = document.getElementById("user_prestamo").value; 

        if(user_prestamo == ""){
            swal({
                title: "Para continuar es neceario agregar la información solicitada",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submit_addprestamo, 1500);     
        }
    });
    function submit_addprestamo() { document.getElementById("submit_addprestamo").submit() }

    $(".check_herramienta").click(function(){
    	$("#add_newherramienta").show();
    });

    $("#add_newherramienta").click(function(){
    	var user_prestamo = document.getElementById("user_prestamo").value; 

        if(user_prestamo == ""){
            swal({
                title: "Para continuar es neceario agregar la información solicitada",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submit_addherramienta, 1500);     
        }
    });
	function submit_addherramienta() { document.getElementById("submit_addherramienta").submit() }


    $(".check_epp").click(function(){
    	$("#add_newepp").show();
    });

    $("#add_newepp").click(function(){
    	var user_prestamo = document.getElementById("user_prestamo").value; 

        if(user_prestamo == ""){
            swal({
                title: "Para continuar es neceario agregar la información solicitada",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submit_addepp, 1500);     
        }
    });
	function submit_addepp() { document.getElementById("submit_addepp").submit() }


    $(".delete_file").click(function(){
    	var id = $(this).data('id');
    	var op = $(this).data('op');

		swal({
			title: "Estas seguro de eliminar el registro?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				});
	            var request = $.ajax({
	                url:"/asistencia/requestdeleteregistroasistencianomina",
	                method:"POST",
	                data: { id : id, op : op},
	                processData: true,
	            });
				//-------------------end de ajax---------------------------
				//---------	----peticion de respuesta de ajax------------------
	            request.done(function(response) {
	                console.log(response);//imprime lo que responde el ajax
	                window.location.reload(true);
	            });
				//-------------------end de respuesta ajax---------------------
	             return false;
		  	} else {
		    	swal("La asignacion fue cancelada!");
		  	}
		});
    });

    $(".delete_registro").click(function(){
    	var id = $(this).data('id');
		swal({
			title: "Estas seguro de eliminar el registro?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				});
	            var request = $.ajax({
	                url:"/asistencia/requestdeleteregistronominanormal",
	                method:"POST",
	                data: { id : id},
	                processData: true,
	            });
				//-------------------end de ajax---------------------------
				//---------	----peticion de respuesta de ajax------------------
	            request.done(function(response) {
	                console.log(response);//imprime lo que responde el ajax
	                window.location.reload(true);
	            });
				//-------------------end de respuesta ajax---------------------
	             return false;
		  	} else {
		    	swal("La asignacion fue cancelada!");
		  	}
		});
    });


</script>