<?php foreach ($this->archivoedit2 as $archivo) { $id_cliente=$archivo['id_cliente']; $id_carpeta=$archivo['id_carpeta'];}?>
<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/clientes/subcarpeta/id/<?php echo $id_carpeta; ?>/cliente/<?php echo $id_cliente; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
    </div>
</div>

<div class="row">
	<div class="col m12 s12 text-center" style="margin-top: 10px;">
		<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Editar Archivo
	</div>
</div>

<div class="col m12 s12">
	<form action="/clientes/requestupdatearchivos" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_archivo">
		<?php foreach ($this->archivoedit2 as $archivo) { ?>
			<input type="hidden" name="idarchivo" value="<?php echo $archivo["id"]; ?>">
			<input type="hidden" name="id_cliente" value="<?php echo $archivo["id_cliente"]; ?>">
			<input type="hidden" name="idcta" value="<?php echo $archivo["id_carpeta"]; ?>">
				<div class="row">
			        <div class="input-field col m6 s12">
			          	<i class="material-icons prefix">account_circle</i>
			          	<input id="name" type="text" name="name" value="<?php echo $archivo["nombre_archivo"]; ?>" class="validate" required>
			          	<label for="name">* Nombre Documento:</label>
			        </div> 
			        <div class="input-field col m6 s12">
				       	<i class="material-icons prefix">account_circle</i>
				       	<input id="fecha" type="date" name="fecha" value="<?php echo $archivo["fecha"]; ?>" required>
				       	<label for="fecha">Fecha Documento: dd/mm/yyyy</label>
				    </div>
		      	</div>

		      	
		      	<div class="file-field input-field col m12 s12">
		      	 	<div class="btn">
		      	 		<span>Actualiza documento</span>
					    <input type="file" name="url">
					    <input type="hidden" name="imahidden" value="<?php echo $archivo["archivo"]; ?>">   
					</div>
					<div class="file-path-wrapper">
					    <input class="file-path validate" type="text">
					</div>
				</div>
		<?php } ?>
	</form>
</div>

<div class="input-field col m12 s12 text-right">
	<div class="row">
		<a href="/clientes/subcarpeta/id/<?php echo $id_carpeta; ?>/cliente/<?php echo $id_cliente; ?>" class="waves-effect red waves-light btn">Cancelar</a>
		<button  id="udparchivo" class="waves-effect waves-light btn">Actualizar</button>
	</div>	
</div>


<script type="text/javascript">


    $("#udparchivo").click(function(){
        var name = document.getElementById("name").value;

        if(name == "" ){
            swal({
                title: "Para un archivo llena los datos requeridos(*)",
            });
        }else{
             swal("Espera un momento, la información esta siendo procesada", {
				icon: "success",
			 	buttons: false,
			});
            setTimeout(submitForm, 500);     
        }

    });


    function submitForm() {
        document.getElementById("submit_archivo").submit()
    }
</script>