<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 
 
    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }
?>

<?php foreach ($this->user as $value) {
    $rol_user = $value['fkroles'];
} ?>

<!-- Inicio Botones -->
<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6"> </div>
    <?php if ($rol_user == 1 || $rol_user == 8) { ?>
        <div class="col m6 s6 text-right">
            <a class="waves-effect green btn modal-trigger" href="#modal1">+ Agregar Cliente</a>
	      </div>
	<?php } else { } ?>
</div>
 
<div class="row">
    <div class="col m12 s12 text-center" style="margin-top: 10px;">
        <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Documentación
    </div>
</div>
<!-- End Inicio Botones -->


<!-- Buscador -->

<div class="row">
	  <div class="col m2 s12"></div>
	 
    <div class="col m8 s12">
		  <form action="/clientes/busquedaclt" enctype="multipart/form-data" class="form-horizontal form-material">
          <div class="input-field col m8 s8">
              <input placeholder="Ingresa nombre" name="nombre" id="first_name" type="text" class="validate" required>
	            <label for="first_name">Buscar Cliente</label>
	        </div>
	        
          <div class="input-field col m4 s4">
	        	  <button tyle="submit" id="add_user" class="waves-effect waves-light btn">Buscar<i class="material-icons left">search</i></button>
	        </div>
    	</form>
	  </div>
	  
    <div class="col m2 s12"></div>

</div>

<!-- End Buscador -->

<!-- Modal Structure 1 -->
<div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
        <div class="col m12 s12" style="margin-top: 10px;">
            <span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar Cliente
        </div>

        <div class="col m12 s12">
            <form action="/clientes/requestaddcliente" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_clt">
                <div class="row">
                    
                    <div class="input-field col m12 s12">
                        <i class="material-icons prefix">assignment</i>
                        <input id="name" type="text" name="name" class="validate" required>
                        <label for="name">* Nombre:</label>
                    </div>

      			        <div class="file-field input-field col m12 s12">
                        <div class="btn">
                            <span>Logo del Cliente</span>
                            <input type="file" name="url">
      				      	  </div>

                        <div class="file-path-wrapper">
      				        <input class="file-path validate" type="text">
      				    </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="modal-footer">
    		<button class=" btn" id="add_cliente">Guardar</button>	
    		<button  class="modal-close red btn">Cerrar</button>
    </div>
</div>
<!-- End Modal -->


<div class="col s12 m12">
	<div class="row">
		<?php if ($this->paginator) {
		    foreach ($this->paginator as $cliente) { ?>
			<div class="col s12 m4">
				<div class="card">
					<div class="card-content ">
						<div class="row">
							<div class="col m12 s12 text-left">
								<span class="card-title text-center" style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"><?php echo $cliente["nombre_cliente"]; ?>
								<hr>
							</div>
						</div>
						
            <div class="row">
							  <div class="col m12 s12">
								    <div class="text-center">
                        <?php if($cliente["logo"]== null){ ?>
                            <img src="/img/no_disponible1.png" class="responsive-img" style="width: 150px; height: 150px;  margin-top: 5px;">
                        <?php }else{ ?>
                            <a href="/clientes/carpetas/id/<?php echo $cliente["id"] ?>" ><img class="example-image oculto" src="/<?php echo $cliente['logo']; ?>" id="camara_div" alt="<?php echo $cliente["nombre_cliente"]; ?>" style="width: 260px; height: 130px;  margin-top: 5px; border-radius: 10px;"/></a>
                        <?php } ?>
		          			</div>
		          			<?php if ($rol_user == 1 || $rol_user == 8) { ?>
                        <div class="text-right">
                            <a href="/clientes/carpetas/id/<?php echo $cliente["id"] ?>"><i class="fa fa-2x fa-folder"></i></a>
                            <a href="/clientes/clienteedit/id/<?php echo $cliente["id"] ?>"><i class="fa fa-2x fa-edit"></i></a>
                            <a class="delete" data-id="<?php echo $cliente["id"]; ?>" data-nombre="<?php echo $cliente["nombre_cliente"]; ?>"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
                        </div>
                    <?php } else {  ?>
                        <div class="text-center">
                            <a href="/clientes/carpetas/id/<?php echo $cliente["id"] ?>"><i class="fa fa-2x fa-folder"></i></a>
                        </div>
                    <?php }  ?>
		          	</div>
		        </div>
		      </div>
	      </div>
	    </div>
	   <?php } } ?>
	</div>
</div>
  
<!-- Table Clientes -->
<!-- <div class="col m12 s12">
    <h3>Lista de Clientes</h3>

    <table class="table text-left table-hover">
    		<thead>
      			<tr>
      				  <th>Id</th>
      				  <th>Cliente</th>	
      				  <th>Logo</th>
      				  <th>Editar</th>
      				  <th>Eliminar</th>
      			</tr> 
    		</thead>
        <?php if ($this->paginator) {
		    foreach ($this->paginator as $cliente) { ?>
            <tbody>
                <tr>
            				<td><?php echo $cliente["id"]; ?></td>
            				<td><?php echo $cliente["nombre_cliente"]; ?></td>
            				<td>
                        <?php if($cliente["logo"]== null){ ?>
                            <img src="/img/no_disponible1.png" class="responsive-img" style="width: 100px; margin-top: 5px;">
                        <?php }else{ ?>
                            <a class="example-image-link" href="/<?php echo $cliente['logo']; ?>" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $cliente['logo']; ?>" id="camara_div" alt="<?php echo $cliente["nombre_cliente"]; ?>" style="width: 100px; height: 100px;  margin-top: 5px;"/></a>
                        <?php } ?>
                    </td>
            				<td>
            					<a href="/clientes/clienteedit/id/<?php echo $cliente["id"] ?>"><i class="fa fa-2x fa-edit"></i></a>
            				</td>
            				<td>
            					<a class="delete" data-id="<?php echo $cliente["id"]; ?>" data-nombre="<?php echo $cliente["nombre_cliente"]; ?>"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
            				</td>
                </tr>
		        </tbody>
		    <?php } } else{ ?>

            <tbody>
      				  <td></td>
      				  <td></td>
      				  <td>
      					   <h4>No se encontraron Clientes</h4>
      				  </td>
      				  <td></td>
      				  <td></td>
      			</tbody>
        <?php }?>
    </table>
</div> -->
<!-- End Table Clientes -->

<!-- Paginador -->
<div class="row">
  <div class="col m12 s12 text-center">
    <div class="white-box">
      <div class="paginationControl">
        <ul class="pagination justify-content-center">
          <?php if($pagina - 1 == 0){ ?>
          <li class="page-item disabled">
            <a><span class="page-link"><i class="fa fa-chevron-left" style="color:gray;"></i></span></a>
          </li>
          <?php }else{ ?>
          <li class="page-item">
            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"><i class="fa fa-chevron-left" style="color: #FCA007;"></i></a>
          </li>
          <?php } ?>
          <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
            <?php echo $links; ?>
          </li>
          <?php if($pagina >= $this->total): ?>
          <li class="page-item disabled">
            <a><span class="page-link"><i class="fa fa-chevron-right" style="color:gray;"></i></span></a>
          </li>
          <?php else: ?>
            <li class="page-item">
              <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>"><i class="fa fa-chevron-right" style="color:#FCA007;"></i></a>
            </li>
          <?php endif; ?>
        </ul>
      </div>
    </div>
  </div> 
</div>
<!-- End Paginator -->



<script src="/js/lightbox.js"></script>

<!-- Scripts -->
<script type="text/javascript">

    lightbox.option({
      'resizeDuration': 200,
      'wrapAround': true
    });

	  $(document).ready(function(){
	  
    	$('.modal').modal();
	  
    }); //Modal script//

	  
    $("#add_cliente").click(function(){
	  	
      var name = document.getElementById("name").value;

            if(name == ""){
                swal({
                  title: "Para agregar un cliente llena los datos requeridos (*)",
                });
            }else{
                 swal("Espera un momento, la información esta siendo procesada", {
				icon: "success",
			 	buttons: false,
			});
                setTimeout(submitForm, 500);     
            }
        });

        function submitForm() {
            document.getElementById("submit_clt").submit()
        }
        //Agregar Cliente Script

//Inicio Delete Ajax

        $(".delete").click(function(){
    	id=$(this).data('id');
    	nombre=$(this).data('nombre');
		swal({
			title: "¿Estas seguro de eliminar al cliente "+nombre+"?",
		  	icon: "warning",
		  	buttons: true,
		  	dangerMode: true,
		})

		.then((willDelete) => {
			if (willDelete) {
				 swal("Espera un momento, la información esta siendo procesada", {
				icon: "success",
			 	buttons: false,
			});

            var request = $.ajax({
            	url:"/clientes/requestdeletecliente",
                method:"POST",
                data: { id : id },
                processData: true,
            });
//-------------------end de ajax---------------------------

//-------------peticion de respuesta de ajax------------------
            request.done(function(response) {
                console.log(response);//imprime lo que responde el ajax
                // alert
                window.location.reload(true);
            });
//-------------------end de respuesta ajax---------------------
             return false;

              } else {
              	swal("La accion fue cancelada!");
              }
          });
	});
 // End Ajax
</script>