<?php 
  function isActhref($nameBtn,$urlname){
      if($nameBtn==1 && $urlname==null){
        return "active"; 
      }
      return ($nameBtn == $urlname)?"active":"";
  }

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>

<style type="text/css">
  .oculto{display: none;}
  .active_menu{
    -webkit-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
    -moz-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
    box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
  }
</style>

  <?php foreach ($this->residente_info as $key){  
    $nombre = $key['nombre'];
    $ap = $key['apellido_pa'];
    $am = $key['apellido_ma'];
  } ?>

<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/solicitud/combrobaciones" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
</div>


<div class="row">
  <div class="col m12 s12 text-center" style="margin-top: 10px;">
    <span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Comprobación: <?php echo $nombre; ?> <?php echo $ap; ?> <?php echo $am; ?></span>
  </div>
</div>


<div class="row" style="margin-top: 20px;">
  <div class="col m8 s8">
      <ul>
          <li class="tab col s3">
            <a class="" href="/solicitud/comprobacionesresidente/id/<?php echo $this->residente_id; ?>">
            <h4>En Proceso
              <div class="chip">
                <?php echo $this->enproceso; ?>
              </div>
            </h4>
            </a>
          </li>

        <li class="tab col s3"><a href="/solicitud/comprobacionresidenteauditada/id/<?php echo $this->residente_id; ?>"><h4>Auditadas</h4></a></li>


        <li class="tab col s3 active_menu">
          <a class="" href="/solicitud/comprobaciones/id/<?php echo $this->residente_id; ?>">
            <h4>Comprobaciones</h4>
          </a>
        </li>
      </ul>
    </div>

    <div class="colm m4 s4">
      <!-- <h4><?php echo $nombre; ?> <?php echo $ap; ?> <?php echo $am; ?> </h4> -->
    </div>
</div>


<div class="row">
  <div class="col m12 s12">
    <span style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de comprobaciones</span>

    <table class="table text-left table-hover">
      <thead>
        <tr>
          <th>Id.</th> 
          <th>Fecha Solicitud</th>
          <th>Sitio</th>
          <th>Monto</th>
          <th>Monto anterior</th>
          <th class="text-center">Detalle comprobacion</th>
          <th></th>
        </tr> 
      </thead>
      <?php
      if ($this->comprobacion) { 
      foreach ($this->comprobacion as $usr) { ?>
      <tbody>
        <tr>
          <td>
            <h5><?php echo $usr['id']; ?></h5>
          </td>
          <td>
            <h5><?php echo $usr['fecha_solicitud']; ?></h5>
          </td>
          <td>
            <h5><?php echo $usr['nombre_sitio']; ?></h5>
          </td>
          <td>
            <h5 style="font-weight: bold;">
              $<?php echo number_format($usr['monto'], 2, '.', ','); ?>
            </h5>
          </td>

          <td>
            <h5 style="font-weight: bold;">
              $<?php echo number_format($usr['monto_anterior'], 2, '.', ','); ?>
            </h5>
          </td>

          <td class="text-center">
            <a href="/comprobacion/reportecomprobaciones/id/<?php echo $usr["id"]; ?>/residente/<?php echo $this->residente_id; ?>"><i class="fa fa-2x fa-id-card-o"></i></a>
          </td>
        </tr>
        <?php } }else{ ?>
        </tbody> 
        <tbody>
            <tr>
                <td class="text-center" colspan="6"><h4>No hay comprobaciones pendientes.</h4></td>
            </tr>
        </tbody>
                    
        <?php } ?>
    </table>

  </div>
</div>

<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
                  <?php if($pagina - 1 == 0){ ?>
                      <li class="page-item disabled">
                          <span class="page-link">Anterior</span>
                      </li>
                  <?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
                  <?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
                  <?php if($pagina >= $this->total): ?>
                        <li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                        </li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>
