<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>


<style type="text/css">
	.oculto{display: none;}
	.active_menu{
		-webkit-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
		-moz-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
		box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	}

	.table_wrapper{
		overflow-x: auto;
	}
</style>

<?php 
	$status =  $this->status_documento;
?>

<div class="row" style="margin-top: 20px;">
	<div class="col m12 s12">
  		<ul >
  			<?php if($status == 0){ ?>
	    		<li class="tab col s3 active_menu">
	    			<a class="" href="/solicitud/listaordencompracoordinador/status/0">
	    			<h4>En Proceso
	  					<div class="chip">
	    					<?php echo $this->enproceso; ?>
	  					</div>
	    			</h4>
	    			</a>
	    		</li>
  			<?php }else{ ?>
	    		<li class="tab col s3">
	    			<a class="" href="/solicitud/listaordencompracoordinador/status/0">
	    			<h4>En Proceso
	  					<div class="chip">
	    					<?php echo $this->enproceso; ?>
	  					</div>
	    			</h4>
	    			</a>
	    		</li>
  			<?php } ?>

  			<?php if($status == 2){ ?>
  				<li class="tab col s3 active_menu"><a href="/solicitud/listaordencompracoordinadorauditoria/status/2"><h4>Auditoria</h4></a></li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/solicitud/listaordencompracoordinadorauditoria/status/2"><h4>Auditoria</h4></a></li>
  			<?php } ?>

  			<?php if($status == 1){ ?>
  				<li class="tab col s3 active_menu">
  					<a href="/solicitud/listaordencompracoordinadoraceptadas/status/1"><h4>Dirección</h4></a>
  					<div></div>
  				</li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/solicitud/listaordencompracoordinadoraceptadas/status/1"><h4>Dirección</h4></a></li>
  			<?php } ?>

  			<?php if($status == 3){ ?>
  				<li class="tab col s3 active_menu">
  					<a href="/solicitud/listaordencompracoordinadorpagadas/status/3"><h4>Pagadas</h4></a>
  					<div></div>
  				</li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/solicitud/listaordencompracoordinadorpagadas/status/3"><h4>Pagadas</h4></a></li>
  			<?php } ?>	
  		</ul>
	</div>
</div>


<!-- <div class="row"> 
	<div class="col m12 s12">
		<h2>Solicitud de Orden de Compra</h2>
	</div>
</div> -->

<div class="row">
	<div class="col m12 s12">
		<div class="row">
			<div class="col m8 s8">
				<h3>Lista de solicitudes de orden de compra</h3>
			</div>
			<div class="col m4 s4 text-right">
				<a href="/archivos/excelsolicitudescompracoord"> <h4 style="color: green;">Generar Excel  <i class="material-icons">insert_drive_file</i></h4></a>
			</div>
		</div>
		<div class="col m12 s12 table_wrapper">
			<table class="table text-left table-hover">
				<thead>
					<tr>
						<th>NO.</th>
						<th>Usuario</th>
						<th>Sitio</th>		
						<th>Servicio</th>
						<th>Proveedor</th>
						<th>Monto</th>
						<th>Autorización</th>
						<!-- <th>Documento</th> -->
						<th>Detalle Solicitud</th>
						<!-- <th>Eliminar</th> -->
					</tr> 
				</thead>
				<?php
				if ($this->paginator) { 
				foreach ($this->paginator as $usr) { ?>
				<tbody>
					<tr>
						<td>
							<h5><?php echo $usr['id_solicitud']; ?></h5>
						</td>
						<td>
							<h5><?php echo $usr['nombre']; ?> <?php echo $usr['ap']; ?></h5>
						</td>
						<td>
							<?php if($usr["nombre_sitio"] == "oficina"){ ?>
								<h5>Oficina</h5>
							<?php } ?>
							<?php if($usr["nombre_sitio"] == "Stock Almacen"){ ?>
								<h5>Stock almacen</h5>
							<?php } ?>

							<?php if($usr["nombre_sitio"] != "Stock Almacen" && $usr["nombre_sitio"] != "oficina"){ ?>
								<h5><?php echo $usr["nombre_sitio"]; ?> / <?php echo $usr['nombre_proyecto']; ?></h5>
							<?php } ?>	
						</td>
						<td>
							<h5><?php echo $usr['nombre_servicio']; ?></h5>
						</td>
						<td>
							<h5><?php echo $usr['name_proveedor']; ?></h5>
						</td>
						<td>
							<h5 style="font-weight: bold;">
								$<?php echo number_format($usr['total'], 2, '.', ','); ?>
							</h5>
						</td>
						<td>
						<?php if($usr['status_documentouno'] == 0){ ?>
							<?php if($usr['status_documento'] == 0){ ?>
								<div class="chip" id="inactivo_personal">
							    	<img src="/img/gris.jpg" >
							    	En proceso
							  	</div>
							<?php } ?>

							<?php if($usr['status_documento'] == 1){ ?>
								<div class="chip" id="activo_personal">
							    	<img src="/img/correct.png" >
							    	Autorizada
							  	</div>
							  	
							<?php } ?>

							<?php if($usr['status_documento'] == 2){ ?>
								<div class="chip" id="inactivo_personal">
							    	<img src="/img/rojo.png" >
							    	Rechazada
							  	</div>
							<?php } ?>
						<?php } ?>

						<?php if($usr['status_documentouno'] == 1){ ?>
							<?php if($usr['status_documento'] == 0){ ?>
								<div class="chip" id="inactivo_personal">
							    	<img src="/img/gris.jpg" >
							    	En proceso
							  	</div>
							<?php } ?>

							<?php if($usr['status_documento'] == 1){ ?>
								<div class="chip" id="activo_personal">
							    	<img src="/img/correct.png" >
							    	Autorizada
							  	</div>
							  	
							<?php } ?>

							<?php if($usr['status_documento'] == 2){ ?>
								<div class="chip" id="inactivo_personal">
							    	<img src="/img/rojo.png" >
							    	Rechazada
							  	</div>
							<?php } ?>
						<?php } ?>

						<?php if($usr['status_documentouno'] == 2){ ?>

								<div class="chip" id="inactivo_personal">
							    	<img src="/img/rojo.png" >
							    	Rechazada
							  	</div>
						<?php } ?>

						</td>

						<td class="text-center">
							<a href="/solicitud/solicituddetailcoordinador/id/<?php echo $usr["id_solicitud"] ?>"><i class="fa fa-2x fa-id-card-o"></i></a>
						</td>
	<!-- 					<td class="text-center">
							<a class="delete_cotizacion" data-id="<?php echo $usr["id_solicitud"]; ?>" data-nombre="cotizacion"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
						</td> -->
					</tr>
			    <?php } }else{ ?>
			    </tbody> 
			    <tbody>
			        <tr>
			            <td class="text-center" colspan="6"><h4>No hay solicitudes de compra.</h4></td>
			        </tr>
			    </tbody>
			                
			    <?php } ?>
			</table>
		</div>
	</div>
</div>


<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
               		<?php if($pagina - 1 == 0){ ?>
                    	<li class="page-item disabled">
                        	<span class="page-link">Anterior</span>
                    	</li>
               		<?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
               		<?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
               		<?php if($pagina >= $this->total): ?>
                       	<li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                       	</li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                   	<?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>

<script type="text/javascript">
   	$(".delete_cotizacion").click(function(){
    	id=$(this).data('id');
		swal({
			title: "Estas seguro de eliminar la solicitud ?",
		  	icon: "warning",
		  	buttons: true,
		  	dangerMode: true,
		})
		.then((willDelete) => {
	  		if (willDelete) {
	    		swal("Bien! La solicitud se elimino!", {
	      			icon: "success",
	    		});

            	var request = $.ajax({
	                url:"/solicitud/requestupdatestatusdeletesolicitudordencompra",
	                method:"POST",
	                data: { id : id },
	                processData: true,
            	});

		        request.done(function(response) {
		            console.log(response);
		            window.location.reload(true);
		        });
             	return false;
	  		} else {
	    		swal("La accion fue cancelada!");
	  		}
		});
   	});

</script>