<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>


<style type="text/css">
	.oculto{display: none;}
	.active_menu{
	-webkit-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	-moz-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	}

	.table_wrapper{
		overflow-x: auto;
	}
</style>

<?php 
	$status =  $this->status_documento;
?>

<div class="row" style="margin-top: 20px;">
	<div class="col m12 s12">
  		<ul >
  			<?php if($status == 0){ ?>
	    		<li class="tab col s3 active_menu">
	    			<a class="" href="/solicitud/listarolsolicitudes/status/0">
	    			<h4>En Proceso
	  					<div class="chip">
	    					<?php echo $this->enproceso; ?>
	  					</div>
	    			</h4>
	    			</a>
	    		</li>
  			<?php }else{ ?>
	    		<li class="tab col s3">
	    			<a class="" href="/solicitud/listarolsolicitudes/status/0">
	    			<h4>En Proceso
	  					<div class="chip">
	    					<?php echo $this->enproceso; ?>
	  					</div>
	    			</h4>
	    			</a>
	    		</li>
  			<?php } ?>

  			<?php if($status == 2){ ?>
  				<li class="tab col s3 active_menu"><a href="/solicitud/listarolsolicitudes/status/2"><h4>Rechazadas</h4></a></li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/solicitud/listarolsolicitudes/status/2"><h4>Rechazadas</h4></a></li>
  			<?php } ?>

  			<?php if($status == 1){ ?>
  				<li class="tab col s3 active_menu">
  					<a href="/solicitud/listarolsolicitudes/status/1"><h4>Dirección</h4></a>
  					<div></div>
  				</li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/solicitud/listarolsolicitudes/status/1"><h4>Dirección</h4></a></li>
  			<?php } ?>

  			<?php if($status == 3){ ?>
  				<li class="tab col s3 active_menu">
  					<a href="/solicitud/listarolsolicitudes/status/3"><h4>Pagadas</h4></a>
  					<div></div>
  				</li>
  			<?php }else{ ?>
  				<li class="tab col s3"><a href="/solicitud/listarolsolicitudes/status/3"><h4>Pagadas</h4></a></li>
  			<?php } ?>
  		</ul>
	</div>
</div>

<!-- <div class="row" style="margin-top:10px;">
	<div class="col m2 s12"></div>
	<div class="col m8 s12"> 
		<div class="col m12 s12" id="search_nombre">
		        <div class="input-field col m10 s8">
		          <input placeholder="Ingresa nombre" name="sitio" id="name_sitios" type="text" value="<?php echo $this->nombre_sitio; ?>">
		          <label for="name_sitios">Buscar por nombre del Sito</label>
		        </div>
		        <input type="hidden" id="status_search" value="<?php echo $status; ?>">
		        <div class="input-field col m2 s4">
		        	<button tyle="submit" id="buscador" class="waves-effect waves-light btn"><i class="material-icons left">search</i></button>
		        </div>
		</div>
	</div>
	<div class="col m2 s12"></div>
</div> -->



<?php $opcion = $this->opcion_search; ?>


<div class="row" style="margin-top:10px;">
	<div class="col m4 s12">
	  	<div class="input-field col s12">
	    	<select id="search_tipo">
	    		<?php if($opcion == 1){ ?>
		      		<option value="1" selected>Sitio</option>
		      		<option value="2">Proveedor</option>
		      		<option value="3">Id de la solicitud</option>
		      		<option value="5" >Servicio</option>
	    		<?php } ?>

	    		<?php if($opcion == 2){ ?>
		      		<option value="1">Sitio</option>
		      		<option value="2" selected>Proveedor</option>
		      		<option value="3">Id de la solicitud</option>
		      		<option value="5" >Servicio</option>
	    		<?php } ?>

	    		<?php if($opcion == 3){ ?>
		      		<option value="1">Sitio</option>
		      		<option value="2">Proveedor</option>
		      		<option value="3" selected>Id de la solicitud</option>
		      		<option value="5" >Servicio</option>
	    		<?php } ?>

	    		<?php if($opcion == 4){ ?>
		      		<option value="1">Sitio</option>
		      		<option value="2">Proveedor</option>
		      		<option value="3">Id de la solicitud</option>
		      		<option value="5" >Servicio</option>
	    		<?php } ?>

	    		<?php if($opcion == 5){ ?>
		      		<option value="1">Sitio</option>
		      		<option value="2">Proveedor</option>
		      		<option value="3">Id de la solicitud</option>
		      		<option value="5" selected>Servicio</option>
	    		<?php } ?>
	    	</select>
	    	<label>Buscar por:</label>
	  </div>
	</div>
	
	
	<div class="col m8 s12"> 
		<?php if($opcion == 1){ ?>
			<div class="col m12 s12" id="search_nombre">
		<?php }else{ ?>
			<div class="col m12 s12 oculto" id="search_nombre">
		<?php } ?>
		    <div class="input-field col m10 s8">
		        <input placeholder="Ingresa nombre" name="sitio" id="name_sitios" value="<?php echo $this->nombre_sitio; ?>" type="text" class="validate">
		         <label for="name_sitios">Buscar por nombre del Sito</label>
		    </div>
		    <input type="hidden" id="status_search" value="<?php echo $status; ?>">
		    <div class="input-field col m2 s4">
		        <button tyle="submit" id="buscador" class="waves-effect waves-light btn"><i class="material-icons left">search</i></button>
		    </div>
		</div>

		<?php if($opcion == 2){ ?>
			<div class="col m12 s12" id="search_proveedor">
		<?php }else{ ?>
			<div class="col m12 s12 oculto" id="search_proveedor">
		<?php } ?>
		    <div class="input-field col m10 s8">
		        <input placeholder="Ingresa nombre" name="proveedor" id="name_proveedor" value="<?php echo $this->nombre_prov; ?>" type="text" class="validate">
		        <label for="name_proveedor">Buscar por Proveedor</label>
		    </div>
		    <div class="input-field col m2 s4">
		     	<button tyle="submit" id="buscador_prov" class="waves-effect waves-light btn"><i class="material-icons left">search</i></button>
		    </div>
		</div>

		<?php if($opcion == 3){ ?>
			<div class="col m12 s12" id="search_solicitud">
		<?php }else{ ?>
			<div class="col m12 s12 oculto" id="search_solicitud">
		<?php } ?>
		    <div class="input-field col m10 s8">
		        <input placeholder="Ingresa el id de la solicitud" value="<?php echo $this->id_search; ?>" name="solicitud" id="id_sol" type="number" class="validate">
		        <label for="id_sol">Buscar por id de la solicitud</label>
		    </div>
		    <div class="input-field col m2 s4">
		     	<button tyle="submit" id="buscador_solicitud" class="waves-effect waves-light btn"><i class="material-icons left">search</i></button>
		    </div>
		</div>



		<?php if($opcion == 5){ ?>
			<div class="col m12 s12" id="search_servicio">
		<?php }else{ ?>
			<div class="col m12 s12 oculto" id="search_servicio">
		<?php } ?>
		    <div class="input-field col m10 s8">
				<select id="servicio_name" name="servicio_name">
			    	<?php foreach ($this->servicios as $mar) { 
			     		if ($mar['id']==$this->servicio_search) { ?>
			                <option value="<?php echo $mar["id"]; ?>" selected><?php echo $mar["nombre_servicio"]; ?></option>
			     	<?php } if ($mar['id']!=$this->servicio_search) { ?>
			                <option value="<?php echo $mar["id"]; ?>" ><?php echo $mar["nombre_servicio"]; ?></option>
			     	<?php } } ?>  
				</select>
				<label>Servicios</label>
		    </div>
		    <div class="input-field col m2 s4">
		     	<button tyle="submit" id="buscador_servicio" class="waves-effect waves-light btn"><i class="material-icons left">search</i></button>
		    </div>
		</div>

	</div>

</div>

 	

<div class="row">
	<div class="col m12 s12">
		<div class="row">
			<div class="col m8 s8">
				<h3>Lista de Solicitudes de orden de Compra en proceso</h3>
			</div>
			<div class="col m4 s4 text-right">
				<h4><a href="/solicitud/missolicitudes/id/<?php echo $this->user_list; ?>">Mis Solicitudes Creadas</a></h4>
			</div>
		</div>

		<div class="col m12 s12 table_wrapper">
			<table class="table text-left table-hover">
				<thead>
					<tr>
						<th>NO.</th>
						<th>Usuario</th>
						<th>Sitio</th>		
						<th>Servicio</th>
						<th>Proveedor</th>
						<th>Monto</th>
						<th>Autorización</th>
						<th>Detalle Solicitud</th>
					</tr> 
				</thead>
				<?php
				if ($this->paginator) { 
				foreach ($this->paginator as $usr) { ?>
				<tbody>
					<tr>
						<td><h5><?php echo $usr['id_solicitud']; ?></h5></td>
						<td>
							<h5><?php echo $usr['nombre']; ?> <?php echo $usr['ap']; ?></h5>
						</td>
						<td>
							<?php if($usr["nombre_sitio"] == "oficina"){ ?>
								<h5>Oficina</h5>
							<?php } ?>
							<?php if($usr["nombre_sitio"] == "Stock Almacen"){ ?>
								<h5>Stock almacen</h5>
							<?php } ?>

							<?php if($usr["nombre_sitio"] != "Stock Almacen" && $usr["nombre_sitio"] != "oficina"){ ?>
								<h5><?php echo $usr["nombre_sitio"]; ?> / <?php echo $usr['nombre_proyecto']; ?></h5>
							<?php } ?>	
						</td>
						<td>
							<h5><?php echo $usr['nombre_servicio']; ?></h5>
						</td>
						<td>
							<h5><?php echo $usr['name_proveedor']; ?></h5>
						</td>
						<td>
							<h5>$<?php echo $usr['total']; ?></h5>
						</td>
						<td>
						<?php if($usr['status_documentouno'] == 0){ ?>
							<?php if($usr['status_documento'] == 0){ ?>
								<div class="chip" id="inactivo_personal">
							    	<img src="/img/gris.jpg" >
							    	En proceso
							  	</div>
							<?php } ?>

							<?php if($usr['status_documento'] == 1){ ?>
								<div class="chip" id="activo_personal">
							    	<img src="/img/correct.png" >
							    	Autorizada
							  	</div>
							  	
							<?php } ?>

							<?php if($usr['status_documento'] == 2){ ?>
								<div class="chip" id="inactivo_personal">
							    	<img src="/img/rojo.png" >
							    	Rechazada
							  	</div>
							<?php } ?>
						<?php } ?>

						<?php if($usr['status_documentouno'] == 1){ ?>
							<?php if($usr['status_documento'] == 0){ ?>
								<div class="chip" id="inactivo_personal">
							    	<img src="/img/gris.jpg" >
							    	En proceso
							  	</div>
							<?php } ?>

							<?php if($usr['status_documento'] == 1){ ?>
								<div class="chip" id="activo_personal">
							    	<img src="/img/correct.png" >
							    	Autorizada
							  	</div>
							  	
							<?php } ?>

							<?php if($usr['status_documento'] == 2){ ?>
								<div class="chip" id="inactivo_personal">
							    	<img src="/img/rojo.png" >
							    	Rechazada
							  	</div>
							<?php } ?>
						<?php } ?>

						<?php if($usr['status_documentouno'] == 2){ ?>

								<div class="chip" id="inactivo_personal">
							    	<img src="/img/rojo.png" >
							    	Rechazada
							  	</div>
						<?php } ?>
						</td>


						<td class="text-center">
							<a href="/solicitud/solicituddetailencargado/id/<?php echo $usr["id_solicitud"] ?>"><i class="fa fa-2x fa-id-card-o"></i></a>
						</td>
					</tr>
			    <?php } }else{ ?>
			    </tbody> 
			    <tbody>
			        <tr>
			            <td class="text-center" colspan="6"><h4>No hay solicitudes agregadas.</h4></td>
			        </tr>
			    </tbody>
			                
			    <?php } ?>
			</table>
		</div>
	</div>
</div>


<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
               		<?php if($pagina - 1 == 0){ ?>
                    	<li class="page-item disabled">
                        	<span class="page-link">Anterior</span>
                    	</li>
               		<?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
               		<?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
               		<?php if($pagina >= $this->total): ?>
                       	<li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                       	</li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                   	<?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>




<script type="text/javascript">

  $(document).ready(function(){
    $('.tabs').tabs();
  });

   	$(".delete_cotizacion").click(function(){
    	id=$(this).data('id');
		swal({
			title: "Estas seguro de eliminar la solicitud ?",
		  	icon: "warning",
		  	buttons: true,
		  	dangerMode: true,
		})
		.then((willDelete) => {
	  		if (willDelete) {
	    		swal("Bien! La solicitud se elimino!", {
	      			icon: "success",
	    		});

            	var request = $.ajax({
	                url:"/solicitud/requestupdatestatusdeletesolicitudordencompra",
	                method:"POST",
	                data: { id : id },
	                processData: true,
            	});
		        request.done(function(response) {
		            console.log(response);
		            window.location.reload(true);
		        });
				//-------------------end de respuesta ajax---------------------
             	return false;
	  		} else {
	    		swal("La accion fue cancelada!");
	  		}
		});
   	});

	$('#search_tipo').on('change', function() {
		var value = this.value;
		if(value == 1){
			$("#search_nombre").show();
			$("#search_proveedor").hide();
			$("#search_solicitud").hide();
			$("#search_usuario").hide();
			$("#search_servicio").hide();
		}

		if(value == 2){
			$("#search_proveedor").show();	
			$("#search_nombre").hide();
			$("#search_solicitud").hide();
			$("#search_usuario").hide();
			$("#search_servicio").hide();
		}

		if(value == 3){
			$("#search_solicitud").show();
			$("#search_proveedor").hide();	
			$("#search_nombre").hide();
			$("#search_usuario").hide();
			$("#search_servicio").hide();
		}

		if(value == 4){
			$("#search_usuario").show();
			$("#search_solicitud").hide();
			$("#search_proveedor").hide();	
			$("#search_nombre").hide();
			$("#search_servicio").hide();
		}

		if(value == 5){
			$("#search_servicio").show();
			$("#search_usuario").hide();
			$("#search_solicitud").hide();
			$("#search_proveedor").hide();	
			$("#search_nombre").hide();
		}

	});



   	$("#buscador").click(function(){
   		var name_sitio = document.getElementById("name_sitios").value;
   		var status = document.getElementById("status_search").value;
		swal({
			title: "La busqueda sera para el sitio "+name_sitio+", Desea continuar?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				}); 
			window.location.href = "/solicitud/listarolsolicitudessitio/status/"+status+"/sitio/"+name_sitio+"/op/1";
		  } else {
		    swal("La asignacion fue cancelada!");
		  }
		});
   	});	


   	$("#buscador_prov").click(function(){
   		var name_prov = document.getElementById("name_proveedor").value;
   		var status = document.getElementById("status_search").value;
		swal({
			title: "La busqueda sera por proveedor "+name_prov+", Desea continuar?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				}); 
			window.location.href = "/solicitud/listarolsolicitudessitio/status/"+status+"/proveedor/"+name_prov+"/op/2";
		  } else {
		    swal("La asignacion fue cancelada!");
		  }
		});
   	});	

   	$("#buscador_solicitud").click(function(){
   		var id = document.getElementById("id_sol").value;
   		var status = document.getElementById("status_search").value;
		swal({
			title: "La busqueda sera por id "+id+", Desea continuar?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				}); 
			window.location.href = "/solicitud/listarolsolicitudessitio/status/"+status+"/id/"+id+"/op/3";
		  } else {
		    swal("La asignacion fue cancelada!");
		  }
		});
   	});

   	$("#buscador_usuario").click(function(){
   		var id = document.getElementById("name_usuario").value;
   		var status = document.getElementById("status_search").value;

		swal({
			title: "La busqueda sera por nombre del usuario "+id+", Desea continuar?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				}); 
			window.location.href = "/solicitud/listarolsolicitudessitio/status/"+status+"/usuario/"+id+"/op/4";
		  } else {
		    swal("La asignacion fue cancelada!");
		  }
		});

   	});

   	$("#buscador_servicio").click(function(){
   		var status = document.getElementById("status_search").value;
   		var servicio = document.getElementById("servicio_name").value;

		swal({
			title: "La busqueda sera por la opción de servicio, Deseacontinuar?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				}); 
			window.location.href = "/solicitud/listarolsolicitudessitio/status/"+status+"/servicio/"+servicio+"/op/5";
		  } else {
		    swal("La asignacion fue cancelada!");
		  }
		});
   	});


</script>