<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>


<style type="text/css">
	.oculto{display: none;}
	.active_menu{
	-webkit-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	-moz-box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	box-shadow: 0px 6px 3px -1px rgba(255,72,60,1);
	}
</style>


<?php 
	$user =  $this->usuario;
?>

<?php $opcion = $this->opcion_search; ?>

<div class="row" style="margin-top: 30px;">
	<div class="col m12 s12">
		<h2>Mis solicitudes de orden de compra creadas</h2>
	</div>
</div>


<!-- Buscador -->
<div class="row" style="margin-top:10px;">
	<div class="col m4 s12">
	  	<div class="input-field col s12">
	    	<select id="search_sol">
	    		<?php if($opcion == 1){ ?>
		      		<option value="1" selected>Sitio</option>
		      		<option value="2">Id Solicitud</option>
		      		<option value="3">Proveedor</option>
	    		<?php } ?>

	    		<?php if($opcion == 2){ ?>
		      		<option value="1">Sitio</option>
		      		<option value="2" selected>Id Solicitud</option>
		      		<option value="3">Proveedor</option>
	    		<?php } ?>

	    		<?php if($opcion == 3){ ?>
		      		<option value="1">Sitio</option>
		      		<option value="2">Id Solicitud</option>
		      		<option value="3" selected>Proveedor</option>
	    		<?php } ?>
	    	</select>
	    	<label>Buscar por:</label>
	  	</div>
	</div>

	<div class="col m8 s12"> 
		<?php if($opcion == 1){ ?>
			<div class="col m12 s12" id="search_sitio">
		<?php }else{ ?>
			<div class="col m12 s12 oculto" id="search_sitio">
		<?php } ?>
			<div class="input-field col m10 s8">
		        <input placeholder="Ingresa nombre" name="sitio" id="namesitio" type="text" value="<?php echo $this->nombre_sto; ?>" class="validate">
		        <label for="namesitio">Buscar por sitio</label>
		    </div>
		    <input type="hidden" id="status_search" value="<?php echo $user; ?>">
		    <div class="input-field col m2 s4">
		     	<button tyle="submit" id="buscador_sitio" class="waves-effect waves-light btn"><i class="material-icons left">search</i></button>
		    </div>
		</div>

		<?php if($opcion == 2){ ?>
			<div class="col m12 s12" id="search_solicitud">
		<?php }else{ ?>
			<div class="col m12 s12 oculto" id="search_solicitud">
		<?php } ?>
		    <div class="input-field col m10 s8">
		        <input placeholder="Ingresa el id de la solicitud" value="<?php echo $this->id_search; ?>" name="solicitud" id="id_sol" type="number" class="validate">
		        <label for="id_sol">Buscar por id de la solicitud</label>
		    </div>
		    <div class="input-field col m2 s4">
		     	<button tyle="submit" id="buscador_solicitud" class="waves-effect waves-light btn"><i class="material-icons left">search</i></button>
		    </div>
		</div>

		<?php if($opcion == 3){ ?>
			<div class="col m12 s12" id="search_p">
		<?php }else{ ?>
			<div class="col m12 s12 oculto" id="search_p">
		<?php } ?>
		    <div class="input-field col m10 s8">
		    	 <input placeholder="Ingresa nombre proveedor" value="<?php echo $this->proverdor_name; ?>" name="proveedor" id="namepro" type="text" class="validate">
		        <label for="namepro">Buscar por Proveedor</label>
		    </div>
		    <div class="input-field col m2 s4">
		     	<button tyle="submit" id="buscador_pro" class="waves-effect waves-light btn"><i class="material-icons left">search</i></button>
		    </div>
		</div>
	</div>
</div>
<!-- End Buscador -->
<div class="row">
	<div class="col m12 s12 text-right">
		<h4><a href="/solicitud/missolicitudes/id/<?php echo $this->usuario; ?>">Todas mis Solicitudes</a></h4>
	</div>
</div>

<div class="row">
	<div class="col m12 s12">
		<table class="table text-left table-hover"> 
			<thead>
				<tr>
					<th>NO.</th>
					<th>Usuario</th>
					<th>Sitio</th>		
					<th>Servicio</th>
					<th>Proveedor</th>
					<th>Monto</th>
					<th>Auditoria</th>
					<th>Dirección</th>
					<!-- <th>Documento</th> -->
					<th>Detalle Solicitud</th>
					<!-- <th>Eliminar</th> -->
				</tr> 
			</thead>
			<?php
			if ($this->paginator) { 
			foreach ($this->paginator as $usr) { ?>
			<tbody>
				<tr>
					<td>
						<h5><?php echo $usr['id_solicitud']; ?></h5>
					</td>
					<td>
						<h5><?php echo $usr['nombre']; ?> <?php echo $usr['ap']; ?></h5>
					</td>
					<td>
						<h5><?php echo $usr["nombre_sitio"]; ?></h5>
					</td>
					<td>
						<h5><?php echo $usr['nombre_servicio']; ?></h5>
					</td>
					<td>
						<h5><?php echo $usr["name_proveedor"]; ?></h5>
					</td>
					<td>
						<h5>$<?php echo $usr['total']; ?></h5>
					</td>
					<td>
						<?php if($usr['status_documentouno'] == 0){ ?>
							<div class="chip" id="inactivo_personal">
						    	<img src="/img/gris.jpg" >
						    	En proceso
						  	</div>
						<?php } ?>

						<?php if($usr['status_documentouno'] == 1){ ?>
							<div class="chip" id="activo_personal">
						    	<img src="/img/correct.png" >
						    	Autorizada
						  	</div>
						  	
						<?php } ?>

						<?php if($usr['status_documentouno'] == 2){ ?>
							<div class="chip" id="inactivo_personal">
						    	<img src="/img/rojo.png" >
						    	Rechazada
						  	</div>
						<?php } ?>
					</td>

					<td>
						<?php if($usr['status_documento'] == 0){ ?>
							<div class="chip" id="inactivo_personal">
						    	<img src="/img/gris.jpg" >
						    	En proceso
						  	</div>
						<?php } ?>

						<?php if($usr['status_documento'] == 1){ ?>
							<div class="chip" id="activo_personal">
						    	<img src="/img/correct.png" >
						    	Autorizada
						  	</div>
						  	
						<?php } ?>

						<?php if($usr['status_documento'] == 2){ ?>
							<div class="chip" id="inactivo_personal">
						    	<img src="/img/rojo.png" >
						    	Rechazada
						  	</div>
						<?php } ?>
					</td>
<!-- 					<td>

						<?php if($usr['status_documento'] == 0){ ?>
							No Disponible
						<?php } ?>
						<?php if($usr['status_documento'] == 1){ ?>
							<a href="/solicitud/successsolicitud/id/<?php echo $usr['id_solicitud']; ?>">
								Ver documento
							</a>
						<?php } ?>
						<?php if($usr['status_documento'] == 2){ ?>
							No Disponible
						<?php } ?>
					</td> -->
					<td class="text-center">
						<a href="/solicitud/detallesolicitudcreada/id/<?php echo $usr["id_solicitud"] ?>"><i class="fa fa-2x fa-id-card-o"></i></a>
					</td>
<!-- 					<td class="text-center">
						<a class="delete_cotizacion" data-id="<?php echo $usr["id_solicitud"]; ?>" data-nombre="cotizacion"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
					</td> -->
				</tr>
		    <?php } }else{ ?>
		    </tbody> 
		    <tbody>
		        <tr>
		            <td class="text-center" colspan="6"><h4>No hay solicitudes de compra.</h4></td>
		        </tr>
		    </tbody>
		                
		    <?php } ?>
		</table>
	</div>
</div>


<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
               		<?php if($pagina - 1 == 0){ ?>
                    	<li class="page-item disabled">
                        	<span class="page-link">Anterior</span>
                    	</li>
               		<?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
               		<?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
               		<?php if($pagina >= $this->total): ?>
                       	<li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                       	</li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                   	<?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>


<script type="text/javascript">

	$('#search_sol').on('change', function() {
		var value = this.value;

		if(value == 1){
			$("#search_sitio").show();
			$("#search_solicitud").hide();
			$("#search_p").hide();
		}

		if(value == 2){
			$("#search_sitio").hide();	
			$("#search_solicitud").show();
			$("#search_p").hide();
		}

		if(value == 3){
			$("#search_sitio").hide();	
			$("#search_solicitud").hide();
			$("#search_p").show();
		}

	});


   	$("#buscador_sitio").click(function(){
   		var namesitio = document.getElementById("namesitio").value;
   		var user = document.getElementById("status_search").value;
		swal({
			title: "La busqueda sera por sitio "+namesitio+", Desea continuar?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				}); 
			window.location.href = "/solicitud/missolbuscar/user/"+user+"/sitio/"+namesitio+"/op/1";
		  } else {
		    swal("La asignacion fue cancelada!");
		  }
		});

   	});	
   	$("#buscador_solicitud").click(function(){
   		var id = document.getElementById("id_sol").value;
   		var user = document.getElementById("status_search").value;
		swal({
			title: "La busqueda sera por id "+id+", Desea continuar?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				}); 
			window.location.href = "/solicitud/missolbuscar/user/"+user+"/id/"+id+"/op/2";
		  } else {
		    swal("La asignacion fue cancelada!");
		  }
		});
   	});


   	$("#buscador_pro").click(function(){
   		var namepro = document.getElementById("namepro").value;
   		var user = document.getElementById("status_search").value;
		swal({
			title: "La busqueda sera por el proveedor "+namepro+", Desea continuar?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
		  	if (willDelete) {
				swal("Espere un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				}); 
			window.location.href = "/solicitud/missolbuscar/user/"+user+"/proveedor/"+namepro+"/op/3";
		  } else {
		    swal("La asignacion fue cancelada!");
		  }
		});

   	});	

</script>