<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>

<div class="row" style="margin-top: 30px;">
	<div class="col m12 s12">
		<h2>Mis solicitudes de orden de compra creadas</h2>
	</div>
</div>


<div class="row">
	<div class="col m12 s12">
		<table class="table text-left table-hover">
			<thead>
				<tr>
					<th>NO.</th>
					<th>Usuario</th>
					<th>Sitio</th>		
					<th>Servicio</th>
					<th>Monto</th>
					<th>Auditoria</th>
					<th>Dirección</th>
					<!-- <th>Documento</th> -->
					<th>Detalle Solicitud</th>
					<!-- <th>Eliminar</th> -->
				</tr> 
			</thead>
			<?php
			if ($this->paginator) { 
			foreach ($this->paginator as $usr) { ?>
			<tbody>
				<tr>
					<td>
						<h5><?php echo $usr['id_solicitud']; ?></h5>
					</td>
					<td>
						<h5><?php echo $usr['nombre']; ?> <?php echo $usr['ap']; ?></h5>
					</td>
					<td>
						<h5><?php echo $usr["nombre_sitio"]; ?></h5>
					</td>
					<td>
						<h5><?php echo $usr['nombre_servicio']; ?></h5>
					</td>
					<td>
						<h5>$<?php echo $usr['total']; ?></h5>
					</td>
					<td>
						<?php if($usr['status_documentouno'] == 0){ ?>
							<div class="chip" id="inactivo_personal">
						    	<img src="/img/gris.jpg" >
						    	En proceso
						  	</div>
						<?php } ?>

						<?php if($usr['status_documentouno'] == 1){ ?>
							<div class="chip" id="activo_personal">
						    	<img src="/img/correct.png" >
						    	Autorizada
						  	</div>
						  	
						<?php } ?>

						<?php if($usr['status_documentouno'] == 2){ ?>
							<div class="chip" id="inactivo_personal">
						    	<img src="/img/rojo.png" >
						    	Rechazada
						  	</div>
						<?php } ?>
					</td>

					<td>
						<?php if($usr['status_documento'] == 0){ ?>
							<div class="chip" id="inactivo_personal">
						    	<img src="/img/gris.jpg" >
						    	En proceso
						  	</div>
						<?php } ?>

						<?php if($usr['status_documento'] == 1){ ?>
							<div class="chip" id="activo_personal">
						    	<img src="/img/correct.png" >
						    	Autorizada
						  	</div>
						  	
						<?php } ?>

						<?php if($usr['status_documento'] == 2){ ?>
							<div class="chip" id="inactivo_personal">
						    	<img src="/img/rojo.png" >
						    	Rechazada
						  	</div>
						<?php } ?>
					</td>
<!-- 					<td>

						<?php if($usr['status_documento'] == 0){ ?>
							No Disponible
						<?php } ?>
						<?php if($usr['status_documento'] == 1){ ?>
							<a href="/solicitud/successsolicitud/id/<?php echo $usr['id_solicitud']; ?>">
								Ver documento
							</a>
						<?php } ?>
						<?php if($usr['status_documento'] == 2){ ?>
							No Disponible
						<?php } ?>
					</td> -->
					<td class="text-center">
						<a href="/solicitud/detallesolicitudcreada/id/<?php echo $usr["id_solicitud"] ?>"><i class="fa fa-2x fa-id-card-o"></i></a>
					</td>
<!-- 					<td class="text-center">
						<a class="delete_cotizacion" data-id="<?php echo $usr["id_solicitud"]; ?>" data-nombre="cotizacion"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
					</td> -->
				</tr>
		    <?php } }else{ ?>
		    </tbody> 
		    <tbody>
		        <tr>
		            <td class="text-center" colspan="6"><h4>No hay solicitudes de compra.</h4></td>
		        </tr>
		    </tbody>
		                
		    <?php } ?>
		</table>
	</div>
</div>


<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
               		<?php if($pagina - 1 == 0){ ?>
                    	<li class="page-item disabled">
                        	<span class="page-link">Anterior</span>
                    	</li>
               		<?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
               		<?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
               		<?php if($pagina >= $this->total): ?>
                       	<li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                       	</li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                   	<?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>