<div class="col m12 s12" style="margin-top: 30px;">
	<div class="row">
		<div class="col m6 s6">
			<a href="/solicitud/listaordencompra/status/0">
      		<div class="card">
        		<div class="card-image">
          			<img src="/img/proceso_solicitudes.jpg" style="width: 350px; height: 250px;">
          			<!-- <span class="card-title">Card Title</span> -->
        		</div>
        		<div class="card-content text-center">
          			<p>Solicitudes de orden de compra autorizadas por área.</p>
        		</div>
      		</div>
      		</a>
		</div>


		<div class="col m6 s6">
			<a href="">
      		<div class="card">
        		<div class="card-image">
          			<img src="/img/directo.jpg" style="width: 350px; height: 250px;">
          			<!-- <span class="card-title">Card Title</span> -->
        		</div>
        		<div class="card-content text-center">
          			<p>Solicitudes de orden de compra directas.</p>
        		</div>
      		</div>
      		</a>
		</div>

	</div>
</div>