<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/solicitud/generarcombrobaciones" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
</div>


<div class="row" style="margin-top: 30px;">
	<div class="col m12 s12">
		<div class="text-center">
			<h2></h2>	
			<span style="font-size:26px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">La Comprobación se realizo de forma correcta!</span>	
		</div>

		<div class="text-center">
			<h3>
<!-- 				<a href="/solicitud/comprobacionesresidente/id/<?php echo $this->id_user; ?>">Ver detalles de la comprobacion</a> --> 
			</h3>
		</div>
	
		<div class="text-center" style="margin-top: 30px;">
			<img src="/img/correct.png" style="width: 200px;">
		</div>

	</div>
</div>