<html>
<head>
    <!-- <base href="https://demos.telerik.com/kendo-ui/pdf-export/page-layout">
    <style>html { font-size: 14px; font-family: Arial, Helvetica, sans-serif; } --></style>
    <title></title>
   <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.common.min.css" />
<!--      <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.black.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.black.mobile.min.css" /> -->

    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/kendo.all.min.js"></script>
</head>
<body>
<div id="example">
<!--     <div class="box wide hidden-on-narrow">
        <div class="box-col">
            <button class="export-pdf btn" onclick="getPDF('.pdf-page')">Descargar</button>
        </div>
    </div>
 -->

<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12 text-right">
        <button class="export-pdf btn" onclick="getPDF('.pdf-page')">Descargar</button>
    </div>
</div>

    <?php foreach ($this->solicitud as $key){ 
        $id = $key['id'];
        $fecha = $key['fecha_requerida'];
        $nombre_sitio = $key['nombre_sitio'];
        $condiciones_compra = $key['condiciones_compra'];
        $descripcion = $key['descripcion'];
        $importe = $key['importe'];
        if($key['iva'] == ""){
            $iva = "0.00";
        }else{
            $iva = $key['iva'];
        }

        $referencia=$key["referencia"];
        
        $total = $key['total'];
        $retencion_isr = $key['retencion_isr'];
        $retencion_iva = $key['retencion_iva'];
        $fecha_creacion = $key['fecha_creacion'];
        $solicitud = $key["id_solicitud"];
    } ?>

    <?php foreach ($this->proveedor as $value){ 
        $nombre_prov =  $value['nombre_prov'];
        $telefono_prov = $value['telefono'];
        $rfc_prov = $value['rfc'];
        $datos_prov = $value['datos_banco'];
        $cuenta_prov=$value['cuenta'];
        $email_prov = $value['email'];
        $tarjeta = $value['tarjeta'];
    } ?>

    <?php foreach ($this->usuario as $user){ 
        $nombre_user = $user['nombre'];
        $apellido_pa = $user['ap'];
        $apellido_ma = $user['am'];
    } ?>

    <?php 

    foreach ($this->validacionuser as $val) {
        $name_val = $val['nombre'];
        $ape_val = $val['ap']; 
        $fecha_val = $val['fecha_validacion'];  
    } ?>

    <?php foreach ($this->validacionjefe as $jefe) {
        $name_jefe = $jefe['nombre'];
        $ape_jefe = $jefe['ap'];
        $fecha_jefe = $jefe["fecha_validaciondos"];
    } ?>


    <?php 
            date_default_timezone_set('America/Mexico_City');
            $hoy = date("d/m/Y");
     ?>


    <div class="page-container hidden-on-narrow">
        <div class="pdf-page size-a4">
            <div class="pdf-header">
                <span class="company-logo">
                    <img src="/img/head.png" style="width: 120px;" />
                </span>

                <span class="invoice-number">
                    <img src="/img/logo-2.png" style="width: 125px;" /><br/>
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Solicitud No.<?php echo $solicitud; ?></span>
                </span>
                <div class="row">
                    <div class="company-logo col m12 s12 text-center">
                        Orden de Compra
                    </div>
                </div>
            </div>
            <div class="pdf-footer">
                <p>Nte 31-A No. 96, col. Lindavista Vallejo III, Gustavo A. Madero, C.P. 07720, CDMX<br />
                    Fecha de descarga: <?php echo $hoy; ?><br />
                </p>
            </div>
            <div class="for" style="margin-top: 60px;">
                <h3>Fecha Requerida : <?php echo $fecha; ?></h3>
                <p>
                <span class="title-pdf">Sitio:</span> <span style="font-size: 14px;"><?php echo $nombre_sitio; ?></span><br />
                <span class="title-pdf">Proyecto:</span> <span style="font-size: 14px;"><?php echo $this->proyecto; ?></span><br />
                    <span class="title-pdf">CMS:</span> <?php echo $this->cliente; ?><br />
                    <span class="title-pdf">Ciudad:</span> <?php echo $this->ciudad; ?>
                </p>
            </div>

            <div class="from" style="margin-top: 60px;">
                <h3>Proveedor</h3>
                <p style="padding-bottom: 17px;">
                    <span class="title-pdf">Nombre:</span> <?php echo $nombre_prov; ?> <br />
                    <span class="title-pdf">Telefono:</span> <?php echo $telefono_prov; ?><br />
                    <span class="title-pdf">RFC:</span> <?php echo $rfc_prov; ?><br />
                    <span class="title-pdf">Datos Banco:</span> <?php echo $datos_prov; ?> <br />
                    <span class="title-pdf">Cuenta: <?php echo $cuenta_prov; ?></span> </br>
                    <span class="title-pdf">Tarjeta: <?php echo $tarjeta; ?></span></br>
                    <span class="title-pdf">Email:</span> <?php echo $email_prov; ?><br />

                    <?php if($referencia == ""){ ?>
                    <?php }else{ ?>
                        <span class="title-pdf">Referencia:</span> <?php echo $referencia; ?><br />
                    <?php } ?>
                </p>

            </div>
            <div class="pdf-body">
<!--                 <div id="grid">
                	
                </div> -->
                <div class="row">
<!--                     <div class="text-center">
                        <span style="color:red; font-size: 10px;">DESCRIPCION BREVE DEL MATERIAL (SE TIENE QUE ADJUNTAR LA COTIZACION DEL PROVEEDOR).</span>
                    </div> -->
                	<div class="col m12 s12" style="margin-top: 65px;">
                         <table>
                            <thead>
                              <tr style="background-color: white;">
                                  <th><span class="title-pdf">Condiciones de Compra</span></th>
                              </tr>
                            </thead>

                            <tbody>
                              <tr>
                                <td class="text-center"><?php echo $condiciones_compra; ?></td>
                              </tr>
                            </tbody>
                          </table>
                	</div>

                    <div class="col m12 s12">
                         <table>
                            <thead>
                              <tr>
                                  <th><span class="title-pdf">Descripción</span></th>
                              </tr>
                            </thead>

                            <tbody>
                              <tr>
                                <?php if($descripcion == ""){ ?>
                                    <td class="text-center">Sin Descripción</td>
                                <?php }else{ ?>
                                    <td class="text-center"><?php echo $descripcion; ?></td>
                                <?php } ?>
                              </tr>
                            </tbody>
                          </table>
                    </div>

                    <div class="col m12 s12">
                         <table>
                            <thead>
                              <tr>
                                  <th class="text-center"><span class="title-pdf">Importe</span></th>
                                  <th class="text-center"><span class="title-pdf">IVA</span></th>
                                  <th class="text-center"><span class="title-pdf">Retención ISR</span></th>
                                  <th class="text-center"><span class="title-pdf">Retención IVA</span></th>
                                  <th class="text-center"><span class="title-pdf">Total</span></th>
                              </tr>
                            </thead>

                            <tbody>
                              <tr>
                                <td class="text-center">$<?php echo number_format($importe, 2, '.', ','); ?></td>
                                <td class="text-center">$<?php echo number_format($iva, 2, '.', ','); ?></td>
                                <td class="text-center">$<?php echo number_format($retencion_isr, 2, '.', ','); ?></td>
                                <td class="text-center">$<?php echo number_format($retencion_iva, 2, '.', ','); ?></td>
                                <td class="text-center">$<?php echo number_format($total, 2, '.', ','); ?></td>
                              </tr>
                            </tbody>
                          </table>
                    </div>
                </div>

<!-- <?php 
    $originalDate = $fecha_creacion;
    $newDate = date("d/m/Y H:i", strtotime($originalDate));

    $validacion = $fecha_val; 
    $newDate_val = date("d/m/Y H:i", strtotime($validacion));

    $validacion_jefe = $fecha_jefe;
    $newDate_jefe = date("d/m/Y H:i", strtotime($validacion_jefe));
?> -->

                <div class="row">
                    <span class="title-pdf">
                        Solicito: <?php echo $nombre_user; ?> <?php echo $apellido_pa; ?> <?php echo $apellido_ma; ?> el día <?php echo $newDate; ?>
                            
                    </span> <br> 
<!--                     <span class="title-pdf">
                        Audito: <?php echo $name_val; ?> <?php echo $ape_val; ?> el día <?php echo $newDate_val; ?>        
                    </span> <br>  -->
                    <span class="title-pdf">
                        Autorizo: <?php echo $name_jefe; ?> <?php echo $ape_jefe; ?> el día <?php echo $newDate_jefe; ?>
                    </span>
                </div>

                <div class="row signature">
                    <div class="col m12 s12 text-center">
                        <img src="/img/logo-2.png" style="width: 150px;"><br>
                        Aprobado: ING. Rubén García Guzmán<br /><br />
                        <?php echo $newDate_jefe; ?>
                    </div>
                </div>


<!--                 <p class="signature">
                    Signature: ________________ <br /><br />
                    Date: 12.03.2014
                </p> -->
            </div>
        </div>
    </div>


    
    <div class="responsive-message"></div>

    <style>
        /*
            Use the DejaVu Sans font for display and embedding in the PDF file.
            The standard PDF fonts have no support for Unicode characters.
        */
        .pdf-page {
            font-family: "DejaVu Sans", "Arial", sans-serif;
        }
    </style>

    <script>
        // Import DejaVu Sans font for embedding

        // NOTE: Only required if the Kendo UI stylesheets are loaded
        // from a different origin, e.g. cdn.kendostatic.com
        kendo.pdf.defineFont({
            "DejaVu Sans"             : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans.ttf",
            "DejaVu Sans|Bold"        : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Bold.ttf",
            "DejaVu Sans|Bold|Italic" : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf",
            "DejaVu Sans|Italic"      : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf"
        });
    </script>

    <!-- Load Pako ZLIB library to enable PDF compression -->
    <script src="../content/shared/js/pako.min.js"></script>

    <script>
      function getPDF(selector) {
        kendo.drawing.drawDOM($(selector)).then(function(group){
          kendo.drawing.pdf.saveAs(group, "Solicitud NO <?php echo $solicitud; ?> .pdf");
        });
      }

    $(document).ready(function() {
        var data = [
          { productName: "QUESO CABRALES", unitPrice: 21, qty: 5 },
          { productName: "ALICE MUTTON", unitPrice: 39, qty: 7 },
          { productName: "GENEN SHOUYU", unitPrice: 15.50, qty: 3 },
          { productName: "CHARTREUSE VERTE", unitPrice: 18, qty: 1 },
          { productName: "MASCARPONE FABIOLI", unitPrice: 32, qty: 2 },
          { productName: "VALKOINEN SUKLAA", unitPrice: 16.25, qty: 3 }
        ];
        var schema = {
          model: {
            productName: { type: "string" },
            unitPrice: { type: "number", editable: false },
            qty: { type: "number" }
          },
          parse: function (data) {
                $.each(data, function(){
                    this.total = this.qty * this.unitPrice;
                });
                return data;
          }
        };
        var aggregate = [
          { field: "qty", aggregate: "sum" },
          { field: "total", aggregate: "sum" }
        ];
        var columns = [
          { field: "productName", title: "Product", footerTemplate: "Total"},
          { field: "unitPrice", title: "Price", width: 120},
          { field: "qty", title: "Pcs.", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" },
          { field: "total", title: "Total", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" }
        ];
        var grid = $("#grid").kendoGrid({
          editable: false,
          sortable: true,
          dataSource: {
            data: data,
            aggregate: aggregate,
            schema: schema,
          },
          columns: columns
        });

        $("#paper").kendoDropDownList({
          change: function() {
            $(".pdf-page")
              .removeClass("size-a4")
              .removeClass("size-letter")
              .removeClass("size-executive")
              .addClass(this.value());
          }
        });
    });
    </script>
    <style>

        .title-pdf{
            font-weight: bold;
            font-size: 13px;
        }
        .pdf-page {
            margin: 0 auto;
            box-sizing: border-box;
            box-shadow: 0 5px 10px 0 rgba(0,0,0,.3);
            background-color: #fff;
            color: #333;
            position: relative;
        }
        .pdf-header {
            position: absolute;
            top: .5in;
            height: .6in;
            left: .5in;
            right: .5in;
            /*border-bottom: 1px solid #e5e5e5;*/
        }
        .invoice-number {
            padding-top: .17in;
            float: right;
        }
        .pdf-footer {
            position: absolute;
            bottom: .5in;
            height: .6in;
            left: .5in;
            right: .5in;
            padding-top: 10px;
            border-top: 1px solid #e5e5e5;
            text-align: left;
            color: #787878;
            font-size: 12px;
        }
        .pdf-body {
            position: absolute;
            top: 4.3in;
            bottom: 1.2in;
            left: .5in;
            right: .5in;
        }

        .size-a4 { width: 8.3in; height: 11.7in; }
        .size-letter { width: 8.5in; height: 11in; }
        .size-executive { width: 7.25in; height: 10.5in; }

        .company-logo {
            font-size: 34px;
            font-weight: bold;
            color: #3aabf0;
        }
        .for {
            position: absolute;
            top: 1.5in;
            left: .5in;
            width: 3.5in;
        }
        .from {
            position: absolute;
            top: 1.5in;
            right: .5in;
            width: 3.5in;
        }
        .from p, .for p {
            color: #787878;
        }
        .signature {
            padding-top: .5in;
        }
    </style>

</div>


</body>
