<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/envios/solicitudespendientes" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>
</div>


<div class="row">
	<div class="col m12 s12 text-center" style="margin-top: 30px;">
		<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Error al generar solicitud de envío</span>
	</div>
</div>

<div class="row">
	<div class="col m2 s12"></div>
	<div class="col m8 s12">
		<span>Para generar una solicitud valida es necesario seguir las siguientes condiciones:</span>
	</div>
	<div class="col m2 s12"></div>
</div>

<div class="row">
	<div class="col m2 s12"></div>
	<div class="col m8 s12">
		<div>
			<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Local:</span> <span>No se podra generar una solicitud si el envio es para el mismo día </span>
		</div>
		<div>
			<span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Foraneo:</span> <span>No se podra generar una solicitud si la fecha de envio no tiene al menos 5 días.  </span>
		</div>
	</div>
	<div class="col m2 s12"></div>
</div>


<div class="row">
	<div class="col m2 s12"></div>
	<div class="col m8 s12">
		
	</div>
	<div class="col m2 s12"></div>	
</div>