


<div class="row">
    <div class="col m12 s12 text-center" style="margin-top: 22px;">
        <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Logistica de envíos</span>
    </div>
</div>


<div class="row">
	<div class="col s12 m2"></div>
    <div class="col s12 m8">
      	<div class="card">
       		<div class="card-content">
				<div class="row">
					<div class="col m2 s12"></div>
					<div class="col m8 s12">
					    <div class="input-field col m12 s12">
					        <input placeholder="*selecciona una fecha" id="fecha_uni" name="fecha_envio" type="text" class="datepicker">
					        <label for="fecha_uni">Fecha de envío</label>
					    </div>
					    <div class="input-field col m12 s12 text-center">
					    	<a class="btn" id="obtener"><i class="material-icons right">flight_takeoff</i>Buscar</a>

					    </div>
					</div>
					<div class="col m2 s12"></div>
	        	</div>
      		</div>
   		 </div>
	</div>
	<div class="col s12 m2"></div>
</div>



<script type="text/javascript">
	$(document).ready(function(){
    	$('.datepicker').datepicker( {"format":'dd/mm/yyyy'});
    	$('select').formSelect();
    	$('.modal').modal();
    	$('.timepicker').timepicker();
    	var currentDate = document.getElementById("today_picker").value; 
    	$('.datepicker').datepicker( {"format":'dd/mm/yyyy'} ).datepicker("setDate",currentDate);
	});

	$("#obtener").click(function(){
		var fecha = document.getElementById("fecha_uni").value;
		var dia = fecha.slice(0, -8);
		var mes = fecha.slice(3, -5);
		var year = fecha.slice(6);

		// alert(year);

	    if(fecha == ""){
	        swal({
	            title: "Para continuar debes agregar una fecha ",
	        });
	    }else{
	        swal("Espere un momento, la información esta siendo procesada", {
	            icon: "success",
	            buttons: false,
	        }); 
	        window.location.href = '/envios/logisticaenvios/dia/'+dia+'/mes/'+mes+'/year/'+year+'';   
	    }
	});
	// function submitForm() { document.getElementById("submit_gasolina").submit() }
</script>
