<?php 
	function isActhref($nameBtn,$urlname){
	    if($nameBtn==1 && $urlname==null){
	    	return "active"; 
	    }
	    return ($nameBtn == $urlname)?"active":"";
	}

    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }


 ?>

<style type="text/css">
	.oculto{
		display: none;
	}
</style>


<div class="row"> 
    <div class="col m12 s12 text-center" style="margin-top: 30px;">
        <span style="font-size:24px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Asignación de Cuadrillas</span>
    </div>
</div>


<div class="row">
    <div class="col m1 s12"></div>
    <div class="col m10 s12">
        <div class="row">
            <div class="col m5 s6">
                <div class="input-field col s12">
                    <select id="select_search">
                        <option value="1" selected>Nombre</option>
                        <option value="2">Puesto</option>
                        <option value="3">Sitio</option>
                        <option value="4">Status</option>
                    </select>
                    <label>Buscar por: </label>
                </div>
            </div>
            <div class="col m5 s6">
                <div class="input-field col s12 op_nombre">
                    <input placeholder="Ingresa el nombre(s) del personal" id="name_search" type="text">
                    <label for="name_search">Nombre</label>
                </div>

                <div class="input-field col m12 s12 oculto op_puesto">
                    <select id="puesto" name="puesto">
                        <option value="0" disabled selected>* Selecciona una opcion</option>
                        <?php foreach ($this->puesto as $key){ ?>
                            <option value="<?php echo $key['id']; ?>"><?php echo $key['nombre']; ?></option>
                        <?php } ?>
                    </select>
                    <label>Puesto:</label>
                </div>

                <div class="input-field col s12 oculto op_sitio">
                    <input placeholder="Ingresa el nombre del sitio" id="sitio_search" type="text" class="validate">
                    <label for="sitio_search">Sitio</label>
                </div>

                <div class="input-field col s12 oculto op_status">
                    <select id="select_status">
                        <option value="" disabled selected>Selecciona una opcion</option>
                        <option value="0">Disponible</option>
                        <option value="1">En sitio</option>
                    </select>
                    <label>Status</label>
                </div>

            </div>
            <div class="col m2 s12 text-center">
                <div class="input-field col s12">
                    <a class="btn" id="btn_search">Buscar</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col m1 s12"></div>
</div>


<div class="row">
    <div class="col m12 s12">
        <div class="row">
            <div class="col m8 s6">
                <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista del Personal</span>
            </div>
            <div class="col m4 s6 text-right">
                <div class="row">
                    <div class="col m6 s6 text-right">
                        <a href="/personal/asignarpersonal" class="btn green">Asignar</a>
                    </div>
                    <div class="col m6 s6 text-left">
                        <a href="/personal/liberarpersonal"  class="btn red">Liberar</a>
                    </div>
                </div>
            </div>
        </div>
        <table class="table text-left table-hover">
            <thead>
                <tr>
                    <th>Nombre</th> 
                    <th>Puesto</th>
                    <th>Sitio</th>
                    <th>Fecha Inicio</th>
                    <th>Fecha Final</th>
                </tr> 
            </thead>
            <?php if ($this->paginator) { 
                foreach ($this->paginator as $usr) { ?>
            <tbody>
                <tr>
                    <td><?php echo $usr["nombre"]; ?> <?php echo $usr["apellido_pa"]; ?> <?php echo $usr["apellido_ma"]; ?></td>
                    <td><?php echo $usr["name_puesto"]; ?></td>
                    <td>
                        <?php if($usr["name_sitio"] == NULL || $usr["name_sitio"] == "vacio"){ ?>
                            Por Asignar
                        <?php }else{ ?>
                            <?php echo $usr["name_sitio"]; ?>
                        <?php } ?>

                    </td>
                    <td>
                        <?php echo $usr["fechainicio_asignacion"]; ?>
                    </td>
                    <td>
                        <?php echo $usr["fechafinal_asignacion"]; ?>
                    </td>
                    <td>
                        <?php if($usr['status_cuadrilla'] == 1){ ?>
                            <a class="liberar_personal" data-id="<?php echo $usr["id"]; ?>" data-nombre="<?php echo $usr["nombre"]; ?>" data-ap="<?php echo $usr["apellido_pa"]; ?>" data-am="<?php echo $usr["apellido_ma"]; ?>"><span class="warning"><i class="fa fa-2x fa-external-link" style="color: red"></i></span>
                            </a>
                        <?php }else{ ?>
                            <a class="asignar_personal modal-trigger" href="#modal3" data-id="<?php echo $usr["id"]; ?>" data-nombre="<?php echo $usr["nombre"]; ?>" data-ap="<?php echo $usr["apellido_pa"]; ?>" data-am="<?php echo $usr["apellido_ma"]; ?>"><span class="warning"><i class="fa fa-2x fa-plus" style="color: green"></i></span>
                            </a>
                        <?php } ?>
                    </td>
                    <td>
<!--                     <td>
                        <a href="/personal/asistenciapersonal/id/<?php echo $usr["id"] ?>"><i class="fa fa-2x fa-id-card-o"></i></a>    
                    </td> -->
                    </td>
                </tr>
            </tbody>
            <?php } }else{ ?>
            <tbody>
                <tr>
                    <td>No se ha agregado personal </td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
            <?php } ?>
        </table>
    </div>
</div>





<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
                    <?php if($pagina - 1 == 0){ ?>
                        <li class="page-item disabled">
                            <span class="page-link">Anterior</span>
                        </li>
                    <?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
                    <?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
                    <?php if($pagina >= $this->total): ?>
                        <li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                        </li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>


<div id="modal3" class="modal modal-fixed-footer">
    <div class="modal-content">
        <div class="row">
            <span style="font-size:24px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">
                Asignar Personal
            </span>
        </div>

        <div class="row">
            <div class="col m12 s12">
                <span id="name_userspan"style="font-size:17px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;"></span>
            </div>
        </div>

        <div class="row">
            <div class="col m2 s6 text-center">
                <div class="chip modal-trigger" id="sitio_op">
                    <img src="/img/correct.png" class="sitio_uno">
                    <img src="/img/gris.jpg" class="sitio_dos oculto">
                    Sitio
                </div>
            </div>
            <div class="col m4 s6 text-center">
                <div class="chip modal-trigger" id="compensacion_op">
                    <img src="/img/gris.jpg" class="comp_uno">
                    <img src="/img/correct.png" class="comp_dos oculto">
                    Compensación
                </div>
            </div>
            <div class="col m3 s6 text-center">
                <div class="chip modal-trigger" id="taller_op">
                    <img src="/img/gris.jpg" class="taller_uno">
                    <img src="/img/correct.png" class="taller_dos oculto">
                    Taller
                </div>
            </div>

            <div class="col m3 s6 text-center">
                <div class="chip modal-trigger" id="vacaciones_op">
                    <img src="/img/gris.jpg" class="vacaciones_uno">
                    <img src="/img/correct.png" class="vacaciones_dos oculto">
                    Vacaciones
                </div>
            </div>
        </div>
        
        <div class="row" style="margin-top: 20px;" id="div_sitio">
            <form action="/personal/requestaddpersonalasignar" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_addperson">
                <input type="hidden" name="id_user" id="id_user" value="">
                <input type="hidden" name="op" value="1">
                <div class="col m12 s12">
                    <div class="input-field col m12 s12">
                        <select id="sitio_op" name="sitio">
                            <option value="0" disabled selected>* Selecciona un Sitio</option>
                            <?php foreach ($this->sitios as $key){ ?>
                                <option value="<?php echo $key['id']; ?>"><?php echo $key['nombre']; ?> - <?php echo $key['id_cliente']; ?></option>
                            <?php } ?>
                        </select>
                        <label>Sitio:</label>
                    </div>

                    <div class="input-field col m12 s12">
                        <select id="proyecto_op" name="proyecto">
                            <option value="0" disabled selected>* Selecciona un Proyecto</option>
                            <?php foreach ($this->proyectos as $key){ ?>
                                <option value="<?php echo $key['id']; ?>"><?php echo $key['nombre']; ?> / <?php echo $key['nombre_proyecto']; ?> - Cliente: <?php echo $key['id_cliente']; ?></option>
                            <?php } ?>
                        </select>
                        <label>Proyecto:</label>
                    </div>

                    <div class="input-field col m6 s12">
                        <input id="fecha_inicial" name="fecha_inicial" type="date" class="datepicker">
                        <label for="fecha_inicial">* Fecha Inicial</label>
                    </div>

                    <div class="input-field col m6 s12">
                        <input id="fecha_final" name="fecha_final" type="date" class="datepicker">
                        <label for="fecha_final">* Fecha Final</label>
                    </div>

                </div>
            </form>
        </div>

        <div class="row oculto" style="margin-top: 20px;" id="div_compensacion">
            <form action="/personal/requestaddpersonalasignar" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_compensacion">
                <input type="hidden" name="op" value="2">
                <input type="hidden" name="id_user" id="id_userdos" value="">
                <div class="input-field col m6 s12">
                    <input id="fecha_inicialcomp" name="fecha_inicial" type="date" class="datepicker">
                    <label for="fecha_inicialcomp">* Fecha Inicial</label>
                </div>

                <div class="input-field col m6 s12">
                    <input id="fecha_finalcomp" name="fecha_final" type="date" class="datepicker">
                    <label for="fecha_finalcomp">* Fecha Final</label>
                </div>
            </form>
        </div>

        <div class="row oculto" style="margin-top: 20px;" id="div_taller">
            <form action="/personal/requestaddpersonalasignar" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_taller">
                <input type="hidden" name="op" value="3">
                <input type="hidden" name="id_user" id="id_usertres" value="">
                <div class="input-field col m6 s12">
                    <input id="fecha_inicialtaller" name="fecha_inicial" type="date" class="datepicker">
                    <label for="fecha_inicialtaller">* Fecha Inicial</label>
                </div>

                <div class="input-field col m6 s12">
                    <input id="fecha_finaltaller" name="fecha_final" type="date" class="datepicker">
                    <label for="fecha_finaltaller">* Fecha Final</label>
                </div>
            </form>
        </div>


        <div class="row oculto" style="margin-top: 20px;" id="div_vacaciones">
            <form action="/personal/requestaddpersonalasignar" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_vacaciones">
                <input type="hidden" name="op" value="4">
                <input type="hidden" name="id_user" id="id_usercuatro" value="">
                <div class="input-field col m6 s12">
                    <input id="fecha_inicialvaca" name="fecha_inicial" type="date" class="datepicker">
                    <label for="fecha_inicialvaca">* Fecha Inicial</label>
                </div>

                <div class="input-field col m6 s12">
                    <input id="fecha_finalvaca" name="fecha_final" type="date" class="datepicker">
                    <label for="fecha_finalvaca">* Fecha Final</label>
                </div>
            </form>
        </div>

    </div>
    <div class="modal-footer">          
        <button class=" btn" id="adduser">Guardar</button>
        <button class=" btn oculto" id="btn_compensacion">Guardar</button>
        <button class=" btn oculto" id="btn_taller">Guardar</button>
        <button class=" btn oculto" id="btn_vacaciones">Guardar</button>

        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>

<input type="hidden" id="buscador_op" value="1">
<script type="text/javascript">
    $(document).ready(function(){
        $('.modal').modal();
    });

    $(".asignar_personal").click(function(){
        nombre = $(this).data('nombre');
        ap = $(this).data('ap');
        am = $(this).data('am');
        name = nombre + " " + ap + " "+ am;
        document.getElementById("name_userspan").innerHTML=name;

        id = $(this).data('id');
        document.getElementById("id_user").value=id;
        document.getElementById("id_userdos").value=id;
        document.getElementById("id_usertres").value=id;
        document.getElementById("id_usercuatro").value=id;
    });


    $(".liberar_personal").click(function(){
        id=$(this).data('id');
        nombre=$(this).data('nombre');
        ap=$(this).data('ap');
        am =$(this).data('am');

        swal({
            title: "Estas seguro de liberar a "+ap+" "+nombre+" del sitio?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete) {
                swal("Espere un momento, "+ap+" "+nombre+"  se liberara del sitio", {
                    icon: "success",
                    buttons: false,
                });

                var request = $.ajax({
                    url:"/panel/requestliberarpersonal",
                    method:"POST",
                    data: { id : id },
                    processData: true,
                });
    //-------------------end de ajax---------------------------

    //-------------peticion de respuesta de ajax------------------
                request.done(function(response) {
                    console.log(response);//imprime lo que responde el ajax
                    // alert
                    window.location.reload(true);
                });
    //-------------------end de respuesta ajax---------------------
                 return false;
            } else {
                swal("La accion fue cancelada!");
            } 
        });

    });

    $("#adduser").click(function(){
        var id_user = document.getElementById("id_user").value;
        var sitio_op = document.getElementById("sitio_op").value;
        var proyecto_op = document.getElementById("proyecto_op").value;
        var fecha_inicial = document.getElementById("fecha_inicial").value;
        var fecha_final = document.getElementById("fecha_final").value;

        if(id_user == "" || sitio_op== 0 || proyecto_op== 0 || fecha_inicial=="" || fecha_final== ""){
            swal({
                title: "Para asignar al personal es necesario llenar los datos",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submitForm, 1500);     
        }
    });

    function submitForm() { document.getElementById("submit_addperson").submit() }


    $("#select_search").on('change', function() {
        var value = this.value;
        document.getElementById("buscador_op").value= value;
        if(value == 1){
            $(".op_nombre").show();
            $(".op_puesto").hide();
            $(".op_sitio").hide();
            $(".op_status").hide();
        }

        if(value == 2){
            $(".op_puesto").show();
            $(".op_nombre").hide();
            $(".op_sitio").hide();
            $(".op_status").hide();            
        }

        if(value == 3){
            $(".op_sitio").show();
            $(".op_nombre").hide();
            $(".op_puesto").hide();
            $(".op_status").hide();
        }

        if(value == 4){
            $(".op_status").show();
            $(".op_nombre").hide();
            $(".op_puesto").hide();
            $(".op_sitio").hide();            
        }
    });


    $("#btn_search").click(function(){
        var buscador = document.getElementById("buscador_op").value;
        if(buscador == 1){
            var name_search = document.getElementById("name_search").value;

            if(name_search == ""){
                swal({
                    title: "Es necesario agregar el nombre del personal",
                });
            }else{
                window.location.href = "/personal/buscadorpersonal/nombre/"+name_search+"/op/1"; 
            }
        }

        if(buscador == 2){
            var puesto = document.getElementById("puesto").value;
            if(puesto == 0){
                swal({
                    title: "Es necesario seleccionar un puesto",
                });
            }else{
                window.location.href = "/personal/buscadorpersonal/puesto/"+puesto+"/op/2"; 
            }
        }

        if(buscador == 3){
            var sitio_search = document.getElementById("sitio_search").value;
            if(sitio_search == ""){
                swal({
                    title: "Es necesario agregar el nombre del sitio",
                });
            }else{
                window.location.href = "/personal/buscadorpersonal/sitio/"+sitio_search+"/op/3"; 
            }
        }

        if(buscador == 4){
            var select_status = document.getElementById("select_status").value;
            if(select_status == ""){
                swal({
                    title: "Es necesario seleccionar un status",
                });
            }else{
                window.location.href = "/personal/buscadorpersonal/status/"+select_status+"/op/4"; 
            }
        }
    });

    $("#sitio_op").click(function(){
        $(".sitio_uno").show(); $(".sitio_dos").hide();
        $(".comp_uno").show(); $(".comp_dos").hide();
        $(".taller_uno").show(); $(".taller_dos").hide();
        $(".vacaciones_uno").show(); $(".vacaciones_dos").hide();

        $("#div_sitio").show();
        $("#div_compensacion").hide();
        $("#div_taller").hide();
        $("#div_vacaciones").hide();

        $("#adduser").show();
        $("#btn_compensacion").hide();
        $("#btn_taller").hide();
        $("#btn_vacaciones").hide();
    });

    $("#compensacion_op").click(function(){
        $(".sitio_uno").hide(); $(".sitio_dos").show();
        $(".comp_uno").hide(); $(".comp_dos").show();
        $(".taller_uno").show(); $(".taller_dos").hide();
        $(".vacaciones_uno").show(); $(".vacaciones_dos").hide();

        $("#div_sitio").hide();
        $("#div_compensacion").show();
        $("#div_taller").hide();
        $("#div_vacaciones").hide();

        $("#adduser").hide();
        $("#btn_compensacion").show();
        $("#btn_taller").hide();
        $("#btn_vacaciones").hide();
    });

    $("#taller_op").click(function(){
        $(".taller_uno").hide(); $(".taller_dos").show();
        $(".sitio_uno").hide(); $(".sitio_dos").show();
        $(".comp_uno").show(); $(".comp_dos").hide();
        $(".vacaciones_uno").show(); $(".vacaciones_dos").hide();

        $("#div_sitio").hide();
        $("#div_compensacion").hide();
        $("#div_taller").show();
        $("#div_vacaciones").hide();

        $("#adduser").hide();
        $("#btn_compensacion").hide();
        $("#btn_taller").show();
        $("#btn_vacaciones").hide();
    });

    $("#vacaciones_op").click(function(){
        $(".sitio_uno").hide(); $(".sitio_dos").show();
        $(".comp_uno").show(); $(".comp_dos").hide();
        $(".taller_uno").show(); $(".taller_dos").hide();
        $(".vacaciones_uno").hide(); $(".vacaciones_dos").show();

        $("#div_sitio").hide();
        $("#div_compensacion").hide();
        $("#div_taller").hide();
        $("#div_vacaciones").show();

        $("#adduser").hide();
        $("#btn_compensacion").hide();
        $("#btn_taller").hide();
        $("#btn_vacaciones").show();
    });


    $("#btn_compensacion").click(function(){
        var id_user = document.getElementById("id_user").value;
        var fecha_inicial = document.getElementById("fecha_inicialcomp").value;
        var fecha_final = document.getElementById("fecha_finalcomp").value;

        if(id_user == "" ||  fecha_inicial=="" || fecha_final== ""){
            swal({
                title: "Para asignar al personal es necesario llenar los datos",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submitComp, 1500);     
        }
    });
    function submitComp() { document.getElementById("submit_compensacion").submit() }


    $("#btn_taller").click(function(){
        var id_user = document.getElementById("id_user").value;
        var fecha_inicial = document.getElementById("fecha_inicialtaller").value;
        var fecha_final = document.getElementById("fecha_finaltaller").value;

        if(id_user == "" ||  fecha_inicial=="" || fecha_final== ""){
            swal({
                title: "Para asignar al personal es necesario llenar los datos",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submittaller, 1500);     
        }
    });
    function submittaller() { document.getElementById("submit_taller").submit() }

    $("#btn_vacaciones").click(function(){
        var id_user = document.getElementById("id_user").value;
        var fecha_inicial = document.getElementById("fecha_inicialvaca").value;
        var fecha_final = document.getElementById("fecha_finalvaca").value;

        if(id_user == "" ||  fecha_inicial=="" || fecha_final== ""){
            swal({
                title: "Para asignar al personal es necesario llenar los datos",
            });
        }else{
            swal("Espere un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            }); 
            setTimeout(submitvacaciones, 1500);     
        }
    });
    function submitvacaciones() { document.getElementById("submit_vacaciones").submit() }
    
</script>