<style type="text/css">
  .parallax-container {
  height: 400px;
}

  #prl1{
    width: 100%; height: 500px;
  }

  #logo{
    width: 480px;
  }


@media screen and (max-width: 600px) {
  body {
    /*background-color: olive;*/
  }

  #prl1{
    width: 100%; height: 500px;
  }

  #logo{
    width: 200px;

  }

}

</style>


<!-- Content -->
<div class="parallax-container center valign-wrapper" id="prl1">
  <div class="container">
    <div class="row">
      <div class="col m12 s12 text-left">
        <img src="/img/logo-2.png" id="logo">
      </div>
    </div>
  </div>
  
  <div class="parallax">
    <img src="/img/portada_cuatro.jpeg">
  </div>
</div>


<div class="container" style="margin-top: 20px;">
  <div class="row">
    <div class="col m12 s12 text-center">
      <span style="font-size:40px; color: rgb(74,79,84); letter-spacing: 0.2em;">GPS Constructivos</span>
    </div>
   </div>

<!--    <div class="row">
    <div class="col md12 s12 text-center mt-4">
      <span style="font-size:25px; color: rgb(74,79,84);">Somos una empresa mexicana, <br>  
        que ofrece diversos servicios de construcción de infraestructura <br>
      para la industria de las telecomunicaciones.</span> 
    </div>
   </div> -->
</div>

<div class="container" style="margin-top: 20px;">
  <div class="row">
    <div class="col m12 s12 text-left">
      <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.2em;">Servicios</span>
    </div>
   </div>
</div>

<div class="container">
  <div class="row">
     <div class="col m4 s12">
       <div class="icon-block text-justify">
         <h2 class="center light-blue-text">
           <img src="/img/logo-llaveenmano.png">  
         </h2>
         <h5 class="center">Proyectos llave en mano</h5>
       </div>
       
     </div>
     <div class="col m4 s12">
       <div class="icon-block text-justify">
         <h2 class="center light-blue-text">
          <img src="/img/servicios-ingenieria.png">  
         </h2>
         <h5 class="center">Servicios e ingeniería</h5>
       </div> 
     </div>
     <div class="col m4 s12">
       <div class="icon-block text-justify">
         <h2 class="center light-blue-text">
           <img src="/img/construccion.png"> 
         </h2>
         <h5 class="center">Construccion e instalaciones</h5>
       </div> 
     </div>
   </div>
</div>


<div class="container">
  <div class="row">
     <div class="col m4 s12">
       <div class="icon-block text-justify">
         <h2 class="center light-blue-text">
           <img src="/img/logo-llaveenmano.png">  
         </h2>
         <h5 class="center">Fabricación e instalación de refuerzos de torre</h5>
       </div>
       
     </div>
     <div class="col m4 s12">
       <div class="icon-block text-justify">
         <h2 class="center light-blue-text">
          <img src="/img/servicios-ingenieria.png">  
         </h2>
         <h5 class="center">Fabricaciones de plataformas, herrajes y accesorios</h5>
       </div> 
     </div>
     <div class="col m4 s12">
       <div class="icon-block text-justify">
         <h2 class="center light-blue-text">
           <img src="/img/construccion.png"> 
         </h2>
         <h5 class="center">Mantenimiento</h5>
       </div> 
     </div>
   </div>
</div>


<div class="parallax-container center valign-wrapper">
  <div class="parallax"><img src="https://images.unsplash.com/photo-1463780324318-d1a8ddc05a11?dpr=1&auto=format&fit=crop&w=1500&h=1000&q=80&cs=tinysrgb&crop=">
  </div>
  
  <div class="container white-text">
    <div class="row">
      <div class="col s12">
        <h5>A modern responsive front-end framework based on Material Design</h5>
      </div>
    </div>
  </div>
</div>

<div class="container center-align">
 <div class="section">
    <div class="row">
    <div class="col s12">
      <h4>Contact Us</h4>
      <p class="light left-align">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
      </p>
    </div>      
  </div>
  </div>
</div>




<script type="text/javascript">
  $(document).ready(function(){
  $('.parallax').parallax();
});
</script>