<?php
  // Pregunta 1
  $text = "PROGRAMADOR PHP";

  for($i=0; $i<strlen($text); $i++)
  {
    echo " ".$text[$i];
  }

  //Pregunta 2
  $porciones = explode(" ", $text);
  echo "<br>". $porciones[1] . " " .strrev($porciones[0]);


  //Pregunta 3
  $months = 13;
  $meses = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"];

  for($i=1; $i<$months; $i++)
  {

    echo "<br>". $meses[$i - 1] . " ";
    for( $d=1; $d<=cal_days_in_month(CAL_GREGORIAN, $i, 2022); $d++ ){    
        echo $d. ",";
    }


  }

  //Pregunta 4  Calculo de intereses
  // calcular el interés diario para el mes de marzo del 2021.
    $total = 0;
    for ($i=1; $i<=31; $i++)
    {
      $interes =( (11/360) / 100 ) *$i*100000;
      echo "<br> Dia: ". $i. " Octubre, Interes calculado $". round($interes,2);
      $total = $total + $interes;
    }

    echo "<br>". "Total Interés octubre: $". round($total,2);

?>