  <?php 
  function isActhref($nameBtn,$urlname){
    if($nameBtn==1 && $urlname==null){
      return "active"; 
    }
    return ($nameBtn == $urlname)?"active":"";
  }

    if (isset($_GET['pagina'])) {
      $pagina = $_GET['pagina'];
    } else {
      $pagina = 1;
    }  
  ?>

<?php 

    $links = "";
    $url="";

        if($this->total== 1){
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            if ($this->total >= 1 && $pagina <= $this->total) {

              if (isset($_GET['pagina']) && $this->actpage != 1) {
                $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }else{
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
              }
                
                $i = max(2, $pagina - 3);
                if ($i > 2)
                    $links .= " <li><a>...</a></li> ";
                for (; $i < min($pagina + 3, $this->total); $i++) {
                  if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }else{
                    $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
                  }
                }
                if ($i != $this->total)
                    $links .= " <li><a>...</a></li> ";
                if($i ==$this->actpage){
                    $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }else{
                    $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
                }
                
            }           
        }
?>

<!-- Inicio Botones -->
<div class="row" style="margin-top: 10px;">
  <div class="col m6 s6">
    <a href="/vehiculos/inventariov" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>  
  </div>
  <div class="col m6 s6 text-right">
    <a class="waves-effect green btn modal-trigger" href="#modal1">+ Agregar Grupo</a>
  </div>
</div>

<div class="row">
  <div class="col m12 s12 text-center" style="margin-top: 10px;">
    <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Grupos
  </div>
</div>
<!-- End Inicio Botones -->

<!-- Modal Structure 1 -->
<div id="modal1" class="modal modal-fixed-footer">
  <div class="modal-content">
    <div class="col m12 s12" style="margin-top: 10px;">
      <span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar Grupo</span>
    </div>

    <div class="col m12 s12">
      <form action="/vehiculos/requestaddgrupo" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_g">
        <div class="row">
          <div class="input-field col m12 s12">
            <i class="material-icons prefix">assignment</i>
            <input id="name" type="text" name="name" class="validate" required>
            <label for="name">* Nombre:</label>
          </div>
				</div>
    </div>
	</div>

  <div class="modal-footer">
    		</form>
    <button class=" btn" id="addgrupo">Guardar</button>	
    <button  class="modal-close red btn">Cerrar</button>
  </div>
</div>
<!-- End Modal -->

  
  <!-- Table Grupo -->
<div class="col m8 s12">
  <div class="row">
    <div class="col m12 s12" style="margin-top: 10px;">
      <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Lista de Grupos</span>
    </div>
  </div>

  <table class="table text-center table-hover">
    <thead>
      <tr>
        <th>Id</th>
				<th>Nombre</th>	
				<th>Editar</th>
			</tr> 
		</thead>

    <?php if ($this->paginator) {
		foreach ($this->paginator as $grupo) { ?>
      <tbody>
        <tr class="text-center">
				  <td><?php echo $grupo["id_grupo"]; ?></td>
				  <td><?php echo $grupo["nombre"]; ?></td>
				  <td>
					 <a href="/vehiculos/grupoedit/id/<?php echo $grupo["id_grupo"] ?>"><i class="fa fa-2x fa-edit"></i></a>
				  </td>
			 </tr>
		  </tbody>
    <?php } } else{ ?>
      <tbody>
        <td></td>
				<td>
					<h4>No se encontraron grupos de vehículos</h4>
				</td>
				<td></td>
			</tbody>
    <?php }?>
  </table>
</div>
  <!-- End Table Grupo -->

<!-- Paginación  -->

<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
               		<?php if($pagina - 1 == 0){ ?>
                    	<li class="page-item disabled">
                        	<span class="page-link">Anterior</span>
                    	</li>
               		<?php }else{ ?>
                        <li class="page-item">
                            <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                        </li>
               		<?php } ?>
                        <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                            <?php echo $links; ?>
                        </li>
               		<?php if($pagina >= $this->total): ?>
                       	<li class="page-item disabled">
                            <span class="page-link">Siguente</span>
                       	</li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                   	<?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>


<!-- End Paginacion  -->
<!-- Scripts -->
  <script type="text/javascript">
	  
	  $(document).ready(function(){
	  	$('.modal').modal();
	  });
	  //Modal script//

	  $("#addgrupo").click(function(){
	  	var name = document.getElementById("name").value;

            if(name == ""){
                swal({
                  title: "Para agregar un grupo ingresa el nombre(*)",
                });
            }else{
                 swal("Espera un momento, la información esta siendo procesada", {
				icon: "success",
			 	buttons: false,
			});
                setTimeout(submitForm, 500);     
            }
        });

        function submitForm() {
            document.getElementById("submit_g").submit()
        }
        //Agregar Categoría Script



</script>