<?php foreach ($this->vehiculosc as $veh) { $idv = $veh['id_vehiculos']; }?>

<?php 
function isActhref($nameBtn,$urlname){
    if($nameBtn==1 && $urlname==null){
        return "active"; 
    }
    return ($nameBtn == $urlname)?"active":"";
}
    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>
<?php 
 
$links = "";
$url="";

if($this->total== 1){
    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
}else{
    if ($this->total >= 1 && $pagina <= $this->total) {

        if (isset($_GET['pagina']) && $this->actpage != 1) {
            $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }

        $i = max(2, $pagina - 3);
        if ($i > 2)
            $links .= " <li><a>...</a></li> ";
        for (; $i < min($pagina + 3, $this->total); $i++) {
            if($i ==$this->actpage){
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
            }else{
                $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
            }
        }
        if ($i != $this->total)
            $links .= " <li><a>...</a></li> ";
        if($i ==$this->actpage){
            $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
        }else{
            $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
        }

    }           
}

?>

<?php 
    date_default_timezone_set('America/Mexico_City');
    $hoy = date("d/m/Y");
    $year = date("Y");
?>

<?php foreach ($this->user as $value) {
    $rol_user = $value['fkroles'];
} ?>

<input type="hidden" name="idvh" id="idvh" value="<?php echo $this->idvh; ?>">

<style type="text/css">
    .table_wrapper{
        overflow-x: auto;
    }

    .oculto{
        display: none;
    }
</style>



<!-- INICIO DETAIL-->
<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <?php foreach ($this->vehiculosc as $veh) { ?>
        <a href="/vehiculos/vehdetail/id/<?php echo $veh['id_vehiculos']; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
        <?php } ?>    
    </div>

    <div class="col m6 s6 text-right">
         <div class="input-field col m12 s12">
            <a class="waves-effect green darken-1 waves-light lighten-4 btn modal-trigger" href="#modaldoc">Añadir Documentación</a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col m12 s12 text-center" style="margin-top: 10px;">
        <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Documentación
    </div>
</div>

<!-- END INICIO DETAIL-->

<!-- Modal Añadir Documento -->
<div id="modaldoc" class="modal modal-fixed-footer">
    <div class="modal-content">
        <div class="row">
            <div class="col m12 s12 text-left" style="margin-top: 5px;">
                <span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Añadir Documentación
            </div>
        </div>
        <div class="row">
            <form action="/vehiculos/requestadddoc" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_doc">
                 <?php foreach ($this->vehiculosc as $veh) { ?>
                    <input type="hidden" name="idhs" value="<?php echo $veh["id_vehiculos"]; ?>">
                <?php } ?> 

                <div class="row">
                    <div class="input-field col m12 s12">
                        <select name="accion" id="accion" required>
                            <option value="" disabled selected>¿La documentación aplica en este vehículo?</option>
                            <option value="1">Aplica</option>
                            <option value="2">No Aplica</option>
                        </select>
                        <label>¿Aplica?</label>
                    </div>

                    <div id="docd" class="file-field input-field col m12 s12 oculto">
                        <div class="btn">
                            <span>Agregar Documento</span>
                            <input type="file" name="url" required>
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" id="url" type="text">
                        </div>
                    </div>

                    <!-- <div class="input-field col m6 s12">
                        <i class="material-icons prefix">today</i>
                        <input type="date" id="fecha" name="fecha"  class="validate">
                        <label for="fecha">*Fecha: dd/mm/yyyy</label>
                    </div> -->

                    <div id="tdocd" class="input-field col m6 s12 oculto">
                        <select name="nombred" id="nombred" required>
                            <option value="" disabled selected>Selecciona Tipo de Documento:</option>
                            <?php foreach ($this->tpod as $tipodoc) { ?>
                                <option value="<?php echo $tipodoc["id"]; ?>"><?php echo $tipodoc["nombredoc"]; ?></option>
                            <?php } ?>
                        </select>
                        <label>*Nombre Documentación:</label>
                    </div>


                    <div id="vigd" class="input-field col m6 s12 oculto">
                        <i class="material-icons prefix">today</i>
                        <input type="date" id="vigencia" name="vigencia"  class="validate">
                        <label for="vigencia">*Vigencia: dd/mm/yyyy</label>
                    </div>

                    <!-- <div class="input-field col m6 s6">
                        <select name="solicitud" id="solicitud" required>
                            <option value="" disabled selected>Selecciona la solicitud que le corresponde:</option>
                            <?php foreach ($this->solicitud as $sveh) { ?>
                                <option value="<?php echo $sveh["id"]; ?>">Id: <?php echo $sveh["id"]; ?> Servicio: <?php echo $sveh["nombre_servicio"]; ?> Monto: $<?php echo $sveh["monto"]; ?></option>
                            <?php } ?>
                        </select>
                        <label>Solicitud:</label>
                    </div> -->

                    <div id="sold" class="input-field col m6 s12 oculto">
                        <select name="solicitud" id="solicitud">
                            <option value="" disabled selected>Selecciona la solicitud que le corresponde:</option>
                            <?php foreach ($this->solicitud as $sveh) { ?>
                                <option value="<?php echo $sveh["id"]; ?>">Id: <?php echo $sveh["id"]; ?> Servicio: <?php echo $sveh["nombre_servicio"]; ?> Monto: $<?php echo $sveh["monto"]; ?></option>
                            <?php } ?>
                        </select>
                        <label>Solicitud:</label>
                    </div>

                    <div id="comd" class="input-field col m6 s12 oculto">
                        <textarea id="comentarios" name="comentarios" class="materialize-textarea"></textarea>
                        <label for="comentarios">Comentarios: </label>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" id="añadirdoc" class="btn">Guardar</button>
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>
<!-- End Modal Añadir Documento -->

<!-- Inicio Tabla Vehiculo -->
<div class="col m8 s12 text-center">
    <div class="row">
        <div class="col s12 m12">
            <div class="row table_wrapper">
                <table class="table text-center table-hover ">
                    <thead>
                        <tr>
                            <th>Marca</th>
                            <th>Submarca</th>
                            <th>Modelo</th>
                            <th>Color</th>
                            <th>Placas</th>
                        </tr>
                    </thead>
                    <?php if ($this->vehiculosc) { 
                    foreach ($this->vehiculosc as $veh) { ?>
                        <tbody>
                            <tr>
                                <td>
                                    <?php echo $veh['marca']; ?>
                                </td>
                                <td>
                                    <?php echo $veh['submarca']; ?>
                                </td>
                                <td>
                                    <?php echo $veh['modelo']; ?>
                                </td>   
                                <td>
                                    <?php echo $veh['color']; ?>
                                </td>
                                <td>
                                    <?php echo $veh['placas']; ?>
                                </td>
                            </tr>
                        </tbody>
                    <?php } }else{ ?>
                        <tbody>
                            <tr>
                                <td></td>
                                <td></td>
                                <td>No existe este vehículo.</td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
                    <?php } ?>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="col m4 s12 text-center">
    <?php if($veh['imagen'] == null){ ?>
            <img src="/img/no_disponible1.png" class="responsive-img" style="width: 200px; margin-top: 5px;">
    <?php }else{ ?>
            <a class="example-image-link" href="/<?php echo $veh['imagen']; ?>" data-lightbox="example-1"><img class="example-image" src="/<?php echo $veh['imagen']; ?>" id="camara_div" style="width: 240px;  margin-top: 5px;"/></a>
        <?php } ?> 
</div>
<!-- End Tabla Vehiculo-->


<!-- Inicio Tabla Documentacion -->
<!-- <div class="col m2 s2 text-center">
    <div class="row">
        <div class="col s12 m12">
            <div class="card darken-1">
                <div class="card-content">
                    <div class="row table_wrapper">
                        <table class="table text-center table-hover ">
                            <thead>
                                <tr>
                                    <th>Tipo Documento</th>
                                </tr>
                            </thead>
                            <?php if ($this->tpodoc) { 
                            foreach ($this->tpodoc as $tipc) { ?>
                                <tbody>
                                    <tr>
                                        <td>
                                            <?php foreach ($this->vehdoc as $c) { $checkl = $c['tipo_doc']; ?>
                                            
                                                <?php if($tipc['id'] == $checkl ) { ?> 
                                                    <?php $tpo = ($checkl) ? true : false;   ?> 

                                                        <input type="checkbox" checked="<?php print $tpo; ?>" disabled name="tipos">
                                                        <span><?php echo $tipc['nombredoc']; ?></span>

                                                <?php }  ?> 
                                            <?php } ?>
                                        </td>
                                    </tr>
                                </tbody>
                            <?php } }else{ ?>
                                <tbody>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td> No existe documentación este vehículo.</td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </tbody>
                            <?php } ?>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>  -->
<!-- End Tabla Documentacion-->


<div class="col m2 s4 text-center">
    <div class="row">
        <div class="col s12 m12">
            <div class="card darken-1">
                <div class="card-content">
                    <div class="row ">
                        <table class="table text-center table-hover ">
                            <thead>
                                <tr>
                                    <th class="text-center">Documentos Faltantes</th>
                                </tr>
                            </thead>
                            <?php if ($this->tpod) { 
                            foreach ($this->tpod as $tipc) { ?>
                                <tbody>
                                    <tr>
                                        <td>
                                            <input type="checkbox"  disabled name="tipos">
                                            <span><?php echo $tipc['nombredoc']; ?></span>
                                        </td>
                                    </tr>
                                </tbody>
                            <?php } }else{ ?>
                                <tbody>
                                    <tr>
                                        <td class="text-center"> Ninguno</td>
                                    </tr>
                                </tbody>
                            <?php } ?>
                        </table>
                        <table class="table text-center table-hover ">
                            <thead>
                                <tr>
                                    <th class="text-center">Documentos Agregados</th>
                                </tr>
                            </thead>
                            <?php if ($this->vehdoc) { 
                            foreach ($this->vehdoc as $completo) { ?>
                                <tbody>
                                    <tr>
                                        <td>
                                            <input type="checkbox" checked="<?php print $tpo; ?>" disabled name="tipos">
                                            <span><?php echo $completo['nombre_doc']; ?></span>
                                        </td>
                                    </tr>
                                </tbody>
                            <?php } }else{ ?>
                                <tbody>
                                    <tr>
                                        <td class="text-center"> Ninguno</td>
                                    </tr>
                                </tbody>
                            <?php } ?>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 


<!-- Inicio Tabla Documentacion -->
<div class="col m10 s8 text-center">
    <div class="row">
        <div class="col s12 m12">
            <div class="card darken-1">
                <div class="card-content">

                    <div class="row">
                        <div style="padding: 1rem 1rem 1rem 1rem;" class="col m6 s8 text-left">
                            <span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Documentación del vehículo  
                        </div>
                        <div class="col m6 s6 text-right">
                             <div class="input-field col m12 s12">
                                <a class="waves-effect darken-1 waves-light lighten-4 btn" href="/vehiculos/historialvd/id/<?php echo $idv; ?>/year/<?php echo $year; ?>">Historial Documentación</a>
                            </div>
                        </div>
                      <!--   <div class="col m6 s6 text-right">
                            <a href="/vehiculos/excelop/id/<?php echo $idv; ?>"> <h4 style="color: green;">Generar Excel  <i class="material-icons">insert_drive_file</i></h4></a>
                        </div> -->
                    </div>

                    <div class="row table_wrapper">
                        <table class="table text-center table-hover ">
                            <thead>
                                <tr>
                                    <!-- <th>Fecha</th> -->
                                    <th>Tipo Documento</th>
                                    <th>Vigencia</th>
                                    <th>Status</th>
                                    <th>Solicitud Asignada</th>
                                    <th>Comentarios</th>
                                    <th>Pago</th>
                                    <th>Documento</th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <?php if ($this->paginator) { 
                            foreach ($this->paginator as $vehd) { ?>
                                <tbody>
                                    <tr>
                                        <!-- <td>
                                            <?php echo $vehd['fecha']; ?>
                                        </td> -->
                                        <td>
                                            <?php echo $vehd['nombre_doc']; ?>
                                        </td>
                                        <td>
                                            <?php if ($vehd['vigencia'] == "") { ?>
                                                No Aplica
                                            <?php } else { ?>
                                                <?php echo $vehd['vigencia']; ?>
                                            <?php } ?>
                                        </td>
                                        <td class="text-center">
                                            <?php if ($vehd['vigencia'] == "") { ?>
                                                No Aplica
                                            <?php } else { ?>
                                                <?php if ($vehd['diasvigencia'] == true) { ?>

                                                    Por Vencer/Vencida<br/>

                                                    <a class="text-center modal-trigger info_res" title="Actualiza Documento" href="#modalactualiza" data-id="<?php echo $vehd["id"] ?>" data-tpo="<?php echo $vehd["tipo_doc"] ?>" data-nombre="<?php echo $vehd["nombre_doc"] ?>"style="color: blue; font-size:8px;"> 
                                                        <i class="material-icons">sync</i> 
                                                    </a><br/>
                                                    
                                                    <b>Actualiza el documento</b><br />
                                                 
                                                <?php } else { ?>
                                                    <?php if (date("Y-m-d",strtotime($vehd['vigencia']."- 1 days")) <= date("Y-m-d",strtotime(date("Y-m-d")."- 31 days"))) { ?>
                                                         Por Vencer/Vencida<br/>

                                                        <a class="text-center modal-trigger info_res" title="Actualiza Documento" href="#modalactualiza" data-id="<?php echo $vehd["id"] ?>" data-tpo="<?php echo $vehd["tipo_doc"] ?>" data-nombre="<?php echo $vehd["nombre_doc"] ?>"style="color: blue; font-size:8px;"> 
                                                            <i class="material-icons">sync</i> 
                                                        </a><br/>
                                                        
                                                        <b>Actualiza el documento</b><br />
                                                    
                                                    <!--  <?php echo date("d-m-Y",strtotime($vehd['vigencia']."- 1 days")) ?>  
                                                     <?php echo date("d-m-Y",strtotime(date("d-m-Y")."- 31 days")) ?> -->


                                                    <?php } else { ?>
                                                        <?php echo $vehd['statusd']; ?>
                                                        <!-- <?php echo date("d-m-Y",strtotime($vehd['vigencia']."- 31 days")) ?>  
                                                        <?php echo date("d-m-Y") ?> -->  
                                                    <?php } ?>
                                                <?php } ?>
                                            <?php } ?>        
                                            <!-- if (date("d-m-Y",strtotime($vehd['vigencia']."- 1 days")) >= date("d-m-Y",strtotime(date("d-m-Y")."- 31 days")) -->
                                        </td>
                                        <td>
                                            <?php if ($vehd['vigencia'] == "") { ?>
                                                <b>El documento no aplica en este vehículo</b>
                                            <?php } else { ?>
                                                <?php if ($vehd["id_sol"] == 0) { ?>
                                                    <b>Sin Solicitud Asignada</b>
                                                <?php } else { ?>
                                                    <b>Solicitud No.<?php echo $vehd['id_sol']; ?></b>
                                                <?php } ?>
                                            <?php } ?>
                                        </td> 
                                         <td>
                                            <?php echo $vehd['comentarios']; ?>
                                        </td>
                                        <td>
                                            <?php if ($vehd['vigencia'] == "") { ?>
                                                No aplica
                                            <?php } else { ?>
                                                <?php if ($vehd["id_sol"] == 0) { ?>
                                                    No cuenta con solicitud.
                                                <?php } else { ?>
                                                    <?php if ($vehd["comprobante_pago"] == null) { ?>
                                                        Aún no se ha pagado.
                                                    <?php } else { ?>
                                                        <a title="Descargar Archivo" href="/<?php echo $vehd["comprobante_pago"]; ?>" download="<?php echo substr(strrchr($vehd["comprobante_pago"], "/"), 1); ?>" style="color: blue; font-size:18px;"> <i class="material-icons left">file_download</i> </a>
                                                    <?php } ?>
                                                <?php } ?>
                                            <?php } ?> 
                                        </td> 
                                        <td>
                                            <?php if ($vehd['vigencia'] == "") { ?>
                                                
                                            <?php } else { ?>
                                                <a title="Descargar Archivo" href="/<?php echo $vehd["documento"]; ?>" download="<?php echo substr(strrchr($vehd["documento"], "/"), 1); ?>" style="color: blue; font-size:18px;"> <i class="material-icons left">file_download</i> </a>
                                           
                                                <a title="Visualizar" href="/<?php echo $vehd["documento"]; ?>" target="_blank" style="color: blue; font-size:18px;"><i class="material-icons left">gamepad</i> </a>

                                            <?php } ?>
                                        </td>

                                        <td>
                                            <?php if($rol_user == 1 || $rol_user == 8){ ?>
                                                <?php if ($vehd['vigencia'] == "") { ?>
                                                
                                                <?php } else { ?>
                                                    <a style="color: blue;" href="/vehiculos/documentoedit/id/<?php echo $vehd["id"] ?>"><i class="fa fa-2x fa-edit"></i></a> 
                                                <?php } ?>
                                                    <a class="delete" data-id="<?php echo $vehd["id"]; ?>" data-nombre="<?php echo $vehd["nombre_doc"]; ?>"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
                                            <?php } else { ?>
                                            <?php } ?>
                                        </td>
                                    </tr>
                                </tbody>
                            <?php } }else{ ?>
                                <tbody>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td> No existe documentación este vehículo.</td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </tbody>
                            <?php } ?>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 
<!-- End Tabla Documentacion-->

<!-- Modal Actualizar Documento -->
<div id="modalactualiza" class="modal modal-fixed-footer">
    <div class="modal-content">
        <div class="row">
            <div class="col m12 s12 text-left" style="margin-top: 5px;">
                <span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Actualizar Documentanción
            </div>
        </div>
         
        <div class="row">
            <form action="/vehiculos/requestudpdoc" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submitudp">
                 <?php foreach ($this->vehiculosc as $veh) { ?>
                    <input type="hidden" name="idhs" value="<?php echo $veh["id_vehiculos"]; ?>">
                <?php } ?> 

                <input type="hidden" name="idi" id="id" value="">
                <input type="hidden" name="nombred" id="tpo" value="">

                <div class="row">

                    <div class="file-field input-field col m12 s12">
                        <div class="btn">
                            <span>Agregar Documento</span>
                            <input type="file" name="url" required>
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" id="urls" type="text">
                        </div>
                    </div>

                  <!--   <div class="input-field col m6 s12">
                        <i class="material-icons prefix">today</i>
                        <input type="date" id="fechas" name="fecha"  class="validate">
                        <label for="fecha">*Fecha: dd/mm/yyyy</label>
                    </div> -->

                    <div class="input-field col m6 s12">
                        <input type="text" id="nombre" value="" disabled class="validate">
                    </div>

                    <div class="input-field col m6 s12">
                        <i class="material-icons prefix">today</i>
                        <input type="date" id="vigencias" name="vigencia"  class="validate">
                        <label for="vigencia">*Vigencia: dd/mm/yyyy</label>
                    </div>

                    <div class="input-field col m6 s6">
                        <select name="solicitud" id="solicitudes"  required>
                            <option value="" disabled selected>Selecciona la solicitud que le corresponde:</option>
                            <?php foreach ($this->solicitud as $sveh) { ?>
                                <option value="<?php echo $sveh["id"]; ?>">Id: <?php echo $sveh["id"]; ?> Servicio: <?php echo $sveh["nombre_servicio"]; ?> Monto: $<?php echo $sveh["monto"]; ?></option>
                            <?php } ?>
                        </select>
                        <label>Solicitud:</label>
                    </div>

                    <div class="input-field col m6 s12">
                        <textarea id="comentarioss" name="comentarios" class="materialize-textarea"></textarea>
                        <label for="comentarios">Comentarios: </label>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" id="updatedoc" class="btn">Guardar</button>
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>
<!-- End Modal Actualiar Documento -->

<!-- Paginador -->
<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
                    <?php if($pagina - 1 == 0){ ?>
                    <li class="page-item disabled">
                        <span class="page-link">Anterior</span>
                    </li>
                    <?php }else{ ?>
                    <li class="page-item">
                        <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                    </li>
                    <?php } ?>
                    <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                        <?php echo $links; ?>
                    </li>
                    <?php if($pagina >= $this->total): ?>
                    <li class="page-item disabled">
                        <span class="page-link">Siguente</span>
                    </li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>
<!-- End Paginator -->


<script src="/js/lightbox.js"></script>
<script type="text/javascript">

    lightbox.option({
      'resizeDuration': 200,
      'wrapAround': true
    });

    $(document).ready(function(){
        $('.modal').modal();
        $('select').formSelect();
        $('.datepicker').datepicker();

        $('.validanumeros').keypress(function(e) {
            if(isNaN(this.value + String.fromCharCode(e.charCode))) 
                return false;
        })
        .on("cut copy paste",function(e){
            e.preventDefault();
        });
       
    });


    // $("#añadirdoc").click(function(){

    //     var comentarios = document.getElementById("comentarios").value;
    //     var nombred = document.getElementById("nombred").value;
    //     var vigencia =  document.getElementById("vigencia").value;
    //     var url =  document.getElementById("url").value;
    //     var solicitud = document.getElementById("solicitud").value;

    //     if(comentarios == "" || fecha == "" || nombred == 0 || vigencia  == "" || url == "" || solicitud == 0){
    //         swal({
    //             title: "Para añadir documentación, llena los campos(*)",
    //         });
    //     }else{
    //         swal("Espera un momento, la información esta siendo procesada", {
    //             icon: "success",
    //             buttons: false,
    //         });
    //         setTimeout(submitForm1, 500);     
    //     }    
    // }); 

    // function submitForm1() {

    //     document.getElementById("submit_doc").submit()

    // }
    // //Validar Asignar Documentacion


    $("#añadirdoc").click(function(){

        var comentarios = document.getElementById("comentarios").value;
        var nombred = document.getElementById("nombred").value;
        var vigencia =  document.getElementById("vigencia").value;
        var url =  document.getElementById("url").value;
        // var solicitud = document.getElementById("solicitud").value;

        if(comentarios == "" || nombred == 0 || vigencia  == " " || url == ""){
            swal({
                title: "Para añadir documentación, llena los campos(*)",
            });
        }else{
            swal("Espera un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            });
            setTimeout(submitForm1, 500);     
        }    
    }); 

    function submitForm1() {

        document.getElementById("submit_doc").submit()

    }
    //Validar Asignar Documentacion

    $("#updatedoc").click(function(){

        var comentarioss = document.getElementById("comentarioss").value;
        // var fechas =  document.getElementById("fechas").value;
        var vigencias =  document.getElementById("vigencias").value;
        var urls =  document.getElementById("urls").value;
        var solicitudes = document.getElementById("solicitudes").value;

        if(comentarioss == "" || vigencias  == "" || urls == "" || solicitudes == 0){
            swal({
                title: "Para Actualizar documentación, llena los campos(*)",
            });
        }else{
            swal("Espera un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            });
            setTimeout(submitFormUdp, 500);     
        }    
    }); 

    function submitFormUdp() {

        document.getElementById("submitudp").submit()

    }


        //Inicio Delete Ajax
    $(".delete").click(function(){
        id=$(this).data('id');
        nombre=$(this).data('nombre');
        swal({
            title: "Estas seguro de eliminar el Documento de "+nombre+"?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })

        .then((willDelete) => {
            if (willDelete) {
                swal("Espera un momento, la información esta siendo procesada", {
                    icon: "success",
                    buttons: false,
                });

                var request = $.ajax({
                    url:"/vehiculos/requestdeldoc",
                    method:"POST",
                    data: { id : id },
                    processData: true,
                });
        //-------------------end de ajax---------------------------

        //-------------peticion de respuesta de ajax------------------
                request.done(function(response) {
                    console.log(response);//imprime lo que responde el ajax
                    // alert
                    window.location.reload(true);
                });
        //-------------------end de respuesta ajax---------------------
            return false;

            } else {
                swal("La accion fue cancelada!");
            }
        });
    });
    // End Delete Ajax

    $(".info_res").click(function(){
        var id = $(this).data('id');     
        document.getElementById("id").value = id;

        var tpo = $(this).data('tpo');
        document.getElementById("tpo").value = tpo; 

        var nombre = $(this).data('nombre');
        document.getElementById("nombre").value = nombre;
    }); 

    $('#accion').on('change', function() {
        var value = $(this).val();
        if(value==1){
            $("#docd").show();
            $("#tdocd").show();
            $("#vigd").show();
            $("#sold").show();
            $("#comd").show();

        }

        if(value==2){

            $("#docd").hide();
            $("#tdocd").show();
            $("#vigd").hide();
            $("#sold").hide();
            $("#comd").show();

            document.getElementById('url').value='0';
            document.getElementById('vigencia').value="";
            document.getElementById('solicitud').value=' ';
        }
    });

</script>

