<?php foreach ($this->documentoedit as $documento) { $vehiculoid = $documento['id_vehiculo']; $nombred = $documento['nombre_doc']; }?>
<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
			<a href="/vehiculos/documentacion/id/<?php echo $vehiculoid ?>"  class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
	</div>
</div>

<div class="row">
	<div class="col m12 s12 text-center" style="margin-top: 10px;">
		<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Editar Documento <?php echo $nombred ?>
	</div>
</div>

<div class="col m12 s12" style="margin-top: 12px;">
	<form action="/vehiculos/requestupdatedocumentos" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_archivo">
		<?php foreach ($this->documentoedit as $documento) { ?>
			<input type="hidden" name="iddocumento" value="<?php echo $documento["id"]; ?>">
			<input type="hidden" name="vehiculo" value="<?php echo $vehiculoid; ?>">

				<div class="row">
					<div class="file-field input-field col m12 s12">
			      	 	<div class="btn">
			      	 		<span>Actualiza Documento</span>
						    <input type="file" name="url">
						    <input type="hidden" name="imahidden" value="<?php echo $documento["archivo"]; ?>">   
						</div>
						<div class="file-path-wrapper">
						    <input class="file-path validate" type="text">
						</div>
					</div>

			        <div class="input-field col m6 s12">
			          	<i class="material-icons prefix">account_circle</i>
			          	<input id="comentarios" type="text" name="comentarios" value="<?php echo $documento["comentarios"]; ?>" class="validate" required>
			          	<label for="comentarios">Comentarios: </label>
			        </div> 
			        
			        <div class="input-field col m6 s12">
				       	<i class="material-icons prefix">account_circle</i>
				       	<input id="vigencia" type="date" name="vigencia" value="<?php echo $documento["vigencia"]; ?>" required>
				       	<label for="vigencia">*Vigencia: dd/mm/yyyy</label>
				    </div>
		      	
		      	</div>
		<?php } ?>
	</form>
</div>

<div class="input-field col m12 s12 text-right">
	<div class="row">
		<a href="/vehiculos/documentacion/id/<?php echo $vehiculoid ?>" class="waves-effect red waves-light btn">Cancelar</a>
		<button  id="udparchivo" class="waves-effect waves-light btn">Actualizar</button>
	</div>	
</div>


<script type="text/javascript">


    $("#udparchivo").click(function(){
        var comentarios = document.getElementById("comentarios").value;

        if(comentarios == "" ){
            swal({
                title: "Para un editar un documento llena los datos requeridos(*)",
            });
        }else{
             swal("Espera un momento, la información esta siendo procesada", {
				icon: "success",
			 	buttons: false,
			});
            setTimeout(submitForm, 500);     
        }

    });


    function submitForm() {
        document.getElementById("submit_archivo").submit()
    }
</script>