<html>
<head>
    
    <title></title>
   <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.common.min.css" />
<!--      <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.black.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2017.1.223/styles/kendo.black.mobile.min.css" /> -->

    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/kendo.all.min.js"></script>
</head>
<body>
<div id="example">
<!--     <div class="box wide hidden-on-narrow">
        <div class="box-col">
            <button class="export-pdf btn" onclick="getPDF('.pdf-page')">Descargar</button>
        </div>
    </div>
 -->
    <?php foreach ($this->vehasignado as $veh){ 

        $responsiva = $veh['id'];
        $id_responsable = $veh['id_responsable'];
        $status_veh = $veh['status_veh'];
        $fecha_asignacion = $veh['fecha_asignacion'];
        $tarjeta_efecticard = $veh['tarjeta_efecticard'];

        $comentarios = $veh['comentarios'];
        $id_vehiculos = $veh['id_vehiculos'];
        $marca = $veh['marca'];
        $submarca = $veh['submarca'];
        $modelo = $veh['modelo'];
        
        $placas = $veh['placas'];
        $color = $veh['color'];
        $imagen = $veh['imagen'];
        $id_personal = $veh['id_personal'];
        $nombre = $veh['nombre'];
        $apellido_pa = $veh['apellido_pa'];
        $apellido_ma = $veh['apellido_ma'];
        $imagenper = $veh['imagenper'];

        $email_personal = $veh['email_personal'];
        $telefono = $veh['telefono'];
        $puesto = $veh['puesto'];
        $nombre_puesto = $veh['nombre_puesto'];

    } ?>

    <?php 
            date_default_timezone_set('America/Mexico_City');
            $hoy = date("d-m-Y");
     ?>


<div class="row" style="margin-top: 10px;">
    <div class="col m6 s6">
        <a href="/vehiculos/vehdetail/id/<?php echo $this->vehiculo; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>    
    </div>

    <div class="col m6 s6 text-right">
        <button class="export-pdf btn" onclick="getPDF('.pdf-page')">Descargar Responsiva</button>
    </div>
</div>


<div class="page-container hidden-on-narrow">
    <div class="pdf-page size-a4">

        <div class="pdf-header">
            <span class="company-logo">
                <!--  <img src="/img/pdfgps.jpg" style="width: 600px;" /> -->
                <img src="/img/head.png" style="width: 130px;" />
            </span>

            <span class="invoice-number">
                <img src="/img/logo-2.png" style="width: 135px;" />
            </span>

            <div class="row">
                <div class="company-logo col m12 s12 text-center">
                    Entrega Vehículo 
                </div>
            </div>
        </div>


        <div class="pdf-footer">
            <p>Nte 31-A No. 96, col. Lindavista Vallejo III, Gustavo A. Madero, C.P. 07720, CDMX<br />
                    Fecha de descarga: <?php echo $hoy; ?><br />
                </p>
        </div>

        <div class="for" style="margin-top: 60px;">
            <h3> Datos del Personal</h3>

            <p style="padding-bottom: 20px;">
                <span class="title-pdf">Personal:</span> <?php echo $nombre; ?> <?php echo $apellido_pa; ?> <?php echo $apellido_ma; ?> <br />
                <span class="title-pdf">Puesto:</span> <?php echo $nombre_puesto; ?><br />
                <span class="title-pdf">Telefono:</span>
                <?php if($telefono == "") { ?> 
                    Sin Telefono<br />
                <?php } else { ?>
                    <?php echo $telefono; ?><br />
                <?php } ?>
                <span class="title-pdf">Email:</span>
                <?php if($email_personal == "") { ?> 
                    Sin Email<br />
                <?php } else { ?>
                    <?php echo $email_personal; ?><br />
                <?php } ?>

                 <p class="text-center">
                <?php if($imagenper ==  NULL || $imagenper ==""){ ?>
                    <img class="text-center" src="/img/no_disponible1.png" class="responsive-img" style="width: 120px; margin-top: 5px;">
                <?php }else{ ?>
                    <img class="text-center" src="/<?php echo $imagenper; ?>" style="width: 150px;">
                <?php } ?>
                </p>
            </p>

        </div>

        <div class="from" style="margin-top: 60px;">
            <h3> Datos del Vehículo</h3>

            <p style="padding-bottom: 20px;">
                <span class="title-pdf">Marca: </span><?php echo $marca; ?> <br />
                <span class="title-pdf">Submarca: </span><?php echo $submarca; ?><br />
                <span class="title-pdf">Modelo: </span><?php echo $modelo; ?><br />
                 <span class="title-pdf">Placas: </span><?php echo $placas; ?><br />

                 <p class="text-center">
                <?php if($imagen ==  NULL || $imagen ==""){ ?>
                    <img class="text-center" src="/img/no_disponible1.png" class="responsive-img" style="width: 120px; margin-top: 5px;">
                <?php }else{ ?>
                    <img class="text-center" src="/<?php echo $imagen; ?>" style="width: 150px;">
                <?php } ?>
                </p>
            </p>
        </div>

        <div class="pdf-body" style="margin-top:240px;">

            <div class="row">

                <h4><b>Fecha de Asignación:</b> <?php echo $fecha_asignacion; ?></h4> 
                <h4><b>Comentarios:</b> <?php echo $comentarios; ?></h4> 

            </div>

            <div class="row signature">
                <div class="col m2"></div>
                <div class="col m8 s12 text-center">
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Recibido por:</span><br><br>
                    <?php echo $nombre; ?> <?php echo $apellido_pa; ?> <?php echo $apellido_ma; ?>
                    <hr>
                    <span style="font-size:14px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Nombre y Firma</span>
                </div>
                <div class="col m2"></div>
            </div>
        </div>
    </div>
</div>

<div class="responsive-message"><br> </div>

 

    <style>
        .pdf-page {
            font-family: "DejaVu Sans", "Arial", sans-serif;
        }
    </style>

    <script>
        kendo.pdf.defineFont({
            "DejaVu Sans"             : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans.ttf",
            "DejaVu Sans|Bold"        : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Bold.ttf",
            "DejaVu Sans|Bold|Italic" : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf",
            "DejaVu Sans|Italic"      : "https://kendo.cdn.telerik.com/2016.2.607/styles/fonts/DejaVu/DejaVuSans-Oblique.ttf"
        });
    </script>

    <!-- Load Pako ZLIB library to enable PDF compression -->
    <script src="../content/shared/js/pako.min.js"></script>

    <script>
      function getPDF(selector) {
        kendo.drawing.drawDOM($(selector)).then(function(group){
          kendo.drawing.pdf.saveAs(group, "Responsiva <?php echo $responsiva; ?> .pdf");
        });
      }


    $(document).ready(function() {
        var data = [
          { productName: "QUESO CABRALES", unitPrice: 21, qty: 5 },
          { productName: "ALICE MUTTON", unitPrice: 39, qty: 7 },
          { productName: "GENEN SHOUYU", unitPrice: 15.50, qty: 3 },
          { productName: "CHARTREUSE VERTE", unitPrice: 18, qty: 1 },
          { productName: "MASCARPONE FABIOLI", unitPrice: 32, qty: 2 },
          { productName: "VALKOINEN SUKLAA", unitPrice: 16.25, qty: 3 }
        ];
        var schema = {
          model: {
            productName: { type: "string" },
            unitPrice: { type: "number", editable: false },
            qty: { type: "number" }
          },
          parse: function (data) {
                $.each(data, function(){
                    this.total = this.qty * this.unitPrice;
                });
                return data;
          }
        };
        var aggregate = [
          { field: "qty", aggregate: "sum" },
          { field: "total", aggregate: "sum" }
        ];
        var columns = [
          { field: "productName", title: "Product", footerTemplate: "Total"},
          { field: "unitPrice", title: "Price", width: 120},
          { field: "qty", title: "Pcs.", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" },
          { field: "total", title: "Total", width: 120, aggregates: ["sum"], footerTemplate: "#=sum#" }
        ];
        var grid = $("#grid").kendoGrid({
          editable: false,
          sortable: true,
          dataSource: {
            data: data,
            aggregate: aggregate,
            schema: schema,
          },
          columns: columns
        });

        $("#paper").kendoDropDownList({
          change: function() {
            $(".pdf-page")
              .removeClass("size-a8")
              .removeClass("size-a4")
              .removeClass("size-letter")
              .removeClass("size-executive")
              .addClass(this.value());
          }
        });
    });
    </script>
    <style>

        .title-pdf{
            font-weight: bold;
            font-size: 13px;
        }
        .pdf-page {
            margin: 0 auto;
            box-sizing: border-box;
            box-shadow: 0 5px 10px 0 rgba(0,0,0,.3);
            background-color: #fff;
            color: #333;
            position: relative;
        }
        .pdf-header {
            position: absolute;
            top: .1in;
            height: .6in;
            left: .5in;
            right: .5in;
            /*border-bottom: 1px solid #e5e5e5;*/
        }
        .invoice-number {
            padding-top: .17in;
            float: right;
        }
        .pdf-footer {
            position: absolute;
            bottom: .5in;
            height: .6in;
            left: .5in;
            right: .5in;
            padding-top: 10px;
            border-top: 1px solid #e5e5e5;
            text-align: left;
            color: #787878;
            font-size: 12px;
        }
        .pdf-body {
            position: absolute;
            top: 3.5in;
            bottom: 1.2in;
            left: .5in;
            right: .5in;
        }

        td, th{

            padding: 1px 5px;

        }

      /*  5,8 x 8,3 pulgadas*/

        .size-a5 { width: 8.3in; height: 5.8in; }
        .size-a4 { width: 8.3in; height: 11.7in; }
        .size-letter { width: 8.5in; height: 11in; }
        .size-executive { width: 7.25in; height: 10.5in; }

        .company-logo {
            font-size: 30px;
            font-weight: bold;
            color: blue;
        }
        .for {
            position: absolute;
            top: 1.5in;
            left: .5in;
            width: 3.5in;
        }
        .from {
            position: absolute;
            top: 1.5in;
            right: .5in;
            width: 3.5in;
        }
        .from p, .for p {
            color: #787878;
        }
        .signature {
            padding-top: 1.7in;
        }
    </style>

</div>


</body>
