<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/vehiculos/catalogos" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
    </div>
</div>

<div class="row">
	<div class="col m12 s12 text-center" style="margin-top: 10px;">
		<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Editar Grupo</span>
	</div>
</div>


<div class="col m12 s12">
	<form action="/vehiculos/requestupdategrupo" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_g">
		<?php foreach ($this->vehiculog as $vg) { ?>
		<input type="hidden" name="ids" value="<?php echo $vg["id_grupo"]; ?>">
			<div class="row">
				<div class="input-field col m12 s12">
					<i class="material-icons prefix">account_circle</i>
			        <input id="name" type="text" name="name" value="<?php echo $vg["nombre"]; ?>" class="validate" required>
			        <label for="name">* Nombre: </label>
			    </div> 
		    </div>
		<?php } ?>
	</form>
</div>

<div class="input-field col m12 s12 text-right">
	<div class="row">
		<a href="/vehiculos/catalogos" class="waves-effect red waves-light btn">Cancelar</a>
		<button  id="addgrupo" class="waves-effect waves-light btn">Actualizar</button>
	</div>	
</div>


<script type="text/javascript">
    $("#addgrupo").click(function(){
        var name = document.getElementById("name").value;

        if(name == ""){
            swal({
                title: "Para editar un grupo debes agregarle un nombre",
            });
        }else{
             swal("Espera un momento, la información esta siendo procesada", {
				icon: "success",
			 	buttons: false,
			});
            setTimeout(submitForm, 500);     
        }

    });


    function submitForm() {
        document.getElementById("submit_g").submit()
    }
</script>