<?php 
function isActhref($nameBtn,$urlname){
	if($nameBtn==1 && $urlname==null){
		return "active"; 
	}
	return ($nameBtn == $urlname)?"active":"";
}
	if (isset($_GET['pagina'])) {
		$pagina = $_GET['pagina'];
	} else {
		$pagina = 1;
	}  
?> 
<?php 

$links = "";
$url="";

if($this->total== 1){
	$links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
}else{
	if ($this->total >= 1 && $pagina <= $this->total) {

		if (isset($_GET['pagina']) && $this->actpage != 1) {
			$links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
		}else{
			$links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
		}

		$i = max(2, $pagina - 3);
		if ($i > 2)
			$links .= " <li><a>...</a></li> ";
		for (; $i < min($pagina + 3, $this->total); $i++) {
			if($i ==$this->actpage){
				$links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
			}else{
				$links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
			}
		}
		if ($i != $this->total)
			$links .= " <li><a>...</a></li> ";
		if($i ==$this->actpage){
			$links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
		}else{
			$links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
		}

	}           
}

?>

<style type="text/css">
	.oculto{
		display: none;
	}

	.table_wrapper{
		overflow-x: auto;
	}

	.icon_style{
	    font-size: 17px;
	    font-family: "Nunito", sans-serif;
	    cursor:pointer; 
	}

	.colorfont strong{
		color: rgb(169,68,66);
		font-weight: bold;
	}

	.colorfont span{
		color: rgb(169,68,66);
		font-weight: 350;
	}

	.colorfont1 strong{
		color: rgb(114,97,40);
		font-weight: bold;
	}

	.colorfont1 span{
		color: rgb(114,97,40);
		font-weight: 350;
	}
</style>

<?php foreach ($this->user as $value) {
	$rol_user = $value['fkroles'];
	// echo $rol_user;
} ?>

<!-- Inicio Botones -->
<div class="row" style="margin-top: 10px;">
	<?php if($rol_user != 9){ ?> 
	    <div class="col m12 s12 text-right">
	        <a href="/vehiculos/catalogos" class="waves-effect green btn modal-trigger">Grupos</a>
	        <a class="waves-effect green btn modal-trigger" href="#modal1">+ Agregar Vehículo</a>    
	    </div>
	<?php } else { ?>
	<?php } ?>
</div>

<!-- Alertas -->
<?php if($rol_user != 9){ ?> 


<div class="col m12 s12">
    <div class="row">
        <div class="col m12 s12" id="alert_box">
            <?php if ($this->alertas || $this->alertasvencidas) { ?>
                <!-- <div class="col m12 s12 text-right">
                    <i class="fa fa-times icon_style" id="alert_close" aria-hidden="true"></i>
                </div> -->

                <?php foreach ($this->alertasvencidas as $vencidas) { ?>
                    <div style="background: rgb(242,222,222);"  class="card darken-1">
                        <div style="padding: 10px;" class="card-content white-text colorfont">
                            <strong>¡Cuidado!</strong> 
                            <span>
                                El vehículo <?php echo $vencidas['marca']; ?> <?php echo $vencidas['modelo']; ?> 
                                con placas <?php echo $vencidas['placas']; ?> tiene el/la <b><?php echo $vencidas['nombre_doc']; ?></b> vencida: <?php echo $vencidas['vigencia']; ?>
                            </span> &nbsp; 
                            <a href="/vehiculos/documentacion/id/<?php echo $vencidas["id_vehiculo"] ?>">
                               <i style="color: rgb(171,68,68);" class="fa fa-2x fa-arrow-circle-right text-right"></i>
                            </a>
                        </div>    
                        <!-- <i class="fa fa-times icon_style" id="alert_close" aria-hidden="true"></i> -->
                    </div>              
                <?php } ?>

                <?php foreach ($this->alertas as $not) { ?>
                    <div style="background: rgb(250,252,217);"  class="card darken-1">
                        <div style="padding: 10px;" class="card-content white-text colorfont1">
                            <strong>¡Advertencia!</strong> 
                            <span>
                                El vehículo <?php echo $not['marca']; ?> <?php echo $not['modelo']; ?> 
                                con placas <?php echo $not['placas']; ?> tiene el/la <b><?php echo $not['nombre_doc']; ?></b> por vencer el día: <?php echo $not['vigencia']; ?>
                            </span> &nbsp; 
                            <a href="/vehiculos/documentacion/id/<?php echo $not["id_vehiculo"] ?>">
                               <i style="color: rgb(114,97,40);" class="fa fa-2x fa-arrow-circle-right text-right"></i>
                            </a>
                        </div>    
                        <!-- <i class="fa fa-times icon_style" id="alert_close" aria-hidden="true"></i> -->
                    </div>              
                <?php } ?>

                <div class="col m12 s12 text-right">
                    <a><i class="icon_style"  id="alert_close" aria-hidden="true"> Cerrar todo </i></a>
                </div> 
            <?php } else { } ?>
        </div>
    </div>
</div>

<!-- <div class="col m12 s12">
    <div class="row">
        <div class="col m12 s12" id="alert_box">
            <?php if ($this->alertasvencidas) { ?>
                <?php foreach ($this->alertasvencidas as $vencidas) { ?>
                    <div style="background: rgb(242,222,222);"  class="card darken-1">
                        <div style="padding: 10px;" class="card-content white-text colorfont">
                            <strong>¡Cuidado!</strong> 
                            <span>
                                El vehículo <?php echo $vencidas['marca']; ?> <?php echo $vencidas['modelo']; ?> 
                                con placas <?php echo $vencidas['placas']; ?> tiene el/la <b><?php echo $vencidas['nombre_doc']; ?></b> vencida: <?php echo $vencidas['vigencia']; ?>
                            </span> &nbsp; 
                            <a href="/vehiculos/documentacion/id/<?php echo $vencidas["id_vehiculo"] ?>">
                               <i style="color: rgb(171,68,68);" class="fa fa-2x fa-arrow-circle-right text-right"></i>
                            </a>
                        </div>    
                        <i class="fa fa-times icon_style" id="alert_close" aria-hidden="true"></i>
                    </div>              
                <?php } ?>
                <div class="col m12 s12 text-right">
                    <a><i class="icon_style"  id="alert_close" aria-hidden="true"> Cerrar todo </i></a>
                </div> 
            <?php } else { } ?>
        </div>
    </div>
</div> -->

<?php } else { ?>
<?php } ?>	
<!-- end alertas -->

<div class="row">
	<div class="col m12 s12 text-center" style="margin-top: 10px;">
		<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Vehículos
	</div>
</div>
<!-- End botones -->



<!-- Buscador -->
<div class="row">
	<div class="input-field col m2 s12"></div> <!-- espacio -->
	<div class="input-field col m4 s12">  
		<select id="mySelect">
			<option value="1" selected>Marca</option>
			<option value="2">Placas</option>
			<option value="3">Status</option>
		</select>
		<label>Buscador</label>
	</div>

	<div class="col m4 s12" id="buscar_marca">
		<form action="/vehiculos/buscarvehiculo" enctype="multipart/form-data" class="form-horizontal form-material">
			<div class="input-field col m10 s8">
				<input placeholder="Ingresa marca" name="marca" id="first_name" type="text" class="validate" required>
				<label for="first_name">Buscar por Marca</label>
			</div>
			<div class="input-field col m2 s4">
				<button tyle="submit" id="add_user" class="waves-effect waves-light btn"><i class="material-icons left">search</i></button>
			</div>
		</form>
	</div>
	<div class="col m4 s12 oculto" id="buscar_placas">
		<form action="/vehiculos/buscarvehiculo" enctype="multipart/form-data" class="form-horizontal form-material">
			<div class="input-field col m10 s8">
				<input placeholder="Ingresa placas" id="placas" name="placas" type="text" class="validate" required>
				<label for="placas">Buscar por Placas</label>
			</div>
			<div class="input-field col m2 s4">
				<button tyle="submit" id="add_user" class="waves-effect waves-light btn"><i class="material-icons left">search</i></button>
			</div>	
		</form>
	</div>

	<div class="col m4 s12 oculto" id="buscar_status">
		<form action="/vehiculos/buscarvehiculo" enctype="multipart/form-data" class="form-horizontal form-material">
			<div class="input-field col m10 s8">
				<select name="status" required>
					<option value="" disabled selected>Selecciona una opcion</option>
					<option value="0">Disponible</option>
					<option value="1">Ocupado</option>
					<option value="2">En Reparación</option>
					<option value="3">Baja</option>
				</select>
				<label>Status Vehículo</label>
			</div>
			<div class="input-field col m2 s4">
				<button tyle="submit" id="add_user" class="waves-effect waves-light btn"><i class="material-icons left">search</i></button>
			</div>	
		</form> 
	</div>
	<div class="input-field col m2 s12"></div> <!-- espacio -->
</div>
<!-- End Buscador -->


<!-- Inicio Modal Insertar Vehículos -->
<div id="modal1" class="modal modal-fixed-footer">
	<div class="modal-content">
		<div class="col m12 s12 text-left" style="margin-top: 10px;">
			<span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Agregar Vehículo
		</div>
		<div class="col m12 s12">
			<form action="/vehiculos/requestaddveh" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_veh">
				<div class="row">
					<div class="file-field input-field col m12 s12">
						<div class="btn">
							<span>Añade Foto</span>
							<input type="file" name="url">
						</div>
						<div class="file-path-wrapper">
							<input class="file-path validate" type="text">
						</div>
					</div>

					<div class="file-field input-field col m12 s12">
						<div class="btn">
							<span>Añade Tarjeta Circulación</span>
							<input type="file" name="url2">
						</div>
						<div class="file-path-wrapper">
							<input class="file-path validate" type="text">
						</div>
					</div>

					<div class="input-field col m6 s12">
						<i class="material-icons prefix">class</i>
						<input id="marca" type="text" name="marca" class="validate" required>
						<label for="marca">* Marca:</label>
					</div>
					<div class="input-field col m6 s12">
						<i class="material-icons prefix">description</i>
						<input id="submarca" type="text" name="submarca" class="validate" required>
						<label for="submarca">* Submarca: </label>
					</div>
					<div class="input-field col m12 s12">
						<i class="material-icons prefix">airplay</i>
						<input id="modelos" type="text" name="modelo" class="validate" required>
						<label for="modelos">* Modelo: </label>
					</div>
					<div class="input-field col m6 s12">
						<i class="material-icons prefix">confirmation_number</i>
						<input id="placa" type="text" name="placas" class="validate" required>
						<label for="placa">* Placas: </label>
					</div>
					<div class="input-field col m6 s12">
						<i class="material-icons prefix">invert_colors</i>
						<input id="color" type="text" name="color" class="validate" required>
						<label for="color"> Color: </label>
					</div>
					<div class="input-field col m12 s12">
						<i class="material-icons prefix">event_available</i>
						<input id="com" type="text" name="com" class="validate">
						<label for="com">Comentarios: </label>
					</div>
					<div class="input-field col m12 s12">
						<select id="grupo" name="grupo" required>
							<option value="0" disabled selected>* Selecciona una opcion:</option>
							<?php foreach ($this->grupov as $gv) { ?>
								<option value="<?php echo $gv["id_grupo"]; ?>"><?php echo $gv["nombre"]; ?></option>
							<?php } ?>
						</select>
						<label>Grupo</label>
					</div>
				</div>
			</div>
		</div>
		<div class="modal-footer">
		</form>
		<button class=" btn" id="addveh">Guardar</button>
		<button  class="modal-close red btn">Cerrar</button>
	</div>
</div>
<!-- End Vehículos -->

<!-- Table Vehículos-->
<div class="col m12 s12">
	<div class="row">
		<div class="col m6 s12 text-left" style="margin-top: 10px;">
			<span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Inventario Vehículos
		</div>
		<div class="col m6 s6 text-right">
			<a href="/vehiculos/excelv/status/1"> <h4 style="color: green;">Generar Excel  <i class="material-icons">insert_drive_file</i></h4></a>
		</div>
	</div>
	<div class="col m12 s12 text-right table_wrapper">
		<table class="table text-left table-hover">
			<thead>
				<tr>
					<th>Marca</th>
					<th>Submarca</th>
					<th>Modelo</th>
					<th>Placas</th>
					<th>Grupo</th>
					<th>Asignado a:</th>
					<th>% Documentación</th>
					<th>Status</th>
					<th></th>
					<th></th>
					<th></th>	
				</tr> 
			</thead>
			<?php if ($this->paginator ) {

				foreach ($this->paginator as $veh) { ?>
					<tbody>
						<tr>
							<td><?php echo $veh["marca"]; ?></td>
							<td><?php echo $veh["submarca"]; ?></td>
							<td><?php echo $veh["modelo"]; ?></td>
							
							<td><?php echo $veh["placas"]; ?></td>
							<td><?php echo $veh["grupo"]; ?></td>
							<td>
								<?php if($veh['id_responsable'] == 0){ ?>
									<b>Sin Asignar</b>
								<?php } else { ?>
									<b><?php echo $veh["nombrea"]; ?> <?php echo $veh["apellido_pa"]; ?></b>
								<?php } ?>
									
							</td>
							<td>
								<?php if($veh["porcentaje_doc"] == 0){ ?>
									<div class="progress">
										<div class="determinate orange" style="width: 0%"></div>
	  								</div>
	  										<b>0%</b>
								

								<?php } else if ($veh["porcentaje_doc"] >= 90) { ?>
									<div class="progress">
	      								<div class="determinate green" style="width: <?php echo $veh["porcentaje_doc"]; ?>%"></div>
	  								</div>
	  									<b><?php echo round($veh["porcentaje_doc"],2) ; ?>%</b>
								
								<?php } else if ($veh["porcentaje_doc"] >= 1 || $veh["porcentaje_doc"] < 90) { ?>
									<div class="progress">
	      								<div class="determinate orange" style="width: <?php echo $veh["porcentaje_doc"]; ?>%"></div>
	  								</div>
	  									<b><?php echo round($veh["porcentaje_doc"],2) ; ?>%</b>
								<?php } ?>

							</td>
							<td>
								<?php if($veh['id_status'] == 0){ ?>
									<div class="chip" id="disponible">
										<img src="/img/correct.png" >
										Disponible
									</div>
								<?php } ?>

								<?php if($veh['id_status'] == 1){ ?>
									<div class="chip" id="ocupado">
										<img src="/img/naranja.png" >
										Ocupado
									</div>
								<?php } ?>

								<?php if($veh['id_status'] == 2){ ?>
									<div class="chip" id="manto">
					    				<img src="/img/azul.png" >
					    				Reparación
					  				</div>
								<?php } ?>
								<?php if($veh['id_status'] == 3){ ?>
									<div class="chip" id="baja">
										<img src="/img/rojo.png" >
										Baja
									</div>
								<?php } ?>
							</td>
							<!-- <td><?php echo $veh["nombre_status"]; ?></td> -->
							
							<td>
								<?php if($rol_user != 9){ ?> 
									<a href="/vehiculos/vehdetail/id/<?php echo $veh["id_vehiculos"] ?>/op/0"><i class="fa fa-2x fa-id-card-o"></i></a>
								<?php } else { ?>
								<?php } ?>	
							</td>
							<td>
								<?php if($rol_user != 9){ ?> 
									<a href="/vehiculos/vehiculoedit/id/<?php echo $veh["id_vehiculos"] ?>/op/0"><i class="fa fa-2x fa-edit"></i></a>
								<?php } else { ?>
								<?php } ?>
							</td>
							<td>
								<?php if($rol_user == 1 || $rol_user == 8 || $rol_user == 4){ ?> 
									<a class="delete" data-id="<?php echo $veh["id_vehiculos"]; ?>" data-nombre="<?php echo $veh["placas"]; ?>"><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
								<?php } else { ?>
								<?php } ?>
							</td>
						</tr>
					</tbody>
				<?php } }else{?>
					<tbody>
						<td></td>
						<td></td>
						<td></td>
						<td>
							<h4>No se encontrarón Vehículos</h4>
						</td>
						<td></td>
						<td></td>
						<td></td>
					</tbody>
				<?php } ?>
		</table>
	</div>
</div>
<!-- End Table Vehículos -->



	<!-- Paginador -->
<div class="row">
	<div class="col m12 s12 text-center">
		<div class="white-box">
			<div class="paginationControl">
				<ul class="pagination justify-content-center">
					<?php if($pagina - 1 == 0){ ?>
					<li class="page-item disabled">
						<span class="page-link">Anterior</span>
					</li>
					<?php }else{ ?>
					<li class="page-item">
						<a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
					</li>
					<?php } ?>
					<li class="page-item <?php echo isActhref($links,$this->actpage);?>">
						<?php echo $links; ?>
					</li>
					<?php if($pagina >= $this->total): ?>
					<li class="page-item disabled">
						<span class="page-link">Siguente</span>
					</li>
					<?php else: ?>
						<li class="page-item">
							<a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
						</li>
					<?php endif; ?>
				</ul>
			</div>
		</div>
	</div> 
</div>
	<!-- End Paginator -->


<script type="text/javascript">

	$(document).ready(function(){
		$('.modal').modal();
		$('select').formSelect();
		$('.validanumeros').keypress(function(e) {
			if(isNaN(this.value + String.fromCharCode(e.charCode))) 
				return false;
		})
		.on("cut copy paste",function(e){
			e.preventDefault();
		});
 	});

 	// Inicio Add vehiculo

	$("#addveh").click(function(){
		var marca = document.getElementById("marca").value;
		
		if(marca == ""){
			swal({
				title: "Para agregar un vehículo, llena los campos (*)",
			});
		}else{
			swal("Espera un momento, la información esta siendo procesada", {
				icon: "success",
				buttons: false,
			});
			setTimeout(submitForm, 500);     
		}
	});

	function submitForm() {
		document.getElementById("submit_veh").submit()
	}
	// End Add vehiculo

	//Inicio Delete Ajax
	$(".delete").click(function(){
		id=$(this).data('id');
		nombre=$(this).data('nombre');
		swal({
			title: "¿Estas seguro de eliminar el vehículo con placas "+nombre+"?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})

		.then((willDelete) => {
			if (willDelete) {
				swal("Espera un momento, la información esta siendo procesada", {
					icon: "success",
					buttons: false,
				});

				var request = $.ajax({
					url:"/vehiculos/requestdeleteveh",
					method:"POST",
					data: { id : id },
					processData: true,
				});
		//-------------------end de ajax---------------------------

		//-------------peticion de respuesta de ajax------------------
				request.done(function(response) {
	                console.log(response);//imprime lo que responde el ajax
	                // alert
	                window.location.reload(true);
	            });
		//-------------------end de respuesta ajax---------------------
			return false;

			} else {
				swal("La accion fue cancelada!");
			}
		});
	});
	// End Delete Ajax


	//Inicio Selected
	$('#mySelect').on('change', function() {
		var value = $(this).val();
		if(value==1){
			$("#buscar_marca").show();
			$("#buscar_placas").hide();
			$("#buscar_status").hide();
		}

		if(value==2){
			$("#buscar_marca").hide();
			$("#buscar_placas").show();
			$("#buscar_status").hide();
		}
		if(value==3){
			$("#buscar_marca").hide();
			$("#buscar_placas").hide();
			$("#buscar_status").show();

		}
	});
	// End Selected

	$('#alert_close').click(function(){
	    $( "#alert_box" ).fadeOut( );
	});

</script>

