<?php foreach ($this->vehiculosc as $veh) { $idv = $veh['id_vehiculos']; }?>

<?php 
function isActhref($nameBtn,$urlname){
    if($nameBtn==1 && $urlname==null){
        return "active"; 
    } 
    return ($nameBtn == $urlname)?"active":"";
}
    if (isset($_GET['pagina'])) {
        $pagina = $_GET['pagina'];
    } else {
        $pagina = 1;
    }  
?>
<?php 

$links = "";
$url="";

if($this->total== 1){
    $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
}else{
    if ($this->total >= 1 && $pagina <= $this->total) {

        if (isset($_GET['pagina']) && $this->actpage != 1) {
            $links .= "<li class=\"page-item\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }else{
            $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina=1\">1</a></li>";
        }

        $i = max(2, $pagina - 3);
        if ($i > 2)
            $links .= " <li><a>...</a></li> ";
        for (; $i < min($pagina + 3, $this->total); $i++) {
            if($i ==$this->actpage){
                $links .= "<li class=\"page-item active\" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
            }else{
                $links .= "<li class=\"page-item \" ><a href=\"{$url}?pagina={$i}\">{$i}</a></li>";
            }
        }
        if ($i != $this->total)
            $links .= " <li><a>...</a></li> ";
        if($i ==$this->actpage){
            $links .= "<li class=\"page-item active\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
        }else{
            $links .= "<li class=\"page-item\"><a href=\"{$url}?pagina={$this->total}\">{$this->total}</a></li>";
        }

    }           
}

?>

<input type="hidden" name="idvh" id="idvh" value="<?php echo $this->idvh; ?>">

<style type="text/css">
    .table_wrapper{
        overflow-x: auto;
    }
</style>

<!-- INICIO DETAIL-->
<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <?php foreach ($this->vehiculosc as $veh) { ?>
        <a href="/vehiculos/vehdetail/id/<?php echo $veh['id_vehiculos']; ?>" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
        <?php } ?>    
    </div>
</div>

<div class="row">
  <div class="col m12 s12 text-center" style="margin-top: 10px;">
    <span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Operadores
  </div>
</div>

<!-- END INICIO DETAIL-->

<!-- Inicio Tabla Vehiculo -->
<div class="col m8 s12 text-center">
    <div class="row">
        <div class="col s12 m12">
            <div class="row table_wrapper">
                <table class="table text-center table-hover ">
                    <thead>
                        <tr>
                            <th>Marca</th>
                            <th>Submarca</th>
                            <th>Modelo</th>
                            <th>Color</th>
                            <th>Placas</th>
                        </tr>
                    </thead>
                    <?php if ($this->vehiculosc) { 
                    foreach ($this->vehiculosc as $veh) { ?>
                        <tbody>
                            <tr>
                                <td>
                                    <?php echo $veh['marca']; ?>
                                </td>
                                <td>
                                    <?php echo $veh['submarca']; ?>
                                </td>
                                <td>
                                    <?php echo $veh['modelo']; ?>
                                </td>   
                                <td>
                                    <?php echo $veh['color']; ?>
                                </td>
                                <td>
                                    <?php echo $veh['placas']; ?>
                                </td>
                            </tr>
                        </tbody>
                    <?php } }else{ ?>
                        <tbody>
                            <tr>
                                <td></td>
                                <td></td>
                                <td>No existe este vehículo.</td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
                    <?php } ?>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="col m4 s12 text-center">
    <?php if($veh['imagen'] == null){ ?>
            <img src="/img/no_disponible1.png" class="responsive-img" style="width: 200px; margin-top: 5px;">
    <?php }else{ ?>
            <a class="example-image-link" href="/<?php echo $veh['imagen']; ?>" data-lightbox="example-1"><img class="example-image oculto" src="/<?php echo $veh['imagen']; ?>" id="camara_div" alt="<?php echo $nombre; ?>" style="width: 240px;  margin-top: 5px;"/></a>
        <?php } ?>
</div>
<!-- End Tabla Vehiculo-->


<!-- Inicio Tabla Operadores -->
<div class="col m12 s12 text-center">
    <div class="row">
        <div class="col s12 m12">
            <div class="card darken-1">
                <div class="card-content">

                    <div class="row">
                        <div class="col m6 s6 text-left">
                            <span style="font-size:20px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Operadores asignados a vehículo  
                        </div>
                        <div class="col m6 s6 text-right">
                            <a href="/vehiculos/excelop/id/<?php echo $idv; ?>"> <h4 style="color: green;">Generar Excel  <i class="material-icons">insert_drive_file</i></h4></a>
                        </div>
                    </div>

                    <div class="row table_wrapper">
                        <table class="table text-center table-hover ">
                            <thead>
                                <tr>
                                    <th>Fecha Asignación</th>
                                    <th>Responsable</th>
                                    <th>Efecticard</th>
                                    <th>Status</th>
                                    <th>Fecha Entrega</th>
                                    <th>Entrega</th>
                                    <th>Liberación</th>
                                </tr>
                            </thead>
                            <?php if ($this->paginator) { 
                            foreach ($this->paginator as $vehas) { ?>
                                <tbody>
                                    <tr>
                                        <td>
                                            <?php echo $vehas['fecha_asignacion']; ?>
                                        </td>
                                        <td>
                                            <?php echo $vehas['nombre']; ?> <?php echo $vehas['apellido_pa']; ?> <?php echo $vehas['apellido_ma']; ?>
                                        </td>
                                        <td>
                                            <?php echo $vehas['efecticard']; ?>
                                        </td>
                                        <td>
                                            <?php echo $vehas['statusv']; ?>
                                        </td>
                                         <td>
                                            <?php echo $vehas['fentrega']; ?>
                                        </td> 
                                        <td class="text-center">
                                            <?php if ($vehas['archivo'] == null) { ?>
                                                <b>Subir Archivo</b><br/>
                                                    <a class="text-center modal-trigger info_res" title="Subir Archivo" href="#modalarchivo" data-id="<?php echo $vehas["id"] ?>" style="color: blue; font-size:15px;"> <i class="material-icons center">present_to_all</i> </a>
                                            <?php } else { ?>
                                                <a title="Visualizar" href="/<?php echo $vehas['archivo']; ?>" target="_blank" style="color: blue; font-size:18px;"><i class="material-icons">gamepad</i> </a>

                                                <a class="text-center modal-trigger info_mod" title="Modificar Archivo" href="#modalmodarchivo" data-ido="<?php echo $vehas["id"] ?>" data-arc="<?php echo $vehas["archivo"] ?>" style="color: blue; font-size:15px;"><i class="fa fa-2x fa-edit"></i></a>
                                                
                                            <?php } ?> 
                                        </td>
                                        <td class="text-center">
                                            <?php if ($vehas['archivo2'] == null) { ?>
                                                <b>Subir Archivo</b><br/>
                                                    <a class="text-center modal-trigger info_res2" title="Subir Archivo" href="#modalarchivo2" data-id2="<?php echo $vehas["id"] ?>" style="color: blue; font-size:15px;"> <i class="material-icons center">present_to_all</i> </a>
                                            <?php } else { ?>
                                                <a title="Visualizar" href="/<?php echo $vehas['archivo2']; ?>" target="_blank" style="color: blue; font-size:18px;"><i class="material-icons">gamepad</i> </a>

                                                <a class="text-center modal-trigger info_mod2" title="Modificar Archivo" href="#modalmodarchivo2" data-ido2="<?php echo $vehas["id"] ?>" data-arc2="<?php echo $vehas["archivo2"] ?>" style="color: blue; font-size:15px;"><i class="fa fa-2x fa-edit"></i></a>
                                                
                                            <?php } ?> 
                                        </td>                                  
                                    </tr>
                                </tbody>
                            <?php } }else{ ?>
                                <tbody>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td> No existe personal asignado este vehículo.</td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </tbody>
                            <?php } ?>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Tabla Operadores-->



<!-- Modal añadir Archivo -->
<div id="modalarchivo" class="modal modal-fixed-footer">
    <div class="modal-content">
        <div class="row">
            <div class="col m12 s12 text-left" style="margin-top: 5px;">
                <span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Añadir Archivo de Entrega
            </div>
        </div>
        <div class="row">
            <form action="/vehiculos/updatearchivo" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submitarc">
                 <?php foreach ($this->vehiculosc as $veh) { ?>
                    <input type="hidden" name="idhs" value="<?php echo $veh["id_vehiculos"]; ?>">     
                <?php } ?> 
                <input type="hidden" name="idi" id="id" value="">
                <div class="row">

                    <div class="file-field input-field col m12 s12">
                        <div class="btn">
                            <span>Añadir Archivo</span>
                            <input type="file" name="url" required>
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" id="url" type="text">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" id="addarchivo" class="btn">Guardar</button>
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>
<!-- End Modal añadir Archivo -->


<!-- Modal Modificar Archivo -->
<div id="modalmodarchivo" class="modal modal-fixed-footer">
    <div class="modal-content">
        <div class="row">
            <div class="col m12 s12 text-left" style="margin-top: 5px;">
                <span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Archivo de Entrega
            </div>
        </div>
        <div class="row">
            <form action="/vehiculos/updatemodarchivo" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submitmod">
                 <?php foreach ($this->vehiculosc as $veh) { ?>
                    <input type="hidden" name="idhs" value="<?php echo $veh["id_vehiculos"]; ?>">     
                <?php } ?> 
                <input type="hidden" name="idi" id="ido" value="">
                <div class="row">

                    <div class="file-field input-field col m12 s12">
                        <div class="btn">
                            <span>Archivo Nuevo</span>
                            <input type="file" name="url2">
                            <input type="hidden" name="imahidden" id="arc" value="">   
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" id="url2" type="text">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" id="modarchivo" class="btn">Guardar</button>
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>
<!-- End Modal Modificar Archivo -->


<!-- Modal añadir Archivo -->
<div id="modalarchivo2" class="modal modal-fixed-footer">
    <div class="modal-content">
        <div class="row">
            <div class="col m12 s12 text-left" style="margin-top: 5px;">
                <span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Añadir Archivo de Liberación
            </div>
        </div>
        <div class="row">
            <form action="/vehiculos/updatearchivo2" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submitarc2">
                 <?php foreach ($this->vehiculosc as $veh) { ?>
                    <input type="hidden" name="idhs" value="<?php echo $veh["id_vehiculos"]; ?>">     
                <?php } ?> 
                <input type="hidden" name="idi" id="id2" value="">
                <div class="row">

                    <div class="file-field input-field col m12 s12">
                        <div class="btn">
                            <span>Añadir Archivo</span>
                            <input type="file" name="url3" required>
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" id="url3" type="text">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" id="addarchivo2" class="btn">Guardar</button>
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>
<!-- End Modal añadir Archivo -->


<!-- Modal Modificar Archivo -->
<div id="modalmodarchivo2" class="modal modal-fixed-footer">
    <div class="modal-content">
        <div class="row">
            <div class="col m12 s12 text-left" style="margin-top: 5px;">
                <span style="font-size:22px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Modificar Archivo de Liberación
            </div>
        </div>
        <div class="row">
            <form action="/vehiculos/updatemodarchivo2" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submitmod2">
                 <?php foreach ($this->vehiculosc as $veh) { ?>
                    <input type="hidden" name="idhs" value="<?php echo $veh["id_vehiculos"]; ?>">     
                <?php } ?> 
                <input type="hidden" name="idi" id="ido2" value="">
                <div class="row">

                    <div class="file-field input-field col m12 s12">
                        <div class="btn">
                            <span>Archivo Nuevo</span>
                            <input type="file" name="url4">
                            <input type="hidden" name="imahidden2" id="arc2" value="">   
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" id="url4" type="text">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" id="modarchivo2" class="btn">Guardar</button>
        <button  class="modal-close red btn">Cerrar</button>
    </div>
</div>
<!-- End Modal Modificar Archivo -->



<!-- Paginador -->
<div class="row">
    <div class="col m12 s12 text-center">
        <div class="white-box">
            <div class="paginationControl">
                <ul class="pagination justify-content-center">
                    <?php if($pagina - 1 == 0){ ?>
                    <li class="page-item disabled">
                        <span class="page-link">Anterior</span>
                    </li>
                    <?php }else{ ?>
                    <li class="page-item">
                        <a class="page-link <?php if($pagina <= 1){ echo 'disabled'; } ?> " href="<?php if($pagina <= 1){ echo '#'; } else { echo "?pagina=".($pagina - 1); } ?>"> Anterior </a>
                    </li>
                    <?php } ?>
                    <li class="page-item <?php echo isActhref($links,$this->actpage);?>">
                        <?php echo $links; ?>
                    </li>
                    <?php if($pagina >= $this->total): ?>
                    <li class="page-item disabled">
                        <span class="page-link">Siguente</span>
                    </li>
                    <?php else: ?>
                        <li class="page-item">
                            <a class="page-link"  href="<?php echo "?pagina=".($pagina + 1); ?>">Siguiente</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div> 
</div>
<!-- End Paginator -->


<script src="/js/lightbox.js"></script>
<script type="text/javascript">

    lightbox.option({
      'resizeDuration': 200,
      'wrapAround': true
    });

    $(document).ready(function(){
        $('.modal').modal();
        $('select').formSelect();
        $('.datepicker').datepicker();

        $('.validanumeros').keypress(function(e) {
            if(isNaN(this.value + String.fromCharCode(e.charCode))) 
                return false;
        })
        .on("cut copy paste",function(e){
            e.preventDefault();
        });
       
    });


    $("#addarchivo").click(function(){
        
        var url =  document.getElementById("url").value;

        if(url == ""){
            swal({
                title: "Añade un archivo, para continuar.",
            });
        }else{
            swal("Espera un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            });
            setTimeout(submitFormArc, 500);     
        }    
    }); 

    function submitFormArc() {

        document.getElementById("submitarc").submit()

    }


    $(".info_res").click(function(){
        var id = $(this).data('id');     
        document.getElementById("id").value = id;
    });

    $("#modarchivo").click(function(){
        
        var url2 =  document.getElementById("url2").value;

        if(url2 == ""){
            swal({
                title: "Añade un archivo, para continuar.",
            });
        }else{
            swal("Espera un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            });
            setTimeout(submitFormMod, 500);     
        }    
    }); 

    function submitFormMod() {

        document.getElementById("submitmod").submit()

    }

    $(".info_mod").click(function(){
        var ido = $(this).data('ido');     
        document.getElementById("ido").value = ido;

        var arc = $(this).data('arc');
        document.getElementById("arc").value = arc;
    });  
  
   
    $("#addarchivo2").click(function(){
        
        var url3 =  document.getElementById("url3").value;

        if(url3 == ""){
            swal({
                title: "Añade un archivo, para continuar.",
            });
        }else{
            swal("Espera un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            });
            setTimeout(submitFormArc2, 500);     
        }    
    }); 

    function submitFormArc2() {

        document.getElementById("submitarc2").submit()

    }


    $(".info_res2").click(function(){
        var id2 = $(this).data('id2');     
        document.getElementById("id2").value = id2;
    });

    $("#modarchivo2").click(function(){
        
        var url4 =  document.getElementById("url4").value;

        if(url4 == ""){
            swal({
                title: "Añade un archivo, para continuar.",
            });
        }else{
            swal("Espera un momento, la información esta siendo procesada", {
                icon: "success",
                buttons: false,
            });
            setTimeout(submitFormMod2, 500);     
        }    
    }); 

    function submitFormMod2() {

        document.getElementById("submitmod2").submit()

    }

    $(".info_mod2").click(function(){
        var ido2 = $(this).data('ido2');     
        document.getElementById("ido2").value = ido2;

        var arc2 = $(this).data('arc2');
        document.getElementById("arc2").value = arc2;
    });  
  

        //Inicio Delete Ajax
    $(".delete").click(function(){
        id=$(this).data('id');
        nombre=$(this).data('nombre');
        swal({
            title: "Estas seguro de eliminar el EPP "+nombre+"?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })

        .then((willDelete) => {
            if (willDelete) {
                swal("Espera un momento, la información esta siendo procesada", {
                    icon: "success",
                    buttons: false,
                });

                var request = $.ajax({
                    url:"/epp/requesteppdel",
                    method:"POST",
                    data: { id : id },
                    processData: true,
                });
        //-------------------end de ajax---------------------------

        //-------------peticion de respuesta de ajax------------------
                request.done(function(response) {
                    console.log(response);//imprime lo que responde el ajax
                    // alert
                    window.location.reload(true);
                });
        //-------------------end de respuesta ajax---------------------
            return false;

            } else {
                swal("La accion fue cancelada!");
            }
        });
    });
    // End Delete Ajax


</script>

