<div class="row" style="margin-top: 10px;">
    <div class="col m12 s12">
        <a href="/vehiculos/tpodocumento" class="orange lighten-2 btn" style="color:black"><i class="material-icons left">arrow_back</i>Regresar</a>
    </div>
</div>

<div class="row">
	<div class="col m12 s12 text-center" style="margin-top: 10px;">
		<span style="font-size:30px; color: rgb(74,79,84); letter-spacing: 0.1em; font-weight: bold;">Editar Tipo Documento
	</div>
</div>

<div class="col m12 s12">
	<form action="/vehiculos/requestupdtpodoct" method="POST" enctype="multipart/form-data" class="form-horizontal form-material" id="submit_updtpo">
		<?php foreach ($this->tpo_doc as $tpodoc) { ?>
			<input type="hidden" name="ids" value="<?php echo $tpodoc["id"]; ?>">
			<div class="row">
			    <div class="input-field col m12 s12">
			    	<i class="material-icons prefix">assignment</i>
			        <input id="name" type="text" name="name" value="<?php echo $tpodoc["nombredoc"]; ?>" class="validate" required>
			        <label for="name">* Nombre:</label>
			    </div> 
		    </div>
		<?php } ?>
	</form>
</div>

<div class="input-field col m12 s12 text-right">
	<div class="row">
		<a href="/vehiculos/tpodocumento" class="waves-effect red waves-light btn">Cancelar</a>
		<button  id="updtpo" class="waves-effect waves-light btn">Actualizar</button>
	</div>	
</div>


<script type="text/javascript">
    
    $("#updtpo").click(function(){
        var name = document.getElementById("name").value;

        if(name == ""){
            swal({
                title: "Para editar un tipo de documento debes agregar un nombre",
            });
        }else{
             swal("Espera un momento, la información esta siendo procesada", {
				icon: "success",
			 	buttons: false,
			});
            setTimeout(submitForm, 500);     
        }

    });


    function submitForm() {
        document.getElementById("submit_updtpo").submit()
    }

</script>